### PR TITLE
Khami Barrens

### PR DESCRIPTION
**Pull request by Warfan1815**
# About the pull request

A new map! The Weyland Yutani Corporation foolishly decided to make a colony on top of some Yautja ruins, hoping to make greater study of them. Unfortunately, they unearthed more than they bargained for....

A rural, and desert-esque map, I have tried my best to encapsulate the visuals I think both sand maps (which both feature water prominently) are lacking.

# Explain why it's good for the game

The more maps the merrier.

<summary>Screenshots & Videos</summary>
<details>

</details>

# Changelog

:cl:
mapadd: adds the Khami Barrens map to normal rotation (with a minimum of 130 pop)
code: adds the ability for walls to force the blending of turfs with the force_blend var (tangentially related to the map due to a certain map 'bug')
/:cl:

### CODE REVIEW

**Comment by Diegoflores31** [comment]
images broken . cant see it

**Comment by c4xmaniac2** [comment]
Tried to load the map on a private server, it doesn't show up in the map selection.

image

**Comment by c4xmaniac2** [comment]
image

Needs a redesign, too much loot in one easily accessible area. Remove the double barrel, the incen slugs, and one of the flamer tanks. Add in an HG with 2 boxes of buckshot. Look at the science annex armory/lv armory for what these armories should look like. 

image
Remove the double barrel here too, Morrow will probably want the incen slugs removed. Only place for incen slugs is in fairly hard to reach areas, thing lambda labs on BR. It's got an auto shotty with 2 boxes of incen slugs, but you need to blow your way through lambda and risk the hive being there. Longer process and dangerous.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by morrowwolf** [comment]
Free to re-open after merge conflicts and redesign are complete.

I still can't guarantee a speedy review/testing phase though sadly. Low on mapping folks.

**Pull request closed without merging**
