### PR TITLE
Added two new trucker hats, new latex glove sprites, new shoe sprites and new medical scrub sprites.

### PR DESCRIPTION
**Pull request by BadAtThisGame302**
# About the pull request

Added a blue and red trucker hat

Updated the latex glove sprites.

Updated the laceup, sneaker, sandals and marine boots sprites.

Changed the medical scrubs, including adding a new orange scrubs sprite along with removing the nurse armband from the nurse scrubs and making it an accessory with a new sprite.

# Explain why it's good for the game

Two new trucker hats for that epic survivor gameplay.

Alot of new medical sprites, the scrubs, the headscrubs and the new apron.

Aswell as new sprites for laceup shoes, sneakers and black/brown/jungle marine boots.

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

(The Medical Scrubs)

image

image

image

image

image

(The Trucker Hats)

image

image

(The Sandals)

image

(The Marine Boots)

image

image

image

(The Laceups)

image

image

</details>

# Changelog
:cl:
add: Added light blue scrubs to the medical and synth vendors and closets
imageadd: added two trucker hat sprites, blue and red
imageadd: added new latex, laceup, sneakers, sandals and marine boot sprites.
imageadd: added new medical apron, new scrub uniforms and scrub headcover sprites, including a new orange one.
imagetweak: tweaked the wizard sandal name to good old sandals
/:cl:

### CODE REVIEW

**Comment by nauticall** [comment]
please post ingame screenshots of your sprites for review

**Comment by BadAtThisGame302** [comment]
> please post ingame screenshots of your sprites for review

Updated the screenshots section.

**Review by nauticall — APPROVED** [review]
looks good

**Comment by BadAtThisGame302** [comment]
> > imaginetweak: tweaked the wizard sandal name to good old sandals
> 
> imaginetweak is not valid for the changelog. Also you need a closing /:cl: for the changelog


Did both of those.

**Review by Drulikar — APPROVED** [review]

**Pull request merged**
