### PR TITLE
Create a new vendor for medics to handle the medical consumables.

### PR DESCRIPTION
**Pull request by Huffie56**
# About the pull request
The idea is to move all the medical consumable to a new vendor that would use snowflake point instead of regular point.

# Explain why it's good for the game
Avoid to penalize medic fighting load-out because he as to buy medical stuff for the group instead of improving it's fighting capability.
# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl:
balance: add a new vendor to move all the medical consumables in it. this vendor is using snowflak point.
/:cl:

### CODE REVIEW

**Comment by hislittlecuzingames** [comment]
aren't most of the medical supplies you can pay for free in the lobby of medical? 

Like Pills, splints, etc?

**Comment by Huffie56** [comment]
> aren't most of the medical supplies you can pay for free in the lobby of medical?
> 
> Like Pills, splints, etc?

i mean yes but lot's of stuff you can buy are available for free on the ship so....

**Comment by hislittlecuzingames** [comment]
> > aren't most of the medical supplies you can pay for free in the lobby of medical?
> > Like Pills, splints, etc?
> 
> i mean yes but lot's of stuff you can buy are available for free on the ship so....

I just imagined that going to medical was part of the gearing up process. 

Now that I had more time to think about it-why not try it out?

**Comment by Nanu308** [comment]
dunno how i feel about it, more player interaction is always good and removing it for vendors idk about

besides that, I'd think we would want a separate sprite for the 3rd set of different vendor so players know to check it.

**Review by Drulikar — CHANGES_REQUESTED** [review]
I don't know if this is an oversight, but this is a **MASSIVE** increase to the amount of points available to medics.

Not only do they still have 45 like they have had before, now they have another vendor that has 120 points per person. You did increase the cost of items ~3x but this is in total way more points to spend on items that already are too plentiful.

Additionally the new vendor looks literally no different than the others - and is placed in line with the others so you wouldn't even know its a vendor you ought to go to unless that's the vendor you would typically use positionally.

**Comment by Zonespace27** [comment]
Thank you for the PR, but I am currently not interested in adding this to the game.

**Comment by Huffie56** [comment]
> I don't know if this is an oversight, but this is a **MASSIVE** increase to the amount of points available to medics.
> 
> Not only do they still have 45 like they have had before, now they have another vendor that has 120 points per person. You did increase the cost of items ~3x in that vendor but this is in total way more points to spend on items that already are too plentiful.
> 
> Additionally the new vendor looks literally no different than the others - and is placed in line with the others so you wouldn't even know its a vendor you ought to go to unless that's the vendor you would typically use positionally.

it was more of a demo concept to see what zonespace think about the idea.
I didn't want to spend too much time thinking about price since it had an high chance of being rejected.

**Pull request closed without merging**
