### PR TITLE
Sorokyne's Easter Miracle (re-adds Soro)

### PR DESCRIPTION
**Pull request by Agameofscones**
## About The Pull Request

It's an easter miracle, Sorokyne is back from the dead and crammed full of new features like auto-turfs, less ledges, and more weather effects (that's a joke lad), and a Chunkeez Diner.

Todo, add images later.

## Why It's Good For The Game

4khan and I ran a psyops campaign 2 years ago after fixing the lag on Sorokyne. The problem was, the reputation of the map was outperforming the actual ingame performance, such that no one voted for it. The plan was to remove the map, say it was down for maintenance, and then re-add it with only minimal changes (since weather had already been fixed).

Unfortunately techwebs and open sourcing and the dev civil war happened, so only now am I returning it.

## Changelog

:cl: Triiodine, Monkeysfist101
add: Re-added Sorokyne Strata to rotation. Applied a bunch of much needed fixes and also new unique turfs.
/:cl:

### CODE REVIEW

**Comment by Carnage068** [comment]
It's a little less laggy, I think, but it's still really laggy. I think you need to simplify the weather sprites or something. Too much animation on too many tiles, and it's really showing. Nice to see Sorokyne again though, no matter the conditions.

**Comment by stanalbatross** [comment]
image
 stray corner

**Comment by stanalbatross** [comment]
image
issue here, idk why

**Review by Watermelon914 — COMMENTED** [review]
Code changes are minimal and don't really require coder review, mapper can merge if the maps look good

**Review by Nanu308 — APPROVED** [review]
Needs a check for Instanced Objects etc. but otherwise map is fine and ready to be merged.

**Comment by fira** [comment]
See #190 for related performance improvements with weather and areas that likely make a difference on Sorokyne

**Review by nauticall — APPROVED** [review]
sprites lgtm 👍

**Comment by PalJohnson** [comment]
Could you add medical vendors to the map. Survivors don't have a way to get any medical items of value atm other than a trick injector from first aid boxes.

**Pull request merged**
