### PR TITLE
staff and longaxe now in the elite vendor

### PR DESCRIPTION
**Pull request by Nomoresolvalou**
# About the pull request

the staff and the longaxe weapons are now in the elite yautja vendor

Changes the description of the staff to be more fitting.

Also adds back onmobs for the longaxe. Sprites by Thwomper of course
# Explain why it's good for the game

I thought I had added the weapons to both the normal and elite vendors, but I guess I gaslit myself or something.

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

image
image
image
image

</details>

# Changelog
:cl: Nomoresolvalou, Thwomper
add: Added staff and longaxe weapons to the elite yautja vendor.
imageadd: Adds onmob sprites for the longaxe.
spellcheck: Changes hunter staff description to be more in line with other weapons.
/:cl:

### CODE REVIEW

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Review by Nanu308 — COMMENTED** [review]
code be good

**Review by Nanu308 — APPROVED** [review]
a

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Review by realforest2001 — APPROVED** [review]

**Pull request merged**
