### PR TITLE
Poncho access removal

### PR DESCRIPTION
**Pull request by morrowwolf**
## About The Pull Request

Pending discussion on readability and art style direction the ponchos will be removed from being accessible.

## Why It's Good For The Game

Maintaining a style and aesthetic consistent and synergizing with the universe is important.

## Changelog

:cl: Morrow
del: Removes USCM ponchos from vendors.
/:cl:

### CODE REVIEW

**Review by Agameofscones — APPROVED** [review]
the night they drove old dixie down. If anyone is mad, this was my call. Approved

**Comment by morrowwolf** [comment]
Triiodine may have made the hard call but this was very much a group decision from devs.

**Review by stanalbatross — APPROVED** [review]

**Comment by PhantomEpicness** [comment]
God has giveth

and god taketh away

😔

**Comment by Diegoflores31** [comment]
> God has giveth
> 
> and god taketh away
> 
> 😔

too much drip for CM

**Pull request merged**
