### PR TITLE
New Marine Hairstyles

### PR DESCRIPTION
**Pull request by zc-byte-boxer**
# About the pull request

I have tested these changes. This PR adds 12 new hairstyles for marines to use that are designed around helmets.

# Explain why it's good for the game

Adds more customization options for marines.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Loaded up local host and tried these sprites on from the character editor.

image

image

image

image

Tested hairs.

image

All newly added hairs.

</details>

# Changelog

:cl: Byte-Boxer
add: Added 12 new hairstyles for marines!
/:cl:

### CODE REVIEW

**Comment by zc-byte-boxer** [comment]
Hairs done by Mossmoth.

**Comment by Drulikar** [comment]
Stale exempt until sprite reviewed.

**Review by nauticall — CHANGES_REQUESTED** [review]
the hair having a gray base practically guarantees it will throw off any coloring people try to put on it. should be darkened to near-black like all the other ones for the sake of consistency. either that or make every other hair gray to compensate (which i know is out of scope)

**Comment by zc-byte-boxer** [comment]
image

Should be done and good, @nauticall

**Comment by zc-byte-boxer** [comment]
@nauticall

**Comment by zc-byte-boxer** [comment]
@nauticall

**Review by nauticall — APPROVED** [review]

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Review by Blundir — APPROVED** [review]

**Comment by DorfGuy1** [comment]
Fairly Certain you broke something. All of a sudden hair styles that worked fine yesterday are completely different.

**Comment by DorfGuy1** [comment]
Please refer to https://github.com/cmss13-devs/cmss13/issues/7393
Thank you.

**Pull request merged**
