### PR TITLE
Resprites cats and kitten sprite [corgis and crabs no longer replaced]

### PR DESCRIPTION
**Pull request by sleepynecrons**
## About The Pull Request

Replaces sprites for both cats, the kitten, [EDIT: Doesn't replace corgis/crabs]

## Why It's Good For The Game

Legacy cat sprites bad

animalResprites

## Changelog

:cl: Sleepynecrons
imageadd: New icons for cats and the kitten. Added onmob icons for Jones when holding in hands.
imagedel: Removed old icons for cats and kitten
code: Added a holder for the kitten so object sprites and descriptions are consistent when picking one up.
/:cl:

### CODE REVIEW

**Comment by fira** [comment]
Changed mind?

**Comment by LoJoFan** [comment]
hopefully spriting siamese cat 😊

**Comment by sleepynecrons** [comment]
> Changed mind?

wanted to work on them more but i figure i should just leave it up to at least get approval or feedback. hopefully not breaking any rules randomly closing and opening


> hopefully spriting siamese cat 😊

😈

**Review by monkeysfist101 — CHANGES_REQUESTED** [review]
Cats approved. Corgis and crabs denied.

**Review by monkeysfist101 — APPROVED** [review]
Approved

**Pull request merged**
