### PR TITLE
Fix the missing icon for the really black suit 

### LINKED ISSUE #1594: suit_jacket/really_black is honked (and can be found on Sorokyne)
## Description

`/obj/item/clothing/under/suit_jacket/really_black` can be found in `/obj/structure/closet/wardrobe/suit`, which can be found on Sorokyne in Personal Storage area:

image

## Difference between expected and actual behavior

Have proper sprite, or the item removed / changed.

## Steps to reproduce

Go to the location, open locker.

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

### PR DESCRIPTION
**Pull request by moltoretardo**
## About The Pull Request
The really black suit was missing its icon so I added it by copying the charcoal suit and making it a bit blacker to fairly represent it, also made the tie red like on the item.
fixes #1594

## Why It's Good For The Game
Missing icons are bad and I couldn't find the original.
reallyblack

## Changelog

:cl: Molto
fix: fixed the really black suit missing icon
/:cl:

### CODE REVIEW

**Comment by ThePiachu** [comment]
I wonder how the sprite used to look originally, maybe it would be interesting to go digging for that and seeing if it still holds up.

**Comment by ThePiachu** [comment]
I did a bit of digging , and the old leaked version of CM had the original suit, not sure if it's better:

[Old Uniforms.zip](https://github.com/cmss13-devs/cmss13/files/10036883/Old.Uniforms.zip)

image

I'll leave that up to the spriters.

**Comment by moltoretardo** [comment]
I am honestly open to both, as long as the icon isn't a honk anymore. Though on the old leaked version the shirt underneath is gray while on the item it's a clear white. Won't mind changing to whichever the spriters likes most

**Review by monkeysfist101 — APPROVED** [review]
approved

**Pull request merged**
