### PR TITLE
Crawling

### PR DESCRIPTION
**Pull request by Geevies**
## About The Pull Request

You now crawl if you move while lying down. Crawling one tile takes three seconds.

## Why It's Good For The Game

I don't know actually, just felt like a cool thing to add.

## Changelog

:cl:
add: You can now crawl if you try moving while lying down, crawling takes three seconds.
/:cl:

### CODE REVIEW

**Comment by Geevies** [comment]
testmerge because this might break in unexpected ways

**Comment by spartanbobby** [comment]
CRAWLING

**Comment by c4xmaniac** [comment]
Holy shit the HRP army crawl

**Comment by FlamermanGrills** [comment]
Based and obstacle course pilled

**Comment by MusselMain** [comment]
Legit bush ambushes can be a thing now (if you can still hold items) WICKED!

**Comment by morrowwolf** [comment]
SMG arm brace buff

**Comment by Shad0vvs** [comment]
Whole marine force pushes up while crawling ontop of eachother!!!

**Comment by Sargeantmuffinman** [comment]
Okay so, used it in the T-Dome. 3 seconds seem just a tiny bit too long. Maybe that's just the lag but yeah it seems like it won't really matter at all in the grand scheme of things. Will hopefully try it soon.

**Comment by Chainsawicus** [comment]
Make it so that when you're getting up from resting, you cannot initiate crawling. As-is it causes weird interactions like occasionally locking you out of movement even after you've stood up until the crawling time ends, leading to sluggish and inconsistent-feeling movement.

**Review by stanalbatross — CHANGES_REQUESTED** [review]
you should being able to take out your gun while resting with `e`

**Review by stanalbatross — CHANGES_REQUESTED** [review]
fixing being able to give / put in hands items to people who are lying down is a prerequisite to merging this PR

fix it in it or another PR

**Review by stanalbatross — CHANGES_REQUESTED** [review]
no xeno crawling, resting sprites clearly cannot crawl so it makes little sense and looks weird and unnatural.

**Review by stanalbatross — APPROVED** [review]

**Pull request merged**
