### PR TITLE
(Mapping) Minor Almayer Edits

### PR DESCRIPTION
**Pull request by spartanbobby**
## About The Pull Request
Okay, So I basically removed a bunch of contraband and expensive items from public areas of the Almayer, I replaced the diamond coin, gold coins and silver coins on the Almayer with falling falcons challenge coins and added an easter egg if you collect them all.

I also touched up the VCs bunks to be more fitting for PFCs instead of sergeants (Bunk beds and no more wooden floors) as well I added some wheelchairs and canes to medical and removed them from the CO, XO, and ROs offices because why were they even there in the first place?

Finally, the 5 colony cigarette vendors on the ship have been replaced with the correct USS Almayer ones
## Why It's Good For The Game

Immersion, the USS Almayer is a military vessel and the amount of free access to alcohol on the ship was frankly, absurd. Now if you want a drink you'll have to get it from the CO, officers mess, bribe the CL for his sake or get it from the colony. And if you want expensive cigs you'll need to secure them from the much nicer colony vendors.

The challenge coins are more of a fluff thing replacing the somewhat out-of-place diamond and golden coins with something that people may be able to RP around (wanting to get the COs challenge coin as a souvenir of your tour on the Almayer)

## Changelog

:cl: SpartanBobby
add: Added Falling Falcon Challange coins to the USS Almayer.
add: Added Wheelchair storage to the medical bay.
del: Removed Contraband such as Alcohol from the public spaces of the USS Almayer.
fix: Fixed the USS Almayer having colony cigarette vendors.
add: Remodeled the VC bunk to be more fitting for lower enlisted
/:cl:

### CODE REVIEW

**Comment by Agameofscones** [comment]
can you not remove the cabinet man easter egg thx. Also the bowler and tie from the XO.

That is all, rest looks good to me

**Comment by monkeysfist101** [comment]
image
Approved

**Review by monkeysfist101 — APPROVED** [review]

**Comment by Diegoflores31** [comment]
Ok but arent the VCs like higher ranking than PFCs ? Thats why they have like better stuff

**Comment by spartanbobby** [comment]
> Ok but arent the VCs like higher ranking than PFCs ? Thats why they have like better stuff

after checking you are correct they are corporals but I still believe the last bunk was two fancy for E3s

however I will edit to changelog

**Comment by joookschad** [comment]
the XO deserves to keep his bowler hat and tie

**Pull request merged**
