### PR TITLE
CL Breifcase Bugfix

### PR DESCRIPTION
**Pull request by PalJohnson**
## About The Pull Request

Fixes timer issue with briefcase accessibility. In short the previous PR #657 sought to limit items from being dispensed prior to marine drop to discourage power gaming. The timer is supposed to make it so you cant access certain items by 12:25 (20min in game). The fix applied a value of 25min which in theory should work but the server start time is 12:05. This means items cannot be retrieved until 12:30.

## Why It's Good For The Game

Fixes oversight caused by server time beginning 5min.

:cl:
fix: fixed timer on CL briefcase not dispensing items at 12:25 server time
/:cl:

### CODE REVIEW

**Comment by fira** [comment]
This isn't the correct way to fix this. Server start might be anytime.

**Review by fira — CHANGES_REQUESTED** [review]
To fix this properly use `SSticker.mode.round_time_lobby`

**Comment by fira** [comment]
Would like a clarification on that by original author @stanalbatross

**Comment by stanalbatross** [comment]
It's meant to be at 12:25, if the timer doesn't take preround time into account then this is fine

**Review by fira — APPROVED** [review]
That's fine then

**Pull request merged**
