### PR TITLE
Ceremonial sword: the respritening

### PR DESCRIPTION
**Pull request by Mister-moon1**
# About the pull request
Changes the sprites for the ceremonial sword to be more saber esc and fixes an empty holster sprite

# Explain why it's good for the game
The ceremonial sword has always just used the katana icon for object and with the on mob sprite looking much different, this PR gives it a custom look (belt rings included) based on a real saber that i own (the gold hilt does remain though)

# Testing Photographs and Procedure
https://imgur.com/M3SWCs6
https://imgur.com/ovq3Q5c
https://imgur.com/gdFnwfi

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
fix: fixed sprite for ceremonial sword empty holster on mob icon
imageadd: new sprites for the ceremonial sword including sprites for the scabbard
/:cl:

### CODE REVIEW

**Review by Agameofscones — CHANGES_REQUESTED** [review]
onmobs look ok.

obj icons don't.

image

For the actual sword, set the curve into the blade more. Right now it just looks like the CO tripped and bent the tip of their replica katana they got from space daiso

**Comment by Mister-moon1** [comment]
https://imgur.com/sEBaNda
https://imgur.com/ZJVUi8h

**Comment by Agameofscones** [comment]
image
Your curve steps here are totally imbalanced and look wonky. Clean 'em up.

chrome_ejJRdlL6Ni
This highlight line should run the length of the scabbard.

image
Flip these clips so the highlight is on the inside, and increase the color contrast on the grey. Maybe give it a gentle blue shift?

Sword sprite is 👍 good job. Lmk when you work on the scabbard some more.

**Comment by Mister-moon1** [comment]
https://imgur.com/qGq3koL
https://imgur.com/NojsafW
@Agameofscones made the curve more natural for the scabbard, improved the highlight to be more consistent and made gave the belt hooks a hint of blue

**Review by FransFeiffer — COMMENTED** [review]
Sprites look good, LGTM

**Pull request merged**
