### PR TITLE
[IDB IGNORE] moves all the sprites into the main repo

### PR DESCRIPTION
**Pull request by harryob**
## About The Pull Request

no i didn't just go crazy and do this i asked before

i also included xenos_old and xenos_halloween for funsies

## Why It's Good For The Game

it was a bit inconvenient and it simplifies things for TMs, etc

## Changelog

:cl:

/:cl:

### CODE REVIEW

**Comment by Watermelon914** [comment]
please change all the file dmi names to be lowercase as well.
This is because linux has some issues handling case, so it's better to just keep everything lowercase for futureproofing.

**Comment by Watermelon914** [comment]
> Note that under the readme:
> 
> > Assets including icons and sound are under the [Creative Commons 3.0 BY-SA license](https://creativecommons.org/licenses/by-sa/3.0/) unless otherwise indicated. Authorship for assets including art and sound under the CC BY-SA license is defined as the active development team of CM-SS13 unless stated otherwise (by author of the commit).
> 
> Since the sprites are likely sourced https://www.newgrounds.com/art/view/afridge/xenomorph-sprites it lists it as https://creativecommons.org/licenses/by-nc/3.0/: image Unless we've moved to https://wiki.creativecommons.org/wiki/public_domain at this point.
> 
> Several other sprites are by https://www.nicboone.com/ but I don't have any more information there.

attribution is given in the changelog, or well it should be.

**Comment by fira** [comment]
No, attribution needs to be easily retrievable, not buried in Changelog...

Just make a text file as root with the attributions

**Comment by harryob** [comment]
idb2 continues to freak out - who cares

**Review by Nanu308 — APPROVED** [review]
Approved by both Head dev (me) and Host TheSoldierLJJK

**Comment by fira** [comment]
Testmerging that ASAP to validate and put it in action

**Comment by Diegoflores31** [comment]
> Note that under the readme:
> 
> > Assets including icons and sound are under the [Creative Commons 3.0 BY-SA license](https://creativecommons.org/licenses/by-sa/3.0/) unless otherwise indicated. Authorship for assets including art and sound under the CC BY-SA license is defined as the active development team of CM-SS13 unless stated otherwise (by author of the commit).
> 
> Since the sprites are likely sourced https://www.newgrounds.com/art/view/afridge/xenomorph-sprites it lists it as https://creativecommons.org/licenses/by-nc/3.0/: image Unless we've moved to https://wiki.creativecommons.org/wiki/public_domain at this point.
> 
> Several other sprites are by https://www.nicboone.com/ but I don't have any more information there.

i dont think the newground stuff applies since it was made in CM first and then posted on newgrounds which means the ones we have were made using the current CM license at that time and later posted on newgrounds

**Pull request merged**
