### PR TITLE
Another good Sprite PR

### PR DESCRIPTION
**Pull request by BadAtThisGame302**
# About the pull request

Adds new insulated sprites for both the item and on-mob

Adds new CMB uniform/jacket/cap sprites, as well as a deputy/marshal variant.

Adds two new overall sprites, tan/red and updates the blue one.

Gives two heavy vehicle operator survs a blue/red trucker hat I added previously.

Adds three new hazard vest sprites. Orange/Blue/Black

Adds five new colonist workclothes. Grey/Khaki/Pink/Blue/Green

# Explain why it's good for the game

Removes legacy sprites, adds new sprites and puts said sprites in rotation.

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

### CMB Deputy and Marshal

image

image

### Hazard Vests and Insulated Gloves

image

image

image

### Workwear

image

image

image

image

image

### Overalls

image

image

image

</details>

# Changelog
:cl:
add: Added trucker hats to the Solaris and Trijent Trucker survs.
add: Added the CMB Marshal jacket to the CMB Marshal.
imageadd: Differentiated the CMB Deputy and CMB Marshal jackets to accurately know which is which. Courtesy of AmoryBlaine.
imageadd: Added new insulated gloves, coveralls (Tan/Red), updated the blue coveralls, Five Colonist Clothes (Grey/Khaki/Pink/Blue/Green), updated the Orange/Blue/Black hazard vests and updated the CMB Uniform and Cap. Courtesy of AmoryBlaine.
/:cl:

### CODE REVIEW

**Review by ItsVyzo — COMMENTED** [review]
uniform_0.dmi has too many icons. You'll want to consider splitting some side factions or survival/misc clothing to a uniform_1.dmi

**Comment by BadAtThisGame302** [comment]
> uniform_0.dmi has too many icons. You'll want to consider splitting some side factions or survival/misc clothing to a uniform_1.dmi

Yeah, moved the halloween and donor uniforms to the second dmi.

**Review by nauticall — CHANGES_REQUESTED** [review]
Only real critique I have is with the pants. They're sprited in such a way that it highlights the groin area and it makes it look very skin-tight and especially weird on women. Make the shading more like a zipper instead, just a single line going down the center.

**Comment by BadAtThisGame302** [comment]
> Only real critique I have is with the pants

Both the CMB and workwear ones?

**Comment by BadAtThisGame302** [comment]
> > Both the CMB and workwear ones?
> 
> Yeah. All of them that have that bit of shading in particular. We removed some clothing sprites that had that look a while ago for similar reasons. That's all that's needed to be changed though, in my mind

I removed the bulge, feel free to re-review the PR.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Review by nauticall — APPROVED** [review]
alright, looks good

**Review by Drulikar — APPROVED** [review]

**Pull request merged**
