### PR TITLE
4 New Haircuts

### PR DESCRIPTION
**Pull request by XDinka**
# About the pull request

## Some new haicuts

Looking at the current sheet it occurred to me to add a few current popular hairstyles that have passed the community evaluation.

It's a bit hard for me to write text and descriptions due to my poor language skills, but I'll try to describe as much as I can.

# Explain why it's good for the game

First of all, playing on the server we try to associate ourselves with the character, try to be in his skin. His appearance plays an important role. A couple of beautiful hairstyles will please the eye of players and add a little more variety

# Photographs
<details>
<summary>Screenshots & Videos</summary>

## Gentle Ponytail

image

hair_gentleponytail

## Edgar haircut

image

hair_edgar

## Emo Bun

image

hair_emobun

## Taper haircut

image

hair_taper

</details>

# Changelog

:cl: XDinka
add: Added four new haircuts: gentle ponytail, edgar haircut, emo bun, taper haircut.
/:cl:

### CODE REVIEW

**Review by Drulikar — APPROVED** [review]
Code changes are fine and working in the creator. Still needs sprite approval.

**Comment by Drulikar** [comment]
I have already reviewed and approved. You need sprite review as I said.

**Comment by XDinka** [comment]
@cm13-github/spriters pr is still need ur review.

**Review by FransFeiffer — APPROVED** [review]
Sprites good, LGTM

**Pull request merged**
