### PR TITLE
Adds cheap flavor suppressor to loadout

### PR DESCRIPTION
**Pull request by carlarctg**
# About the pull request

Adds a 3-point 'cheap suppressor' to the character loadout items which silences the gun but does not have any other effects, such as increasing accuracy or reducing damage. Does not fit on the M4RA. Also added it to some CLF/colony random-spawn weapons.

Removed the random choice between two different attached-to-gun icons suppressors have (???), instead repurposed the second one as a base for the cheap suppressor's sprite.

# Explain why it's good for the game

> Adds a 3-point 'cheap suppressor' to the character loadout items which silences the gun but does not have any other effects, such as increasing accuracy or reducing damage. Does not fit on the M4RA. Also added it to some CLF/colony random-spawn weapons.

This is basically a flavor addition for people to spice up their guns with the cool silencing noise without impacting stats. 'But this is a flat buff without a downside!' Not really! The downside is that it cannot fit any other attachment on the barrel slot, you'll lose out on an extended barrel or bayonet for your gun. It does not fit on the M4RA and I am open to removing it from other special weapons as it would be a flat buff to the gun.

> Removed the random choice between two different attached-to-gun icons suppressors have (???), instead repurposed the second one as a base for the cheap suppressor's sprite.

Sprites sprit.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: Adds a 3-point 'cheap suppressor' to the character loadout items which silences the gun but does not have any other effects, such as increasing accuracy or reducing damage. Does not fit on the M4RA. Also added it to some CLF/colony random-spawn weapons.
imageadd: Removed the random choice between two different attached-to-gun icons suppressors have (???), instead repurposed the second one as a base for the cheap suppressor's sprite.

/:cl:

### CODE REVIEW

**Review by harryob — APPROVED** [review]
code is fine + god i hate attachment code

**Review by nauticall — APPROVED** [review]
sprites are a-ok 👍

**Review by morrowwolf — COMMENTED** [review]
The effect of silencing a gun should probably stay a limited feature. Will discuss with GAs.

**Review by morrowwolf — CHANGES_REQUESTED** [review]
Alright first GA comment:

I don't mind a cheap little muzzle break attachment that doesn't do anything.

The silencing trait should remain limited though. Remove that and reflavor the item and we're good.

**Pull request closed without merging**
