### PR TITLE
fix for typo in tgui docs

### PR DESCRIPTION
**Pull request by FreetoZ**
# About the pull request

fix for a minor spelling error in the documentation for tgui.

# Changelog

:cl:
spellcheck: fixed tgui documentation typo 
/:cl:

### CODE REVIEW

**Comment by Foxtrot13224** [comment]
You might want to add your name in the changelog section so you get proper credit

**Comment by FreetoZ** [comment]
> You might want to add your name in the changelog section so you get proper credit

could care less.

**Comment by fira** [comment]
I mean, this is cool, but you should really be PR'ing this to /tg/ instead so the spellcheck actually sticks. This is going to get reverted at the first update.

**Comment by morrowwolf** [comment]
As Fira said, PR this to /TG/

**Pull request closed without merging**
