### PR TITLE
Project ARES

### PR DESCRIPTION
**Pull request by realforest2001**
# About the pull request
Overhauls ARES and makes it actually feel like a part of the ship and not a square box. 

Adds individual processors for different ARES systems that interact with oneanother to produce the same effects as we normally have.
Bioscans require the bioscan processor to be functional, however will not broadcast if the interface processor is not functioning.
The interface processor handles ARES communications (excluding Apollo) and is chiefly responsible for logging things to the ARES Console. This console can be used to review logs of all ARES' messages/announcements, Bioscans, the Apollo Link logs etc.

PREFACE: The current console uses HTML UI, this is deliberate to allow me to easily experiment and test functionality of core systems. TGUI to come.

# Explain why it's good for the game
Adds a little immersion and use for ARES.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: Added an admin button for an ARES bioscan. Slightly refactored how Bioscans trigger for marines.
add: Added individual proccessors for ARES systems.
add: Added an ARES interaction console in the AI Core room, which holds logs for most ARES functions.
/:cl:

### CODE REVIEW

**Review by Agameofscones — CHANGES_REQUESTED** [review]
unintentional revert on stationobjs.dmi?

Console icons should go with the others in their respective dmi instead of unique to the ares.dmi

other sprites are fine

**Comment by realforest2001** [comment]
Originally put all the sprites in stationobj so probably due to that. Will move the computer sprite when it's all ready to go up for review-proper, helps me reduce risk of conflicts while I'm working

**Comment by Ultimate-Fluff** [comment]
Can you fix #2749 in this PR as well? I have no clue why striking ARES makes fleshy noises instead of a metallic noise.

**Comment by Herotitan772** [comment]
Cool addition, should definitely be TMed some more to work out and problems. But all in all good idea!

**Pull request closed without merging**
