### PR TITLE
Adds One ACCESSORY ONLY Slot for Helmets

### PR DESCRIPTION
**Pull request by Staykeu**
# About the pull request

Allows for the insertion of an extra cosmetic item in helmets that subtype the M10.

# Explain why it's good for the game

Adds more personalization to people who don the helmet. Change is purely cosmetic.

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl: Stakeyng
qol: Lets you put an extra accessory item in your helmet.
/:cl:

### CODE REVIEW

**Comment by Staykeu** [comment]
> How is it qol? And could you be more descriptive on the changelog rather than just "Customization"

Everything else is written down, customization is all that I felt needed to be stated.

It's QOL because it allows for a more personalized character when you use the helmet. I stated that.

**Comment by Staykeu** [comment]
> The changelog is what will be player facing, what people can see in game. People seeing just "Customization" or "allow for a more personalized experience during gameplay" on the ingame changelog or on the discord channel won't understand what that means.

It's changed now.

**Comment by 567Turtle** [comment]
I would probably make it so the helmets have three (3 (III)) slots for garb but besides that code looks good yeah mhmm

**Comment by goobliner** [comment]
In case you didn't know you really don't have to keep your change branches up to date with the master unless youthat update to actively make changes to something after you do that update.

**Review by Drulikar — APPROVED** [review]

**Pull request merged**
