### PR TITLE
Fix nullspaced closet runtime

### PR DESCRIPTION
**Pull request by Zonespace27**
# About the pull request
image

### CODE REVIEW

**Comment by fira** [comment]
Wait, what? This doesn't make sense. How does the closet take damage from the proejctile if it's in nullspace?

**Comment by fira** [comment]
Ohhhhhhhh I think I get it

Shrapnel flies -> scan_a_turf -> Hits the closet -> Closet takes damage and falls below 0 HP -> Closet forceMoves the contents out of it -> Contents movement triggers Crossed with the shrapnel again and scan_a_turf causing the bullet to hit the closet again -> recurse until every contents are forceMoved off, one per frame -> last frame deletes the closet -> previous frame keeps going with copied `as anything in src` list -> loc is null, runtime -> keep unstacking frames

I think that's it because looking at dd.log there are actually 22 runtimes, as it unwinds the stack and fails to move them at every recursion level

It's not directly the bullet code's fault because the closet isn't yet deleted when hit checks happen - but the legacy behavior to rescan the whole turf when Crossed is really dumb. The closet's behavior shouldn't make it recurse bullet hits onto itself

**Comment by fira** [comment]
But yeah if that's it this change won't fix it, you'd need to check `loc` INSIDE the for loop

**Comment by Zonespace27** [comment]
> But yeah if that's it this change won't fix it, you'd need to check `loc` (or QDELETED) INSIDE the for loop
> 
> Edit: An easy way out could be to early return from take_damage if the health is already <0 but i don't know how sane that is

did both

**Review by fira — APPROVED** [review]
🤯

**Pull request merged**
