### PR TITLE
(WIP) CORSAT: The Shrinkening

### PR DESCRIPTION
**Pull request by realforest2001**
# About the pull request
Returns CORSAT to a _hopefully_ playable state.

- Removes Ice Dome
- Removes Monorail
- Removes much of the NW region of the map as it's unused.
- Moves around a few other areas of the map to condense it.
https://forum.cm-ss13.com/t/temp-corsat-map/7955

# Explain why it's good for the game

# Testing Photographs and Procedure
image

# Changelog
:cl: forest2001, Spartanbobby
mapadd: Returns CORSAT, now significantly smaller.
imageadd: Added mapping-sprites for CORSAT hull windows.
/:cl:

### CODE REVIEW

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by Drulikar** [comment]
Just as a note, something might need to be done about the north eastern part of the map to allow more xeno access to it; otherwise for #6363 I would either need to add fog blockers up here (and no survivor spawns inside), or make another way to designate areas so they can be made inhospitable early game. Test merging it as is does smoke up the LZs correctly, but this is a large chunk of map that could be a un-assailable survivor hold.

image
image
image
image

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by Drulikar** [comment]
Removing stale exempt while it's seemingly abaonded. But I'm otherwise interested in this.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by harryob** [comment]
feel free to reopen when you want to keep working on this, remember you can just use updatepaths to fix all the old types to the new ones

**Pull request closed without merging**
