### PR TITLE
MP resprite and overhaul redux [IDB IGNORE]

### PR DESCRIPTION
**Pull request by ItsVyzo**
# About the pull request

Changes up the MP aesthetic to be more akin to Vietnam era MPs, via sprite changes. ~~Command roles no longer require Security hours (up for discussion). SMs are PFCs when they have less than 10 hours in the role, but become Cpls afterwards.~~

~~MP Cadets were removed in favour of folding them into MPs having ranks based on playtime, giving MP mains a way to see if a new MP is playing and show them the ropes.~~

~~The Warden has been removed as individual MPs can handle these duties on a case-by-case basis, or the CMP can assist.~~

Lastly, MPs are now provided either a M41A Pulse Rifle MK2 or a L42A Battle Rifle as their standard-issue rifle, as well as the choice of taking a magazine pouch. This will aid in ship and FOB defense.

An MP is just another boot, not a robot, a fellow marine making sure pandemonium doesn't break out on the ship via enforcing marine law. Their duty is to defend and keep order on the ship and the landing zones.

Reviving the great #1319 

# Explain why it's good for the game

There are various things we'd like to change about MPs to strengthen the bond between them and normal marines. Changing up the aesthetics is a good first step, with effective ML changes to follow, we can make the department a great part of the corps, which contributes both to keeping chaos on the ship to a minimum, and the security of the operation.

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

MP:
image

Chief MP:
image

</details>

# Changelog
🆑 Geeves, Frans_Feiffer, Triiodine, LTNTS
add: Overhauled MP aesthetics. MPs now have standard-issue rifles for ship and FOB defense.
del: Command roles no longer need security/MP hours.
/:cl:

### CODE REVIEW

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by ItsVyzo** [comment]
Need to find conflicts, so had checks run q-q

**Comment by Drulikar** [comment]
This needs to not overwhelm icon diff bot. Remove the [IDB IGNORE] tag when the DMIs aren't just removing basically all sprite changes from then to now.

**Review by realforest2001 — CHANGES_REQUESTED** [review]
There are many undocumented changes in this PR, and it's based on an outdated version of the repo, removing things that already don't exist, such as the MP cadet.

Removing the warden is also unnecessary, amongst the changes made.
DNM pending discussions with Maintainer team.

**Comment by ItsVyzo** [comment]
> There are many undocumented changes in this PR, and it's based on an outdated version of the repo, removing things that already don't exist, such as the MP cadet.
> 
> Removing the warden is also unnecessary, amongst the changes made. DNM pending discussions with Maintainer team.

Not part of my plan to remove warden, drafted as I need to rework a whole buncha things and resolve conflicts and add warden sprites

**Comment by realforest2001** [comment]
> > There are many undocumented changes in this PR, and it's based on an outdated version of the repo, removing things that already don't exist, such as the MP cadet.
> > Removing the warden is also unnecessary, amongst the changes made. DNM pending discussions with Maintainer team.
> 
> Not part of my plan to remove warden, drafted as I need to rework a whole buncha things and resolve conflicts and add warden sprites
My suggestion is to close it entirely, and start over with the sprite changes rather than basing on a PR from more than a year ago.

**Comment by ItsVyzo** [comment]
> > > There are many undocumented changes in this PR, and it's based on an outdated version of the repo, removing things that already don't exist, such as the MP cadet.
> > > Removing the warden is also unnecessary, amongst the changes made. DNM pending discussions with Maintainer team.
> > 
> > 
> > Not part of my plan to remove warden, drafted as I need to rework a whole buncha things and resolve conflicts and add warden sprites
> 
> My suggestion is to close it entirely, and start over with the sprite changes rather than basing on a PR from more than a year ago.

Will work with that, seems like there is a lot of changes that would need adjusting otherwise

**Pull request closed without merging**
