### PR TITLE
Whiskey Outpost fixes and rank changes

### PR DESCRIPTION
**Pull request by Googles-Hands**
## About The Pull Request
This adds to a small PR of mine and makes it into a larger one which contains the following: spelling fixes, changes to two job descriptions and a minor shuffle in the ranks of four jobs (Ground Commander, Lieutenant Commander, Quartermaster and Mortar Crew).
Fixes: #1682
removes the welding goggles from the Squad Engineers, as they already have welding helmets

### Spelling fixes
Always good to have
### description changes
Changes a reference to the Lieutenant Command who was called a "Gunnery Sergeant" when that is not his current rank (Captain) or the rank that I am changing him to (Second Lieutenant). He is just now referenced as his job title, Lieutenant Commander
### Rank changes
As I've explained in a discord post, the CO having the rank of Major while Captain Naiche, the canonical Commander of all marine forces on LV, is giving them orders.
This a leftover from the rank rework when the Ground Commander just had the rank of Commander, which put him one rank below the Captain. Dropping the CO to the difference from before, which in this case is First Lieutenant remedies this lore conflict.
Entailing this also forces me to drop the XO (who was a captain) to Second Lieutenant and the QM (who was a First Lieutenant) to First Sergeant. I don't think these changes are a detriment to the game as all marines besides the CO, XO and QM were enlisted men anyhow, which means it doesn't really matter if the CO is a Captain or First Lieutenant. The QM is still the third highest ranking marine, just no longer an officer.
I am also elevating the Mortar Crew from PFC to Lance Corporal as I think a man that went through specialized training which is now his dedicated assignment ought to outrank a rifleman, like a squad engie or medic.

## Changelog
:cl: Googles_Hands
fix: Changed the WO CO, XO, QM and Mortar Crew ranks to be more lore friendly
fix: Changed the WO reinforcement announcement to be more lore friendly
fix: Fixed the description of the WO XO and CMP in reference to the XO's title
spellcheck: Fixed a few misspellings in WO announcements
fix: removes redundant welding protection from squad engies
/:cl:

### CODE REVIEW

**Comment by Misttyy** [comment]
I think you should just Naiche to be Lieutenant-Colonel Naiche, or Major.

Easier solution that doesn't require the CO with an M46C and special armor to be a 1st Lt.

**Comment by Googles-Hands** [comment]
I mean, before, the CO was a Commander and had the gear that Captains had. It's just a different place, we don't need to compare to the Almayer structure.

**Comment by Googles-Hands** [comment]
Well, since in the few minutes I forked and created this, four PR's were merged, the merge conflicts check won't be finished. I am fairly certain that they don't conflict, but GitHub can't confirm it. Do I just redo it in a hope that no one opens new PR's in the meantime or do I just leave it?

**Comment by Huffie56** [comment]
> Well, since in the few minutes I forked and created this, four PR's were merged, the merge conflicts check won't be finished. I am fairly certain that they don't conflict, but GitHub can't confirm it. Do I just redo it in a hope that no one opens new PR's in the meantime or do I just leave it?

it take time sometime don't worry just wait...

**Comment by fira** [comment]
you can alwasy fix the conflicts if needed

**Comment by Huffie56** [comment]
@Googles-Hands  your still ban from discord?

**Comment by Googles-Hands** [comment]
> @Googles-Hands your still ban from discord?

No, I can be DM'd and pinged about the PR

**Comment by Huffie56** [comment]
> > @Googles-Hands your still ban from discord?
> 
> No, I can be DM'd and pinged about the PR

if you PR got stale you may want to post it on contributor channel to catch dev attention.
 seem to work for it but got remember to keep it for PR that got staled at-least one.

**Review by harryob — APPROVED** [review]

**Pull request merged**
