### PR TITLE
Thermal Alternate PR

### PR DESCRIPTION
**Pull request by c4xmaniac2**
# About the pull request

This PR is an alternate to https://github.com/cmss13-devs/cmss13/pull/4778 which strives to maintain the kit in the game. These items have been in the game for half a decade, and are/have been a non-issue for this entire time. What happens is someone (usually a surv) gets them, then they die and no one takes them because no one thinks they matter. This PR makes it harder to gain access to these items by placing them further afield, and often time placing them inside of a safe further increasing the opportunity cost and time sink required to achieve these items.

# Explain why it's good for the game

I do not think there is a warranted reason to remove thermals from normal play, they've been in the game and actively used for half a decade and I've hardly seen any complaints about them in all of that time. The spawns that were easily accessed have been moved further away, often put into safes so the risk is extremely high. I think this type of gear balancing (time and opportunity cost combined with risk vs reward) should be considered as the norm for dealing with survivor gear rather than simply removing or randomizing gear.

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

image
Science annex has had all of its random goggle spawners removed, and the old thermal spawn in chapel has been returned. With the removal of the west bridge in yard, its still in a high risk area to go for.

image
One of the thermal goggles has been moved into the NE of soro and put into a safe. Getting access to this item will be a major risk.

image
One of kutjevo's goggles have been moved into a safe and to the rear of construction. High risk area because its almost always weeded within 3min of the game starting, and you'll need to guess the safe's combo to get it.

image
The other kutjevo goggles have been moved to where the golden HG spawn is. Super far into the map, you'll need to take a major risk to get it.

</details>

# Changelog

:cl:
balance: Rebalanced the thermal placement on Soro, Science Annex, and Kutjevo
/:cl:

### CODE REVIEW

**Comment by fira** [comment]
If they're useful primarily for surv specifically you could just make their position radomized and/or have them break down after a certain amount of use

**Comment by Steelpoint** [comment]
Full randomization is my belief in the way forward, I'd want to discourage 'secrets' that only veteran players will find, or those who delve into the code. 

That, and all items should be very far into the map, perhaps even literally in the hive spots. Perhaps you can reward it by making the items a subtype that is unmeltable so the xenos can't deny the winning marines a reward.

**Comment by Skatuk** [comment]
Can we get thermals for each map thanks - CLF Main

**Comment by c4xmaniac2** [comment]
> Full randomization is my belief in the way forward, I'd want to discourage 'secrets' that only veteran players will find, or those who delve into the code.
> 
> That, and all items should be very far into the map, perhaps even literally in the hive spots. Perhaps you can reward it by making the items a subtype that is unmeltable so the xenos can't deny the winning marines a reward.

Full randomization has already proven to be a failure with the science annex changes done to it over a year ago. Survivor balance should be made with opportunity cost and risk versus reward in mind. If I spend 3 minutes going to an area and finding/obtaining an item I should not be rewarded with a random item (especially no item reward). Think back to how Halo 1, 2, 3, and Reach balanced the placement of power weapons/pick ups. The energy sword is placed in the center of the map where it has the highest risk, highest opportunity cost, and highest time investment to gain. This is also how quake and other similar games balance power pick ups. They're not randomized. Every side knows where everything is, its up to the individual to create a path from their already randomized spawn to acquire the tools they wish to use to survive. These items are being primarily placed in the sandbox for the survivors to use - with it being kept in mind that marines could get a hold of them, but the primary purpose of them being placed in the sandbox is for the survivor vs xeno TDM phase. Giving power weapons/pickups statuses such as unmeltable so marines could pick up a power item placed in the hive does not follow with any valid game design rule. This essentially would function as a "win more" mechanic, and would still be rushed by veteran players. This defeats the whole point. 

I can go into more detail, outside of maps which have had their loot meticulously balanced like chances claim, they should follow a kind of "strata." Where low valueable loot (think common gear) is available close to where most survs spawn and initially very safe areas like LZs. This kind of loot would be pistols, some rifle/shotgun ammo and very basic medical stuff. This would quantify a "Green zone." Extending out towards the center of the map would begin the "yellow zones" where risk vs reward begins to apply more. Here you would have better weapon spawns, access to medical kit, perhaps minor stims or something of the sort in harder to reach areas (more time consuming). From here you get to highly dangerous areas, the "Red Zones." These areas are close to the hives and have the best loot. Think flamers, maybe a stim like runnerblood-neuroblood, tac shotties, thermals and so on. The difficulty is that you do not want to encourage hive diving, and so these spawns must be placed accordingly to avoid survivors rushing and intercepting larva/young queens moving between hive spawn locations. So placing good loot inside of hive spawns should be avoided. 

image

Here's a pretty crude example on what I proposed to Morrow a while ago for rebalancing science annex to get rid of the randomized loot spawns. If Zonespace wants to approve it too, I can start to work on it when I have time. I want to do some other stuff like adding in gates to delay progress into certain areas for survivors and so on, but that's a topic not relevant to this discussion. My point in all of this is that fixes such as randomizing loot or deleting kit is a bandaid fix that doesn't solve the problem, nor does it make for fun gameplay. Power items make the sandbox more fun, not less. This is not a competitive game at the end of the day, and we don't need to streamline everything. I believe you can put the most comically overpowered things into your map so long as the risk and time cost to acquire the item is equivalent to the value of the item.

**Comment by Steelpoint** [comment]
My concern that pre-placement of powerful items will only benefit veteran players/powergamers, and that it won't actually resolve any issue no matter where you put the item unless it spawns underneath the Queen.

No matter where else you put a overpowered item on the map, all it will take is a 60 second detour for a survivor to run straight there, pick it up, then rejoin the other survivors

"Hey guys, I'm going to go grab the OP items, you can go set up in the meta hold" is how I expect this change to go. 

Alternativity the only change will be the usual suspects taking an extra 5 to 15 seconds to grab their overpowered gear than currently. 

Unless you go full randomization, or you make these items break when Marines arrive, then I think the items should still be removed as simply placing the items further inside a map makes no real effective change.

**Review by Zonespace27 — CHANGES_REQUESTED** [review]
This is a little out of scope, but could you make these take power a la NVGs, except that they drain much faster?

**Comment by c4xmaniac2** [comment]
> This is a little out of scope, but could you make these take power a la NVGs, except that they drain much faster?

Beyond my ability, sorry.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by Steelpoint** [comment]
If this PR does not go ahead can I put forward re-opening the removal version as the current overpowered items are not at all balanced with the current game state.

**Comment by c4xmaniac2** [comment]
Why not just implement this fix and then add then batteries later?

**Pull request closed without merging**
