### PR TITLE
/tg/ Status Effects Prelude D - Mob Freeze Refactor

### PR DESCRIPTION
**Pull request by fira**
# About the pull request

Another bit split off #4828 - this implements TRAIT_IMMOBILIZED partially by using it to replace freeze functionality. It does not include all the interactions with other traits because they're not yet in this version.

# Explain why it's good for the game
Stops issues with freeze getting stuck thanks to Trait magic. 
Also a mandatory passage point toward removing update_canmove in Part 1 PR

# Testing Photographs and Procedure
Tested Admin Panel Freeze/Unfreeze, that they were updated timely and not on Lifetick, Runner pounce, and interaction of both of them

# Changelog
:cl:
fix: Rooting effects should now properly update when stacked and unstacked.
/:cl:

### CODE REVIEW

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Review by harryob — APPROVED** [review]

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Pull request merged**
