### PR TITLE
M10 Auto Pistol

### PR DESCRIPTION
**Pull request by Zenith00000**
# About the pull request

Adds the "M10 Auto Pistol" as a primary "side-arm". Gives it a custom holster much like the m39 one, but can hold only the M10 + 8 magazines of "pistol ammo". Also adds various M10 ammo types boxes, normal HV, extended and drum (even larger extended).

Also side-note - also fixes the broken m39 holster gun camo icons and adds the missing "urban" and "jungle" too.

Tested the gun, may need some tweaking, but it works well as a hyper-fast-firing side-arm with low damage, should be fun.

Also the guns sounds/balance may be up for change if necessary, especially the sound.

# Explain why it's good for the game

Basically for a while now I've always wanted a new type of "SMG", I requested that someone make one,  instead I got the M10 - Auto Pistol, which is equally as cool as a new SMG, and perhaps even more unique. 

We don't have any types of fully automatic pistols, and it's something that I'm sure players would enjoy, as it's more of a side-arm then a primary weapon like the M39 is currently.

Generally it won't change much in the gameplay loop, rather just give you an additional option of playstyle. It will really just be an interesting alternative to the current side-arms, without taking away what makes them unique but being unique in itself.

It also is lore-accurate to the games at least. Here's the wiki-page for it if you want more specific information:

https://avp.fandom.com/wiki/M10_Auto_Pistol

I want to thank **Frans_Feiffer** for their amazing sprites, without them this whole thing wouldn't have come to fruition.

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

M10 Auto Pistol

<a href="https://drive.google.com/file/d/1kgqPovSrnjRLx-MwNKQZA6iYpUpW-UD6/view?usp=sharing">Video of the Gun in action</a>

</details>

# Changelog
:cl: Zenith, Frans_Feiffer

add: Added M10 Auto Pistol, new belt, magazines and boxes to standard marine vendors
fix: fixes the m39 holster sprites not showing correct camo
soundadd: added new M10 gunshot sound
/:cl:

### CODE REVIEW

**Comment by deathrobotpunch** [comment]
google drive is not public

**Comment by Zenith00000** [comment]
> google drive is not public

Yeah should be good now, my bad.

**Comment by deathrobotpunch** [comment]
also make sure to put add a proper PR description once it is off draft!

**Comment by deathrobotpunch** [comment]
one question, how does this look with attachments?

**Comment by Zenith00000** [comment]
> one question, how does this look with attachments?

m10modded

Like this, although obviously you can't use every mod, but honestly I was hoping for some custom mods that fit it better at some point, as the standard stuff is meh...

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Review by harryob — APPROVED** [review]
code

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Review by realforest2001 — APPROVED** [review]

**Review by Blundir — CHANGES_REQUESTED** [review]
make ext and drum ammo boxes have visual difference

**Review by Blundir — APPROVED** [review]

**Pull request merged**
