### PR TITLE
Faction Access & Almayer Security Overhaul

### PR DESCRIPTION
**Pull request by realforest2001**
# About the pull request
Removes the majority of accesses from non marine characters. No more free walking into CIC for the CLF, you're gonna have to work for it.
Creates faction specific accesses for basic things, these are not assigned to anything at the moment.
Overhauled how we get accesses so it no longer uses a bazillion different procs and instead relies on a centralised proc and defines.
Added specific access lists for WY Goons, PMCs, Liaison and Survivor Liaison as they're tailored to their uses.
Added very generic CLF and UPP lists, all UPP personnel have all their accesses FOR NOW.
Added a mapping var (access_changed) for identifying doors/objects that have non-standard access tags to allow for easier locating of things that need updates should access numbers be changed.

# Explain why it's good for the game
Right now we use a million different procs to get accesses. This is really confusing and makes it difficult to tell who's getting what as it's spread out all over the place.
As for why I'm changing ERT accesses, this is something discussed with Morrow and Nanu, it doesn't make a whole lot of sense for your average CLF plebian to be able to walk through all security measures on a military ship like they don't exist. Instead, they'll now get at most the generic Emergency Response codes to open specific areas of the ship key to responders - Medbay and Maintenance.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
code: Overhauled how ID accesses are assigned via proc, compiling all the many different procs we used into one.
add: Added faction specific accesses to all major factions.
del: Removed almost all marine accesses from non marine presets. No more free CIC access to CLF.
code: Removed duplicate code in the VAI file.
add: Adds a mapping var to indicate a door has non-standard access tags. This is to make it significantly easier for any future access changes to know if they need to look somewhere.
maptweak: Applied this var to every door I could find on the Almayer that has non-standard access. Colonies and other stuff to come in a future update.
add: Added various new accesses to colonial doors, added WY_SECURITY and WY_RESEARCH to marine research doors.
maptweak: Added reinforced piping to lifeboats area. Didn't make much sense for a cruicial part of the evacuation procedures to be prone to spontaneous explosions that can singlehandedly end a marine evacuation without hostiles ever seeing it.
maptweak: Added reinforced piping to the research closed loop (it's a closed loop). Also removed CIC access from containment shutters as CIC access can't open the doors.
maptweak: Changed a couple walls around research from standard to reinforced, to fit with the containment breach shutters.
/:cl:

### CODE REVIEW

**Review by Nanu308 — COMMENTED** [review]
Mapping lgtm, just changes to req_access

**Comment by blackdragonTOW** [comment]
Given that ERTs are being sent to take over a ship they know will be locked down to them, it wouldn't hurt to give them breaching charges.  Not in an absurd amount but maybe 1 per rifleman would make for interesting Loud/Quiet entry dynamics.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Review by harryob — CHANGES_REQUESTED** [review]
the rest is fine

**Pull request merged**
