### PR TITLE
Fix restore old dmifiles to avoid missing sprite.

### PR DESCRIPTION
**Pull request by Huffie56**
# About the pull request

# Explain why it's good for the game
# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl:
fix: restore old dmi files to avoid missing sprite(black  tiles).
/:cl:

### CODE REVIEW

**Comment by morrowwolf** [comment]
Missing:
West LZ1 on Fiorina
image

North LZ2 on Fiorina
image

South LZ2 on Fiorina
image

Southwest LZ2 on Fiorina
image

And like... so much more. Just fly around Fiorina you'll find a ton.

In the mean time I've put up a revert for testmerging. <https://github.com/cmss13-devs/cmss13/pull/4332>

**Comment by Huffie56** [comment]
yes note to myself never remove original dmi....
such a pain to fix...
not againt's just reverting the all change i made....

**Comment by Huffie56** [comment]
that make me realize i can't refactor the code this way i need to really think about how i want to approach it...

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Pull request closed without merging**
