### PR TITLE
M4RA Burstifre

### PR DESCRIPTION
**Pull request by joaopslima**
# About the pull request
Adds burstfire mode to the M4RA

# Explain why it's good for the game
Makes the M4RA a bit nicer to use. 

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl:
add: The M4RA battle rifle now has a two-shot burst-fire mode.
/:cl:

### CODE REVIEW

**Comment by Red-byte3D** [comment]
weapon named dmr

**Comment by HeresKozmos** [comment]
I don't see why the M4RA should get burst fire or why it even needs it in the first place, especially since the bullet damage got buffed a while back.

**Comment by GrrrKitten** [comment]
If it's a 2 shot burst fire, why not have it be via the burst fire augmentor attachment

**Comment by joaopslima** [comment]
The scout M4RA had already got burst-fire, so I thought it made sense to add it to the normal gun and to make it a little nicer to use too. Does the code work as intended though? I did it by intuition and might look more into DM in the future

**Comment by Zonespace27** [comment]
Thank you for the PR, but I don't think there's interest in this for the moment. I do think the M4RA needs some work, but this isn't it. (Also in the future, I'd recommend having more than 1 sentence in "why this is good for the game")

**Pull request closed without merging**
