### PR TITLE
[WIP] Reaper Reworked, Again Again

### PR DESCRIPTION
**Pull request by TheKillfish**
# About the pull request

A revival of PR #6610 with much rewriting and reworking. Though much has changed, the core goal remains the same: to rework @Geevies' original Reaper PR #1899 and @ThePiachu's Reaper Re-up #2234 to be better balanced and not end up being Carrier but better, along with some related miscellaneous changes that could be atomized into their own PRs but fuck it, done here instead.

In this state, the Reaper is a frontline support attacker, able to fufil both Carrier-esque duties such as planting eggs, carrying huggers, planting weeds, ordering special constructions and using pheremones, but also able to put on some hurt if need be, mainly being oriented around debilitating damage in the form of toxin rather than directly mulching marines like Praetorian, Crusher or Ravager can. My goal here has been trying to make Reaper fufil a niche that either no other xeno does or is being done in an appreciably different way compared to other xenos without either infringing on the niches of other xenos nor being too blatantly overpowered or utilizing features people generally don't like. Oh, and going hard on morbid, horrific vibes for the RP lovers. **Whether I have succeeded at that or not is up to the judgement of everyone else who reviews this and comes with feedback** of which I'd appreciate getting via Discord or mentioned here (even if at risk of being labled as off-topic by maintainers).

For the specifics regarding what I've given Reaper, [please read this HackMD writeup](https://hackmd.io/@Killfish/BkjLvhlfyl), although the following are TLDR-ish notes:
- Evolves only from Carrier.
- Stats are same as Carrier except for speed (Tier 3 instead of Tier 4), damage (Tier 3 - Tier 3 instead of Tier 2 - Tier 4), plasma (600 instead of 400) and tackling (uses Ravager's tackle stats).
- You can process unrevivable corpses into Flesh Plasma for your main source of marine debilitating. You can also carry up to 4 burst corpses around, useful for replenishing Flesh Plasma reserves if you run out!
- You may have the means for attacking on the frontline, but you are NOT a frontliner like Ravager, Crusher or Praetorian: you have no armor, you have no stuns, you have no mobility tools. You will die quickly if you try to pretend you are one of the aforementioned three. You are meant to weaken marines for others to kill or capture, not play Doom music and slash them at their cadeline.
- Though you don't have storage for bulk transport of either, you can carry eggs in one hand and huggers are nurtured while you hold them, much like Carrier. If you cannot be useful in a fight, you can cooperate with Carriers to build up your backline.

**Some miscellaneous inclusions**
- Plasma cost for pheremones is now a tweakable variable called aura_plasma_cost.
- Most single letter variables on trap.dm have been nuked.

# Explain why it's good for the game

The Drone line lacks any form of T3 and it'd be cool if they had at least one (for now), and T3 as a whole is pretty offensively biased; while I have ended up doing no better, at least Reaper does so in a way different than "move forward and slash the shit out of people" and isn't meant to be getting the kills itself. Wei's sprites for Reaper look sick and they deserve a more permanent spot in the game.

Pheremone costs being modular is useful and opens up interesting future ideas. Single letter variables suck.

# Testing Photographs and Procedure
Vidyas will be provided once I get my new PC set up.

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl: Killfish, credit to Geeves, sleepynecrons, ThePiachu
add: Adds new T3 Xenomorph called the Reaper, evolving from Carrier. It is a supportive attacker oriented around wearing down marines faster through use of toxin damage caused via reagent which itself is applied through a slash ability, a smoke emanation ability and smoke traps.. Also oriented around being a horrifying, morbid creature perfect for RP.
add: Passive: Flesh Plasma. Resource Reaper generates both passively and actively. Starts at 1 per tick, can be temporarily increased by normal slashes, max of 5.
add: 1st Ability: Haul Corpse. Target burst corpses to store them, target self to recover one. Can store up to 4 corpses. Number of stored corpses can be examined by others, and corpses are dropped on death.
add: 2nd Ability: Flesh Harvest. Target bodyparts on unrevivable corpses to harvest: targeting head does nothing, targeting arms and legs rip them off, targeting chest or groin chestbursts unbursted corpses. Generates 30 Flesh Plasma from limbs and 60 Flesh Plasma from bursting chests. Pauses decay on bonus passive generation for 5 seconds.
add: 3rd Ability: Reap. REPLACES TAILSTAB. Simple spriteclick melee with 2-tile range. Hitting humanoid targets injects small amounts of Sepsicine; a simple toxin that causes pain and toxin damage. Additionally increases bonus passive generation and pauses its decay for 5 seconds.
add: 4th Ability: Emit Mist. Consume 150 Flesh Plasma to create a small cloud of toxic mist that applies Sepsicine to humanoid targets, as well as slowing them and unallied xeno targets down.
add: Passive: Mist Mine. Consume 100 Flesh Plasma to charge an empty resin hole with toxic mist. Functions like Boiler neurogas traps.
code: Most single letter vars in trap.dm have been killed.
imageadd: Reaper and Reaper-related sprites.
/:cl:

### CODE REVIEW

**Comment by Zenith00000** [comment]
If you're pretty much making this Carrier ++ then perhaps I can convince Wei to add huggers to the sprite, since originally it was supposed to be this.

This is what it was originally supposed
unknown
 to be - the huggers:

Either way can't wait, keep it up. Looking forward to it.

**Comment by deathrobotpunch** [comment]
Can’t view the hackMD

**Comment by TheKillfish** [comment]
HackMD link should be working now, my potato brain forgot the "let everyone view it" option

**Comment by Red-byte3D** [comment]
Can you write tldrs of abilities in the cl? some people like reading those instead of opening prs and going into hackmd

**Comment by Red-byte3D** [comment]
I think you created a very well xenomorph aesthetic, but i feel like this is going to be less favorable, gameplay wise. I understand that the main point is that you can carry huggers, bodies and eggs but majority of the time two of these three is useless, 

you can carry eggs yes but two per hand as opposed to just carriers being able to store them kinda makes this nearly moot as an evolution. Same with carrying huggers.

Not to put pressure on you but xenomorph side hasnt had a new caste in what i belive is 3-5 years~~? Not counting king since its not in the normal gameplay loop.

I understand that you wanted to mainly go "support" but as it stands i think you are scared to add abilities that people are supposed to fear, im not sure what you are actually supporting as reaper, helping...drones build? Making carriers more lethal by allowing them to make more traps? This caste currently seems like its just going to be wandering around aimlessly. Not being a frontliner doesnt mean you arent deadly. The entire casteline up is very heavy on this, yes you dont have much to fear about a drone when you're far away and theyre usually easy kills, but if they know what they are doing they can instantly just two tap you and win the fight. With its speed and massive size most people will be able to just shoot you to death before you can even two tap them. 

I think you should look more into making this an actual support instead of just a xenomorph whos never supposed to show its face, hivelord and drones can make walls while not showing their face, burrowers are usually sneaky because theyre backlining or making traps. carriers dont show themselves because theyre probably just planting eggs and making traps because they have the storage to do so, you've removed everything from this caste and gave it basically nothing that would reinforce staying behind. 

I think the first step is to make all tier 2 drone's be able to evolve into this so nobody feels the "im locked to this tier 2" effect anymore, and can opt out to tier 3 tier 1 as they wish since you hold your bonus and people dont waste another 200 going hive  > drone > carrier

The trap filling is good but im not seeing why anyone would ever choose these traps over the burrower traps, as it stuns people and does good damage INSTANTLY same goes for spitter. While the damage from the toxin is pretty decent, it takes way too long for it to matter as if its in the heat of the battle, it wont matter at all because most people will instantly retreat once it goes off (which is a good way for scaring away people who doesnt know how the ability works, more average players will push whatever they were pushing regardless because the damage takes a good while to rack up.) and most people can probably already counter this with tricord, and dylovene if theres a medic which doesnt stop them from pushing. (The difference between this and burrower trap is that the burrower traps can work aggressively and defensively, either stunning people so the xenos can do alot of damage to the person or letting them escape, this doesnt really achieve either of them)

The gas shares the same problem with above.


Why did you remove the old flesh construct abilities? I feel like they were pretty cool, i had a few ideas while working on the pr myself that i just didnt have time to finish due to real life stuff. Dm me on discord, i'd love to talk to you more about this caste if you want and i think it has more potential. (i am banned from the discord)


image

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by TheKillfish** [comment]
for fucks sake, git and vsc, why do you insist on making conflict resolving so fucking backwards. closing this and making yet another fucking branch it seems

**Comment by Dicerson** [comment]
I think there are some things wrong this design at a base level, but I do love the aesthetic and the intent. The _space_ its meant to occupy, niche/design wise, is one that I think is fitting for a potential T3 drone caste.

BUT as red byte pointed out it has some issues. The poison isn't very good if its too slow, and its too good if its too fast. Finding that middleground between where its good enough to justify existing but not so good that you kill better than the other T3s is tough. I think a way to meet that middleground is to alter the poison's properties slightly and change the reaper's Stat dynamics a bit. I propose the following:

The Reaper is a High Speed (somewhere between Prae and Lurker), High Armor xeno (Crusher-tier armor) but it doesn't have much health (so despite its armor it still can't take much punishment, and it is especially vulnerable to AP ammunition and fire). This emphasizes its purpose as a hit n run type of caste that trolls the frontlines but doesn't truly hold them. Its instant damage on hit will be relatively low (only a little higher than the Carriers) but it will have a sort of armor penetration of its own and of course a poison that applies on every single hit. The poison is essentially a pain toxin. One hit will knock a marine down but only after a long time and if they don't have any medical attention or pre-existing pain meds, multiple hits will knock him down faster making the Reaper primarily pain-oriented in how it takes marines down. But uniquely, the poison will _slowly_ negate other chems in a marine's system. So if a marine pre-dopes with a ton of pain meds, the Reaper can chew through those and possibly secure a pain crit faster than the other T3s could at the cost of just not doing much in the way of actual raw damage. The cost of having this ability to "bypass" pain meds is that every single attack, basic or otherwise, costs plasma and you _cannot_ attack at all without plasma. Furthermore, your plasma capacity will be very high but your regen will be innately very low. Your costs aren't particularly high either, but unless you make use of the Reaper's other utility you will spend lots of time out of combat just waiting for regen.

It will have only 1 activated "combat" ability which is similar to the sentinel's neuro-stab, except instead of making the next tail attack apply a fast acting neuro-toxin it makes the next _stab_ apply a large dose of the poison. The plasma cost is high and the cooldown moderate, making this not a spammable ability that you can use in every engagement.

But that's only its main combat use, the numbers should line up such that it isn't really as good at taking down marines directly as any of the other T3s; except in the case of heavily armored marines pre-doped with pain meds. The above is mostly just to ensure that it is still a T3 and therefore a bad idea to try and take on solo and significantly threatening all the same even against 2 or 3 marines (if played well).

The Reaper's primary Utility- and why it is in the drone caste- is its utility ability. The Reaper does not steal and store corpses as that would be essentially giving a basic xister the ability to effectively gib multiple marines at once en masse. Sure they might not be technically gibbed but if they're dead and you move them to a back corner of the map somewhere noone knows they are effectively out of the round anyways which is the same net result. Instead the Reaper steals and eats specific limbs off of corpses. By using the ability and targeting a marine, after a relatively short timer the Reaper automatically rips off a limb, eats it, and gains a large amount of plasma over the cooldown of the ability (which will be relatively short, 5-10 seconds somewhere in that range). The limb is whichever one you have targeted using the normal means. The timer breaks if either the Reaper or the target move at all or if the marine is "resisting" (IE not prone on the ground for any reason, essentially the same conditions needed to nest).

This serves a dual-purpose; First it is the Reapers primary source of plasma regneration, as even with pheromones its base regen is just not that great; Second, and most importantly, you're ripping limbs off of marines for free! No chances, no RNG, if they're on the ground for more than a second or two, goodbye to a limb. The Reaper can even target corpses, but can't target head or torso, of course. So if a marine goes down in the xeno lines (such as bleeding out while being dragged away, or getting executed, or just gets abandoned in a temporary retreat) a Reaper can take a bit of time and de-limb them entirely essentially ensuring that even if they are rescued they have to go back to the ship for hella surgery. Its not quite gibbing, but it takes them out of the round long enough (and since it requires multiple uses on a 5-10 sec cd isn't the fastest process) that it serves the same essential purpose without being overwhelmingly broken. Their high speed and armor also supports this ability, letting them abuse short-term advantages like a boiler cloud or a queen screech to quickly gain access to a corpse and then rip off a limb before trolling away back to safety. Being able to do it to any downed marine, not just corpses, also gives it major teamwork opportunities with all three of the combat castes, giving value to simply knocking a marine down even if you dont have the time to whack them into paincrit or drag them somewhere.

**Pull request closed without merging**
