### PR TITLE
reduces job hud clutter for roles that don't need it

### PR DESCRIPTION
**Pull request by stanalbatross**
## About The Pull Request

This PR removes the viewing of most job hud icons from most headsets, other than command headsets and head of department headsets.

Normal headsets can still see CIC, ACS, and squad role job icons.

## Why It's Good For The Game

Reduces the MASSIVE amount of clutter that comes with every single person in the game having a little square by their head. There's a reason that marines don't have these icons. Additionally, it will improve roleplay as marines will have to look a little harder to find out what job random people on the ship are. Also cuts down on the annoying issue of MPs seeing two of every single hud icon.

## Changelog

:cl:
balance: Reduced the number of job HUD icons that most headsets can see. These have been limited to CIC, squad, and aux combat support roles. Command and head of department headsets can still see all roles' job HUDs.
/:cl:

### CODE REVIEW

**Comment by JohnDoe50974** [comment]
Anti-QoL change. Claiming this will "improve roleplay" is preposterous, it'll just re-add unnecessary fuss when attempting to identify another player.

**Comment by Segrain** [comment]
Sounds completely pointless. There is no reason to create an entire new HUD overlay for every marine for the purpose of... forcing us once again examine everybody in medbay to tell the difference between a nurse, a doctor and a CMO? _Not having to do that_ was a QoL change. This is the _opposite_.

**Comment by stanalbatross** [comment]
> Anti-QoL change. Claiming this will "improve roleplay" is preposterous, it'll just re-add unnecessary fuss when attempting to identify another player.

If a job is not wearing their proper clothing, it should be harder to identify them on sight. This serves to discourage wearing improper clothes. If people keep wearing the right clothes for their job it won't get any harder to identify them.



> Sounds completely pointless. There is no reason to create an entire new HUD overlay for every marine for the purpose of... forcing us once again examine everybody in medbay to tell the difference between a nurse, a doctor and a CMO? _Not having to do that_ was a QoL change. This is the _opposite_.

Doctors, nurses, and CMOs all wear unique gear (admittedly since doctors got labcoats, which I was against, they do look a bit more similar now). It won't end up being much harder. Additionally, PFCs should not know the difference between medbay personnel they have no experience with on sight.

**Comment by Zangeiti** [comment]
make it an option to toggle this on/off in preferences

**Comment by stanalbatross** [comment]
> make it an option to toggle this on/off in preferences

considering how clearly a good chunk of people really don't want this, I'll do this instead (make it a headset toggle or something)

**Pull request closed without merging**
