### PR TITLE
(QoL)Bring back the old engi prep tool vendors

### PR DESCRIPTION
**Pull request by PhantomEpicness**
## About The Pull Request
This quality of life PR brings back the old engineering tool vendors before they were removed, though lacking the hacked items available or the coin equipment selection. It sports all basic tools and does not contain upgraded welders or anything of the sort. 

## Why It's Good For The Game

Engineers are pretty much forced to take a toolbelt for basic fucking tools or have to run all the way to engineering/maint. Which sucks because you are provided the illusion of choice when choosing a belt and less flexibility. Tools pouch isnt much better as it has a wirecutter rather than a crowbar, which is a pretty much-required tool and forces you to look for one.

It only has basic tools meaning that if you want a high-cap/industrial blowtorch, you still need to go to engineering and hack a vendor there. Also gave it some etools because those should honestly be free. 

## Changelog

:cl: TotalEpicness
add: Added back the engineering tool vendors to Comtech prep
/:cl:

### CODE REVIEW

**Comment by MusselMain** [comment]
Isn't there an entire locker in upper engineering that contains like 7 industrials?

**Comment by PhantomEpicness** [comment]
> Isn't there an entire locker in upper engineering that contains like 7 industrials?

yes, but this is QoL. The intention of this PR is to make it so engineers can get basic tools without needing to go to engineering. I'd argue that giving engis industrials at the start is powercreep, even though most good engis already l;oot engineering.

**Comment by PhantomEpicness** [comment]
bump

**Comment by Nanu308** [comment]
Powercreep and its intended, if people want different tools such as the HighCapacity they can go through the extra motions to acquire them.

There is an Autolathe etc. near the hangar. Mind you, engineer's are getting a potential goodie change with some welding equipment changes made by geeves from memory.

Closed and Denied for now.

**Comment by Nanu308** [comment]
Misread a couple things, drop the double up of equipment which you can get already from the "Essential Engineer Set" and the other Squad Engineer Vendor/s.

**Comment by PhantomEpicness** [comment]
> Misread a couple things, drop the double up of equipment which you can get already from the "Essential Engineer Set" and the other Squad Engineer Vendor/s.

done

**Review by Nanu308 — APPROVED** [review]
lgtm

**Pull request merged**
