### PR TITLE
Adds all missing lineart images in gun examine

### PR DESCRIPTION
**Pull request by Blundir**
# About the pull request

Adds all missing ones mentioned in https://github.com/cmss13-devs/cmss13/issues/5733, i'll handle some others and resprites of old ones in another pr.

ljaipkGMkF

All sprites by me.

# Explain why it's good for the game

Missing icons bad

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

dreammaker_Xvmf2lXvQS

</details>

# Changelog

:cl:
imageadd: adds lineart images for almost all guns that didn't have it
code: missing lineart error is now a lint
/:cl:

### CODE REVIEW

**Comment by Drulikar** [comment]
Of note the weapons that remain w/o lineart are:
```
[13:21:22]DEBUG: /obj/item/weapon/gun/lever_action does not have a valid lineart icon state, icon=icons/obj/items/weapons/guns/lineart.dmi, icon_state="r4t-placeholder"

[13:21:22]DEBUG: /obj/item/weapon/gun/lever_action/r4t does not have a valid lineart icon state, icon=icons/obj/items/weapons/guns/lineart.dmi, icon_state="r4t"

[13:21:22]DEBUG: /obj/item/weapon/gun/revolver/m44/custom/pkd_special/k2049 does not have a valid lineart icon state, icon=icons/obj/items/weapons/guns/lineart.dmi, icon_state="lapd_2049"

[13:21:22]DEBUG: /obj/item/weapon/gun/shotgun/double/twobore does not have a valid lineart icon state, icon=icons/obj/items/weapons/guns/lineart.dmi, icon_state="twobore"

[13:21:22]DEBUG: /obj/item/weapon/gun/smg/uzi does not have a valid lineart icon state, icon=icons/obj/items/weapons/guns/lineart.dmi, icon_state="uzi"
```

**Review by Drulikar — COMMENTED** [review]
No more debug logs show up for missing lineart now. The debug could be escalated to an error if we wanted to enforce all weapons have lineart now:
https://github.com/cmss13-devs/cmss13/blob/04b313463e6645f7a68ffc62e7a8976a10cbc002/code/modules/asset_cache/asset_list_items.dm#L393-L394

**Comment by Blundir** [comment]
> No more debug logs show up for missing lineart now. The debug could be escalated to an error if we wanted to enforce all weapons have lineart now:
> https://github.com/cmss13-devs/cmss13/blob/04b313463e6645f7a68ffc62e7a8976a10cbc002/code/modules/asset_cache/asset_list_items.dm#L393-L394

That'd be ideal, they are not hard to make, also would be easier to maintain it in newer prs with such reminder

**Comment by Drulikar** [comment]
> > No more debug logs show up for missing lineart now. The debug could be escalated to an error if we wanted to enforce all weapons have lineart now:
> > https://github.com/cmss13-devs/cmss13/blob/04b313463e6645f7a68ffc62e7a8976a10cbc002/code/modules/asset_cache/asset_list_items.dm#L393-L394
> 
> That'd be ideal, they are not hard to make, also would be easier to maintain it in newer prs with such reminder

Then feel free to do what the comment says in the above linked code

**Review by Drulikar — APPROVED** [review]
code is fine

**Pull request merged**
