### PR TITLE
IB fixed fun fact

### PR DESCRIPTION
**Pull request by zzzmike**
# About the pull request

Adds a fun fact for number of times internal bleeding was fixed, similar to the revives fact.

# Explain why it's good for the game

I'm not a huge fan of fun facts in general as it sometimes incentivizes bad behavior (such as focusing on revives exclusively and neglecting other duties just because it has a fun fact), but between removing the revives fact or just adding a second medical fact, I went this direction.

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl:
add: fun fact for internal bleeding fixed
/:cl:

### CODE REVIEW

**Comment by Git-Nivrak** [comment]
Could be cool if instead you made a fun fact for medics comprised of all the activities you can do (defibbing, healing, fixing IBs etc)

**Comment by zzzmike** [comment]
> Could be cool if instead you made a fun fact for medics comprised of all the activities you can do (defibbing, healing, fixing IBs etc) so people won't focus on one activity

If you do a PR I will happily close this one

**Review by kiVts — APPROVED** [review]
Looks good

**Comment by Skatuk** [comment]
How about instead of fixed IB's, Its how many IB's you've recieved from xeno's

**Pull request merged**
