### PR TITLE
Fixed misaligned chestrig sprite

### LINKED ISSUE #7172: Technician Welder Chestrig Sprite oversight
### Testmerges

irrelevant

### Round ID

_No response_

### Description of the bug

When items are put into the Technician Welder Chestrig, it changes sprites to the 'open' sprite. When you open it, it changes back to the 'closed' sprite. Furthermore, the 'opened' sprite is misaligned with the backpack slot.

### What's the difference with what should have happened?

isn't it obvious

### How do we reproduce this bug?

1. put items in a welder chestrig
2. see how it changes sprites to 'open' and moves to the left in the inventory slot

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

### PR DESCRIPTION
**Pull request by Willzadl**
# About the pull request

fixed misaligned chestrig sprite(s) - wasn't able to create a better sprite for the half filled one since i suck at spriting but hey at least it isn't aligned wrong anymore. fixes #7172 - it seems like the half filled sprite is actually meant to look like that since it correlates with the other chestrig, but if anyone wants to make a better sprite feel free

# Explain why it's good for the game
it moves left and right when you half fill it, which looks stupid, so i fixed it

# Testing Photographs and Procedure
works fine

<details>
<summary>Screenshots & Videos</summary>
Screenshot_2659

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl:
fix: fixed misaligned chestrig sprites
/:cl:

### CODE REVIEW

**Comment by Willzadl** [comment]
i might be able to do a better job on this in a few months when i get unbanned from the discord, since i need some help with it :+1:

**Comment by Willzadl** [comment]
oh i fucked it up didnt i

**Review by harryob — CHANGES_REQUESTED** [review]
you deleted `skinnerrangerpack` for some reason... don't do that.

**Comment by Willzadl** [comment]
how in the hell

**Comment by Willzadl** [comment]
ok it should be fixed now 🥰 @harryob

**Comment by Willzadl** [comment]
something's wrong

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Review by harryob — CHANGES_REQUESTED** [review]
please check the icondiffbot, you've changed aw hole bunch of sprites you weren't intending to. also you need to undraft prs when you want them reviewed again

**Comment by harryob** [comment]
pr stale with requested changes, make a new pr if you're still interested in working on this

**Pull request closed without merging**
