### PR TITLE
Updates placeable flag turret to the UA flag, rather than a generic orange flag.

### PR DESCRIPTION
**Pull request by blackdragonTOW**
# About the pull request

Swaps out the two tone orange flag for the flag turret with a stylized UA flag (the animation should be matched as well)

# Explain why it's good for the game

Flavor good! Marines are more likely to be motivated by a UA flag rather than the generic orange.

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Capture

</details>

# Changelog
:cl:
imageadd: altered the turret flag to the UA flag, from generic orange
fix: Flag turrets now correct reference the destroyed state
/:cl:

### CODE REVIEW

**Comment by realforest2001** [comment]
Super nitpicky, but the destroyed icon state is misspelt, could you fix it at same time?
Not mandatory though.

**Comment by harryob** [comment]
CleanShot 2024-01-31 at 12 46 24@2x
a commandment

**Comment by blackdragonTOW** [comment]
PR existed before the commandment.  *guffaw*

I'll get screenies soon.

I'll also see about fixing the typo, I'll just want to make sure that all refs are corrected as well.

**Comment by blackdragonTOW** [comment]
> Super nitpicky, but the destroyed icon state is misspelt, could you fix it at same time? Not mandatory though.

Update on this front.  The icon references are spelled correctly in planted_flag.dm... meaning the destroyed state of these flags has just been busted since forever.    I guess this is a bug fix PR now too, lmao.

**Review by nauticall — CHANGES_REQUESTED** [review]
Red on the flag is a little too saturated. Try reducing it to a desaturated, darker red sort of like #6b1515. Also change the pure white to more of a grayish color.

**Comment by blackdragonTOW** [comment]
> Red on the flag is a little too saturated. Try reducing it to a desaturated, darker red sort of like #6b1515. Also change the pure white to more of a grayish color.

Desaturated!

**Review by nauticall — APPROVED** [review]
yuhh

**Pull request merged**
