### PR TITLE
COs can now vend windbreakers from their clothing vendor 

### PR DESCRIPTION
**Pull request by tallfission**
# About the pull request

This PR adds green, brown, and grey windbreakers to the CO clothing vendor, under the 'utilities extra' section. 

# Explain why it's good for the game

The windbreakers look good and fit for commanding officers, I see no reason for them to /not/ be in the CO's clothing options. Personally I think it goes nicely as a more utilitarian alternative to the more flashy bomber jacket. 

# Testing Photographs and Procedure

Booted it up on a private server, vendor stuff was there, I didn't see anything break. 

<details>
<summary>Screenshots & Videos</summary>
</details>

# Changelog

:cl:
add: COs can now vend windbreakers from their clothing vendor
/:cl:

### CODE REVIEW

**Comment by thevandie** [comment]
add expedition too, I gave it to the CL, may as well have complete parity

**Comment by tallfission** [comment]
> add expedition too, I gave it to the CL, may as well have complete parity

nah im too lazy

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by tallfission** [comment]
closing because im too lazy to actually fix it right now. will remake/reopen this when i'm actually going to take the time to resolve conflicts

**Pull request closed without merging**
