### PR TITLE
tacmap refactor

### PR DESCRIPTION
**Pull request by harryob**
the tacmap now uses minimap code (better, stronger, faster) from tgmc (thanks gang)

:cl:
refactor: the tacmap is now better, everywhere it appears, for the queen and cic
ui: the orbit menu now has icons (from the minimap)
add: ghosts now get a minimap
/:cl:

### CODE REVIEW

**Comment by Starfirejordan** [comment]
image
you need to slightly adjust it

**Comment by TiviPlus** [comment]
You're welcome

**Comment by harryob** [comment]
>@TiviPlus: You're welcome

it really is awesome code, even if i am dragging it through the dirt by putting it in cmcode, thank you!

**Review by kugamo — APPROVED** [review]
Sprites

**Review by morrowwolf — APPROVED** [review]
Looks good, tests went well.

Code approved.

**Pull request merged**
