### PR TITLE
Blowtorch Unnesting

### PR DESCRIPTION
**Pull request by Geevies**
## About The Pull Request

You now need a blowtorch to cut someone free from a nest. Destroying the nest by attacking it with other weaponry also works.

## Why It's Good For The Game

It's cool, and is how the ME3 Hand Welder is used in A:CM, which we get a lot of inspiration from. It shouldn't have that much of a gameplay impact.

## Changelog

:cl:
balance: Unnesting someone by hand now takes eight seconds, cutting them free with something sharp like a knife takes three seconds, and using a blowtorch to cut through takes one second.
/:cl:

### CODE REVIEW

**Comment by Listaless** [comment]
Actually has a decent amount on impact e,g Scout sneaks in or someone somehow fucks up nesting your unlikely going to be able to free people as not a lot of people carry welders(Generally only engi's,synth's and VC)

**Comment by c4xmaniac** [comment]
Why do you need to take eye damage to unnest people, or to free dead prebursts from nests. This has pretty big gameplay impact for 0 reason. Now scout is nerfed even harder.

**Comment by stanalbatross** [comment]
`It shouldn't have that much of a gameplay impact.`
I doubt this

Also the lore argument doesn't work unless you make sharp stuff also able to break nests

**Comment by stanalbatross** [comment]
> `It shouldn't have that much of a gameplay impact.` I doubt this
> 
> Also the lore argument doesn't work unless you make sharp stuff also able to break them out

**Comment by Superreallycoolguy** [comment]
geeves...please stop with some of these PRs I beg you, this is just an awful idea. I completely agree with the people above, just no dawg

**Comment by monkeysfist101** [comment]
I feel like a compromise here would be to allow you to un-nest both unarmed (like Ripley in the film) and with a hand welder (like Winter in A:CM), but that the unarmed un-nest would take a bit longer.

**Comment by joookschad** [comment]
If your argument is "well the blowtorch is used like that in A;CM" then it should keep the eye cover, like the blowtorch in A:CM

**Comment by Nanu308** [comment]
New changes made to the PR makes this a better addition than the original PR did, approved for prolonged testing aka mergeable.

**Comment by DylonBR** [comment]
based bot closes bad PR

**Review by stanalbatross — APPROVED** [review]

**Pull request merged**
