### PR TITLE
Blood work

### PR DESCRIPTION
**Pull request by morrowwolf**
# About the pull request

This PR is a work in progress.

This PR will do the following:
Make blood loss effects happen faster
Remove quickclot
Refactor quickclot functionality into a chem property
Nerf iron
Remove free refills of medical items in vendors
Allow for blood bags to be used in the field while held

# Explain why it's good for the game

Bloodloss is not nearly severe enough for being one of the highest reasons for death in military environments and THE highest reason for preventable death.

Quickclot being able to easily and abundantly turn off a mechanic is bad. The functionality should be rare and is now shifted over to research.

Iron is far too potent as it stands with zero downsides. It will now cost nutriment to process and give less.

Medical refills are far too prevalent. There should be thought put into medical resupply beyond a single medvendor.

This is one step towards making the medical process both slower (in an attempt to slow down the game overall) as well as more intricate and thoughtful.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>
Testing will be ongoing.

</details>

# Changelog

Official changelog closer to finish.

### CODE REVIEW

**Comment by Ultimate-Fluff** [comment]
Please do not remove refills. How will I refill my tramadol during field surgery?

**Comment by Weuyn** [comment]
Buffed bleeds sounds really annoying to deal with, they're already really strong but the marines never notice because they're dead in 6 slashes anyway (light armour) and once they're dead bleeding stops.

Nutrition damage from iron also sounds annoying. Medics are just going to ask for bigger iron/sugar pills and make the doctors hate life even more.

**Comment by SarahJohnson489** [comment]
Ah yes, the "slow the game" which is just a codeword for hijack speedrun if the initial push flops. Good thing xenos damage, burst damage, and increased ranged damage hasn't been powercreeped so this would have a disastrous effect. Phew. I was almost worried that all the high power abilities, ranged abilities, and marine FF would cause tons of bleed as they already do every round every day! Man that would be embarrassing!

**Comment by morrowwolf** [comment]
Alright I'm atomizing this because some stuff I want done before others. *dab

**Pull request closed without merging**
