### PR TITLE
Slug Nerf

### PR DESCRIPTION
**Pull request by usnpeepoo**
# About the pull request

This PR nerfs slugs by removing the 2 second super slow. It also increases the damage by 10. This is to reduce the insane potential slugs have with their slow, and to even out slugs a little more.

# Explain why it's good for the game

Slugs are very powerful, and the fact that it has a 7 second slow (2 of which are superslow seconds) is insane. It knocks down as well, which leaves time to quickly equip another weapon and is simply too much. This PR would fix that issue, however it will not leave slugs in a terrible state as it still has the slow, and marines could possibly still kill the slugged xeno within the time frame (without the need for a 7 second slow).

# Testing Photographs and Procedure
i made a private server, tested the damage and slow on both runner/lurker/warrior/other t1s. It feels like a reasonable amount.

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl:
balance: Slugs now longer superslow.
balance: Slugs have their damage increased by 10.
/:cl:

### CODE REVIEW

**Comment by fira** [comment]
That's not how status effects work.
 - 5 does not mean 5 seconds but 5 ticks of Human Life controller which should result in random between 8 and 10 seconds depending on ticking phase
 - The durations do not stack, Slow and SuperSlow reduce separately with SuperSlow overriding, so it is really 5 and not 7

**Comment by usnpeepoo** [comment]
> 

so would i reduce or increase it then

**Comment by Diegoflores31** [comment]
werent direct number changes not allowed ?

**Comment by fira** [comment]
> so would i reduce or increase it then

I dunno depends on what you want to do. But I'm just putting forward the fact that status effects balancing is pretty awkward and frankly a waste of time. That being said the SuperSlow is real random as a result (2 to 4 seconds) so it might make sense to remove it...

**Comment by stanalbatross** [comment]
kinda unjustified nurf... slugs are not that strong... gonna close

**Pull request closed without merging**
