### PR TITLE
Makes Dropship Pilot Two Dropship Crew Chief hours, instead of Five Marine squad hours.

### PR DESCRIPTION
**Pull request by HumiliatedGoblin**
# About the pull request

### Changes the hours from five marine hours to *two* DCC hours, something that should've been done years ago.

# Explain why it's good for the game

I'm **SICK** and **TIRED** of TROGLADYTE dropship pilots who don't even ATTEMPT to read the guide, and think they're the coolest person ever after direct firing without a laser detector, wiping the front with six minis, and they don't even have the GAL 
to apologize afterwards. I want this to END.

It's honestly comical how terrible pilots have gotten, so much so that I refuse to call them in unless they have a silver medal or above. It makes absolutely no sense how pilots only need five hours as a marine to have the power to kill fifteen marines with one napalm. By making it two DCC hours, you give them a chance to learn how to fly, and also get tips from experienced pilots.

I honestly believe that the reason marine winrate is so low is because of the sheer incompetence shown by command slots and fire support-ists, and by making the hours needed higher, HOPEFULLY marines can actually use fire support without fear of the person faltering and killing everyone.

I was thinking of having Two Fireteam Leader hours as well, but because of the moving away of RTO's, I didn't think it was necessary and would've been overkill. Might be something to consider though.

was brought upon by this screenshot:
https://media.discordapp.net/attachments/604397850675380234/1155395437256249354/image_4.png

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

</details>

# Changelog
:cl: bostonthebear
add: Changes pilot officer timelock from 5 hours as squad marine to 2 hours as DCC
/:cl:

### CODE REVIEW

**Review by morrowwolf — CHANGES_REQUESTED** [review]
Drop to 2 hours pretty please

**Comment by HumiliatedGoblin** [comment]
> Drop to 2 hours pretty please, otherwise this is fine

done!

**Review by morrowwolf — APPROVED** [review]

**Review by morrowwolf — CHANGES_REQUESTED** [review]
OK I shouldn't review things at 4 AM.

Make a timelock type for dropships named like JOB_DROPSHIP_ROLES and have both PO and DCC hours count so people who have never played DCC don't have to go back.

**Comment by HumiliatedGoblin** [comment]
> OK I shouldn't review things at 4 AM.
> 
> Make a timelock type for dropships named like JOB_DROPSHIP_ROLES and have both PO and DCC hours count so people who have never played DCC don't have to go back.

I THINK that worked? I've never coded before, so tell me if I've missed anything.

**Comment by morrowwolf** [comment]
TM'ing because I hate testing timelock stuff on local but looks good from code

**Pull request merged**
