### PR TITLE
Cockpits have windows to passenger area now

### PR DESCRIPTION
**Pull request by TeDGamer**
# About the pull request

Add windows behind the cockpit seats. Now marines can be more aware of what's going on inside the cockpit and pilots can see a runner trying to sneak up to them without having to rely on cameras.

# Explain why it's good for the game

There were many a round where I have seen POs forgotten in the cockpit because marines don't seem to check on them so they go perma-dead even when they perfectly had a shot at getting revived. This is due to how the windows closing.

Also this allows pilots to be more aware of what's going on outside so if someone is sneaking up on them, they don't need to rely on cameras that are easily destroyable.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Alamo 

Updated-Alamo Windows 1

Normandy

Updated-Normandy Windows 1

</details>

# Changelog

:cl:
maptweak: Alamo and Normandy cockpits have windows to passenger area now 
/:cl:

### CODE REVIEW

**Comment by Nanu308** [comment]
mapping lgtm, need sprite review

**Review by sleepynecrons — CHANGES_REQUESTED** [review]
Windows and silver detailing need to match how it's done on the inner cockpit windows.

I68zDWt

**Comment by TeDGamer** [comment]
> Window outline/shading and silver detailing need to match how it's done on the inner cockpit windows.
> 
> I68zDWt

Updated to try to match it as close as I can (check replaced screenshots )

The silver lining on the inner ones are 3-pixels vs the ones on the walls here which is 4. 

Let me know if you wish for me to change it

**Review by sleepynecrons — APPROVED** [review]
Sprites look good to me now nice. Approved

**Comment by carlarctg** [comment]
Cringe handholding, POs getting surprised by runners is fun and soulful - they already have the prying open to notice beforehand

**Pull request merged**
