### PR TITLE
The Standardization: End of Evangelion

### PR DESCRIPTION
**Pull request by NewyearnewmeUwu**
# About the pull request
This removes all /obj/structure{ items from map files and replaces them with appropriate objects. In some cases I've made nonfunctional prop versions of other items, and in others this simple organizes them all under one umbrella.

I also added a checkgrep to detect this kind of obj/structure misuse, so that future mappers will be more efficient.

# Explain why it's good for the game
This removes almost 4x the code it adds, and makes things way clearer for anyone editing the maps. It also adds the opportunity to use these objects in gameplay in the future, ie. fixing broken pipes on the Almayer, etc.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
refactor: massively refactored /obj/structure{ objects into proper items
maptweak: every /obj/structure{ item in map files has been removed.
/:cl:

### CODE REVIEW

**Comment by NewyearnewmeUwu** [comment]
Some of this stuff is so single-use that  I didn't bother adding the update_path entry for it, I just changed them so the checkgrep wouldn't throw a fit.

**Review by harryob — APPROVED** [review]

**Review by Agameofscones — CHANGES_REQUESTED** [review]
lattice instanced to be overhead needs a prop version on layer 5.1 instead of being actually functional lattice for floor construction in space.

**Comment by NewyearnewmeUwu** [comment]
incorporated changes

**Review by Agameofscones — APPROVED** [review]
mapping approved 👍

**Pull request merged**
