### PR TITLE
Reverts tickets system

### PR DESCRIPTION
**Pull request by silencer-pl**
## About The Pull Request

As said on the tin, this PR reverts #490 and returns to the old ahelp system.

The new system has several flaws that despite several attempts at resolving them were never worked on. Instead of asking for said fixes for another week, I'm picking the other option we discussed which is this revert.

Also edits some files that were patched to include hrefs later on. Does not touch one file which is the BYOND export library that was also modified somehow with #490 ; presumably updated to a newer library.

## Why It's Good For The Game

As mentioned, despite some measured improvements here and there the new system overall is actually less comfortable to use by most staff and since changes are hard to come by at present, its more practical to return to the somewhat clunkier system that has all the comforts and functionality that staff is used to.

## Changelog

:cl:silencer_pl
admin: reverted the ahelp system back to the old one
/:cl:

### CODE REVIEW

**Comment by silencer-pl** [comment]
> I dont care what admins are using but reverting is lazy being move.
> 
> However what these several flaws are?

Dev is very aware what the flaws are. I have been given a choice - maybe fixes some day, or a revert. I chose revert after 4+ weeks of asking for changes and functionality that the previous system has. 

This PR is not a surprise to anyone, dev included and has been discussed with them at length.

**Comment by hotimep** [comment]
back to the stone ages

**Comment by spookydonut** [comment]
> > I dont care what admins are using but reverting is lazy being move.
> > However what these several flaws are?
> 
> Dev is very aware what the flaws are. I have been given a choice - maybe fixes some day, or a revert. I chose revert after 4+ weeks of asking for changes and functionality that the previous system has.
> 
> This PR is not a surprise to anyone, dev included and has been discussed with them at length.

Need to list the reasons in this PR.

**Comment by silencer-pl** [comment]
> Need to list the reasons in this PR.

Really? Okay, here goes.

The person who coded the new system in specifically told me, after giving them a list of base fixes that we'd consider the system anything close to finished, to revert the PR. It could not be done automatically, so I did it manually after waiting an additional two weeks from that when someone else said they may put the fixes in. That was on top of it sitting there for a month due to vacation and conflict schedules. 

The "ancient baycode" system, while having its own quirks, has effectively more functionality to it than this one. Not to mention the fact that waiting 6 weeks for fixes that everyone tells me should be easy but no one implements is sort of absurd. 

I'm more than happy to work with someone in bringing this system up to par, but that will take additional weeks and probably months and would require proper feedback and testing to actually implement, something that was never done with this one. In the meantime, I'd like to have the system most consider more functional back, please.

**Comment by spookydonut** [comment]
> > Need to list the reasons in this PR.
> 
> Really? Okay, here goes.
> 
> The person who coded the new system in specifically told me, after giving them a list of base fixes that we'd consider the system anything close to finished, to revert the PR. It could not be done automatically, so I did it manually after waiting an additional two weeks from that when someone else said they may put the fixes in. That was on top of it sitting there for a month due to vacation and conflict schedules.
> 
> The "ancient baycode" system, while having its own quirks, has effectively more functionality to it than this one. Not to mention the fact that waiting 6 weeks for fixes that everyone tells me should be easy but no one implements is sort of absurd.
> 
> I'm more than happy to work with someone in bringing this system up to par, but that will take additional weeks and probably months and would require proper feedback and testing to actually implement, something that was never done with this one. In the meantime, I'd like to have the system most consider more functional back, please.

It's on you to publicly justify the reasons for this revert PR, this is an open source code base and private discussions can not be used as a reason.

You need to be specific about what is wrong with it and/or link open github issues about problems with the existing system.

**Comment by silencer-pl** [comment]
Conflict resolved, additional issues that came from catching it up also resolved.

**Pull request closed without merging**
