### PR TITLE
USMC Nam Era MPs

### PR DESCRIPTION
**Pull request by emoats18**
## About The Pull Request

Makes the MPs use normal marine uniforms WITH attachable brassards and badges.
Gives MPs map variant armor it changes to the cool colors with the maps. (not the helmet only body armor)
The MP Badge spawns in the players hand since medal code is weird so they can attach it to the armor or the uniform

Styled after the Vietnam era USMC Military Police.

**In game screenshots**

mp_front
warden_front
CMP_front

**Obj Sprites**

mphelm
black_mp_badge
mp_medal
mpbadge

**IRL REFERENCE IMAGES**

da0b3f9515585bb29bb971bd1830aa37
IMG_8044-scaled
9417627470_45ebe8536b_b
post-2-0-03795900-1405626609
be26043e9c44ac552ae8df04efb8726e
563f2c271c62377f52be9e1783b43fa3-1

## Why It's Good For The Game

REAL Vietnam era USMC MPs that dress like they are supposed to.

## Changelog

:cl:
add: Added MP Brassard
add: Added MP Badge
add: Added Map Variant MP Vests
add: Added White MP Helmet
del: Removed MP Uniforms and jackets from vendors and loadouts.
imageadd: added MP Brassard, White USMC Styled MP Helmet, and USMC Styled MP Badge icons.
/:cl:

### CODE REVIEW

**Comment by Googles-Hands** [comment]
Isn't this just directly rivaling #1319 which is already being testmerged?
Since that had more time in the oven and dev approval, I'd hold of on this.

**Comment by SexmasterWasTaken** [comment]
This is going more direct to the early-war vietnam era MPs, latewar changed for black helmets and some other changes IIRC. Other PR has more continuity with other uniform styles that regular marines wear. However it'll be up to stan/nanu on which gets added I guess

**Comment by emoats18** [comment]
> Isn't this just directly rivaling #1319 which is already being testmerged?
> Since that had more time in the oven and dev approval, I'd hold of on this.

**Comment by emoats18** [comment]
> This is going more direct to the early-war vietnam era MPs, latewar changed for black helmets and some other changes IIRC. Other PR has more continuity with other uniform styles that regular marines wear. However it'll be up to stan/nanu on which gets added I guess

Show me

**Comment by morrowwolf** [comment]
Should have staled out. Re-open when merge conflicts are fixed and you can get a spriter to review your work.

**Pull request closed without merging**
