### PR TITLE
---- NO MORE BALANCE FEEDBACK IN PRS ABOVE THIS LINE ----

### PR DESCRIPTION
**Pull request by Watermelon914**
Giving balance/design feedback on PRs above this PR on github is not allowed.
As with everything, there will be obvious exceptions, but please use the appropriate discord channel to give feedback on PRs.
Maintainers are exempt from this, if they wish to demand changes related to design.

If you need someone to make a thread for your PR on the discord channel, let maintainers know.

### CODE REVIEW

**Comment by DylonBR** [comment]
litteraly 1984

**Comment by MusselMain** [comment]
sad day considering I've helped make multiple positive suggestions that were later implemented, but understandable, have a good day.

**Comment by MusselMain** [comment]
Does this include emotes?

**Comment by Carnage068** [comment]
that's part of what github is for. why else do they give people the option to comment? what else are people even supposed to say? are we just supposed to spam memes or something??
was this something that was discussed or did you just come up with this on a whim because you're upset and bitter as usual?

**Comment by stanalbatross** [comment]
> Does this include emotes?

no

**Comment by stanalbatross** [comment]
> that's part of what github is for. why else do they give people the option to comment? what else are people even supposed to say? are we just supposed to spam memes or something?? was this something that was discussed or did you just come up with this on a whim because you're upset and bitter as usual?

commenting is primarily for code review, github is awful for discussions

**Comment by Paperbell** [comment]
Will testmerges that can affect balance instead be discussed on the discord ideasguys forums?

**Comment by Carnage068** [comment]
> commenting is primarily for code review, github is awful for discussions

ok, fair enough then. I feel like shit will get cluttered with Discord though. Dozens and dozens of balance discussion threads.

**Comment by stanalbatross** [comment]
> Will testmerges that can affect balance instead be discussed on the discord ideasguys forums?

they should be discussed in the pr forum

**Comment by Watermelon914** [comment]
> ok, fair enough then. I feel like shit will get cluttered with Discord though. Dozens and dozens of balance discussion threads.

It's 1 thread per PR

**Comment by Carnage068** [comment]
> It's 1 thread per PR

do you know how many balance PRs tend to be up at the same time?

**Comment by GoldenDarkness55** [comment]
Weird. It's not like the git got particularly spammy with balance feedback, aside from some spicy PRs.
Discord is an even worse place for this as it'll be inevitably more cluttered due to its nature, as well as even more people joining in. No one's gonna read it, but then again that's apparently the intent for some reason.
Seems like another step down the quality ladder for CM.

**Comment by Watermelon914** [comment]
> Weird. It's not like the git got particularly spammy with balance feedback, aside from some spicy PRs. Discord is an even worse place for this as it'll be inevitably more cluttered due to its nature, as well as even more people joining in. No one's gonna read it, but then again that's apparently the intent for some reason. Seems like another step down the quality ladder for CM.

you don't have to review prs so you wouldn't understand in the first place

**Comment by Carnage068** [comment]
> you don't have to review prs so you wouldn't understand in the first place

oh the horror, some non-maintainer filth is cluttering the PR comment sections with his warped, twisted beliefs on game balance! why must they constantly make life so hard for me? can't they see i'm doing all i can to help cm ;-;

**Comment by Wintermote** [comment]
Sounds like trying to ignore player feedback more than anything. If it's on discord in a spam of messages you can just pretend you never saw it.

**Comment by Carnage068** [comment]
> Very loose ended "rule", I think it's just going to be used to remove people and comments that you disagree with more than anything else.

Well duh! That's the entire point! Lol, he's already doing it

**Comment by kiVts** [comment]
Wow, it really CAN get worse in this cm shit bath. Who could have guessed..

**Comment by morrowwolf** [comment]
Task essentially complete. Closing.

**Pull request closed without merging**
