### PR TITLE
Drone Evolution T3: The Reaper Rehaul, Pseudo-Angelic and Necromancer-esque + Other Changes

### PR DESCRIPTION
**Pull request by TheKillfish**
# About the pull request

[Everything in square brackets are WIP notes, and will be removed when the PR is ready for undrafting]

A rework, or rather overhaul, of @Geevies' original Reaper PR #1899 and @ThePiachu's Reaper Re-up #2234 (Credit to them and Wei/sleepynecrons for the work they did). While very interesting and unique, the original form of the Reaper had a few issues related to it, particularly the nature of directly injecting marines with Larva Juice and it being a straight up superior Carrier, and my retrospective view of it takes issue with the 5-second cooldown marine abduction attack and overall offense-focused nature of it; T3 needs more variation than just offensive castes. Additionally it only evolved from Carrier, which is disappointing to me even if most logical based on looks and it's original design intent.

This rehaul of the Reaper seeks to make it a flexible frontlining support, capable of putting on a bit of hurt if necessary but primarily oriented around doing what the castes before it did; supporting the frontline rather than fighting it, while not doing so much that it makes one or both of it's immediate predecssors entirely inferior. To this end, the following have been inherited from Hivelord and Carrier (both of which it can evolve from);
- Can make weeds.
- Can emit pheremones, which are equal in strength to Praetorians.
- Can thicken non-thick Xeno structures as well as building special structures, like acid wells, but cannot build walls themselves.
- Can order constructions.
- Can carry huggers and eggs in both hands.

In addition to the above, the Reaper has a few new features and abilities. The features and abilities are as follows:
**Flesh Resin**
Has a maximum of 1000, gained primarily through Flesh Harvest, but is also generated by normal attacks (5 per hit) and Rapture (30 per hit). Drains passively at a rate of 1 per tick, paused for 20 seconds by Flesh Harvest, Rapture and Raise Servant (pause is not refreshed)

[I am strongly debating giving a small-ish benefit for resin being drained since currently only Raise Servant uses any. I have two proposed, probably-going-to-be-denied ideas;
- Reducing pheromone plasma drain by half while Flesh Resin is being drained
- Have drain dynamically shift to 5+ ticks when Reaper is damaged and have 5 damage be healed per tick
Of the two, I believe reducing pheromone costs wold be most acceptable.]

**Flesh Harvest**
Cost: 50 Plasma
Cooldown: Min 5 seconds, Max 20 seconds
A relatively long (16s if fully uninterrupted), excessively flavoured channel ability that rips the limbs off unrevivable corpses, leaving them only as nuggets with heads (assuming cause of death wasn't decapitation). Each limb gives 30 flesh resin, and successfully harvesting a corpse uninterrupted (I.e, at least one limb throughout the channel) grants an extra 30 flesh resin. Attempting to harvest a corpse with no limbs or one with all-robotic limbs (God help the poor bastard) will give amusing messages and no flesh resin.

**Rapture**
Cooldown: 15 seconds
A limb-targeting melee attack with a three tile range that deals 30 damage (affected by frenzy pheros and respecting amour) but is mainly for debilitation; every 40 seconds, it will inject non-synth targets with Flesh Venom, a toxic chemical that has level 2 Toxic and level 4 Paining. Additionally if the target has 25 or more toxic damage, they will be made nauseous and will vomit in ~20 seconds.

**Raise Servant**
Cost: 100 Plasma, 200 Flesh Resin
Cooldown: 20 seconds
After a 20 second channel, create a loyal and disposable xenomorph pseudo-zombie our of flesh resin called a Rotting Drone, repeatable until you have 3! While incapable of damaging anything that doesn't live (so sadly no barricade breaking), always dying slowly when not within 3 tiles of the Reaper that made them and unaffected by pheremones or other xeno buffs, they are capable of passing through other xenomorphs, have 400 health and deal the same damage as Drones, making them perfect distractions or meatshields when combined with Command Servants. Upon death, their bodies melt into nothing and their creator is notified of their death.

**Command Servants**
What use are minions if you cannot command them? The Reaper can give simple directions to places or targets within their LOS to their Rot Drones, and their behaviours consist of the following;
- Rot Drones don't wander and are aggressive, focusing on attacking anything they register as hostile over their following behaviors. They can be forced out of attacking by being given orders, but remember they can and probably will return to fighting if they see another hostile. They will attack until their target is unconcious, not necessarily dead.
- When not given any orders, Rot Drones try to remain within 3 tiles of you. They can be forced to somewhere else by giving them an order, and by targeting yourself you recall them to you, cancelling any orders they had previously.
- When targeting an ally, Rot Drones will instead try to remain within 3 tiles of them as opposed to you. Should their escort die or be otherwise removed, they will return to you.
- When targeting an enemy, you directly designate them as the Rot Drones target rather than have them walk over (this is to avoid them endlessly following people).
- If targeting turf or a structure, Rot Drones will walk to or near where you designated.

The Reaper has the following stats:
Health: 650
Armor: 0
Plasma: 500 (regen identical to Carrier)
Speed: T3
Explosive Armor: T2 (identical to Carrier)
Melee: 27 (T2 + T3) [While Reaper can fight, it is NOT a lead fighter. Damage will mainly come from Rapture, and even that is mainly to debilitate and not directly kill.]

Alongside the main course are some smaller changes, primarily ones that were originally done and used by the OG Reaper PR's that, while unused by me here, would allow for greater flexibility with xenos in the future. The changes are;
- Changes pheremone cost from fixed value to modifiable (Default still costs 5) in xeno caste datums
- Changes Tail Stab range from fixed value to modifiable (Default still max 2) in ability parent datum
- Adds a modifiable noun to Tail Stab's message (Default still tail, although tweaks will need to be made to handle_tail_stab procs which still don't use the noun)
- Gives the un-ovi'd Queen a build range of 1 so she can build normally (QOL and consistency, as literally every other build-capable caste has a range of 1 despite legacy code statements)
- Tweaks simple_mob damaging people to respect armor and have random limb targeting be less unnecessarily complex 

# Explain why it's good for the game

Hivelord and Carrier lack a T3, which is sad, and T3 lacks much of a support-focused caste beyond Praetorian's different strains. The Reaper's sprites looked amazing (credit to Wei/Sleepynecrons for originally making them), and they deserve to be implemented. We don't have any minion-oriented caste, and while this is not meant to be one, it can provide legwork for a more complicated, dedicated minion-caste xenos in the future.

The extra ability modularity is good for futureproofing. The Queen change is QOL and makes building as un-ovi'd Queen significantly less awkward than it is for literally every other builder. Finally, hostile simplemobs ignoring armor when damaging people should be no bueno no matter how rarely hostile simplemobs are used.

# [TODO LIST]

- [x] Make Dissection overlay sprites
- [ ] Make Weed Food spites
- [x] Make unique sprites for Rot Drones
- [ ] Once-over and retest code to make sure everything works as best as can be tested solo before requesting TM
- [ ] Have code reviewed and criticized by more competant coders
- [ ] Have balance reviewed and criticized by those more competant in current balance

# Testing Photographs and Procedure
Tweaked and changed a lot, tested a lot.
<details>

image
Center is the Reaper itself, with a pair of Rotting Drones behind.

</details>

# Changelog
:cl: Killfish, Geeves, sleepynecrons, ThePiachu
add: Adds new T3 Xenomorph called the Reaper, evolving from Hivelord and Carrier. Almost entirely support xeno able to create and order around dumb pseudo-zombie drones called Rotting Drones.
balance: Lets un-ovi'd Queens build normally instead of jankily.
balance: Makes simple mobs that can attack people respect armor. Long live Dumbrav, destroyer of Marines.
imageadd: Reaper and Reaper-related sprites.
/:cl:

### CODE REVIEW

**Comment by TheKillfish** [comment]
After brief discussion on Discord, Meat Shield will be going to the shadowrealm, and it's probably going to be replaced with a hallucination ability yoinked from Shaman Rework from a while ago

**Comment by Butlerblock** [comment]
How will flesh harvest interact with bodies covered by weeds? Since both have the same requirement of being unrevivable.

**Comment by TheKillfish** [comment]
I did not think of that actually, I will need to check.

**Comment by Kyogon** [comment]
> I did not think of that actually, I will need to check.
An easy solution would be to make it so weed covering bodies waits until 2x perma time passes. So if a body goes unrevivable in 5 minutes, make it so weeds cover it in 10?

**Comment by blackdragonTOW** [comment]
Hello! Please remember to attach screenshots of your altered sprites in the PR description!!

**Comment by TheKillfish** [comment]
Going to close and restart work on this as a different branch (because my laziness works in mysterious ways regarding undoing some old changes that need removing). I've been dissatisfied with how everything meshes together as is, feeling disjointed and like Reaper simultaneously has too many abilities yet doesn't have enough going on between it's unique ones with my attempted solutions feeling overcomplicated and unnecessary.

This is not to say I don't have a new plan, because I do after a bit of rethinking (specific details will be specified in the new PR). In short; Reaper will be simplified and return somewhat to my original intent of it being a high-tier xeno buffer/marine debilitator that uses Flesh Resin built up by either via Harvest or Rapture to do so (Important: NOT SHAMAN- OR REWORKED SHAMAN-LIKE, NO SHIELDS, NO EFFECTS GREATLY RESEMBLING HIVE BOONS FROM #6334).

**Pull request closed without merging**
