### PR TITLE
Queen remote build pre-drop area restrictions

### PR DESCRIPTION
**Pull request by BOBAMAx**
# About the pull request

Restricts queen remote building for the first 30 minutes (boost duration) to typical hive areas and areas adjacent to hives.

Actual areas to permit/deny are up for discussion and this will likely need a TM to iron out the kinks. 

TODO: CC areas. strata and NV both have really long hallway areas that stretch like half the map that I need to mess with as well.

# Explain why it's good for the game

<details>
<summary>This is bad</summary>

remote1
remote2

</details>

Queen remote build boost is SUPPOSED to be so queen can build hive and defenses early to supplement builders while they evo/give queen something to do predrop. This was mitigated for ages by the LZ no-weeds restrictions, which is a very large part of why nearly every single survivor hold spot was in those areas. Now that pre-drop noweed areas do not exist, queen remote build's power has finally been fully unleashed.

Now, what ends up happening is weed and thick wall spam on top of survivors who do not have marine equipment or numbers to deal with them. This prevents the most egregious survivor remote build cheesing while retaining the ability for queen to build hive defenses using the predrop boost. Hivelord strain can still do this but is time gated and way more vulnerable.  Doesn't effect remote heal or resin markers.

yes this is an ided pr.

# Changelog

:cl: BOBAMA
balance: Queen can no longer use remote build outside of hive areas for the first 30 minutes.
/:cl:

### CODE REVIEW

**Comment by ihatethisengine** [comment]
It's almost like queen's combat remote building is a problem itself and no amount of restriction will fix that.

**Comment by Red-byte3D** [comment]
This wont fix anything and just cause further issues

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by BOBAMAx** [comment]
partial revert of #6071 because of:
<details>
<summary>before</summary>

soro

</details>
Originally these "hallway" areas with glass ceilings were added to allow for CAS lazing but make organizing anything by area impossible.

This now, of course, has the greater balance implication of technically making more areas CASable than before but because of how offsets work and the AOE of the CAS being what it is this doesn't really change anything other than removing the secret knowledge check of knowing which tiles of the canteen are valid for CAS or not.

<details>
<summary>after</summary>

soro2


</details>

This has the side effect of removing annoying power issues where certain rooms had multiple areas controlled by multiple APCs so you could have half a room powered while the other half is depowered because the room is actually split in half by a random hallway area controlled by an APC 100 tiles offscreen. The area an APC powers and which APC powers the room you are in should be very obvious from the player point of view and not require codediving to discern.

**Comment by BOBAMAx** [comment]
drathek doesn't like it it's over

**Pull request closed without merging**
