### PR TITLE
scout ammo and economy nerf

### PR DESCRIPTION
**Pull request by InsaneRed**
# About the pull request
This pr aims to make high impact and incindeary mags rarer.

# Explain why it's good for the game

Currently you get 5 mags per req buy, which is while normally  not alot  for any other weaponhigh impact rounds can bascially stun anything thats a stunnable caste. 
Having this easy access to this many mags is a bit broken in my opinion. I dont think this nerf will make scout useless, but it will definetly make you rethink where and how you use your ammo. Which in my opinion is important when you can solo juggle 3 xenomorphs alone.

I didnt think touching the actual cost of the crates were important as the 2 mag removal should really make a difference and make your special ammo feel special and rarer.

~~I also decided to not change the numbers on the normal bullets because i think they're already not that great, and have instead decided to remove the ARMOR_PENETRATION_TIER_10 (which equals to 50 ARMOR PIERCE ??) from HIGH IMPACT ROUNDS and change it to 10 ap instead.I dont think it needs that much ap, especially since your main combo is incin round into stun mag. This should help armored caste feel like they arent instantly dying to the stun gun.~~

~~I've decided to buff the damage of the normal mags to 60 from 55, while i dont think it will make the mags BETTER then other options, it will certainly give it a chance to deal with tier threes so you arent constantly locked to the backline, alongside its 35 AP.~~

# Testing Photographs and Procedure

</details>

# Changelog
:cl:
balance: Scout specialist incin/high impact mag crates now only has 3 instead of 5
/:cl:

### CODE REVIEW

**Comment by HeresKozmos** [comment]
Cool change

**Comment by wgtjunior743** [comment]
This is not just a scout ammo economy nerf, this is a straight up scout nerf, you are reducing the impact ammo penetration to shambles so it is basically USELESS against castes with a good defenses, such as t3,  reducing the damage by a incredible amount and with a trade off of slowering them by a bit . Also  you are talking about scout incendiary into impact as a pattern combo that comes with the weapon, it is something that not every single scout uses and that don't justify the penetration nerf.
Besides that, you forgot to mention that the scout impact ammo is 5k for requistions, being the most expensive single type of ammo that you can buy, the same way for every other scout ammo being more expensive than all the other specialists ammo, meaning you want to reduce the amount of the most expensive specialist ammo that req can buy, did you ever try to guess why is it the most expensive ammo? it is for the same reason you are trying to nerf it, THE AMOUNT.
This PR sounds like a xeno main mad at scout impact ammo and wants to nerf since you were alone  and got killed by a scout.

**Comment by InsaneRed** [comment]
> This is not just a scout ammo economy nerf, this is a straight up scout nerf, you are reducing the impact ammo penetration to shambles so it is basically USELESS against castes with a good defenses, such as t3, reducing the damage by a incredible amount and with a trade off of slowering them by a bit . Also you are talking about scout incendiary into impact as a pattern combo that comes with the weapon, it is something that not every single scout uses and that don't justify the penetration nerf. Besides that, you forgot to mention that the scout impact ammo is 5k for requistions, being the most expensive single type of ammo that you can buy, the same way for every other scout ammo being more expensive than all the other specialists ammo, meaning you want to reduce the amount of the most expensive specialist ammo that req can buy, did you ever try to guess why is it the most expensive ammo? it is for the same reason you are trying to nerf it, THE AMOUNT. This PR sounds like a xeno main mad at scout impact ammo and wants to nerf since you were alone and got killed by a scout.

image
image

**Comment by wgtjunior743** [comment]
> > This is not just a scout ammo economy nerf, this is a straight up scout nerf, you are reducing the impact ammo penetration to shambles so it is basically USELESS against castes with a good defenses, such as t3, reducing the damage by a incredible amount and with a trade off of slowering them by a bit . Also you are talking about scout incendiary into impact as a pattern combo that comes with the weapon, it is something that not every single scout uses and that don't justify the penetration nerf. Besides that, you forgot to mention that the scout impact ammo is 5k for requistions, being the most expensive single type of ammo that you can buy, the same way for every other scout ammo being more expensive than all the other specialists ammo, meaning you want to reduce the amount of the most expensive specialist ammo that req can buy, did you ever try to guess why is it the most expensive ammo? it is for the same reason you are trying to nerf it, THE AMOUNT. This PR sounds like a xeno main mad at scout impact ammo and wants to nerf since you were alone and got killed by a scout.
> 
> image image

My bad on the numbers, wiki had it wrong, i double checked on my own private server.
Are the playtime supposed to explain something?
With the price it is , i don't really care on reducing the amount of mags the scout gets per crate, but you don't explained the point on heavily nerfing the impact ammo, the main point of your PR that is hidden behind "scout ammo economy nerf".

**Comment by InsaneRed** [comment]
I explained why im nerfing its AP, because tier 10 ap is 50 which means youre dealing full damage to everything ontop of it having already stun rounds which make the mags too powerful, why would anyone even use normal mags currently? nobody would. With the nerf im basically keeping its strength and just making the mags less good at everything, scout is a support specialist and shouldnt be dealing with everything himself (he still will be able to literally kill every stunnable caste) but that shouldnt expand to tier 3's, thats why i've increased the damage the base bullets do so you can deal with tier 3's with that and i will monitor how they work and if it needs more ap i will give it more ap.

**Comment by GoldenDarkness55** [comment]
If you want to handle impact mags then remove the aids permastun by making it shorter or play with the guns RoF and compensate with more damage. Dunno why you're nerfing base ammo dmg or the ammo amount for impacts, it's already the most ammo hungry spec gun/ammo type.

**Comment by wgtjunior743** [comment]
> I explained why im nerfing its AP, because tier 10 ap is 50 which means youre dealing full damage to everything ontop of it having already stun rounds which make the mags too powerful, why would anyone even use normal mags currently? nobody would. With the nerf im basically keeping its strength and just making the mags less good at everything, scout is a support specialist and shouldnt be dealing with everything himself (he still will be able to literally kill every stunnable caste) but that shouldnt expand to tier 3's, thats why i've increased the damage of the base bullets do so you can deal with tier 3's with that and i will monitor how they work and if it needs more ap i will give it more ap.

It still hard to understand the logic behind the nerf, so impact ammo is too strong against t3 , even so a scout soloing a tier 3 is very unlikely to happen since they don't get stunned they can just get away and heal, alright but then your way to "balance" is to increase the base ammo damage by 5,  justifying that the impact ammo is too good for everything and everyone just uses it.
I made some tests with the impact ammo , normal mag and incendiary:

17 shoots on crusher to make it crit with impact ammo.
17 shoots on ravager to make it crit with impact ammo.
12  shoots on defender to make it crit with impact ammo.

13 shoots on crusher to make it crit with normal ammo.
9 shoots on defender to make it crit with normal ammo
12 shoots on ravager to make it crit with normal ammo.

17-18 shoots on crusher to make it crit with incendiary (it will be less if you wait for the incendiary tick)
Reminder:
 Normal ammo on m4ra custom :
Armour Value 0 5 10 15 20 25 30 35 40 45 50 
Bioform 60 60 60 60 60 60 60 60 55 50 45 
Humanoid 60 60 60 60 60 60 60 60 55 50 45 

Impact ammo on m4ra custom:
Armour Value 0 5 10 15 20 25 30 35 40 45 50 
Bioform 44 44 44 44 44 44 44 44 44 44 44 
Humanoid 44 44 44 44 44 44 44 44 44 44 44 

Incendiary ammo on m4ra custom:
Armour Value 0 5 10 15 20 25 30 35 40 45 50 
Bioform 44 44 44 44 44 44 40 36 33 25 21 
Humanoid 44 44 44 44 44 44 40 36 33 25 21 

Impact has a better AP but it still will do less average damage than normal ammo, what is the point of using an impact ammo on a t3 , i know it is slower them but it is not enough to solo one, it could be abit useful to support the marines but if you want to do that against a t3 besides ravager, just use incendiary ammo and it will be helpful enough.
Normal mag is already better but as every single scout ammo, it is situational, if you hear the queen, put normal mag, if you see crusher and prae use incendiary, if you see multiple t1 or t2 , load impact and use it. (Also just use burst mode with normal mag it is strong)

**Comment by Steelpoint** [comment]
For accuracy of information the change to Impact AP will have the denoted changes on the following T1 and T2 xenos. I've not accounted for T3 xenos, but T3s are far harder to kill now as well. Any xeno not mentioned already has no or insufficient armour to make a difference. 

**Defender**
- PreNerf - 13 Shots
- PostNerf - 34 Shots

**Warrior**
- PreNerf - 13 Shots
- PostNerf - 17 Shots

**Lurker Vampire**
- PreNerf - 10 Shots
- PostNerf - 13 Shots

**Spitter**
- PreNerf - 14 Shots
- PostNerf - 16 Shots

**Burrower**
- PreNerf - 13 Shots
- PostNerf - 25 Shots

**Comment by Steelpoint** [comment]
Also, changelog is incorrect, it states that impact ammo has been lowered to 15 AP but it has in fact been lowered to 10 AP. PR title should also reflect this is changing the damage and armour pen values of the scouts weapons as well as changing the economy of its acquisition

**Comment by harryob** [comment]
balance discussion is still not happening on github, take it to the forums or discord

**Comment by InsaneRed** [comment]
> Also, changelog is incorrect, it states that impact ammo has been lowered to 15 AP but it has in fact been lowered to 10 AP. PR title should also reflect this is changing the damage and armour pen values of the scouts weapons as well as changing the economy of its acquisition

should be 15 i mightve forgot to push a commit

**Review by Drulikar — CHANGES_REQUESTED** [review]
I don't think the damage numbers or penetration need to be changed at this time. However I am fine with a reduction in how many mags the scout has access to at round start. Please revert the pen and dmg changes and just keep your magazine amount changes.

**Review by Drulikar — CHANGES_REQUESTED** [review]
Also need to update the names of the crates: 
image

**Review by Drulikar — APPROVED** [review]

**Pull request merged**
