### PR TITLE
Pilot Uniform Resprite

### PR DESCRIPTION
**Pull request by Inanichts**
## About The Pull Request

New uniform and vest for for pilots

## Why It's Good For The Game

Since other officers uniforms and suits were already resprited, the pilot couldn't be left out, so i made a new uniform based on Alien colonial marines.

Link if you want to check out:

https://steamuserimages-a.akamaihd.net/ugc/906779387266658024/1D084926403E078064C7D72F121533D2739D7E1E/?imw=5000&imh=5000&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false

## Changelog

:cl: Inanichts#9688

imageadd: new uniform and vest for pilot officers
imagedel: deleted old pilot flightsuit and vest

/:cl:

### CODE REVIEW

**Comment by Inanichts** [comment]
Will do, thanks!

**Review by Geevies — CHANGES_REQUESTED** [review]
think triiodine meant adding it to the game somewhere as a cosmetic option

**Comment by Agameofscones** [comment]
What Geeves said

**Review by nauticall — CHANGES_REQUESTED** [review]
i like the uniform, only problem is that the rolled state's got boobs

normally i have no problem with that but the fact that it's unisex means it's gonna be weird seeing some people with it on

make it gender-neutral, then it'll be good

**Pull request closed without merging**
