### PR TITLE
Fixes all missing icon states for toys and props

### PR DESCRIPTION
**Pull request by Ultimate-Fluff**
# About the pull request
Even though mercs don't really play with toys, I added icon states for the missing ones, anyway. I also added icon states for some missing props, added, re-shaded, and renamed some coins to better-portray their use, and deleted an object that had no function for over 6 years.

This PR also fixes stuff that broke in #2880, which will be mentioned in the following list. 

Edit: All traces of adamantium are now re-named to platinum. In addition, I changed Platinum's metal color to a much brighter shade of gray. Also added lead sheets.

# Testing Photographs and Procedure

The list of missing toys and props are as follows:
```
/obj/item/paper/flag
/obj/item/toy/therapy_red
/obj/item/toy/therapy_purple
/obj/item/toy/therapy_blue
/obj/item/toy/therapy_yellow
/obj/item/toy/therapy_orange
/obj/item/toy/therapy_green
/obj/item/prop/flower_vase
/obj/item/prop/helmetgarb
/obj/item/prop/torch_frame
/obj/item/prop/almayer/lantern_pod //Deleted.
/obj/item/coin/marine //This broke with #2880 because I re-named the icon state of the coin in the .dmi file. Fixed.
/obj/item/coin/chitin //This also broke because I incorrectly named the icon state in the .dmi file. Woops.
/obj/item/hardpoint //This also, also broke because I forgot to actually name the icon state.

```
image

# Changelog

:cl: Puckaboo2
imageadd: Added several icon states for miscellaneous items that did not have any.
imageadd: Added lead sheets to shield from radiation poisoning and to possibly soundproof rooms.
imageadd: Platinum sheet now have a new sprite that looks like platinum.
fix: The dark indigo blocks that were Platinum have been repurposed as Chitin blocks. Not to be confused with sheets of chitin.
fix: Mercs with battle-related mental trauma may now comfort themselves with therapy dolls! Don't pop their heads off, please.
fix: Several miscellaneous items may now be used, such as paper flags, unlit torches, flower vases, and other items.
fix: Marine specialist weapon tokens can be used again.
fix: Silver, platinum, and uranium coins' color palettes match their metals.
code: Renamed some icon states and incorrect strings of text to apply more missing icon states.
/:cl:

### CODE REVIEW

**Review by nauticall — CHANGES_REQUESTED** [review]
I'd personally prefer for the lead sheets to be patterned in a different way than just stamping a skull and crossbones on every single piece. Maybe instead have a look at these suggestions I drafted up and see which one looks good to you.
image

image
image
image

(You can copy-paste the tiny sprites directly to/from a sprite editor, FYI)

Also I'm sorry but this paper flag is just really lazy. At least make it look like a flag.

image


Something like this, maybe.

image

**Comment by Ultimate-Fluff** [comment]
> I'd personally prefer for the lead sheets to be patterned in a different way than just stamping a skull and crossbones on every single piece. Maybe instead have a look at these suggestions I drafted up and see which one looks good to you. image
> 
> image image image
> 
> (You can copy-paste the tiny sprites directly to/from a sprite editor, FYI)
> 
> Also I'm sorry but this paper flag is just really lazy. At least make it look like a flag.
> 
> image
> 
> Something like this, maybe.
> 
> image

They were, in fact, lazy. Lazy, uninspired designs I came up late at night while I was tired. I'll use your flag design and I will use the lead with the red stamp or whatever it is.

**Review by nauticall — APPROVED** [review]
im not nanu 😭 

but the rest looks good to me now, approved! 👍

**Comment by Ultimate-Fluff** [comment]
> im not nanu 😭
> 
> but the rest looks good to me now, approved! 👍

im sawry. It won't let me amend commit ;A;

**Review by harryob — APPROVED** [review]

**Pull request merged**
