### PR TITLE
Secondary PO and VC gear rooms

### PR DESCRIPTION
**Pull request by stanalbatross**
## About The Pull Request

Puts a secondary gearing up room north of cryo for auxiliary combat roles, since they spawn without equipment and their prep rooms are a good minute's/two minutes' walk away

## Why It's Good For The Game

less mindless walking when latejoining, simple convenience

## Changelog

:cl:
add: Almayer: added a secondary prep room for latejoin POs and TCs north of cryo, next to the alpha-bravo canteen.
tweak: Almayer: removed a duplicate officer vendor from the RO's bedroom. They already had one in their main office.
tweak: Almayer: shuffled around the spawn landmarks in cryo, generally adding more variation and adding more spots for latejoins
/:cl:

### CODE REVIEW

**Review by Nanu308 — CHANGES_REQUESTED** [review]
Move the ladder as requested to make sense.

**Comment by stanalbatross** [comment]
> Move the ladder as requested to make sense.



> Move the ladder as requested to make sense.

wrrong pr

**Comment by stanalbatross** [comment]
> Move the ladder as requested to make sense.



> Move the ladder as requested to make sense.

wrrong pr

**Review by Nanu308 — APPROVED** [review]
lgtm

**Pull request merged**
