### PR TITLE
sg nerf

### PR DESCRIPTION
**Pull request by Red-byte3D**
# About the pull request
nefs sg so they are a bit less effective at having full screen considering they have IFF and are a constant suppressing fire elemetn

# Explain why it's good for the game

Xenos have too much stupid firerate stuff to deal with already, sg was buffed way too much, having full control over your entire screen adds way too much dps for xenos to survive with the recent marine changes either fire rate needs to be moderated (hpr, m2c) or xenos health need to be buffed, and i dont want to make xenos even spongier

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl:
balance: sg effective range nerfed to 5
balance: sg falloff increased 
/:cl:

### CODE REVIEW

**Comment by thevandie** [comment]
Sgs were pretty heavily nerfed recently with their passive vision removal
The one upside of that pr is that they became more effective for longer range, which was designed to keep them behind friendly lines and giving suppression, instead of being the tip of the spear
Now you want to remove that so now they're rushing again? That seems counter productive

Also, from experience, sgs don't have very high dps, especially for suppressive fire

If you can't stay out of range I think that's a legit skill issue, not to be _trite_ or anything.

**Comment by Red-byte3D** [comment]
i would like you to re-read what you just said, think if it makes any sense, re read the pr and then stop making comments on the github about balance

**Comment by Korey45** [comment]
If you wanted to suppress the suppressing fire element, what you could do is make their **falloff tier something like 4 or 5 and maintain the effective range.** Nerfing the SG to three tiles of range encourages them to frontline again and make the problem occur all over again. 

SG prior to its buff was like throwing wet paper towels at fucking godzilla. You could not do any damage unless you were exactly two tiles away from the xeno. The buff was made as SGs kept on frontlining because they could not do that well of damage, which made them go frontline. 

I'd also like to note that CM has an Imperial Guard-type thing with firerate. Their firerate mostly comes from pure power in numbers and the amount of guns firing. If you wanted to fix this, I'd go look at HPR and the M2C rather than the SG. 

Also, what you said to Vandie was rude as fuck, holy shit.

**Comment by Red-byte3D** [comment]
I'm aware of how suppressing fire works, you're implying an sg that is now doing full damage at full screen wide +, with IFF, who basically never has to let go of the mouse one button is not a problem (with nvgs), which is just straight up wrong. I'll up it to 4 as a middle ground, and yes im going to make a pr for hpr and m2c next dont worry

**Comment by Korey45** [comment]
> I'm aware of how suppressing fire works, you're implying an sg that is now doing full damage at full screen wide +, with IFF, who basically never has to let go of the mouse one button is not a problem (with nvgs), which is just straight up wrong. I'll up it to 4 as a middle ground, and yes im going to make a pr for hpr and m2c next dont worry

Usually when people talk about the SG suppressing fire, they mean offscreen damage from the SG. Personally, I would just make it five with an increased falloff tier.

Also, I hate how we have to talk like this and not on Discord. Would make shit so much easier.

**Comment by Red-byte3D** [comment]
Okay im going to make one last comment because for some reason people cant seem to understand the fact that sg's are !!almost!! never alone. Xenomorphs need to be able to push out because that is literally just how the game works. you cannot add all of these iff + suppressing fire elements and expect them to be able to actually do anything at fronts, theres been a creep to these weapons and they need to be tuned back down. You're constantly being shot at, you're constantly under damage. by the time most castes that need time to ramp up, be it warrior / ravager whatever, majority of the time this is counteracted by the fact you have the dark to your advantage, however sgs have night vision as well allowing you to already start chipping away at your health bar before the rest of the people around you start shooting which is now snowballing your health into oblivion.



the fact you're doing "less damage" then an mk2 doesnt matter, not everything needs to be "better then an mk2" or a "alternative" or an "equivelant" you have more tools in your kit (the ability to see in the dark, change ammo at will without reloading, and a shit ton of ammo). YOU ARE STILL PUTTING OUT CONTINOUS DAMAGE, WITHOUT THE WORRY OF FRIENDLY FIRE. that full auto argument simply doesnt work because you're firing so fast it doesnt matter if 10 bullets miss because you just hit antoher 20 that hit. 


The entire point of smartgunner is you are trading off your  ""damage"" with the fact you can see in the dark, fire through marines, and have 500 bullets in the chamber. Yes, you arent supposed to be doing "mk2 damage" you are CONSTANT SUPPRESSING FIRE THAT IS STILL CHIPPING AWAY AT HEALTH. and the buff made the sg TOO GOOD to have all of those things.

**Comment by Korey45** [comment]
> as for your m2c / hpr argument, one marine isnt supposed to be able to "hold off the xeno forces" at most hes supposed to be able to injure them, not straight out dps a drone under 3 seconds. that is not how we are balanced, its supposed to be 3 marines for 1 xeno not 1 marine against whatever fucking dares push the sightline.

The M2C is covered I feel because if you walk infront of it, you die in like three bullets as marine with heartbreak and organ damage (sometimes).

**Comment by GoldenDarkness55** [comment]
4 is better just because it gives the role an actual skill expression - a good SG will stay close enough to maximize damage and far enough to not get picked off. Braindead LMB holding bad.
Dunno if the falloff per tile shouldn't be lowered to 2 though since it's pretty severe - previous buff raised from 1 to 4..

**Comment by sleepynecrons** [comment]
> nerfs sg 

upvoted

**Comment by memoblob** [comment]
> Xenomorphs need to be able to push out because that is literally just how the game works. you cannot add all of these iff + suppressing fire elements and expect them to be able to actually do anything at fronts

Except... xenos are able to do stuff at the front, even when there are smartgunners around, literally just watch any round's frontline and you'll see normal crushers, ravagers, praetorians, warriors, defenders, etc, going ham. It's almost like xenos have tools other than just running out their resin doors blindly. They're designed to have the tools to prevent EVERY marine from shooting at them, and should be taking into account their positining and timing. It's an important thing to learn as a xeno, when you should go in for an attack, when you should back off, where you'll be approaching from, etc, etc.

> You're constantly being shot at, you're constantly under damage. by the time most castes that need time to ramp up, be it warrior / ravager whatever

You also gave the two worst examples of castes that need time to "ramp up", and I'd argue that those who do need to "ramp up" have tools to get around large amounts of focus fire. Ravager and warrior tend to be near the front and get shot alot, not really charge up anything, more like just slashing things down. That's how it is, the smartgunner isn't the one killing the warrior or ravager or whatever though. What you said is also just... the point of smartgunner? I'll get into that later though.

> You have the dark to your advantage, however sgs have night vision as well allowing you to already start chipping away at your health bar before the rest of the people around you start shooting which is now snowballing your health into oblivion.

Resin doors and cover. They exist for a reason. Even if a smartgunner has night vision, it's basically just gonna be **only** them shooting at you, which unless you're just standing still and not even trying to move out the way, will most likely result in you being chipped for like 100 HP, and then you just running away. It's not like a SG will say "hey shoot at this tile" and point into the darkness (where the arrow would be hidden anyways).

> the fact you're doing "less damage" then an mk2 doesnt matter, not everything needs to be "better then an mk2" or a "alternative" or an "equivelant" you have more tools in your kit (the ability to see in the dark, change ammo at will without reloading, and a shit ton of ammo).

Funnily enough, it does matter. Smartgunners really don't do a whole lot of damage, they have night vision to more effectively discourage some xenos from approaching, as well as gaining some intel. They kinda need it so they can more accurately determine where they should be spending their bullets, and how to position themselves better, considering SGs are already massive targets to any xeno. Changing ammo at will is technically a tool, and does come in handy, but I'd still argue it's just a minor thing. Same thing with having a shit ton of ammo, they have alot of ammo cause they end up firing alot, why wouldn't they carry huge drum magazines? It's funny to imagine the smartgun with like a 100 round magazine though.

> YOU ARE STILL PUTTING OUT CONTINOUS DAMAGE, WITHOUT THE WORRY OF FRIENDLY FIRE. 

That's the point of smartgunner, they put out continuous damage to suppress xenos. Even then, every gun is technically continuous damage. What's more, you'll be mostly suppressing the non-frontline castes who tend to be squishier, like drones, sentinels, and the like. 90% of the time, any xeno caste with decent armor or health will just end up ignoring the smartgunner.

>that full auto argument simply doesnt work because you're firing so fast it doesnt matter if 10 bullets miss because you just fired antoher 20 that hit.

It's more like you missed 10, then you missed another 10, then you missed another 10...
The argument **does** work, it has a decent amount of reasoning behind it. You didn't really prove otherwise, you basically said that the argument doesn't work if the smartgunner hits things, which is just the equivalent of you saying "nuh uh". Literally, I'm not trying to make a joke here. Please _look_ at the gameplay of any smartgunner and see how many bullets they hit and how many they miss. Spoiler alert, they miss alot, either because of tracking or just firing into the distance.

> The entire point of smartgunner is you are trading off your ""damage"" with the fact you can see in the dark, fire through marines, and have 500 bullets in the chamber. Yes, you arent supposed to be doing "mk2 damage" you are CONSTANT SUPPRESSING FIRE THAT IS STILL CHIPPING AWAY AT HEALTH. and the buff made the sg TOO GOOD to have all of those things.

Again, this is just what smartgunner does, it's literally chip damage, which is WORSE than anybody with a MK2, or hell, I'd place my bets on a half decent marine with an M39. I'm sorry, but if you're getting seriously injured or dying cause of smartgunner damage, and MAINLY smartgunner damage, then that's just on you. I'd still like to hear you out on how the buff made SG too strong to have all of these things, you didn't really explain why this is all a problem.

> as for your m2c / hpr argument, one marine isnt supposed to be able to "hold off the xeno forces" at most hes supposed to be able to injure them, not straight out dps a drone under 3 seconds.

Yeah, M2C and HPR do have that issue sometimes I feel like, but that's not what we're talking about. You also chose another horrible caste as your example. Drones aren't designed for combat, yes they definitely can do some good damage, but they're meant for support, usually in weeding and hive building. Literally any rifleman worth their salt could win in a 1v1 against a drone. 

So all in all, I don't see any attempt at an argument being made, only the claim that smartgunner is powerful. Like somebody above me said,
> Arguing that xenomorphs should be able to walk into fronts without punishment is just straight up an incorrect perception of the video game as well imo

Smartgunners aren't the punishment themselves even, they're just part of it, and decently good at it. The fact of the matter is, this game isn't a vaccum, You can't look at raw stats and go "these are too high, they should be nerfed", because there are too many factors to consider. It's 12am and I probably said like 19 wrong things but anyways-

**Comment by harryob** [comment]
we still do not do balance feedback on prs, this is for code review. if you have concerns, take them to the [forums](https://forum.cm-ss13.com/w/pr-feedback) where a maintainer will review the feedback

**Review by Drulikar — CHANGES_REQUESTED** [review]
As this is, I think the nerf is too heavy handed. But you may want to see if engine is considering again changing SG; e.g. maybe FF toggle switches between two IFF modes: One that doesn't hit hard but shoots over/around people. And then a hard hitting mode that requires a clear line of fire to shoot.

**Review by Drulikar — APPROVED** [review]
Know that this may be undone in the future regarding what I previously mentioned if we do have SG toggle between different modes. But we can go with this for now.

**Pull request merged**
