### PR TITLE
Helmet Optics Update

### PR DESCRIPTION
**Pull request by morrowwolf**
# About the pull request

This PR:

Adds NVG optics

Removes functional tube NVGs from gameplay

Adds a hotkey to cycle optics

Refactors a bunch of backend optic stuff to make it less redundant

Stops helmet destruction, or somehow visors in helmets destruction ???, from forcing a HUD or effect to stay on

Adds special marine raider optic which gives night vision, medical readouts, and USCM HUD.

Adds examine text for visors

Adds research publication to advanced medical optic

# Explain why it's good for the game

Optics are awesome!

Better code is good (at least I hope it's better)

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl: Morrow
add: Added NVG optics
add: Added a hotkey to cycle optics
add: Added special marine raider optic
add: Added examine text for optics
add: Added research publication to advanced medical optic
del: Removed functional tube NVGs from gameplay
refactor: Moved some optics code around to make it less redundant
fix: Fixed a bug with duplicate optic actions
fix: Fixed a reported bug where HUDs would stay on forever with destruction of a helmet
/:cl:

### CODE REVIEW

**Comment by morrowwolf** [comment]
No real sprite changes, just renaming.

**Comment by morrowwolf** [comment]
Also I hate how the recharger works and I'm gonna refactor it into something else at some point just don't yell at me for how cursed it is right now bless

**Review by sleepynecrons — APPROVED** [review]
cool sprites

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Review by BeagleGaming1 — APPROVED** [review]
code seems good

**Pull request merged**
