### PR TITLE
SEA tracking options

### PR DESCRIPTION
**Pull request by Doubleumc**
# About the pull request

Adds ability to track the CMP.
Adds a SEA headset that can track the CO, XO, and CMP.
Adds handheld crew monitor to SEATech vendor.

image
image

# Explain why it's good for the game

Headset tracking is a convenience for SEAs to find command staff. Access to handheld crew monitor is a convenience for SEAs to find people who can't or don't know how to ask for help: namely, privates.

# Testing Photographs and Procedure
image
image

# Changelog
:cl:
imageadd: adds CMP tracker sprites
add: adds a SEA headset, can track CO, XO, CMP
add: adds handheld crew monitor in SEATech vendor
/:cl:

### CODE REVIEW

**Comment by Blundir** [comment]
What about cmo, ce and qm

**Comment by Doubleumc** [comment]
Was only aware of the desire for CMP: image

**Comment by Doubleumc** [comment]
To avoid needing a tracker for every person of interest, I have added access to a handheld crew monitor for the SEA. Will allow them to find anyone, including privates.

**Comment by harryob** [comment]
your changelog needs to be complete without context of the `add` as that's just a symbol in the changelog, so:

add: Adds an SEA headset, can track CO, XO, CMP

**Comment by Doubleumc** [comment]
Changelog corrected.

**Review by harryob — APPROVED** [review]

**Pull request merged**
