### PR TITLE
Painkiller chemicals rebalance

### PR DESCRIPTION
**Pull request by Diegoflores31**
# About the pull request

**Paracetamol**
- creates paracetamol injectors and packets.
- Paracetamol is now the standard supply for non medic marines.
- Paracetamol is a Weak but safe painkiller.
- OD is now 30 , metab is the same as tramadol now
- Painkilling effect is now 1.5 ( 3 in the old values)

**Tramadol**
- Gives a small amount of toxin damage over time.
- usually provided to medics and found on emergency kits.
- mild painkilling effect 2.5 ( 5 on the old values)
- dangerous to use with oxycodone.

**Oxycodone**
- New recipe ( ethanol + inaprovaline + nitrogen + phoron catalyst)
- no longer available in bottled presentation.
- Toxic to use with tramadol
- gives a small amount of lung damage
- high painkiller 4 ( 8 on the old values)

**Sleen**
- OD as 30 units
- "Illegal" substance
- metabolizes as the same rate than oxycodone
- strong painkiller 3.5 ( 7 in old values)
- gives a small amount of lung damage
- (( on a subsequent PR an additional debuff will be added))

PD: Numbers on the Painkilling levels have been reduced but this will not afffect the VALUE . this is just lowering the numbers in order to clear a path for stronger painkillers in the future.  either via Research or by new chemicals added

# Explain why it's good for the game

This PR seeks to introduce a comprehensive rework of the existing painkiller tiers. The goal is to improve the current system by addressing the varying levels of effectiveness across different tiers and ensuring a more balanced and consistent experience. 
Additionally tackling the effectiveness of the practice of pre-meding by adding small debuffs for using strong painkillers constantly.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
balance: Paracetamol and Tramadol no longer create Toxin
balance: Tramadol mixed with oxycodone now creates Toxin
balance: Changed the Oxycodone Recipe (ethanol, methane, nitrogen)+ ( 5u of phoron as catalyst)
balance: Oxycodone bottle is no longer free on the vendor
balance: Buffed Sleen metabolization time
balance: Replaces Tramadol with Paracetamol autoinjector on First aid and Autoinjector pouches
balance: Oxycodone now give micro organ damage to the user
balance: Tramadol now gives a slight amount of toxin damage
balance: increased paracetamol painkilling effect to 3
balance: emergency autoinjector now provides 10 units of oxycodone
add: adds paracetamol packets and autoinjectors
/:cl:

### CODE REVIEW

**Comment by ghostsheet** [comment]
Pre-medding was never a problem. Its arguably a skill expressive thing marines can do to gain a small edge in combat.

**Comment by Diegoflores31** [comment]
> Pre-medding was never a problem. Its arguably a skill expressive thing marines can do to gain a small edge in combat.

unsure how jabbing yourself each 20 minutes with tramadol "skill" expressive . considering all the benefits you get from it

**Comment by Diegoflores31** [comment]
> > Pre-medding was never a problem. Its arguably a skill expressive thing marines can do to gain a small edge in combat.
> 
> unsure how jabbing yourself each 20 minutes with tramadol "skill" expressive . considering all the benefits you get from it

**Comment by Diegoflores31** [comment]
**update:** 
reduced tramadol liver damage
reduced oxycodone lung damage
fixed paracetamol injectors having no sprite
removed oxycodone from all vendors 
changed oxycodone recipy to be easier to make

**Comment by Diegoflores31** [comment]
After carefully reviewing community suggestions and assessing their impact on gameplay, I've come to the conclusion that Tramadol plays a crucial role in the current game loop. Because of this, implementing any major damage penalties for its use at this time would disrupt the balance too significantly. To address this, Tramadol will now cause a small amount of toxin damage instead. This change is subtle enough to make an impact without being overly punishing, especially since medics can easily counteract the toxin buildup with Dylovene or Tricordrazine. The main objective here is to reduce the effectiveness of pre-medicating, ensuring that Tramadol isn't over-relied upon for extended engagement preparation, while still maintaining its viability for players. It’s important that this adjustment doesn’t unfairly punish medic users

As for Oxycodone, it will remain largely unchanged, with one key revision: the permanent damage it causes has been reduced. This ensures it can still be used multiple times within reason, without becoming an overpowered choice or excessively penalizing players for repeated use. The goal with these changes is to promote balance and strategy, making each choice matter more without breaking the flow of the game.

**Comment by Diegoflores31** [comment]
> After carefully reviewing community suggestions and assessing their impact on gameplay, I've come to the conclusion that Tramadol plays a crucial role in the current game loop. Because of this, implementing any permanent damage penalties for its use at this time would disrupt the balance too significantly. To address this, Tramadol will now cause a small amount of toxin damage instead. This change is subtle enough to make an impact without being overly punishing, especially since medics can easily counteract the toxin buildup with Dylovene or Tricordrazine. The main objective here is to reduce the effectiveness of pre-medicating, ensuring that Tramadol isn't over-relied upon for extended engagement preparation, while still maintaining its viability for players. It’s important that this adjustment doesn’t unfairly punish medic users
> 
> As for Oxycodone, it will remain largely unchanged, with one key revision: the permanent damage it causes has been reduced. This ensures it can still be used multiple times within reason, without becoming an overpowered choice or excessively penalizing players for repeated use. The goal with these changes is to promote balance and strategy, making each choice matter more without breaking the flow of the game.

**Comment by Diegoflores31** [comment]
> What are you doing? A nerf to the overall effectiveness of painkillers _in general_ is not mentioned anywhere in your PR?
> 
> It is also absent from your changelogs. Not to mention the fact that Paracetamol is actually NOT increased in effectiveness at all
> 
> Why are you trying to be sneaky with this?
 
Because i have not . ? if you check again you can see that i have added a multiplier . the numbers are the same . i just made the "number" lower

**Comment by Korey45** [comment]
When has pre-medicating ever been an issue? I genuinely want to know why you think you need to "fix this problem" of people pre-medicating. 

I can not think of a single problem with pre-medicating at all. I genuinely want to know what issues you think there are with it. 
People have brought up why pre-medicating isn't an issue, and i think Zonespace says it well enough.

> "premedding has the risk of you getting capped, in addition to you burning 1/3rd of your injector for something that may / may not happen"

It has always been a trade, why mess up that trade? I want you to be as detailed as possible.

**Comment by TheManWithNoHands** [comment]
You do realise you fuck over NW for tram od if you make para the same od lv as tram. Rigth?
NW works by converting the tram to a chemical that has a larger OD ammount then tram. 
Keep para OD at 60, to much else is fucked over otherwise.

**Comment by Stellarthoughts** [comment]
No.

**Comment by Diegoflores31** [comment]
PR will be closed . i am cooking something better

**Pull request closed without merging**
