### PR TITLE
Starts refactoring Xenomorph.dm and other xenocode.

### PR DESCRIPTION
**Pull request by Birdtalon**
# About the pull request

This PR attempts to begin refactoring parts of Xenocode. It's all over the place and I had to start somewhere. Starting to forget what I've done so far  and this is getting quite big. So this is mainly to keep track of things as my memory is that of a goldfish 🐟

File Structure:

- Moves `/datum/caste_datum` and associated code out of xeno_defines.dm into caste_datum.dm (new)
- xeno_defines.dm now lives in ./__DEFINES
- `/datum/hive_status` now lives in hive_status.dm (new)
- `/datum/hive_status_ui` moved form hive_status.dm lives in hive_status_ui.dm
- `/datum/xeno_mark_define` moved to xeno_marks.dm (new)
- Client procs for getting playtime now moved to xeno_client_procs.dm

Code:

- Refactors `set_hive_and_update()`, moves `istype(src)` to the subclasses for larva and queen
- Refactors xeno numbering, all xeno hives now number 1-999 independently and pick from a list instead of generating rand every time and iterating over `GLOB.all_xenos` every time.
- Removes unneeded `istype(src)` in `/mob/living/carbon/xenomorph/larva/update_icons()` we already have `state_overide` here for this reason.
- Refactors larva name generation out of `update_icons()` and into its own `generate_name()`
- All xenomorph naming is handled by calling `generate_name()` Removed `handle_name()` and moved everything to `generate_name()`
- Calling `generate_name()` to change from "Bloody larva" to "mature" is now in `...larva/Life()` instead of in `update_icons()` since `update_icons()` was called on every Life() tick anyway.
- Refactors `/mob/living/carbon/xenomorph/Initialize()` removes a few duplicate proc calls, `generate_name()` called twice, `recalculate_actions()` called twice etc.
- Adds silly name decorator if a Xeno number is 666
- Replaces single letter vars in hive_status.dm

# Explain why it's good for the game
# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl:
code: Starts refactoring, standardising and cleaning Xenomorph.dm and hive_status.
add: Little easter egg for 666 xeno number.
/:cl:

### CODE REVIEW

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by Birdtalon** [comment]
This is going to be a nightmare to review I should have saved the file structure changes to a different PR but didn't think at the time.  Frustration at xeno_defines.dm not being for xeno defines got to me 😢

**Comment by Birdtalon** [comment]
I am going to split this into atomic PR

**Pull request closed without merging**
