### PR TITLE
Fix marine raider sof ERT not spawning with correct armor.

### PR DESCRIPTION
**Pull request by Huffie56**
## About The Pull Request
https://github.com/cmss13-devs/cmss13/issues/1493

I suppose removing /armor broke the code and unable marine raider aka marsoc to use this armor and so use standard marine armor instead.
I think / armor was removed because they where thinking it's wasn't necessary.
So i revert back to old code but changed marsoc to sof since the armor is named that's way now.

## Why It's Good For The Game
Raider aka Marsoc should spawn with proper armor now.

## Changelog

:cl:
fix: Raider aka marsoc will spawn with their armor now
code: add back /armor at the end of gear preset for raider.
/:cl:

### CODE REVIEW

**Comment by Huffie56** [comment]
Need testing of course to confirm...

**Comment by harryob** [comment]
you need a more descriptive PR title huffie

**Comment by Huffie56** [comment]
I tested it on byond on local server seem to work could play around because my computer is a potato...

**Review by fira — APPROVED** [review]
good catch

**Comment by Huffie56** [comment]
> good catch

Thanks.
So what's the process to get a PR merge after that? i just wait?

**Comment by harryob** [comment]
yes

**Review by harryob — APPROVED** [review]

**Comment by Huffie56** [comment]
> yes

Amazing it's my first PR getting merge i will celebrate this with a warm coffee.
You can also close the linked issue https://github.com/cmss13-devs/cmss13/issues/1493
thanks

**Comment by harryob** [comment]
> > yes
> 
> Amazing it's my first PR getting merge i will celebrate this with a warm coffee. You can also close the linked issue #1493 thanks

done, enjoy it :)

**Pull request merged**
