### PR TITLE
Adds an alternate PO flightsuit for sale in the equipment vendor.

### PR DESCRIPTION
**Pull request by carlarctg**
# About the pull request

Adds an alternate PO flightsuit (and jacket) for sale in the equipment vendor.

Don't worry stan, a bugfix PR is up next.

# Explain why it's good for the game

> Adds an alternate PO flightsuit (and jacket) for sale in the equipment vendor.

More drip, more good.

https://media.discordapp.net/attachments/746325423289401395/1052578413690499122/image.png

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
imageadd: Adds an alternate PO flightsuit (and jacket) for sale in the equipment vendor. Located on the dorms next to CIC.
/:cl:

### CODE REVIEW

**Review by harryob — APPROVED** [review]
the code is fine, sprites obvs still need approval

**Review by nauticall — CHANGES_REQUESTED** [review]
image
Outlines (yellow) are too light and make the whole thing look blurry and out-of-style. Make them darker, you should use the shade highlighted in blue between the legs
image
Would recommend to make the collar less conspicious; something like this is my suggestion but you can do what you want with it.

image
I'm getting deja vu here - I said on a PR that looked similar if not identical that these pec or boob outlines should go; make the whole thing flat so it doesn't look overly tight.

**Comment by Inanichts** [comment]
That undershirt is the PMC one, just so you know if you want it changed.

> image Outlines (yellow) are too light and make the whole thing look blurry and out-of-style. Make them darker, you should use the shade highlighted in blue between the legs image Would recommend to make the collar less conspicious; something like this is my suggestion but you can do what you want with it.
> 
> image I'm getting deja vu here - I said on a PR that looked similar if not identical that these pec or boob outlines should go; make the whole thing flat so it doesn't look overly tight.


That shirt is the PMC Undershirt, just so you know if you want to change it.

**Review by nauticall — CHANGES_REQUESTED** [review]
much better! final suggestion I'd make is to sort of make the thighs not bulge out from the legs, otherwise it's all good

it's such a minor change that I've done it myself you can add this in if you'd like or tune to your liking
image

**Review by nauticall — APPROVED** [review]

**Review by harryob — APPROVED** [review]

**Pull request merged**
