### PR TITLE
Upper aft out of bounds partial hijack fix

### PR DESCRIPTION
**Pull request by morrowwolf**
# About the pull request

Upper aft out of bounds hijack fix.

Adds laundry room to the valid area list as well.

# Explain why it's good for the game

Bug bad

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>
Nope

</details>

# Changelog

:cl: Morrow
fix: Partially fixed upper aft out of bounds hijack crash location
/:cl:

### CODE REVIEW

**Comment by cm13-github** [comment]
#### Test Merge Deployed

<details><summary>Details</summary>

##### Server Instance
CM13 Live Instance

##### Revision
Origin: 24ced9126768119f480e6a8d6d91ac4ba8f25119
Pull Request: 4992932f7283236ac2c590fdcacf14895bb47877
Server: 49d1b8c0ff4d15efdbd4fd0cbecd571fb02623ee

##### Comment

</details>

**Comment by cm13-github** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CM13 Live Instance

##### Revision
Origin: a712c10248439405f450f07ca7c7acf69bb848d7
Pull Request: 4992932f7283236ac2c590fdcacf14895bb47877
Server: fff4ba6badffbafa4be46c98823ac0c89df423b6

##### Comment

</details>

**Comment by cm13-github** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CM13 Live Instance

##### Revision
Origin: 58a51e1246fd072d444ab6bf09944be5f02b92d6
Pull Request: 4992932f7283236ac2c590fdcacf14895bb47877
Server: 34f1cd3bb642446c355fb98cd2cf7255899d2fed

##### Comment

</details>

**Review by harryob — APPROVED** [review]

**Comment by cm13-github** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CM13 Live Instance

##### Revision
Origin: d817dc374787ac3dcce4d37d7b5aaa6bf45aba9b
Pull Request: 4992932f7283236ac2c590fdcacf14895bb47877
Server: eba44f3e93548d2616501d9486bc358c491fdf14

##### Comment

</details>

**Comment by cm13-github** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CM13 Live Instance

##### Revision
Origin: 4708853a780fe8dc72848aaef4a440011ac4490f
Pull Request: 4992932f7283236ac2c590fdcacf14895bb47877
Server: 00a5ba229c15728cc98656fec14ae59ca56c401b

##### Comment

</details>

**Review by harryob — APPROVED** [review]

**Comment by cm13-github** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CM13 Live Instance

##### Revision
Origin: 4708853a780fe8dc72848aaef4a440011ac4490f
Pull Request: 4992932f7283236ac2c590fdcacf14895bb47877
Server: 2553f9eae54e1e8fba39250f1fbaef3aad25d1af

##### Comment

</details>

**Comment by cm13-github** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CM13 Live Instance

##### Revision
Origin: 4708853a780fe8dc72848aaef4a440011ac4490f
Pull Request: 4992932f7283236ac2c590fdcacf14895bb47877
Server: cdd6fe2764fa15eae4632c12aeee0e9d5ece932e

##### Comment

</details>

**Comment by cm13-github** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CM13 Live Instance

##### Revision
Origin: 40e1c33dd3db0c09405cfebc5c063f0bab3afab7
Pull Request: 4992932f7283236ac2c590fdcacf14895bb47877
Server: 51152bdccda4fb695b4f0e8f74f0a6ea3b01a813

##### Comment

</details>

**Comment by cm13-github** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CM13 Live Instance

##### Revision
Origin: 40e1c33dd3db0c09405cfebc5c063f0bab3afab7
Pull Request: 4992932f7283236ac2c590fdcacf14895bb47877
Server: cddc03115ac4de96c00a534facfcfa14c9ba6b07

##### Comment

</details>

**Comment by cm13-github** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CM13 Live Instance

##### Revision
Origin: 0dea5e168383a7e3de233f2e66e92049f13e139c
Pull Request: 4992932f7283236ac2c590fdcacf14895bb47877
Server: 7574a7f61af3be4dbaec4e7bb5f15e7a5932b17f

##### Comment

</details>

**Comment by cm13-github** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CM13 Live Instance

##### Revision
Origin: 0dea5e168383a7e3de233f2e66e92049f13e139c
Pull Request: 4992932f7283236ac2c590fdcacf14895bb47877
Server: 6bb9e7d49ab844c93c1c645dfa57f2ce22e924b2

##### Comment

</details>

**Comment by cm13-github** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CM13 Live Instance

##### Revision
Origin: 0dea5e168383a7e3de233f2e66e92049f13e139c
Pull Request: 4992932f7283236ac2c590fdcacf14895bb47877
Server: 2f52ba8deba310a1f8ff051abba991e66698653d

##### Comment

</details>

**Comment by cm13-github** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CM13 Live Instance

##### Revision
Origin: e683278fb1d596c51e80f921a1810cbad53324db
Pull Request: 4992932f7283236ac2c590fdcacf14895bb47877
Server: 81966dcdc7a3f248e4a56037c647d30c9fcd8500

##### Comment

</details>

**Comment by cm13-github** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CM13 Live Instance

##### Revision
Origin: e683278fb1d596c51e80f921a1810cbad53324db
Pull Request: 4992932f7283236ac2c590fdcacf14895bb47877
Server: 7a8d2996afeaaa238369233ecd3ee0aa0b4ec146

##### Comment

</details>

**Pull request merged**
