### PR TITLE
Tape Recorder records again

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

The Tape Recorder was broken after https://github.com/cmss13-devs/cmss13/pull/410

Tape Recording in storage was broken forever?

Storage "hearing_items" removal was broken after https://github.com/cmss13-devs/cmss13/pull/431

It is now fixed.

## Why It's Good For The Game

BUG BAD UNGA ALSO GBPs

## Changelog

:cl: Morrow
fix: Tape Recorders should record again.  Even in storage containers.
/:cl:

### CODE REVIEW

**Review by Geevies — APPROVED** [review]

**Comment by silencer-pl** [comment]
Tested most recent code on local instance.

The recorded the CMP spawns in a least does not work, this change did not fix the issue I'm afraid.

**Comment by Git-Nivrak** [comment]
Tested that fix a while ago however it causes runtime errors, you should probably test it first

**Comment by morrowwolf** [comment]
So this works on my machine with the exact test scenario of CMP's taperecorder and does not throw any runtimes.

I test every PR I make.

@Git-Nivrak Do you have any details on any runtime errors you ran into?  I'm not getting anything.

**Comment by morrowwolf** [comment]
Alright storages are fucked.  I'm working on it.  Don't merge for now.

**Comment by morrowwolf** [comment]
TFW you fix a runtime error backwards: https://github.com/cmss13-devs/cmss13/pull/431

**Comment by morrowwolf** [comment]
Should be actually good now.

**Review by Geevies — APPROVED** [review]

**Comment by DoomLaser9** [comment]
I haven't tested/confirmed this, but this may have an impact on issue #368 where there's unexpected behavior with radios in storage containers, and where whispering has a different effect than just talking.

**Pull request merged**
