### PR TITLE
Mapping adding a panic room with an armory and an MP office to hangar.

### PR DESCRIPTION
**Pull request by Huffie56**
# About the pull request
adding a panic room in hangar that can be open via an MP office that as an armory to quickly respond to hostile coming from DS's

# Explain why it's good for the game
Will add a room to secure civilian and injuries if hostile are coming up DS's specially if hangar lock down is activated.

# Testing Photographs and Procedure

I have tested all the items etc didn't crash and everything seem to work.

<details>
<summary>Screenshots & Videos</summary>

before
image
after
image
before
image
after
image

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: adding a panic room in hangar that can be open via an MP office that as an armory to quickly respond to hostile coming from DS's
/:cl:

### CODE REVIEW

**Comment by Huffie56** [comment]
> Requested Changes

i fixed it...

**Review by morrowwolf — CHANGES_REQUESTED** [review]
chair

Also the offset is probably not needed.

**Comment by Huffie56** [comment]
> chair
> 
> Also the offset is probably not needed.

i think it is the correct way?
image

**Review by morrowwolf — APPROVED** [review]
Mapping approved

**Comment by morrowwolf** [comment]
Given this is a re-post of an older pull request I am breaking the 24 hour rule as it's technically like 3-4 weeks old.

**Comment by Huffie56** [comment]
> Given this is a re-post of an older pull request I am breaking the 24 hour rule as it's technically like 3-4 weeks old.

thanks. :)

**Pull request merged**
