### PR TITLE
American Spirit Cigarettes

### PR DESCRIPTION
**Pull request by AmoryBlaine**
For merge after sprite freeze. Adds Crowford's American Spirit cigarettes. Available in Yellow (Mellow) and Turquoise (Full Bodied, stronger) 

{CB6FC7B5-8131-4B62-8384-FF2A20051042}
{D6801F71-5103-4E41-85E9-C704A47CEEDB}
{6FAE3AF9-DC9F-4F19-99FF-FD0BBE70B605}

:cl: AmoryBlaine, Crowford
add: American Spirit cigarettes
 /:cl:

### CODE REVIEW

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by AmoryBlaine** [comment]
> You need a changelog

Done

**Review by Blundir — CHANGES_REQUESTED** [review]
inhands for packets are missing

**Review by Blundir — APPROVED** [review]

**Pull request merged**
