### PR TITLE
(finishes) porting emissives from tgmc

### PR DESCRIPTION
**Pull request by harryob**
i somehow forgot to finish this when i was porting fancy lighting, but its here! and only on light switches (we have two of them in the game, fun!) and morgues!

:cl: TiviPlus
add: emissives! for that fun glow in the dark effect
/:cl:

edit: almost forgot, this finishes off what i started in the lighting port which was from https://github.com/tgstation/TerraGov-Marine-Corps/pull/6678

### CODE REVIEW

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Review by Drulikar — CHANGES_REQUESTED** [review]
Attachments and the character screen (even at round start) do not display any icons with this PR. Tested on live and also confirmed locally: 
image
image

**Comment by harryob** [comment]
this pr never went stale. 1984 is real

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Pull request closed without merging**
