### PR TITLE
Poncho Vendable!!!

### PR DESCRIPTION
**Pull request by 567Turtle**
# About the pull request

adds ponchos (drippy) to the squad prep vendor

# Explain why it's good for the game

Ponchos are drippy and do not effect anything but the style of marines.

<details>
<summary>Screenshots & Videos</summary>

works probably

</details>

# Changelog
:cl:
add: Ponchos can be vended from the uniform supply vendor (It's also now properly layered and transparent)
/:cl:

### CODE REVIEW

**Review by Drulikar — CHANGES_REQUESTED** [review]
From my understanding, Sammy would like the layering issues fixed for ponchos & belts fixed before they are obtainable by marines. Speak with them for more details.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by harryob** [comment]
without commenting on if this pr should exist or be merged

**Comment by Blundir** [comment]
Hello, i am against them being present in regular rounds, unless you find out a way to add things in vendors on specific maps only, i'm not gonna approve this

**Pull request closed without merging**
