### PR TITLE
adds a placeholder for Workin' Joey, a future storytelling device. 

### PR DESCRIPTION
**Pull request by NewyearnewmeUwu**
# About the pull request

Adds a placeholder for Workin' Joey, a future Almayer storytelling device in the maints bar.

# Explain why it's good for the game

The sprite looks cool and what Thwomp has planned is Cool.*

*please help me thwomp wont let me drink water unless i code for him

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: Added Workin' Joey, a (currently dormant) storyteller.
/:cl:

### CODE REVIEW

**Comment by thwompa** [comment]
sprite could use some work, WIP. monkey said he liked the idea, no issues about it fitting the setting.

**Comment by NewyearnewmeUwu** [comment]
> sprite could use some work, WIP. monkey said he liked the idea, no issues about it fitting the setting.

i will change the sprite accordingly sir yes sir (i am not the spriter)

**Review by nauticall — APPROVED** [review]
map's fine but since sprites could use some work I'll mark this as a draft for now

**Comment by NewyearnewmeUwu** [comment]
Putting a pin in this so I can fork and work on other stuff/

**Pull request closed without merging**
