### PR TITLE
Separated shotgun and MOU53 fire delay

### PR DESCRIPTION
**Pull request by carlarctg**
# About the pull request

Separated shotgun and MOU53 fire delay, meaning you can fire a MOU53 inmediately after an M37 or vice versa.

# Explain why it's good for the game

Fire delay groups were initially added to the MOU53 because marines did double or even triple MOU loadouts that were positively satanic and dealt way too much burst damage. Afterwards they were incorporated into all shotguns to remove 'double chung', the tactic in which you switch between two buckshot shotguns and consecutively fire them. This was, I believe, more of an oversight and happenstance than intended design.

This PR will allow marines to have a MOU53 and a M37 in the same loadout, but double-MOU and double-M37 is still impossible.

"Delays are a horribly unfun part of the game and taking away player freedom in this instance doesn't have a good justification - double chung was removed because it's not fair for 1% of the playerbase to instakill T1s and T2s. Sure, I get it, but to apply that to a loadout that had comparatively no significance and requires the use of thoughtful ammo loading is just putting salt in the wound when it comes to having fun that doesn't involve blasting mobile xenos with a rifle while chasing them. The MOU isn't that easy to use and it's a good benchmark to see how "combo" loadouts realistically affect xenos coming into 2023."

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
balance: Separated shotgun and MOU53 fire delay, meaning you can fire a MOU53 inmediately after an M37 or vice versa. You still cannot do double-shotgun loadouts.
/:cl:

### CODE REVIEW

**Review by harryob — APPROVED** [review]
the code is fine and the balance is not my problem ❤️

**Comment by stanalbatross** [comment]
your "why it's good for the game" is really shit btw

**Comment by harryob** [comment]
active TM, not stale

**Review by morrowwolf — APPROVED** [review]
GA approving.

I think it's alright right now but if it becomes a problem post-merge this may be reverted.

**Review by morrowwolf — COMMENTED** [review]
Nah I'm waffling on it, I'll have a hard decision by the end of the week.

So far it doesn't seems to have effected balance intensely but I really dislike the stun->PB buckshot wombo combo.

**Review by morrowwolf — COMMENTED** [review]
GA team discussed this.

We're not looking to bring back dual wielding shotguns in any form at this time.

**Pull request closed without merging**
