### PR TITLE
OT/Req delivery system repair

### PR DESCRIPTION
**Pull request by SpypigDev**
# About the pull request
This is a simple fix for the delivery system between the OT workshop and Requisitions. Previously the system has been either forgotten, left on a to-do list somewhere, or not noticed entirely. I have added a teleporting pipe connection from OT workshop to Req using the same system as the one in Research, as well as a special sorting T-junction to ensure items move correctly in the pipes.

I have tested the change and all appears to be working as intended
# Explain why it's good for the game
The OT/Req delivery system was a great concept and certainly an excellent quality of life upgrade for the two distant departments. However, since its initial addition, it has sat as an incomplete system within the map files. With this quick and harmless fix, we can have this great feature properly on its feet
# Photo Overview
<details>

image
_The OT side of the teleporting pipe system (no, this was not here before)_

image
_The new Req side of the pipe system with new custom T-junction sorter (door was removed for ease of viewing)_

</details>

# Changelog
:cl:
fix: Completed the teleporting pipeline delivery system between OT workshop and Requisitions
/:cl:

### CODE REVIEW

**Comment by SpypigDev** [comment]
Seeing a failing check here, am hoping this wont be an issue. This my first time using a new engine, perhaps I have made a mistake

**Comment by ItsVyzo** [comment]
- Don't go through window frames/walls

- Make sure you didn't break Research/Req

- You should be able to use the disposal pipes instead of making another pipeline

**Comment by Huffie56** [comment]
hello @SpypigDev please use the old system it use teleporting pipes...
so what you need to do is to put back the orange pipe on the bellow the door.
and replace the blue pipe with a T junction ....
the red one is for research...
image

**Comment by fira** [comment]
I thought this was the full dest tagger system for a moment, i'm sad :(

**Comment by SpypigDev** [comment]
> hello @SpypigDev please use the old system it use teleporting pipes... so what you need to do is to put back the orange pipe on the bellow the door. and replace the blue pipe with a T junction .... the red one is for research... you don't even need to touch anything in OT workshop... in the image you provide you are breaking the connection for research... image

Whatever the old system was, it wasnt working. Have built a functional wireless pipe system now, having trouble with the T-junction in Req sending items to research. Will continue to work on it

**Comment by Huffie56** [comment]
> Whatever the old system was, it wasnt working. Have built a functional wireless pipe system now, having trouble with the T-junction in Req sending items to research. Will continue to work on it

the T junction isn't suppose to send items to research but research chute is suppose to send items to requisition.

**Comment by SpypigDev** [comment]
> > Whatever the old system was, it wasnt working. Have built a functional wireless pipe system now, having trouble with the T-junction in Req sending items to research. Will continue to work on it
> 
> the T junction isn't suppose to send items to research but research chute is suppose to send items to requisition.

Apologies, perhaps I was unclear. I am aware of this and have added a special sorting T junction to make sure all items input go to Req as intended. In my previous comment, I was mentioning how a default T junction sends items to research when its not supposed to. This is no longer an issue

**Comment by Huffie56** [comment]
> > > Whatever the old system was, it wasnt working. Have built a functional wireless pipe system now, having trouble with the T-junction in Req sending items to research. Will continue to work on it
> > 
> > 
> > the T junction isn't suppose to send items to research but research chute is suppose to send items to requisition.
> 
> Apologies, perhaps I was unclear. I am aware of this and have added a special sorting T junction to make sure all items input go to Req as intended. In my previous comment, I was mentioning how a default T junction sends items to research when its not supposed to. This is no longer an issue

no worries i just wanted to make sure you understood how it suppose to work.
for your changelog i think it's more fix: rather than qol: since your fixing an existing system.
but that's just a small detail your choice...

**Comment by SpypigDev** [comment]
> > > > Whatever the old system was, it wasnt working. Have built a functional wireless pipe system now, having trouble with the T-junction in Req sending items to research. Will continue to work on it
> > > 
> > > 
> > > the T junction isn't suppose to send items to research but research chute is suppose to send items to requisition.
> > 
> > 
> > Apologies, perhaps I was unclear. I am aware of this and have added a special sorting T junction to make sure all items input go to Req as intended. In my previous comment, I was mentioning how a default T junction sends items to research when its not supposed to. This is no longer an issue
> 
> no worries i just wanted to make sure you understood how it suppose to work. for your changelog i think it's more fix: rather than qol: since your fixing an existing system. but that's just a small detail your choice...

Noted, will change

**Review by Nanu308 — APPROVED** [review]
lgtm

**Pull request merged**
