### PR TITLE
adds timer to queen hijack

### PR DESCRIPTION
**Pull request by Cthulhu80**
# About the pull request

Added a timer to the hijacking. It's not longer automatic. Also, added a sequence of voiced AI sounds from the ds for each step during the hijack process. 

# Explain why it's good for the game

The Queen being able to instantly hijack the dropship seems to be rather unbalanced and it also makes no sense as a well timed screech can ground a ds of 30 marines. It would make more sense if the Queen could only hijack if she had full control over the ds or at-least lots of xenos onboard to keep the marines busy. When it comes to the sounds, I just thought it would add to hijacking process and make it a bit more interesting and immersive. If you're interested in hearing and seeing what the new hijack would look like then take a look in the development channel on discord. 

# Changelog
:cl:
add: Added timer to Queen hijacking
soundadd: Added a list of voiced ai sounds from the ds navcomputer for each step during the hijack.
/:cl:

### CODE REVIEW

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by HeresKozmos** [comment]
The Queen already has to make it into the cockpit, this seems like an unnecessary change to me?

**Comment by Cthulhu80** [comment]
> The Queen already has to make it into the cockpit, this seems like an unnecessary change to me?

Even with that if the Queen is good she can still usually squeeze through and ground the ds most of the time.

**Comment by MistChristmas** [comment]
The Queen already has to wade through and pry open atleast two doors before touching the cockpit. And if the marines have brains. Then she has to touch the Dropship ground console, this is usually the case. Now yes. A Queen can make it through the first door, and she can then screech. And then go through the second and touch the console. But this usually results in about 20 marines fighting for the 1 tile space they can to get in position to shoot her.

If marines actually allow this to happen it's a skill issue. And if the Queen rushes the DS whilst 20+ ground marines are still alive she's prbobably not surviving it. Unless all her xenos are with her.

Also whilst Alarms might be "Immersive" in this uh 2D Ancient Spess Game. I don't think we need more of them. The Dropship Departure alarm is already annoying as is. 

And considering how often queens will just kill all the ground side marines and wait for bursts and everyone to get in the dropship I don't think we need a timer. Funny xeno stealth DS runs, are just that funny. And usually just result in a xeno wipe after hijack.

**Comment by Cthulhu80** [comment]
> The Queen already has to wade through and pry open atleast two doors before touching the cockpit. And if the marines have brains. Then she has to touch the Dropship ground console, this is usually the case. Now yes. A Queen can make it through the first door, and she can then screech. And then go through the second and touch the console. But this usually results in about 20 marines fighting for the 1 tile space they can to get in position to shoot her.
> 
> If marines actually allow this to happen it's a skill issue. And if the Queen rushes the DS whilst 20+ ground marines are still alive she's prbobably not surviving it. Unless all her xenos are with her.
> 
> Also whilst Alarms might be "Immersive" in this uh 2D Ancient Spess Game. I don't think we need more of them. The Dropship Departure alarm is already annoying as is.
> 
> And considering how often queens will just kill all the ground side marines and wait for bursts and everyone to get in the dropship I don't think we need a timer. Funny xeno stealth DS runs, are just that funny. And usually just result in a xeno wipe after hijack.

it's not really a skill issue, it's just not balanced. Alarm can be removed, but there are more sounds that aren't just alarms. I have been in a few matches where comms are down, queen breaks through and no one notices and then she runs up to the ds and locks it within a second and then scurries off.  Wasn't really talking about meme hijacks.

**Comment by InsaneRed** [comment]
why not make the unhacking process easier instead

**Review by Drulikar — CHANGES_REQUESTED** [review]
Unresolved licensing issues with https://www.pond5.com/legal/license that would likely require at a minimum an All Media License and even then likely has other issues being in an open source project. At a minimum the license would have to be included with the pull request along the files.

I also don't think the alarm is necessary, nor think another do_after for queen is necessary especially when marines already have an easier time removing a queen override bringing the time cost down below 4 minutes #5143

**Comment by Cthulhu80** [comment]
yawl are TRIPPIN'.

**Pull request closed without merging**
