### PR TITLE
New Defender Strain: Steel Tail

### PR DESCRIPTION
**Pull request by usnpeepoo**
## About The Pull Request

New strain for defender, Steel Tail. All about using it's tail for combat, with an emphasis on zoning/displacement.

Health is 450
Armor is 25
Speed is now the same as warrior.
Loses all of its base abilities, 10 armor, 50 health, for 3 new abilities.

**Tail Slam:**
A 1 tile Tail Slam that deals 25 damage (5 less from base defenders headbutt) with 10 armored damage to chest (5 more from base defenders headbutt). It shakes the screen of a marine, and dazes for 3 seconds. It has another effect, when a marine is already knocked down. The effect is a 2 second slow.

**Tail Swing:**
A 2x3 tile Tail Swing that is activatable (With a short windup) and knocks down any marine in those tiles for 1 second. Works on corners, similar to Oppressors tail lash however it looks different, and does not fling/slow.

**Tail Fling:**
An adjacent displacement fling (With a 0.2 second knockdown) that has a unique mode. On help/grab/disarm intent, it will throw the marine behind the defender for 1 tile. On harm, it simply throws forward for 2 tiles.

## Why It's Good For The Game

Allows defenders to choose between it's tanky and anti-stun but combatable base, and a new, less tanky zoning/displacement  combat strain. I made this PR in the belief that, the only other strain defender has, is all about using its crest, and it's combat ability is really small. Although it has an entire ability with its tail, there's nothing else similar to it.

With this PR, I want to introduce a comparable option to base defender, with a focus on the mace looking tail that it has. I believe that the current abilities are not too powerful, comparable even to base defender except for the fact that it has knockdowns rather than a simple fling on each ability usage. However, the loss of crest down, and some of its stats merit these effects as they are integral to base defender play. With new abilities, it makes up for this loss and hopefully shows it can be a fun, but not an extremely powerful strain.

## Changelog

:cl: usnpeepoo, Drathek
add: Added a new strain for Defender, called "Steel Tail".
add: Steel Tail strain exchanges all of your abilities, and some stats for 3 new abilities with a focus on Tail usage.
add: Active 1: Tail Slam, 1 tile, slam with your tail. 25 damage, 10 armored damage to chest. Dazes for 3 seconds, when used on an already stunned marine, slows for 2 seconds. (8 Second Cooldown)
add: Active 2: Tail Swing, 2x3 swing with your tail that knocks down for 1 second. Has a short windup. Works on corners. (12 second cooldown)
add: Active 3: Tail Fling, an adjacent displacement, has a 0.2 sec knockdown. The displacement depends on your intent. On Help/Disarm/Grab intent, it will send the marine backwards 1 tile. On harm, it will send them forward for 2 tiles.
/:cl:

### CODE REVIEW

**Comment by PhantomEpicness** [comment]
ok epic

**Comment by usnpeepoo** [comment]
https://streamable.com/sd8otw

**Comment by carlarctg** [comment]
the throw behind ability is awful and insanely unfun imagine getting backthrown into the xeno horde theres literally nothing u can do about it. play on tgmc and see for yourself

**Comment by ilikesaying** [comment]
^
getting flung into the xenos is almost always a death sentence, even more so here since marines are squishier.

**Comment by oniondry** [comment]
At the very least the backfling shouldn't pull marines over cades, that seems a bit strong for a T1 caste ability that has no telegraphy.

**Comment by usnpeepoo** [comment]
> At the very least the backfling shouldn't pull marines over cades, that seems a bit strong for a T1 caste ability that has no telegraphy.

the telegraphy is it walking up to you while you are next to an unwired cade, it's only 1 tile now n i tested it in a test server n it doesnt seem to be that powerful. Should be good now

**Comment by GoldenDarkness55** [comment]
All this fling coping. Just buck/slug it. Would be cool if it worked with wired cades too.
I just hope the knockdown triggers after displacement so you still got ur gun under you and not behind the fender.

**Review by Agameofscones — APPROVED** [review]
haha color loss results in smaller dmi files, neat

sprites check out fine :+1:

**Comment by usnpeepoo** [comment]
reopening later.

**Pull request closed without merging**
