### PR TITLE
Queen Charge

### PR DESCRIPTION
**Pull request by Geevies**
## About The Pull Request

Re-adds Queen Charge using Charger backend. It's pretty expensive plasma-wise so they won't be replacing crushers.

## Why It's Good For The Game

https://youtu.be/1sE-YwK6_PI

## Changelog

:cl:
add: Re-added Queen charge using Charger code.
/:cl:

### CODE REVIEW

**Comment by stanalbatross** [comment]
Please provide an actual "why it's good for the game"

**Comment by novaepee** [comment]
>queen charge back in CM

image

**Comment by CABSHEP** [comment]
Rename it to "Get out of Jail Free Card", because that is what it will always be used for and that was the reason it was removed. 
Now Queen will either just charge, screech and then retreat, or just charge to run away.

**Review by kugamo — CHANGES_REQUESTED** [review]
Can we make sure the damage overlays work while the queen is charging, they were added in the mean time since this was in the game.

**Pull request closed without merging**
