### PR TITLE
New TWE Warcries

### PR DESCRIPTION
**Pull request by Kyogon**
# About the pull request

I felt like the TWE (Royal Marine Commandos) ERT wasn't flavored enough with their stock warcries, despite being painfully bri'ish. I added some warcries for them (for both genders) that should make playing them feel a little more unique.

Yes, I know Sniper is Australian. No, I don't care. 

# Explain why it's good for the game

GOD SAVE THE QUEEN!!

UPP has custom warcries that make them really stand out from marines, so RP-wise TWE having their own voicelines will enhance immersion and add a little bit of fun to those who get the ERT roll.

# Testing Photographs and Procedure
I took a recording of the warcries, and after I was satisfied with the results I realized I was recording in gif form. It works though. It's just a simple code addition that uses the same code the UPP warcries do.

Each gender has two voice matching voice lines.

# Changelog

:cl:
soundadd:  Added unique warcries to TWE ERT
/:cl:

### CODE REVIEW

**Comment by IroquoisLou** [comment]
Australia is a member state of the TWE, so it makes sense some would sound australian.

**Comment by cuberound** [comment]
I did read this title as warcrimes several time and hoped for those...

**Comment by Valiant1st** [comment]
Australia got nuked.

**Comment by Kyogon** [comment]
> Australia got nuked.

Sniper sounds more british than aussie anyway, so it's fineeeeee

**Review by Zonespace27 — CHANGES_REQUESTED** [review]
These sounds don't really fit. The only one that might be salvageable is female 2.

**Pull request closed without merging**
