### PR TITLE
JIMA Pride Flag

### PR DESCRIPTION
**Pull request by senorsapo**
## About The Pull Request

It resprites the JIMA flags into a rainbow-pride flag for pride month.

## Why It's Good For The Game

We're in pride month and it could be a nice change for the month.

## Changelog

:cl:
add: The JIMA flag has been resprited into the pride flag for pride month.
/:cl:

### CODE REVIEW

**Comment by S1tr3p** [comment]
YOU SHOULD SPEEDMERGE THIS PR...

**Comment by PhantomEpicness** [comment]
if this doesnt get speed merged we will CANCEL cm

in all seriousness JIMA actually needs a logo, its bland to have it just red and we all know who is red.... **COMMIES!**

_Better dead than red!_

**Comment by MusselMain** [comment]
after this month I mean

**Comment by Nanu308** [comment]
Similar to last year we try and remain apolitical which was a management decision and i am not aware of this having been officially changed yet.

Closed until further notice.

**Pull request closed without merging**
