### PR TITLE
Welder chestrig

### PR DESCRIPTION
**Pull request by Dorodomki**
# About the pull request

Adds an Welder chestrig for Drip purposes, the chestrig spawns for the MT's for now and works exactly like an Welder Satchel

# Explain why it's good for the game

Adds higher quality sprites for the game, being usable by almost any human faction since is not fully sprited into "Marine art Style"

Captura de pantalla (336)

Captura de pantalla (335)

# Changelog
:cl:
add: Adds a welder chestrig for MT that works like a welder satchel.
/:cl:

### CODE REVIEW

**Review by harryob — APPROVED** [review]
code fine

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by Drulikar** [comment]
Please use the PR template so that you can have a changelog for players to view. Feel free to add your ckey with a space to the right of `:cl:` if you don't want your github username attributed. I have already edited the template back in the description and added a basic changelog line for you.

If you install the hooks at https://github.com/cmss13-devs/cmss13/tree/master/tools/hooks the two conflicts you have with the sprites will automatically be handled by adding the sprites to the end of the file. Feel free to re-arrange them again if you like afterwards.

**Comment by Dorodomki** [comment]
do whatever im too tired for this and im not even able to play the game since a funny dude banned me without any evidence

**Comment by harryob** [comment]
#4029

**Pull request closed without merging**
