### PR TITLE
[WIP] Kutjevo Refinery Rework.

### PR DESCRIPTION
**Pull request by Venuska1117**
I will improve description later when map will be ready.

# About the pull request

Change Kutjevo Refinery base concept by adding more terrain destruction, map patterns and expands areas of contact.

Requires:

- [x] #7096 
- [x] #7199

# Explain why it's good for the game

Makes Game Experience better, add new terrain, more structures, enhance visuals, all of this will improve gameplay and experience.

List of changes:
- You can now walk "behind" rafinery sprites.
- Farinery sprites now block sight.
- LZ1 south tcomm got moved more south. 
- LZ2 north tcomm got moved more east.
- Changed stucture north of LZ2 to "Water Pump" station.
- East of "Water Pump" station, there is 'structure' where water is pumped to.
- North of medical is now expanded with 'surgery wing'.
- Added Sand patterns for visuals.
- Increased amount of grass and grass clusters.
- Caves are now rich in dryied grass and grass clusters.
- Monkeys spawns now only inside tall grass clusters.
- Added more "green plants" close to bodies of water.
- Replaced Big unused part of botany with science departament, to study plants and "lifeforms"

# Testing Photographs and Procedure
high quality image from map maker: (open in browser or download for higher quality)

<details>
<summary>Click THIS to see image</summary>

StrongDMM-2024-08-30 00 52 10

</details>

Last Image Updated: 22.08 at 12:55 (GTM +2)

# Changelog
:cl:
maptweak: Rework Kutjevo Refinery
/:cl:

### CODE REVIEW

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by Venuska1117** [comment]
I will re-open this PR after i do any work on it.

**Pull request closed without merging**
