### PR TITLE
Fixes minor mapping errors

### PR DESCRIPTION
**Pull request by Releasethesea**
# About the pull request

The last one i put up had merge conflicts so i decided to just close it and make a new one since i couldnt figure out how to fix them lmao

# Explain why it's good for the game
Mapping errors bad, fixing them good

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl:

fix: Fixxed the improperly area'd hull south of construction site, adds fire shutters to north fueling pod to make it mirror the south one

/:cl:

### CODE REVIEW

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Review by harryob — APPROVED** [review]

**Pull request merged**
