### PR TITLE
Squad Leader Specialization Kits

### PR DESCRIPTION
**Pull request by Geevies**
## About The Pull Request

Added specialization kits for Squad Leaders. Squad leaders no longer have engi level skills, but their skills increase based on what kit they take.

**-- Always Spawns --**
 - 1x breaching charge
 - laser designator
 - map
 - zipcuffs

**Pyrotechnic Kit:**
 - USCM Pyrotechnician G4-1 fueltank
 - M240A1 incinerator unit (with extinguisher)
 - 2x incinerator tanks
 - 1x incinerator tank (greenfire)
 - mini fire extinguisher
 - 6x M40 HIDP incendiary grenades
 + CQC Skill: Skilled

**Construction Kit:**
 - 2x plastic explosives
 - full toolbelt
 - ES-11 fuel canister
 - 25x empty sandbags
 - 50x metal sheets
 - 30x plasteel sheets
 - 20x barbed wire
 - folded e-tool
 + Engineering Skill: Engineer
 + Construction Skill: Engineer

**Recon Kit:** - Added in backend
 - 2x breaching charges
 - motion detector
 - helmet NVGs
 - M4A3 service pistol (suppressor, laser sight)
 - 2x spare M4A3 mags
 - large general pouch
 - machete pouch
 - 15x M20 Claymore anti-personnel mine
 + Endurance Skill: Master
 
**Triage Kit:**
 - MS-11 Smart Refill Tank
   - 60u bicaridine
   - 60u kelotone
   - 60u tramadol
 - auto-injector pouch
   - 2x bicaridine autoinjector
   - 2x kelotane autoinjector
   - 2x tramadol autoinjector
   - emergency autoinjector
 - pressurized reagent canister pouch
   - 192u tricordrazine
   - 192u inaprovaline
   - 96u peridaxon
 - SensorMate HUD
 + Fireman Carrying: 1 Second

## Why It's Good For The Game

Currently, squad leaders only have the one kit, the flamethrower, which is kind of boring.

## Changelog

:cl:
add: Added two new SL kits, Construction, and Triage.
balance: SLs no longer have engi-level skills by default, but will gain skills based on the kit they've taken.
balance: SLs now get 40 budget points instead of 45. Additionally, NVGs cost 25 points now.
/:cl:

### CODE REVIEW

**Comment by c4xmaniac** [comment]
Holy shit lois recon SL is the new protagonist

**Comment by Don2137** [comment]
Unsure if SL kits is a good idea or not so I'll simply comment on the contents.

**Pyro**
Is the greenfire the exact same as the spec one, with the cone aoe and all? That, and HIDPs will lead to endless chokepoint stalling most likely.
Also, why does this increase CQC?

**Construction**
Same mats engis get for free + 20 in the form of wire. Nothing an SL can't get elsewhere here but definitely convenient. At least it will hammer in the point that SLs should be building the FOB if need be.

**Recon**
The best one, objectively. MD and breaching charges (or C4) is necessary equipment for SLs so getting those for free means you can spend points on something else (probably AP or grenades). The rest is kinda pointless. Claymores are funny though.

**Triage**
This one is honestly really wacky. The refill tank is eh, the autoinjector pouch you can get from the SL vendor normally I think? The pressurized pouch is also wack, 3 different chems all with different ODs and no medical scanner to prevent murderizing your squaddies. This should also probably give you med 1.




If you want more ideas, signal flares are very useful on SL. So maybe something with that.

**Comment by arrkaxe** [comment]
As a Bravo SL main, me likey

**Comment by Katskan** [comment]
Looking at the lineup, CQC is really only useful in HvH. Would be nicer I think if maybe there was some overlap, e.g. pyro and recon both have 1 extra level in endurance over normal (going all the way to master seems... overkill and they're both the frontline sort of options) and then their unique aspect is the easy kit access. To that effect as well with the support options of engineer and triage, engineer getting construction/engi 3 is a really good fit. Triage getting faster fire carry is nice but without medical 2, the slow HF2 speed and inaccuracy of fracture scans is a problem for someone needing to assist medical and potentially sling meds plus the kit items are mostly easily sourced and/or not really useful to someone without medical 2's fast and accurate scanning. 

I really like the idea of the SL kits as being like a "this person used to be this role before they got promoted to being a squad leader" so having them take on mergers with other kits like medic, engineer, specialist and RTO is a really cool RP and soul addition. "Yeah the sergeant was a medic for 10 years before they got promoted" or "sarge used to be a jungle recon marine" is neat.

**Comment by Superreallycoolguy** [comment]
Master endurance...

Holy crap Lois the new protag just dropped!

**Comment by Don2137** [comment]
Ok i read what you wrote about endurance on discord and I still don't think recon should have that

**Comment by hotimep** [comment]
HOOOOOLY SHIT
18f8a65324d0331facbc8e16b2248bc0

**Comment by ZAB909** [comment]
I don't think SL should be specialised. It gets people to roll SL for the gear, and not for actually leading people.... Like they're meant to.

**Comment by GoldenDarkness55** [comment]
As people said, endurance buff is uhhhh questionable. Maybe give them scout armor instead or a buff to weapon skills? Possibly give flamer endu and scout cqc, since flamer seems to be the worst one.

As for triage - just turn them into full fledged medics, or at least give them defib access somehow. SLs used to have medic skills at some point, would be cool to see that return.

**Comment by stanalbatross** [comment]
fix conflict

**Comment by IngloriouslyBad** [comment]
This isn't balance, this is a SL nerf. So we're losing the ability to help build FOB by default and have to take a shitty vendor option to do something SL's have been able to do for years and years when no one else shows up to help? Clown neverplayer of SL role 
 big brain nerf ideas... 

None of these options are remotely good except for recon, but you're not really taking that for anything but endurance stat

**Comment by c4xmaniac** [comment]
SL should have engineer skill because they’re frequently required to be the ones to build the fob, especially on lowpop. If I’m the alpha SL and bravo is assigned to fob duty but bravo has no engineers (or an SL) and I’m tasked to the fob after already choosing my kit, that would mean the op is fucked. There’s plenty of situations, just give the engineer SL powerloader skill or something. 

Also, arent mortar skills are tied to engineering or construction, I can’t remember. So this means if you don’t go the engineer SL kit you cannot use the mortar. 

Overall this seems like a huge SL nerf. Medic and pyro are useless, one is just OD all your Joes and the other is just a budget pyro spec that does nothing different than what the flamer you can vend now already does. Recon is okay, and engineer is mandatory if you don’t want gimped skills. I’d recommend relooking over the kits and reconsidering the medic one entirely - SL is a leadership role and you are not leading if you’re sitting in the back triaging. I and many others rarely assigned aSL to corpsmen for a reason.

**Comment by stanalbatross** [comment]
fix conflict

**Comment by hotimep** [comment]
you dont build as SL you yell and command people to build as SL

**Comment by SarahJohnson489** [comment]
Yelling doesn't always work and at times you have to handle critical functions yourself whether from incompetence, lack of interest, all of them leaving for the front, or just lowpop meaning they don't even exist. We'd love it if things ran smoothly and you could just lie in a bed on the fob shouting orders but it doesn't work out like that nor should it be coded so a working situation is broken.

**Comment by JohnDoe50974** [comment]
I beg to differ with this baseline engineering skill removal, FOB construction is something SLs are normally expected to do in a pinch, and restricting engineering skills to a specific kit means the players will (esp on lowpop) set themselves up for failure, through no fault of their own. What would make the engineering kit worthwhile is to add a sentry gun to it instead.

**Comment by Misttyy** [comment]
Feedback and balance suggestions from playing SL:

- Add NVGs to each SL kit. Make NVGs cost an SL's entire vendor points. Making them chose between buffing themselves or their spec, or putting their spec at an advantage over themselves. Currently able to get 3 NVGs with recon kit, way too many.

- Remove the claymores. Unable to carry them as an SL with how many spawn - More or less they're just going to get handed off to Bravo and make FOB sieges even more painful for both sides.

- Add defibbing to triage SL kit. Make sure they can't use synth line or surgical graft, ensuring medics still stay relevant by being the only squad personnel who can treat high damage dead. Add health scanner. Possibly make SL defibbing take longer(?)

- Possibly add a nerfed version of the pyro spec's extinguisher to the pyro kit? Giving it the one tap extinguish would make the pyrotechnician kit a viable grab for SL. Currently, there's no reason for any SL to take it seeing as you're expected to be at the front of a push usually and can't put out your own flames fast enough. The one tap extinguish but with far lower reserves than the pyro spec would still leave it something to be thoughtfully used.

- Lower recon kit to only have one breaching charge, or otherwise drop the standard spawn breaching charge from every SL kit. Having 3 breaching charges from recon feels excessive.

- Possibly remove the recon M4A3? I don't see much use for it, I tried to use it as recon and it was useless more or less. Would be good if it was a custom M4A3 but that'd probably powercreep recon too much.

- Probably remove the fuel canister from the construction kit and spawn them a welderpack as a QOL change.

- Making the SL kits spawn in cases like specialist kits would be a nice QOL change.

I think this would be a nice outline for SL kits. On lowpop, it means you can act as a worse engineer (no sentry) or a worse medic (no ability to treat high damage victims). Letting SLs fill gaps within their squad as support ontop of leadership.

Pyro becomes viable as frontline support and recon would be a nice pick for more aggressive frontline SLs.

**Comment by Kenju22** [comment]
Feedback suggestions from observations:

Add a single encryption key to each of these SL spec kits based on which case is selected:

Construction: Engineering channel

Recon: Intelligence channel

Triage: Medical channel

The above would benefit those specific SL kits a great deal given the additional duties they are taking on. Pyro doesn't really need one.

Add some kind of unique belt to the Recon kit that can carry mines, as others have pointed out there is no way to carry that many claymore mines.

Add Technician helmet to Construction Spec kit and Industrial blowtorch.

**Comment by Ticker175** [comment]
I’ve played a few rounds as SL with this merged and I figured I’d leave some feedback (I normally play bravo SL). I can say I dislike this TM because SLs are supposed to be able to lead their squad and cover for any shortcomings in their squad.
The main issue I have with the specialisation idea is the skill tank you take when you pick each specialisation. If I play bravo SL and I want to have a flamethrower or something other than building then I have no engie skills so I cannot reinforce/crest fob which half the time means fob doesn’t get built

suggestion: leave the skills as they are and give the SLs a choice of special weapon/speed boost/speciality item

**Comment by ddamousd** [comment]
I think some stuff needs to be toned down, Recon and Pyro are WAY too good.

**Pull request closed without merging**
