### PR TITLE
Adds Urban Sprite For Ghillie Suit

### PR DESCRIPTION
**Pull request by Steelpoint**
# About the pull request

Replaces the Green ghillie sprites for the Sniper/AMR into a more Urban sprite, using the Elite Mercenary Sprites akin to Forecon, for urban maps like Chances Claim or Fiorina. 

# Explain why it's good for the game

Very odd the Sniper/AMR are using Green on a grey map for camo. This makes it look appropriate, and precedent the USCM uses this scheme in forecon. 

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Screenshot 2024-06-26 04 48 39

</details>

# Changelog
:cl:
imageadd: The Sniper and Anti-Material Rifle Specialists will now use an urban camouflage sprite for their ghillie suit instead of a green camouflage. 
/:cl:

### CODE REVIEW

**Comment by Steelpoint** [comment]
Error is not obvious to me.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by Drulikar** [comment]
stale exempt until sprite reviewed

**Review by nauticall — APPROVED** [review]
not exactly much of a ghillie anymore but i suppose the alternative would be making it out of trash or something for urban

either way, approved, does the job

**Review by harryob — APPROVED** [review]

**Pull request merged**
