### PR TITLE
allows synthetics to paint their faces with facepaint

### PR DESCRIPTION
**Pull request by AndroBetel**
# About the pull request

adds HAS_LIPS flag to synthetic species parent class

# Explain why it's good for the game

synth drip
lipstick for working joes

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

image

</details>

# Changelog
:cl:
add: Synthetics can use facepaint and lipstick.
/:cl:

### CODE REVIEW

**Comment by AndroBetel** [comment]
image
evil wj =)!

**Comment by thevandie** [comment]
Scary!

**Review by fira — APPROVED** [review]

**Comment by Red-byte3D** [comment]
There is no reason for a synthetic to ever use these, nor should they per roleplay standards?

**Comment by AndroBetel** [comment]
> There is no reason for a synthetic to ever use these, nor should they per roleplay standards?

dont they have helmets, marine uniform, camo ponchos and even synthetic "armor" in their vendors? whats stopping them from putting a lil paint on their faces...

**Pull request closed without merging**
