### PR TITLE
Update to some ultra ancient sprites

### PR DESCRIPTION
**Pull request by Blundir**
# About the pull request

This pr aims to update/correct sprites that look like this:
<details>
<summary>Example</summary>

StrongDMM_j51KDPeYYU
StrongDMM_8kBEwLWHKn
StrongDMM_vCmcme098x
StrongDMM_YcpXSx2Csu
StrongDMM_x8ze6bT0Ye
StrongDMM_PkvyE8FMPW
StrongDMM_mjvY3r7nMT
StrongDMM_WoHe9doCda
StrongDMM_xWgkCF5uC3
StrongDMM_IFnTgcGcUY
StrongDMM_OlOJTtvvhL
dreammaker_MVtobf4dvv

</details>

Such sprites are very very old, pre cm era most of them, some of which weren't updated for 12+ years.

Most of updated sprites were taken from TGMC, others from Baystation, Aurora and TG, all credits to them, remaining sprites were made by me.

To see full list of what i've updated, see icondiffbot changes.

# Explain why it's good for the game

Less fossilized stuff.

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

StrongDMM_u5OswblCBx
StrongDMM_1UHx0NK8Q6
StrongDMM_rbth5mZSWJ
StrongDMM_Mp66s8sWGx
StrongDMM_ceEEajlHNZ
StrongDMM_uIVfaqHsGd
StrongDMM_FikQODdmRy
StrongDMM_hH03QCpTJR
StrongDMM_U3Jb51Gcs0
StrongDMM_wczgnQ89oE
StrongDMM_M09Y0daC8u
dreammaker_MmtlKcPWIk

</details>

# Changelog
:cl:
imageadd: updated many old/legacy sprites
/:cl:

### CODE REVIEW

**Review by Nanu308 — COMMENTED** [review]
Mapping lgtm

**Comment by Nanu308** [comment]
I see you mention porting some sprites, have you made sure to update them to CMs style / standard regarding sprites?

**Comment by Blundir** [comment]
> I see you mention porting some sprites, have you made sure to update them to CMs style / standard regarding sprites? 

I've reused many cm sprites here, the sprites I took from tgmc are CM stylized, they were made in early tgmc era, about other sprites, they look passing, especially compared to their current counterpart, I've included a comparison, in case you didn't notice.

**Review by sleepynecrons — APPROVED** [review]
good to see someone helping chip away at legacy sprites. approved 👍

**Pull request merged**
