### PR TITLE
Fixes users getting locked in simulation view / simulation refactor

### LINKED ISSUE #4927: getting stuck in the demolitions simulator with two people.
### Testmerges

N/A

### Round ID

19518

### Description of the bug

Whenever two people enter the demolitions simulator, after the first person exits the second person can only exit by ghosting, as the exit option/UI goes away. 

### What's the difference with what should have happened?

 The UI to leave goes away when the first person exits the console.
 Right now I have to tell people to ghost then put their ckey back in to get them back into the game. This shouldn't be happening.

### How do we reproduce this bug?

1. Person one enters the demolitions simulator camera/UI.
2. Person two enters also.
3. Someone leaves the UI first, it doesn't matter who. 
4. Once someone leaves, the option for person two to leave disappears. 
5. The only way out that I know of is to ghost.

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

### PR DESCRIPTION
**Pull request by Cthulhu80**
# About the pull request

Initially I thought I introduced this bug, but it looks like it's existed for a few years. Fixes #4927. Also did some minor refactoring for the simulator.

# Explain why it's good for the game

bug bad

# Changelog

:cl:
fix: fixes users getting stuck inside of the simulator
/:cl:

### CODE REVIEW

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Review by Drulikar — APPROVED** [review]
Code looks fine and can confirm the fix is working.

**Comment by dadlips** [comment]
detonate explosive button doesn't work (it stays grayed out.)
https://streamable.com/pmm2vu

**Comment by Cthulhu80** [comment]
> detonate explosive button doesn't work (it stays grayed out.) https://streamable.com/pmm2vu

oh shit, let me fix that.

**Pull request merged**
