### PR TITLE
Squad Briefings 2: The Briefening

### PR DESCRIPTION
**Pull request by Warfan1815**
# About the pull request

Adds optional briefing rooms in place of long-rest bunks (moved further north and south respectively) that don't replace standard briefing.

Excuse for me having to make a new PR, I fucked up the old branch so beyond repair I had to close it (next time I won't mess around with merge conflicts and just trust the hook)

# Explain why it's good for the game

Gives SLs a platform where they can host anything they want. As well , if command wants to brief the SLs and then have the SLs brief squads they can also do that.

The old squad briefing room PR was cool, its just it was replacing instead of adding. Here I hope to satisfy both camps.

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>
map

</details>

:cl:
mapadd: New Squad Briefings south and north of normal briefing! Feel free to use them to your heart's content.
maptweak: Moved long-rest bunks further north and further south of where they were originally
/:cl:

### CODE REVIEW

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by Zonespace27** [comment]
I have my reservations but I'm willing to TM for a few days

**Comment by Zonespace27** [comment]
I'm happy with how it's been (even if it hasn't been a massive amount of SLs briefing), adds soul to the game. Mapping was happy w/ the PR map-wise

**Pull request merged**
