### PR TITLE
Adds hazard joe voicelines

### PR DESCRIPTION
**Pull request by Mister-moon1**
# About the pull request

Finally the hazard joe will have its own voice lines along with some minor changes, since they were added it was planned for them to be more durable and maybe get the voice lines from alien isolation. This PR is here to do this by increasing the HP by a small 25 and a minor increase to burns at the cost of a bit of speed along with porting around 43 unique hazard joe voice lines.

# Explain why it's good for the game

Adds soul by making hazard joes more realistic, they were supposed to be dealing with cores and reactors as opposed to the standard maintenance that of a normal working joe along with giving them lore accurate voices.

# Testing Photographs and Procedure

https://streamable.com/hze2y8

</details>

# Changelog

:cl:
soundadd: added new voice lines for the hazard varient of the working joe
balance: minor changes regarding hazard joe durability and speed
code: made hazard joe its own species for ease of editing
/:cl:

### CODE REVIEW

**Review by Zonespace27 — CHANGES_REQUESTED** [review]
How you went about this is, in my eyes, fundamentally wrong.

Ideally, you should be adding a 2nd variable to WJ emote datums with the hazard joe variant sounds, and overriding the base WJ emote datum's `get_sound()` to use the alternate voiceline if the person is a hazard joe

**Comment by Mister-moon1** [comment]
along with issues with VSC telling me that it cannot find a file which i did not ask it to every time i try to do something and other issues getting code to work i will be closing this, if anyone wishes to try and do this you may DM me for the sound files

**Comment by CGosling** [comment]
> 

May be worth linking your discord info for the DMing.

**Comment by Mister-moon1** [comment]
mrmoon8844 is my discord

**Pull request closed without merging**
