### PR TITLE
Science Annex Nightmare Inserts

### PR DESCRIPTION
**Pull request by c4xmaniac2**
# Science Annex Nightmare Inserts

Apparently I'm the only one in CM who actually likes this fucking map, and like a year ago I told nanu I'd make NM for science annex and kutjevo. Also so help me God if this fucking lowers my GBP because i don't know how the shitty GBP economy works I'm going to have an aneurism. 

**Also I'm not on the discord, if you have comments leave them on the PR.** Nor will I be rejoining. That place sucks and I don't like interacting with the retards on it. Sorry sweeties, but daddy has no desire to rejoin that shitshow. You have no idea how freeing it is to not hear people crying about everything at all times.

> This PR adds 4 new NM to the map Science Annex.

WRONG WE'RE AT 10 NOW BABY!!!!!!!!!

**Lan Party** 20% Chance

gamerannex
This insert features an epic lan party between the prisoners and the prison staff, who will win in this epic competition? Xenos.

**Pizza Palace** 30% Chance
pizzaannex
This insert changes the kitchen to be a pizza palace. Mamma Mia! (The pizza time is replacing the sentry spawn, its so fricken thematic)

**Pool Party** 20% Chance
poolannex
Woah dude, prison's out man heh surf's up dude! Come and hang out with your best pals while everyone else around the station dies.

**Warden Office - Redecorated** 15% Chance
wardenannex
The warden has found God, well a god, the god of HEFA and chose to sacrifice himself to bring the pain! The knights said he had a change of heart, but too bad!

**POD HOLD BABY** 10% Chance
podhold2
Oh yeah baby! I heard you've never even heard of this SOULFUL HOLD!!!! Don't worry, with the NEW CHANGES coming to it, its now 25% better! Better hope that medium chance sentry actually does spawn, though.

**Engineering Office** 30% Chance
engieoffice
Thought it would be cool if they didn't demolish the office, so here it is repaired and with new minor stuff like a cool beret to tempt you to check it out. Also don't read the paper.

**Research Cells Containment** 25% Chance
research
The prison staff assumed that whoever was the cause of the outbreak was in these cells. Unfortunately for everyone, they ended up being wrong. You get to witness what's left over in the research cellblock if they walls weren't destroyed from the beginning!

**Emergency Medical Practice** 20% Chance
medicalhold
Shit really started hitting the fan, so the medical staff set up a temporary treatment area in the triage zone. Strangely, the sounds of men screaming in agony attracts xenos, who knew?

**Scav Ship Hold** 10% Chance
scavship
I heard you liked single man suicide holds? Awesome news then, I've got another one for you. This one even comes with elite mercenary gear to help you survive. Only problem is the guy who owned it before you didn't maintain it, and its not that protective now. One might say the slow down of the armor will kill you, I say drip or drown loser. Go out in style!

**Looted Armory** 15% Chance
empty
You know what they say, the early bird gets the worm. Well in this case, the early prisoners got all the gear. Help yourself to what's leftover, it's not much!

**Miscellaneous changes**

The sentry gun in the park is gone. This shit still massacres new surv players and they don't know what happened. Call it baby sitting, I don't care. I intended to remove it when I changed LZ1 and forgot, so it goes bye bye now!

podhold
This piece of shit console now no longer blocks movement. The META DEFINING pod hold is now slightly stronger. Honestly, 70% of the people reading this probably don't even know where this is located and 100% don't go into it. Listen, it bugs me that this shit blocks you being able to move. Imagine having an extra dude to FF you in the now 4x4 box of hell. The possibilities are endless, not really, but I'd like to think so.
 
# Explain why it's good for the game
Nanu asked me to make NM for this map and kutjevo. I like this map more than kutjevo, so I made some for here first. It adds character, who doesn't want to sacrifice the warden for HEFA?

Sentry change is QOL for new players. It had literally 0 impact outside of killing new players. Its funny, but we have to protect the children. Call this the protect the children change and it will pass through the dev team, I guarantee it. 

The console change is a QOL change for me because its so fucking annoying that this little piece of shit can stop me from moving. LOOK AT IT, IT'S AGAINST THE FUCKING WALL, HOW DOES IT BLOCK THE ENTIRE TILE?!

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl:
mapadd: added 4 new NM inserts to Science Annex
maptweak: sentry in the park no longer terrorizes new players, and the stupid fucking console doesn't block movement.
/:cl:

### CODE REVIEW

**Comment by morrowwolf** [comment]
There's zero obligation to be on the discord. If you ever want to talk about dev stuff or whatever feel free to add me: morrow#1453. Good to see ya around still brother.

Otherwise, I'll take a look at this in the next week or two. Looks neat.

**Comment by c4xmaniac2** [comment]
You're welcome, I made this review 150% more work for you. Have a CM day!

**Comment by Agameofscones** [comment]
The grille as a grill. Peak mapping.

**Review by harryob — APPROVED** [review]

**Comment by scoutskywalker** [comment]
Pod hold is back let's go! I would say that having the pod always having a static sentry would probably be fine, since that hold will get gassed out by boilers at 12:20. If it could get picked up then it should stay medium chance.

**Pull request merged**
