### PR TITLE
Warrior Nerf

### PR DESCRIPTION
**Pull request by morrowwolf**
# About the pull request

This PR removes cooldown reduction on slash.

This PR slightly lowers fling and punch cooldowns.

This PR lowers fling stun to a micro stun and adds a slow.

This PR decreases lunge range to 4 tiles.

As a reminder design feedback and balance concerns go here: https://forum.cm-ss13.com/w/pr-feedback/steps/step_1

# Explain why it's good for the game

Warrior rework has been on my mind for a while. I'm not quite sure how I want to do it. The cooldowns on abilities and the abilities themselves are incredibly powerful crowd control and just a few warriors can do immense damage to large groups of marines. It's just... not in a great place for a T2 and sadly I don't have a thorough game plan yet to rework it into something more bearable while equally enjoyable to play. In the mean time, this is what we're getting. Am I promising a rework in the near future? Not really. It's on my list somewhere. Does warrior need some changing around? Yeah.

Overall, this should make warrior a bit more bearable. We'll see. More changes as testing goes.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl: Morrow
balance: Removes warrior cooldown reduction on slash
balance: Warrior slightly lowered fling and punch cooldowns
balance: Lowers fling stun to a micro stun and adds a slow
balance: Decreases warrior lunge range to 4 tiles
/:cl:

### CODE REVIEW

**Comment by cm13live** [comment]
This pull request has been mentioned on **CM-SS13**. Please provide feedback here:

https://forum.cm-ss13.com/t/warrior-lunge-changed-to-a-wind-up/2287/14

**Comment by InsaneRed** [comment]
Dropping the lunge to 4 tiles is only going to enable and reward warrior players to camp corners and doors more this is exactly what people are complaining about

**Comment by morrowwolf** [comment]
Future me add a very small stun to fling thanks bro

**Comment by Flerpin** [comment]
" It's just... not in a great place for a T2 and sadly I don't have a thorough game plan yet to rework it into something more bearable while equally enjoyable to play. In the mean time, this is what we're getting."

Then why are you making a change in the first place? Why do you feel like there's a need to change warrior if there isn't a clear cut goal? Seems like you're blindfolding yourself and throwing darts at a board, then shrugging your shoulders with the results.

The fling stun into a micro-stun doesn't really do much as the main purpose of it is displacement, so it seems pretty okay to change as is as, again, the purpose of it is to fling the marine into a very bad position.

As far as the fling goes - that is a horrid nerf in the most obvious way. 
1 - Encourages the playstyle people hate the most (door/corner camping) while nerfing mobile and risky playstyles that are less frustrating to fight.
2 - you're directly removing a choices from a player. currently, a warrior can CHOOSE to simply not lunge full screen to get a marine - but with this change, they're forced into particular playstyle and having choices removed from a player is just not fun
3 - removes the ability to just straight up make awesome and risky plays. how many times has there been a good warrior that has made a risky play of lunge full screen only to get immediately dog piled on by marines? on the flipside, there have been situations where a warrior making a risky lunge on a key marine player like SADAR, pyro, etc has made a huge difference when they were successful.

Just feels like this entire change was clearly rushed and had not really been fully thought out.

**Review by harryob — APPROVED** [review]
fuck it we ball

**Pull request merged**
