### PR TITLE
CO armor resprite

### PR DESCRIPTION
**Pull request by Blundir**
# About the pull request

Gives CO armor an actual non placeholder sprite, that matches helmet, gloves and overall aesthetics.

dreamseeker_s83IOE5iBL

Sprites by **Iamtheguy** (discord tag)

# Changelog
:cl:
imageadd: unique non placeholder CO armor sprites
/:cl:

### CODE REVIEW

**Comment by zc-byte-boxer** [comment]
Looks really cool. Any thought about adding a camo-comforing version? @Blundir

**Comment by Blundir** [comment]
> Looks really cool. Any thought about adding a camo-comforing version? @Blundir

Not really, CO has none to begin with

**Comment by Drulikar** [comment]
stale exempt until sprite reviewed.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Review by harryob — APPROVED** [review]

**Pull request merged**
