### PR TITLE
Gravity removal ;) unused var that was 1 on ALL tiles

### PR DESCRIPTION
**Pull request by cuberound**
# About the pull request

newton created gravity and I removed it. (it is just dead apendige left from old ss13)

# Explain why it's good for the game

less mess in the code, removes (at least some of it still looking what all can be removed with it) gravity code

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl:
del: Removes gravity :)
/:cl:

### CODE REVIEW

**Comment by HaultyAnonie** [comment]
I am not sure if this was fixed but in certain rare cases of the crashing of the dropship into the Almayer, you actually expose the back port to space. And so when you go out there, you start floating. It's just niche, and I don't think you should fully remove the floating animations. But that's just my only conclusion until that gets fixed/is fixed.

**Comment by hislittlecuzingames** [comment]
I'd like gravity to remain should I ever finish "Space Hulk"

**Comment by cuberound** [comment]
for those who did not reed it SPACE has ALSO gravity 1 same as ALL the other tiles

**Review by harryob — APPROVED** [review]
downvotes and comments seem to be under the impression this removes floating when you hit a space tile, which it does not

**Pull request merged**
