### PR TITLE
Adds Pizza to Requisitions

### PR DESCRIPTION
**Pull request by HeresKozmos**
# About the pull request

Adds a box of pizza and a replica of PIZZA TIME to Requisitions.

# Explain why it's good for the game

I miss the days of Requisitions having pizza... I also miss PIZZA TIME...

# Testing Photographs and Procedure

image

# Changelog

:cl:
add: Added pizza and pizza cutter to Req
del: Deleted a random kepler crisps bag
/:cl:

### CODE REVIEW

**Review by Nanu308 — CHANGES_REQUESTED** [review]
So the Pizza cutter you see is actually quite strong, quite so, so if you're adding it to the Almayer make a subtype of it that's weaker or VV the Pizza cutter to be more akin to a knife.

Other than that, the mapping seems fine.

**Comment by HeresKozmos** [comment]
> So the Pizza cutter you see is actually quite strong, quite so, so if you're adding it to the Almayer make a subtype of it that's weaker or VV the Pizza cutter to be more akin to a knife.
> 
> Other than that, the mapping seems fine.

I'm going to attempt to make it have only 20 melee damage (I believe bayonets are 25) and I will name it "Replica PIZZA TIME" and change its description to reflect it.

**Comment by HeresKozmos** [comment]
Tested it, it deals 20 melee damage as intended. 

Hit the mob once.
image

**Review by Nanu308 — APPROVED** [review]
lgtm

**Pull request merged**
