### PR TITLE
Human bursting sounds + sprite, new hugging sounds

### PR DESCRIPTION
**Pull request by Blundir**
# About the pull request

Gives pre burst sound to humans and yautja, restores long broken overlay of larva bursting, gives yautja unique after burst gore marks, adds new hugging sounds.

https://github.com/user-attachments/assets/adf510b5-b9c8-40fb-9780-d76f1429a233

All the sounds are from here https://github.com/tgstation/TerraGov-Marine-Corps/pull/3046

# Explain why it's good for the game

More immersion = good.

# Testing Photographs and Procedure

<details>

https://github.com/user-attachments/assets/eb867ec5-14b8-4bab-a12e-8cf96af0348c

https://github.com/user-attachments/assets/84e31985-9411-406c-9516-40b4bef1f09b

https://github.com/user-attachments/assets/7be9accb-7fa8-4ed3-a231-803f029f7601

https://github.com/user-attachments/assets/df025acb-7755-4178-a7c1-4ed72b47af9b

https://github.com/user-attachments/assets/10943418-9f5b-49ab-8d0c-a730eb11e260

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl:
fix: fixed larva bursting on mob image not working
soundadd: new hugging sounds to humans
soundadd: bursting screams to humans and yautja
imageadd: added yautja bursting and afterburst gore icons
/:cl:

### CODE REVIEW

**Comment by RainbowStalin** [comment]
Thats haunting. 10/10

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by efzapa** [comment]
this needs to if possible not be a usable emote, hearing this shit spammed in briefing is just pain

**Comment by Blundir** [comment]
> this needs to if possible not be a usable emote, hearing this shit spammed in briefing is just pain

i already fixed it, nobody just retmed it

**Review by kiVts — APPROVED** [review]

**Comment by kiVts** [comment]
it was on tm for the past week or so

**Comment by Git-Nivrak** [comment]
Most sounds are barely audible compared to the current hugged sounds either due to being too short or too quiet

**Comment by Blundir** [comment]
> Most sounds are barely audible compared to the current hugged sounds either due to being too short or too quiet

Just compared volume in the game and in the sound editor, almost the same, and i've heard them normally in the game myself, as for the length, different in 0.1 and 0.2 from current one, which isn't a big deal really.

**Comment by Git-Nivrak** [comment]
image
male facehug1 (top) compared to male facehug2 - more than double the length

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Review by nauticall — APPROVED** [review]
pritess

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Review by harryob — APPROVED** [review]

**Pull request merged**
