### PR TITLE
ASO new icon

### PR DESCRIPTION
**Pull request by Kitsunemitsu**
# About the pull request
Replaces the small steel star with a brighter, larger star.

# Explain why it's good for the game
The old steel star was too hard to see on the black background.
This cleans it up to be brighter, and larger.
# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl:
imageadd: added new ASO icon sprite.
/:cl:

### CODE REVIEW

**Comment by c4xmaniac2** [comment]
Could you add a screenshot?

**Comment by Kitsunemitsu** [comment]
Of course! Let me nab one in game

**Comment by Kitsunemitsu** [comment]
okay, I cannot grab one in game, here's a screencap.
image

**Comment by Kitsunemitsu** [comment]
That is a great point, but I don't really think that the old one was good at all; and too hard to see. 
Would a blue border around the white admiral star be an acceptable change?

**Comment by c4xmaniac2** [comment]
super similar to the CO star

**Comment by Kitsunemitsu** [comment]
If you don't want change or are unconvinced.; Just tell me outright.
image

This is admiral vs CO star.

**Comment by Kitsunemitsu** [comment]
It absolutely is not.
Top to bottom, left to right.

image

New Proposed Admiral Star, 
Old Admiral Star
CO Star
New ASO Star
Old ASO Star

The main problem with the old ASO star is that it's really hard to see during gameplay and looks like a mass of pixels until you squint.

**Comment by nauticall** [comment]
I think having a different logo than the star altogether for the ASO would be good. Maybe a 🚫 symbol in gold similar to the FTL?

**Comment by Kitsunemitsu** [comment]
I don't really like the FTL logo that much, but I absolutely can give it a whole different logo.

**Pull request closed without merging**
