### PR TITLE
Adds icon for hive core and cluster to Xeno tacmap

### PR DESCRIPTION
**Pull request by Birdtalon**
There was supposed to be an icon for the hive core but it doesn't seem to exist.

I added one for hive core and cluster

dreammaker_2023-11-01_21-26-47

My sprites even at this level are awful. If someone who is actually artistic could make better ones I will use those. Likewise if you would like to make 2 states for the core, damaged and healthy I can restore the intended functionality of displaying a different icon for a damaged core.

<!-- Remove this text and explain what the purpose of your PR is.

# Explain why it's good for the game
# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl:
add: Xeno tacmap icons for hive core and clusters.
/:cl:

### CODE REVIEW

**Review by harryob — CHANGES_REQUESTED** [review]
you've resized every map blip, here, which isn't documented. if you wanna use a larger map blip for this one, just use map_blips_large.dmi for 10x10 or make a new one for 8x8

**Comment by Birdtalon** [comment]
> you've resized every map blip, here, which isn't documented. if you wanna use a larger map blip for this one, just use map_blips_large.dmi for 10x10 or make a new one for 8x8

😱 definitely not intended. All should be 8x8. Will fix.

**Comment by Birdtalon** [comment]
That is now fixed. Have just made the 7x7 as the other icons are. 🤦‍♂️

**Review by harryob — APPROVED** [review]
tacmap is codersprites anyway ...

**Pull request merged**
