### PR TITLE
Mapping swapping OT workshop and morgue

### PR DESCRIPTION
**Pull request by Huffie56**
# About the pull request
swapping OT workshop and morgue to bring research and OT closer and bring morgue close to medbay and DS's.

# Explain why it's good for the game
Bring OT closer to research to reinforce link between them.
bring morgue closer to medbay and DS's to make it easier to drag dead into morgue.

# Testing Photographs and Procedure
Morgue
Before
image
after
image
OT workshop
before
image
after
image

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: swapping OT workshop and morgue places.
/:cl:

### CODE REVIEW

**Comment by moltoretardo** [comment]
Maybe add a screenshot of both 'after' location as to make sure everything looks okay

**Comment by Huffie56** [comment]
> Maybe add a screenshot of both 'after' location as to make sure everything looks okay

on it

**Comment by Huffie56** [comment]
> Maybe add a screenshot of both 'after' location as to make sure everything looks okay

i just complete it one for each location before and after....

**Comment by Huffie56** [comment]
Last change added an extra machine and semiotics.
image
image

**Comment by Diegoflores31** [comment]
Where is the morgue APC at ? i cannot see it 

also the OT with white walls + tiles looks a little out of place specially the storage part

**Comment by Huffie56** [comment]
> Where is the morgue APC at ? i cannot see it
> 
> also the OT with white walls + tiles looks a little out of place specially the storage part

i probably forgot the apc... thanks for catching it.
the problem with the walls is that they touch some of the research room east and i want to have an unify color.
make me think i probably forgot those window and door in the middle....

**Comment by ItsVyzo** [comment]
image
These walls should be changed to normal walls instead of medical

**Comment by Huffie56** [comment]
> image These walls should be changed to normal walls instead of medical

good point but i don't know if i should put all the walls in white or grey waiting on maintainer to review it and give is opinion

**Pull request closed without merging**
