### PR TITLE
Gardener and Healer sprites. Actually not broken this time.

### PR DESCRIPTION
**Pull request by Ultimate-Fluff**
image
Drone strains! Finally! These strains are based on the xenonid strains I created [here](https://gitlab.com/cmdevs/colonial-warfare/-/merge_requests/2406). Expect Carrier next!

Healers are so passionate about healing their sisters, they traded their building resin for recovery node resin and lather it on their hands and tails, ready to apply it to any bubbling and sizzling wounds their sisters obtain in battle. Affectionately called 'Goopers' by me.

Gardeners have grown a rusty throat sac from which they draw their vital liquids (xeno blood) and regurgitate them into their hands to make resin fruits. Their hands are stained with the dried and darkened liquids. 

## Why It's Good For The Game
As a healer, I am sick of people demanding me to build in the front lines while I'm sitting down and recovering my health from 10% after saving a cocky Rav nearly blown to bits. With these sprites, people will know exactly what kind of drone you are so they will not demand any tasks you are incapable of performing.

## Changelog
:cl: Puckaboo2
imageadd: Added Healer and Gardener sprites for Drone. Healer is distinguishable by purple resin all over her body and Gardener has a throat sac and vital fluids on her hands.
/:cl:

### CODE REVIEW

**Comment by harryob** [comment]
fyi, bolding your name in the changelog will hust make your author name show up with \*\* around it

**Comment by Ultimate-Fluff** [comment]
> Although walking/running isn't currently toggleable, you may as well copy the sprite state in. Also, it looks like you renamed one of the sprite states for knocked down: image Oh you also deleted normal drone walking too that I didn't notice but is also pictured above. The status column for what you're doing should only ever say Modified (not created or deleted). You can find the icon diff below in the checks section by clicking Details to the right of Icon Diffs.

I appreciate you discovering my oversights. They have been reviewed and appropriately fixed. 

image

**Review by Agameofscones — CHANGES_REQUESTED** [review]
While the edits here are fine in terms of quality, their actual communicative ability in the gamespace is limited down to distinct splotches of colors that can easily get lost in the chaos of your average firefight. While a good step in the right direction, I encourage you to experiment more with the designs here and focus a single unified language across each xeno design.

My main complaints are with the gardner, which just has the fruit colors slapped haphazardly onto the xeno. You may want to consider instead adding fruits growing on the back in place of spines, modify the crest shape slightly, and change the position of the hands (maybe having them closer to the ground like a knuckle dragger?)

The healer is actually pretty OK looking, the only change I would make would be to modify the head crest or change the position of the arms for further visual identification aid. The excess of color actually works in your favor and clearly reads as "purple drone", which can translate quickly to "oh it's a healer" at any angle save for the back, which needs just a bit more work to be easily identifiable (you only have the purple on the back of the head, throw some on the back and you're good to go)

**Comment by Ultimate-Fluff** [comment]
I will see what I can do! I will start working on the new designs now and post them by the end of the night.

**Review by Ultimate-Fluff — COMMENTED** [review]
Gardener has been completely overhauled from having spores on her back to having a sac from which she draws her vital juices and shapes them into resin fruit.

image

**Review by Agameofscones — DISMISSED** [review]

**Review by kugamo — CHANGES_REQUESTED** [review]
Not a fan of the drips on the sprite. Xenos arent slugs. Just having changed colors dripping off them is a lazy design. I'd really like to see designs that affect the whole carapace, in a subtle but visually distinct way.

Imagine how the strains' unique mechanics would work, and how that'd change the base sprite's looks. Muddy green hands, and drippy purple body splotches dont communicate them well imo.

At the very least the sprites ought to be made less oozy and more chitin-like.

**Comment by harryob** [comment]
superseded by #1933

**Pull request closed without merging**
