### PR TITLE
Pilot Bunks to Hangar

### PR DESCRIPTION
**Pull request by ItsVyzo**
# About the pull request

Moves Pilot Bunks from CIC to Hangar, allowing for faster prep for dropships instead of late-join POs/DCCs running all the way to CIC then hangar.

# Explain why it's good for the game

Less walk time from Cryo to Bunks then Hangar. Allows Flight Crew to head to Bunks for Food and Quick Gear up before heading back to Dropship to resume their duties.

Conflicts: #1918 #1832 

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

image

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
maptweak: Moves Pilot Quarters from CIC to Hangar
qol: Improves Flight Crew lives, focusing more on gameplay and less walking for late-join
/:cl:

### CODE REVIEW

**Comment by MusselMain** [comment]
maybe add a bathroom too? the old pilot bunks had one.

**Comment by Huffie56** [comment]
in conflict with mine https://github.com/cmss13-devs/cmss13/pull/1918
also we don't see what you did with the old PO quarter...

**Comment by ItsVyzo** [comment]
> maybe add a bathroom too? the old pilot bunks had one.

I considered that, but it was not feasible without making the bunks too crowded



> in conflict with mine #1918 also we don't see what you did with the old PO quarter...

It was turned into old foam, also it unfortunately conflicts w/ #1832 too

**Comment by Nanu308** [comment]
See linked PR above.

**Pull request closed without merging**
