### PR TITLE
M5 Camera Gear

### PR DESCRIPTION
**Pull request by realforest2001**
# About the pull request
Adds the M5 Camera Gear, an ear mounted camera designed to allow personnel without use of a standard issue helmet to be visible on overwatch consoles.
These are intended to be extremely rare, and not accessible to more than a few people at a time.

# Explain why it's good for the game
# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

image
image
image
image

</details>

# Changelog
:cl:
add: Added the M5 Camera Gear, an ear-mounted camera that works with Overwatch consoles. Small numbers can be found in surplus uniform vendors.
/:cl:

### CODE REVIEW

**Comment by Diegoflores31** [comment]
I see this new item has no interaction with Huggers . is the camera intended to keep working after being Hugged/capped?

**Review by nauticall — CHANGES_REQUESTED** [review]
Doesn't really look like a camera from the front but for some reason looks like a camera to the side? Can you show what it looks like on a marine?

**Comment by realforest2001** [comment]
> Doesn't really look like a camera from the front but for some reason looks like a camera to the side? Can you show what it looks like on a marine?

Popped in the dropdown. Not sure how best to make it look correct

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Review by harryob — CHANGES_REQUESTED** [review]
where's your where it's good for the game section... and for that matter, why is it good for the game? it's an intentional tradeoff that going drip means you lose overwatch

**Pull request closed without merging**
