### PR TITLE
Operation Name Tidying

### PR DESCRIPTION
**Pull request by Misttyy**
## About The Pull Request
Fixes some LRP operation names.

I wanted to work on something simple for my first PR to learn how to use GitKraken, Visual Studio Code and how to create a PR. I've removed a number of LRP operation names like unga-bald-69-420, and generally tried to make them more serious.

I've gone with the general rule, if I wouldn't want to tell someone that their son died in this operation name then it's not going in. 

References for names have been taken from the Vietnam war to fit Aliens Vietnam war based inspiration.

## Why It's Good For The Game

More soul. Less LRP-minge names for everyone to have to see.

## Changelog

:cl: Mistfrag
add: Added new operation-prefix, postfixes and two new titles in order to add some more variety.
del: Deleted campaign operation title since that's outside our usual round's scope, deleted some LRP prefixes like 69-420, and some lrp postfixes like unga-bald.
/:cl:

### CODE REVIEW

**Comment by Misttyy** [comment]
Massive thanks to Geeves for helping me figure out all this stuff.

**Comment by Misttyy** [comment]
Did a bit of further altering.

**Review by stanalbatross — APPROVED** [review]
config stuff so will need to be updated on server

**Comment by Misttyy** [comment]
> config stuff so will need to be updated on server

Not entirely sure what's meant by that. Don't think it's updated properly or I've made an error somewhere considering I've still seen names taken out of rotation crop up.

**Comment by pedr69** [comment]
>tidying

more like removing soul

**Pull request merged**
