### PR TITLE
Renamed Warden's 'Protect' Ability and created a new icon for it

### PR DESCRIPTION
**Pull request by Ultimate-Fluff**
# About the pull request
closes https://github.com/cmss13-devs/cmss13/issues/1992
Wardens can no longer 'protect' xenomorphs by providing a shield, so so I renamed the ability to 'Aid', changed the flavor text, and I also created a new icon state for it, which I will commit when my other PR merges.
image

# Changelog

:cl: Puckaboo2
code: Renamed Warden's 'Protect' ability to 'Aid' and fixed its flavor text to better represent its function.
imageadd: Added a new ability icon for Warden's aforementioned 'Aid' ability.
/:cl:

### CODE REVIEW

**Comment by NewyearnewmeUwu** [comment]
How about just 'Aide'?

**Comment by Ultimate-Fluff** [comment]
> How about just 'Aide'?

Uhhh.... Yeah, I'll do that. But an 'aide' is an assistant. To 'aid' is to help somebody in need.

**Review by Agameofscones — CHANGES_REQUESTED** [review]
Design is a bad read, weird chunky bit on the arm as well.

Not at acceptable standard. Suggest you take inspiration from the prae cleave ability with its split design and adopt the upper portion of your design as the entire thing and ignore the arm entirely.

alternatively have the hand reaching out and dispensing the 'buff' icons (see attached images for quick and dirty mockups)

Also the arm could use better outline shading.
dreammaker_klY0qSTdNO
8-dc7b8534-1fbe-4c1b-b121-6c3f460f7f98.png)

**Comment by Ultimate-Fluff** [comment]
> Design is a bad read, weird chunky bit on the arm as well.
> 
> Not at acceptable standard. Suggest you take inspiration from the prae cleave ability with its split design and adopt the upper portion of your design as the entire thing and ignore the arm entirely.
> 
> alternatively have the hand reaching out and dispensing the 'buff' icons (see attached images for quick and dirty mockups)
> 
> Also the arm could use better outline shading.
> 
> dreammaker_klY0qSTdNO dreammaker_9FJBWzFUju

Ayo, I do enjoy the cleave much better. Would you mind if I used that with some slight modifications?

**Comment by Agameofscones** [comment]
approved, waiting on PR stack to clear

**Review by harryob — APPROVED** [review]

**Pull request merged**
