### PR TITLE
New Charger Strain sprite

### PR DESCRIPTION
**Pull request by TheManWithNoHands**
# About the pull request

* Adds a new sprite for the Charger strain, making it visually distinct from base Crusher.

# Explain why it's good for the game

A lot of Strains already have uniqe sprites, and for a good reason. visual clearity is important. And being able to see immediatly what strain the cast is, is important information. Crusher didnt have a sprite for Charger, so now it got one.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

https://imgur.com/a/NUpH6fT

</details>

# Changelog
:cl:TheManWithNoHands
code: changes Charger strain use a uniqe sprite
imageadd: addes uniqe sprites for Charger strain
/:cl:

### CODE REVIEW

**Comment by ihatethisengine** [comment]
Honestly I don't think the red parts are necessary.

**Comment by TheManWithNoHands** [comment]
> Honestly I don't think the red parts are necessary. 

I went through multiple options and colors. And the red got the best response from people.

The spriter channel on discord has a ton of the different versions i made and some other tryd too.
Take a look there.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by Blundir** [comment]
let me know when you want to return to it

**Pull request closed without merging**
