### PR TITLE
Strain icon format change

### PR DESCRIPTION
**Pull request by aceroyuno**
## About The Pull Request
Adds var/mutation_icon_state to the xenomorph base type. All sprite logic is handled by this var as opposed to the mutation_type var. Strains will no longer need an updated sprite sheet and can now use the base sprite with the original .dmi file.

Had to make a new one since the last one went stale.

## Why It's Good For The Game
Allows for creation of strains gameplay wise not to be affected by the strains icon logic. And it makes it simpler for checking code for spriters. If it has no sprite for it's strain, it defaults to using the normal icon state.

## Changelog

:cl: aceroy
refactor: Changed xenomorph icon logic to use new var mutation_icon_state and not mutation_type
/:cl:

### CODE REVIEW

**Comment by fira** [comment]
Think we should first roll sprites merge update then run it together... Lots of changes being made to xeno sprites currently

**Comment by aceroyuno** [comment]
Alright, I'll mark this as draft. Think you can send me a link to the current stuff so I can take a gander.

**Comment by aceroyuno** [comment]
Don't mind me. Just using github on the phone. Close and comment should not be right next to eachother

**Comment by fira** [comment]
Basically waiting on #1373 - TestMerging it next round. 
This is gonna simplify xeno icon handling a lot, it shouldn't actually conflict i think but...

**Pull request merged**
