### PR TITLE
Makes Liaison spawn in the correct place

### PR DESCRIPTION
**Pull request by BeagleGaming1**
## About The Pull Request

Removed the “nightmare” section of the liaison's job.
It also removes its attached liaison nightmare equipment preset as it is unused without this.

hope I didn’t break something
This should fix: https://github.com/cmss13-devs/cmss13/issues/1352
## Changelog
:cl:
fix: Fixed CL incorrectly spawning at late join cryo room at round start
/:cl:

### CODE REVIEW

**Comment by fira** [comment]
I'm a bit confused, it's been like this for years, why does this cause this?

**Comment by fira** [comment]
Looks like one of the job system "it accidentally worked" cases

Need to also remove the gear preset

**Review by fira — APPROVED** [review]

**Comment by ThePiachu** [comment]
From what I could gather looking into this, it's due to one of those global variable maps mapping all the job / gear datums to some key that the /nightmare preset didn't rename. Not sure which though.

**Comment by fira** [comment]
Yeah the job system can't make that distinction at all. It just sort of falls right for some reason using dark magic. There used to be the same kind of issues with Whiskey Outpost roles before we refactored it.

**Review by stanalbatross — APPROVED** [review]

**Pull request merged**
