### PR TITLE
Fixes Kutjevo Shutters

### PR DESCRIPTION
**Pull request by c4xmaniac**
## About The Pull Request

Kutjevo shutters have been renamed, fixing the shutters just named "s" and adding a proper name to most of the shutters detailing the location they belong.

## Why It's Good For The Game

Bug fix and more accurate info good.

## Changelog

:cl:
fix: Fixed kutjevo shutters.
/:cl:

### CODE REVIEW

**Review by morrowwolf — CHANGES_REQUESTED** [review]
Doubled shutters top middle of image: https://cdn.discordapp.com/attachments/985905303247798304/1021620435936366592/unknown.png

**Comment by c4xmaniac** [comment]
> Doubled shutters top middle of image: https://cdn.discordapp.com/attachments/985905303247798304/1021620435936366592/unknown.png

fixed

**Review by Agameofscones — CHANGES_REQUESTED** [review]
image
StrongDMM_PAuMfaMCD6

**Comment by c4xmaniac** [comment]
> image StrongDMM_PAuMfaMCD6

changed and made sure all the shutters had a similar naming scheme

**Review by Agameofscones — APPROVED** [review]
Looks good to me

**Pull request merged**
