### PR TITLE
Creating a small portion of the Royce from wish W-Y PMC can be deploy for ERT or else....

### PR DESCRIPTION
**Pull request by Huffie56**
# About the pull request
Remove PMC ERT shuttle from standard station and move it in the newly created small portion of the Royce from wish W-Y PMC can be deploy for ERT or else....

image

# Explain why it's good for the game
Will  allow PMC to better RP since they won't have an UPP shuttle in their hangar....

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
mapadd: added a section of the Royce from where the W-Y PMC can deploy.
maptweak: move the PMC ERT shuttle and hangar to the new section of the Royce.
/:cl:

### CODE REVIEW

**Comment by harryob** [comment]
fyi: you can't add areas by editing them in strongdmm. you *have* to edit them, look in code/areas for examples

**Comment by Huffie56** [comment]
> fyi: you can't add areas by editing them in strongdmm. you _have_ to edit them, look in code/areas for examples

ok i will try to look into it.....

**Comment by Huffie56** [comment]
image

**Comment by Huffie56** [comment]
> how about a phone and fax like the regular ERT station?

i added a fax but the phone is not lore friendly royce isn't in the system

**Pull request closed without merging**
