### PR TITLE
Dropship 3 'Saipan'

### PR DESCRIPTION
**Pull request by realforest2001**
# About the pull request
Adds a template for a dropship 3.
This uses the existing DS3 sprites, with some revisions to bring them up to date.
The sprites are NOT perfect, there are some colour patches that don't match up. I am not graphically inclined, so if someone wants to touch up the bits I've missed you are more than welcome to.

# Explain why it's good for the game
Short term I expect this to have event function more than anything else.
Long term who knows.

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl:
add: Added Dropship 3 Saipan template.
/:cl:

### CODE REVIEW

**Comment by Steelpoint** [comment]
I believe this should prove very useful for OpFor events. With a minor amount of access tweaking. I may investigate adding a alt version for non-USCM factions.

**Review by Blundir — APPROVED** [review]

**Comment by ihatethisengine** [comment]
Would be cool to use this to paradrop ERTs

**Comment by Rem1-code** [comment]
should it not be named after a battle like the other 2?

**Review by harryob — APPROVED** [review]
i was just about to ask you to change the name, perfect

**Pull request merged**
