### PR TITLE
The weeds are hungry: Bodies for the weeds

### PR DESCRIPTION
**Pull request by Drulikar**
# About the pull request

This PR adds Kugamo's sprites where bodies can be integrated into the weeds. The bodies lose their interactivity, examinability, and HUDs when merged with the weeds, and are anchored. Destroying the weeds though will restore the body to normal. Currently requires the body to not be grabbable by a xeno (as in not impregnated or bursted) as well as unrevivable.

Once they are permadead it currently waits 5 minutes to start merging, then 1 minute on each sprite state (there are 5).

Support is basically already in place for non-humans to also use this system (just uncomment two blocks of commented out code), but I am unsure what sprites or method to hide their corpses would be used instead. I also see no issues (visual or code) with this merging nested hosts, but it will not currently merge bursts until they are no longer considered grabbable.

# Explain why it's good for the game

Less clutter, and it just looks neat.

image

After fixing the flipped lighting:
image

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

As an animation when it was fast:
weeds

Earlier testing:
image
image

Tested with zombies (they don't have undefib set when they die so won't be consumed before revival, and revival removes the component off of them until they die again - if they decap they will get a undefib signal to cause them to be consumed), smols (look at that cute little tail), rollers, coffins (now they don't suck up anchored mobs), beds, chairs, and fulton:
image

</details>

# Changelog
:cl: Drathek Kugamo
add: Added the ability for weeds to merge with unrevivable corpses
imageadd: Added human shaped weeds by Kugamo
code: Added a signal for weeds sent to the turf to indicate it is now weeded, and added a signal for afterbuckle.
fix: Closets (including coffins) can no longer move anchored mobs.
/:cl:

### CODE REVIEW

**Comment by kooarbiter** [comment]
this looks really cool, but maybe leave a tiny portion of the body sticking out so people are less likely to miss it?

**Comment by Diegoflores31** [comment]
Ando chance the body absorption happens on slow steps ? Example 1 stage each 20 seconds requiring the body ti be there for at least a minute for the full absorption to happen .
Why? It would looks very cool like some kind of slow decay

**Comment by Drulikar** [comment]
Yeah when its more finalized I will make each animation step take a minute as well as the initial time probably a few minutes.

**Comment by Venuska1117** [comment]
aww... no more hidding in bodies as hugger to got marines :(

**Comment by Venuska1117** [comment]
can queen gib body if its under weeds? just asking.

**Comment by Drulikar** [comment]
> can queen gib body if its under weeds? just asking.

No because when weeded they are untargetable, and it would be a waste because only permadead can be weeded.

**Comment by Diegoflores31** [comment]
Just before you merge this any change NON perma humans get the first weed sprite ? It would look VERY epic . Like weed is starting to grow over them but it doesnt cover them

**Comment by Drulikar** [comment]
> Just before you merge this any chance NON perma humans get the first weed sprite ? It would look VERY epic . Like weed is starting to crawl over them but it doesnt cover them

I'm not sure about before they're perma'd but I could when the first delay begins when they perma if I add another static sprite icon_state and have that be the appearance when in the "started" phase.

With how its designed, it just has 3 states: dormant when attached (waiting for conditions to be ready via signals), started (timer started), and merging (its anchored, untouchable, unexamineable, no-huds, and the sprite animation has started). It exits these states either by that one timer (for started -> merging), or by qdel signals from the weeds they are on. I tried to design it to be as performant as possible; so really the most that I could tweak without changing that current logic is to make the first sprite state considerably longer than the other states in the sprite animation delays.

**Comment by Diegoflores31** [comment]
Oh . Nevermind then because it could affect balance . Ty for gygafast response lol

**Comment by Drulikar** [comment]
Headless zombies are no exception: 
image

**Comment by ihatethisengine** [comment]
A bit confusing, especially as xeno, since the bodies that being devoured by weeds don't show skull icon. So you can think they are alive.

**Comment by Drulikar** [comment]
> A bit confusing, especially as xeno, since the bodies that being devoured by weeds don't show skull icon. So you can think they are alive.

See testing images (the red weeds) if HUDs aren't removed. They can't target them in any of the merged states, so they'll figure it out.

**Comment by ihatethisengine** [comment]
Maybe remove HUD icon when body is fully consumed (or at least when weeds are obvious)? Because again, on the first stage(s) you may assume that it's just someone in crit and spend time trying to interact with them. Or even worse, you can assume that someone is dead and being devoured by weeds, when they are not.

**Comment by ihatethisengine** [comment]
Example. One may think marine on the left is still alive. It's not a big deal, of course, and this feature worth it, but ideally there should be a way to distinguish.

**Comment by Diegoflores31** [comment]
Plan B would be to make their alpha 0 so they are invisible while on the last stage but i personally like the invisibility one bcs it sounds easier

**Comment by Drulikar** [comment]
Changing invisibility is what I was referring to either making it so xenos can't see them at all; or an expensive system that is checking line of sight to change the xeno's invisibility sight (basically its a range of 100 values and when your invisibility sight is past the value of the invisible thing, you can't see it anymore. It doesn't help with the aspect of whether they are in light of sight or not, just whether they are visible at all.

**Comment by Diegoflores31** [comment]
Fr thermals need a rework.

**Comment by kugamo** [comment]
There should be two versions of the sprites for when they are laying e/w, your screenshots show only the sprites for when their heads are facing east. Shading looks bad when theyre facing west due to the incorrect sprites being used in this case. Also i saw nested people getting covered? I dont know how much anyone would care but please only apply these sprites to unbuckled corpses.. Itd really help clarify the state of the body visually, them working simultaneously confuses things.

**Comment by ihatethisengine** [comment]
Nested corpses look fine while weeded and you still can unnest them without an issue.

**Comment by Drulikar** [comment]
> There should be two versions of the sprites for when they are laying e/w, your screenshots show only the sprites for when their heads are facing east. Shading looks bad when theyre facing west due to the incorrect sprites being used in this case. Also i saw nested people getting covered? I dont know how much anyone would care but please only apply these sprites to unbuckled corpses.. Itd really help clarify the state of the body visually, them working simultaneously confuses things.

I wasn't sure how the flipped sprites mattered, but I see now its just to accommodate the lighting. I'll fix that in a moment. Thanks for taking a look!

And yes the sprites working on nested seemed to work fine; and I prefer the effect of it especially once bursted are no longer grabbable. It might make it hard to tell where something already is nested, but the xeno should already have a prompt in this situation that something is already there. It will make it so bodies aren't just standing upright in the hive when viewed through walls, and will instead then have the weeds covering them. I'd prefer them not to be visible through walls, but see previous messages.

**Comment by Drulikar** [comment]
image
image

**Comment by Drulikar** [comment]
As far as nested: 
image

**Review by sleepynecrons — APPROVED** [review]
sprites look great i think the upright sprite looks fine. approved

**Review by BeagleGaming1 — APPROVED** [review]
Code seems good

**Pull request merged**
