### PR TITLE
mk1 nerf

### PR DESCRIPTION
**Pull request by stanalbatross**
## About The Pull Request

nerfs the mk1 by changing its standard ammo to normal ammo

ap is rarer 

also nerfs availability by removing from sls

## Why It's Good For The Game

the mk1 is undeniably a very strong "wholesome burst track chunger" rifle and needs a nerf, it should function more as a side grade to the mk2 rather than a straight upgrade (let's be honest, because of the masterkey it is a straight upgrade most of the time, the less attachments thing barely comes into play). As such this PR will nerf it a bit by reducing how much you see its most powerful component - the 95 round AP mags.

The mk1 loading mk2 mags also makes no sense (they use totally different sizes, feeding mechanisms) and it just adds to the ability of the mk1 to be a straight upgrade and keep spamming out ap etc. so that's being removed too

## Changelog

:cl: Stan_Albatross, Nanu308
balance: added MK1 AP mags, the normal MK1 mags no longer have AP rounds in them. 
balance: removed the ability of the MK1 to load MK2 mags
add: gave the CIC armoury MK1 AP mags
add: added MK1 AP mags to the CO vendor, and some to req
balance: tweaked some ammo prices in the CO vendor
del: removed the mk1 kit from SLs
/:cl:

### CODE REVIEW

**Comment by Sargeantmuffinman** [comment]
Could you also remove the backwards compatibility with MK2 magazines?
Or would that be too much?

**Comment by VagabondZero79** [comment]
This kinda feels like a random nerf outta left field.

**Review by Geevies — APPROVED** [review]

**Comment by ObsidianCrow23** [comment]
i think this is a good change. maybe im turning cringe xeno main now but it feels like im always being barraged by endless AP ammo as a t3 even like an hour into the round.

**Comment by DesertFox2** [comment]
> i think this is a good change. maybe im turning cringe xeno main now but it feels like im always being barraged by endless AP ammo as a t3 even like an hour into the round.

This is just because req gets funds every 30 mins, and generally they'll save the money and buy ammo boxes / AP boxes.


So instead of making AP ammo harder to get, or more costly to acquire, they straight out nerf it instead

**Comment by Wintermote** [comment]
The MK1 has lower damage and lower RoF than the MK2 even when firing normal rounds, and it doesn't get IFF grenades like the MK2 does either. It's just the AP that sets it apart in any way.

At the moment the MK1 is basically a specialized MK2 for countering T3's - in fact it's one of the very few weapons marines have that can do appreciable damage to T3's. You say it should "work as a sidegrade" and frankly it already DOES. You sacrifice strength against T1's and T2's to kill T3's better.

I don't think this nerf is warranted. There's no pressing balance issue here, marines need to have options for countering T3's, the MK1 is largely restricted enough already that most people can't run around using it anyway, and the proposed change will just make it completely useless in comparison to the MK2 without RoF/damage buffs to make it equivalent.

**Comment by stanalbatross** [comment]
> _The MK1 has lower damage and lower RoF than the MK2_

mk1 : 
`	fire_delay = FIRE_DELAY_TIER_9
	
damage_mult = BASE_BULLET_DAMAGE_MULT + BULLET_DAMAGE_MULT_TIER_2`
mk2 : 
`	fire_delay = FIRE_DELAY_TIER_9
	
damage_mult = BASE_BULLET_DAMAGE_MULT + BULLET_DAMAGE_MULT_TIER_2`

Please stop lying. You may disagree with the nerf but lying to push your point is extremely poor form.

> This stinks of "I was killed by this, now I will get rid of it"

🙄

**Comment by Wintermote** [comment]
Just misremembering the RoF differences then. These things get changed around too often.

**Comment by Lafrien** [comment]
It is a big nerf for a weapon that is: 

- Restricted in obtaining; 
- As easily meltable on the battlefield if person overextend (which you do with this weapon as a frontliner, since it has no IFF);
- Has less accessories than MK2;
- Has great cost of points and money (compared to free MK2);
- Has unique magazines.

> As such this PR will nerf it a bit by reducing how much you see its most powerful component - the 95 round AP mags.

By this the MK1 will turn into big mag MK2 with **MUCH** more restrictions, removing it's 1 out of 2 upsides it has. And it does not feels like "*a bit*" part.

The cost of it will surely not meet the product quality expectations after this nerf. But it will nerf *mostly* the accessibility for marines lower than SL.

I do not like it.

**Comment by stanalbatross** [comment]
> * Restricted in obtaining;

You can get it from main req it's barely as restricted as a mou

> * As easily meltable on the battlefield if person overextend (which you do with this weapon as a frontliner, since it has no IFF);

This is the case with every gun in the game I don't get your point here. Also take a magharn

> * Has less accessories than MK2;

Irrelevant it can still attach the very strong ugl and masterkey

> * Has great cost of points and money (compared to free MK2);

Irrelevant since you get it from req

> * Has unique magazines.

Irrelevant it can load mk2 mags

**Comment by sose96** [comment]
On like 140 high pop you get 5 in req, and they are expensive as fuck to buy more of so nobody does.

**Comment by BKryth** [comment]
the funny part about the comments are this isnt even a nerf LMAO

this is a huge buff for mk1, only knowers will realize

**Comment by ElFuente** [comment]
Good nerf, The mk1 has too much ammo capacity with ap, so this pr will reduce ap ammo at round start / early just like the pr from geeves that i dont recall the name.

For the people that are crying 'waaah BOOOHOO, i do not like this' 96 ammo capacity with 5 ap is able to hit the same to xenomorph's with 20 armor ((warrior, hivelord , spitter, lurker, carrier, drone, runner, boiler)) if you see an xeno with more than 25 armor just simply switch your mag to mk2 ap, get good, nothing else to say.

**Comment by PhantomEpicness** [comment]
bit racist toward req rushers but ok

**Comment by c4xmaniac** [comment]
Adding them to req was a mistake to begin with tbh, good change tho the knowers are correct

**Comment by IngloriouslyBad** [comment]
I was killed by a Mk1, therefore the nerf had to happen 
-xeno dev probably

**Comment by FoxyStalin** [comment]
Is it really that much of an issue that something available in such incredibly limited quantities is a strait upgrade? 
Req gets like,a grand total of five on highpop.  
Honestly If this is the idea I'd just say remove the free ones from the roundstart req vendor entierly and make them purchase only.

**Comment by Diegoflores31** [comment]
Mmm and literally no AP for ordering on req?
Massive marine nerf . Command used to have it too nd req should be able to order extra

**Comment by RadiationFan** [comment]
This change is not really warranted. Currently, minimal MK1 usage is seen, as a BC MK2 does far more damage, and more valuable burst damage. If anything, reducing the amount of points REQ receives would do more for game balance than this, as AP will still end up flooding the battlefield, AP can still be bought from vendors by everyone and shoved in to a MK2, this just takes an objectively sidegraded gun, and weakens it. A better change would be to not let it have a UGL, as having 5 grenades to juggle a t2 with is far stronger than the AP it packs, in general.

**Comment by joookschad** [comment]
I really dont want this in for one reason: All the people who are coping in this thread will start playing SL not to lead, but to use the mk1.

**Comment by stanalbatross** [comment]
> I really dont want this in for one reason: All the people who are coping in this thread will start playing SL not to lead, but to use the mk1 with free AP.

A fair and understandable concern, any ideas

**Comment by FoxyStalin** [comment]
Correct me if I'm wrong, but wasn't the statement made that 
'If you really want AP on your MK1,  snag some MK2 mags from the vendor'? 
Well, RIP to that I suppose.

If the goal of this nerf is to discourage the neo-chung it's going to fail, as standard ammo is honestly more effective on the shit that you're going to buck into burst.  
Instead of putting a bandaid on it and nerfing the MK1 unecessarily remove it's masterkey capability or remove the buck stun from masterkey.

**Comment by stanalbatross** [comment]
> Correct me if I'm wrong, but wasn't the statement made that 'If you really want AP on your MK1, snag some MK2 mags from the vendor'? Well, RIP to that I suppose.
> 
> If the goal of this nerf is to discourage the neo-chung it's going to fail, as standard ammo is honestly more effective on the shit that you're going to buck into burst. Instead of putting a bandaid on it and nerfing the MK1 unecessarily remove it's masterkey capability or remove the buck stun from masterkey.

nah there are ap mk1 mags in the req vendor too

**Review by Nanu308 — CHANGES_REQUESTED** [review]
See Discord comment i made

**Comment by FoxyStalin** [comment]
Are SLs getting anything to compensate for this or is this just a strait up marine nerf now?
SL kits are so tightly packed that the extended mags on the MK1 meant you could actually lead for a reasonable amount of time without running out of ammo, and the backwards compatibility meant that you didn't need to go all the way back to FOB for your snowflake ammo.
I didn't see the need for the initial nerf, but now it just seems like you're trying to make this a CIC exclusive in the same vein as the auto shotguns, and if that's the case, just say it outright.

**Comment by stanalbatross** [comment]
> Are SLs getting anything to compensate for this or is this just a strait up marine nerf now? SL kits are so tightly packed that the extended mags on the MK1 meant you could actually lead for a reasonable amount of time without running out of ammo, and the backwards compatibility meant that you didn't need to go all the way back to FOB for your snowflake ammo. I didn't see the need for the initial nerf, but now it just seems like you're trying to make this a CIC exclusive in the same vein as the auto shotguns, and if that's the case, just say it outright.

the main concern here was that people would go sl to use the funny mk1 with ap rather than actually lead (which they have been doing for a while)

further down the line sl could look at getting another kit option, but it would be a sidegrade/situational weapon like the flamer. not an mk1

**Comment by Diegoflores31** [comment]
> change

Isnt it unfair to weaken a relatively dead role ? SL is almost allways Open unless it's highpop hours and stripping their snowflake and making them just a pfc with OOC responsabilities is not good

**Comment by hotimep** [comment]
awesome can't wait to use the flamer for sl now

**Comment by Diegoflores31** [comment]
Also having gaming gear as an incentive guarantees player flow of SLs and some of them may actually like the role and main it.
If you want to take it away take it from PFCs and Req not from SL

**Comment by stanalbatross** [comment]
> Also having gaming gear as an incentive guarantees player flow of SLs and some of them may actually like the role and main it. If you want to take it away take it from PFCs and Req not from SL

there's good gear and shit in the sl vendor already, also the excuse of "people may go SL to PFC++ and may end up actually SLing" is a weak one

without the mk1 they are in no way " just a pfc with OOC responsabilities ". They have better med and engi skills, jtac gear by default, and mds etc in their vendor as well PLUS the communication advantage and natural position of leadership. They are so much more than a simple PFC and if you think taking away some of their fragging power will make them the same as a pfc you don't understand the role

**Comment by PhantomEpicness** [comment]
why is this thread still going + racist change

**Review by Shad0vvs — APPROVED** [review]

**Comment by Diegoflores31** [comment]
> > Also having gaming gear as an incentive guarantees player flow of SLs and some of them may actually like the role and main it. If you want to take it away take it from PFCs and Req not from SL
> 
> there's good gear and shit in the sl vendor already, also the excuse of "people may go SL to PFC++ and may end up actually SLing" is a weak one
> 
> without the mk1 they are in no way " just a pfc with OOC responsabilities ". They have better med and engi skills, jtac gear by default, and mds etc in their vendor as well PLUS the communication advantage and natural position of leadership. They are so much more than a simple PFC and if you think taking away some of their fragging power will make them the same as a pfc you don't understand the role

If thats true then remove CO special weapons and synth extra gear because arent they there to "lead / support "

**Comment by JediKing112** [comment]
> i dont know if you intended for this to be a nerf for the MK1 exclusively but you've also massively nerfed SL and removed any incentive to play the role, why can't we command AND have an actual gun that we don't have to go to req for? The MK1 is the gift you get for taking the responsibility and being bothered TO command, and without that you're essentially just an SO that deploys.

**Comment by ElFuente** [comment]
> > i dont know if you intended for this to be a nerf for the MK1 exclusively but you've also massively nerfed SL and removed any incentive to play the role, why can't we command AND have an actual gun that we don't have to go to req for? The MK1 is the gift you get for taking the responsibility and being bothered TO command, and without that you're essentially just an SO that deploys.

You are the reason why is getting removed from sl, you dont play a command / leading role only for the gun, because they are so many people that plays solely for the gun and everytime they talk is something stupid, they dont give orders.

**Comment by ValoTheValo** [comment]
remove SL kekw

**Pull request merged**
