### PR TITLE
Research Trait fixes

### PR DESCRIPTION
**Pull request by Diegoflores31**
# About the pull request

ALL traits will now use Potency instead of level to calculate their effects . I have noticed there was some traits that were not using this and as a result they were not working at all when used with modifiers like Boosting. This PR corrects that behaviour to work as it should .

PD : STATS UNTOUCHED THIS PR JUST FIXES THE BEHAVIOUR ALL NUMBERS ARE THE SAME AS BEFORE .
PD 2 : potency = level / 2 which means i have to add a (potency * POTENCY_MULTIPLIER_MEDIUM) to keep the numbers the same

# Explain why it's good for the game
bug bad . research = funny

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl:
fix: Fixes Booting , Cryometabolizing , and other metabolites  not working on some traits
/:cl:

### CODE REVIEW

**Comment by Weuyn** [comment]
Allowing boosting to affect ciphering is a terrible idea, ciphering costs many times times as much to amplify to make it harder to spam hives (it had a unique modifier that no other property has, except the egg plasma one iirc).

Amplifying boosting from 1 to 5 costs only 7 points. Amplifying ciphering from 1 to 5 costs like 40? I think? It would be really funny, but not balanced.

fire/explosive mod traits don't care about boosting anyway, boosting only has an effect when metabolized?

**Comment by Diegoflores31** [comment]
> Allowing boosting to affect ciphering is a terrible idea, ciphering costs many times times as much to amplify to make it harder to spam hives (it had a unique modifier that no other property has, except the egg plasma one iirc).

only corrupted are allowed to be friendly at marines anyways so spamming hives is not really concern . and boosting is not something you get every round . its almost as rare as fire penetrating and its outright  dumb that such a high tier, hard to get modifier just doesnt work with like half of traits

**Comment by Huffie56** [comment]
would it fixed this issue @Diegoflores31 ?
https://github.com/cmss13-devs/cmss13/issues/3894

**Comment by Diegoflores31** [comment]
> would it fixed this issue @Diegoflores31 ? #3894

No . That issue is not a bug sadly it is "intended" because of how research warcrimes if anything i will rather do something about it on a different PR

**Comment by Unknownity** [comment]
This should require clarification from a developer regarding Boosting not affecting some properties whether that is actually intended or not.
@Segrain

**Comment by Diegoflores31** [comment]
Well the description clearly says that boost other properties . And wiki says the same . Its counter intuitive that it just applies to some chems and not to others

**Comment by Diegoflores31** [comment]
i realized i did a lil bit of shitcode will rewrite this PR tomorrow

**Pull request closed without merging**
