### PR TITLE
white phosphorus smoke can no longer override stronger flames

### PR DESCRIPTION
**Pull request by iloveloopers**
# About the pull request
white phosphorus smoke will no longer forcefully set the reagent of the mob

# Explain why it's good for the game
when hit by a WP rocket, a mob is supposed to be set with the blueflame reagent but sometimes the phosphorus smoke can override it just as you leave the fire and the mob's fire reagent ends up being normal UT napalm, which is signficantly weaker than blueflame.

# Testing Photographs and Procedure
yes I tested it

# Changelog
:cl:
fix: White phosphorus will no longer forcefully set a mob's fire_reagent to be UT napthal
/:cl:

### CODE REVIEW

**Comment by ihatethisengine** [comment]
just make it a regular smoke? Otherwise it's a balance change because it makes a lot easier to follow up on WP.

**Comment by iloveloopers** [comment]
> just make it a regular smoke? Otherwise it's a balance change because it makes a lot easier to follow up on WP.

done

**Comment by PhantomEpicness** [comment]
how about you fix the overriding instead of nerfing WP rockets

**Comment by ihatethisengine** [comment]
> how about you fix the overriding instead of nerfing WP rockets

how is this a nerf

**Comment by fira** [comment]
why not just fix the phosphorous smoke?

**Comment by iloveloopers** [comment]
> why not just fix the phosphorous smoke?

what do you mean by fix?

**Comment by iloveloopers** [comment]
> why not just fix the phosphorous smoke?

is this good enough?

**Comment by fira** [comment]
Oh yeah that works i think

**Review by Drulikar — APPROVED** [review]
Counter-intuitive that the proc works that way but works.

**Pull request merged**
