### PR TITLE
Removes the sainja language from roles who don't need it

### PR DESCRIPTION
**Pull request by SuprisedBaby**
## About The Pull Request
Removes the pred language from synth and freelancer warlord.
(Approved by monkey)

## Why It's Good For The Game
It makes 0 sense for these roles to know the yautja language as not much is known about the yautja themselves. It would be better if synths tried to RP knowing the language but most if not all interactions i've had with them they immediately understand it and don't try and RP it

## Changelog

:cl:
del: remove sainja from roles that should not have it

/:cl:

### CODE REVIEW

**Review by Shad0vvs — APPROVED** [review]
code comfy

**Comment by ThePiachu** [comment]
From the Discord discussion - it doesn't seem Synths use this language too much, while it might be useful for niche roleplay opportunities like when a Predator gets captured and loses their bracers so they have at least someone to roleplay off of.

**Comment by NGGJamie** [comment]
> It would be better if synths tried to RP knowing the language but most if not all interactions i've had with them they immediately understand it and don't try and RP it

I'm out of touch, but this used to be part of the synthetic guidelines. Synths were encouraged to RP not entirely understanding the language immediately, but the instant understanding was mechanically more simple than trying to implement a language learning system for a single role.

It really wouldn't be a big ask to say "Hey synth players, try to RP more about picking up the language through conversation on the fly rather than knowing it immediately."

Other roles make sense, but as one of the OG synthetic players, I oppose removing the language from the role.

**Comment by morrowwolf** [comment]
I don't think the language should be removed from synth whitelisted roles. I will be talking to game architects about it. Until then I'm formally blocking merge until the conversation is had.

**Comment by Chainsawicus** [comment]
> > It would be better if synths tried to RP knowing the language but most if not all interactions i've had with them they immediately understand it and don't try and RP it
> 
> I'm out of touch, but this used to be part of the synthetic guidelines. Synths were encouraged to RP not entirely understanding the language immediately, but the instant understanding was mechanically more simple than trying to implement a language learning system for a single role.
> 
> It really wouldn't be a big ask to say "Hey synth players, try to RP more about picking up the language through conversation on the fly rather than knowing it immediately."
> 
> Other roles make sense, but as one of the OG synthetic players, I oppose removing the language from the role.

I believe feedback should be left on the PR's discord thread per new guidelines.

**Review by morrowwolf — CHANGES_REQUESTED** [review]
Talked with Monkey and councils. Remove the removal of yautja language from synths. You can keep the removal from the freelancer leader.

**Pull request closed without merging**
