### PR TITLE
Mapping adding a panic room with an armory and an MP office to hangar.

### PR DESCRIPTION
**Pull request by Huffie56**
# About the pull request
adding a panic room in hangar that can be open via an MP office that as an armory to quickly respond to hostile coming from DS's

# Explain why it's good for the game
Will add a room to secure civilian and injuries if hostile are coming up DS's specially if hangar lock down is activated.

# Testing Photographs and Procedure

I have tested all the items etc didn't crash and everything seem to work.

<details>
<summary>Screenshots & Videos</summary>

before
image
after
image
before
image
after
image

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: adding a panic room in hangar that can be open via an MP office that as an armory to quickly respond to hostile coming from DS's
/:cl:

### CODE REVIEW

**Review by monkeysfist101 — CHANGES_REQUESTED** [review]
Needs Semiotic Standard applied. You can find the signs by typing "safety" in the filepath. Reference the names for their function and existing standards for offsets.

**Comment by Huffie56** [comment]
> Needs Semiotic Standard applied. You can find the signs by typing "safety" in the filepath. Reference the names for their function and existing standards for offsets.

done tell me if it's not enough.
image

**Review by Agameofscones — CHANGES_REQUESTED** [review]
Add another entrance to maintenance with a shutter. Parity with CL's office. There should also be a ID locked shutter release on the exterior in maintenance, similar to the CL's own lockdown.

The actual mapping checks out, and I'm in favor of this change.

**Comment by Huffie56** [comment]
> Add another entrance to maintenance with a shutter. Parity with CL's office. There should also be a ID locked shutter release on the exterior in maintenance, similar to the CL's own lockdown.
> 
> The actual mapping checks out, and I'm in favor of this change.

done
image

**Comment by Huffie56** [comment]
> Needs Semiotic Standard applied. You can find the signs by typing "safety" in the filepath. Reference the names for their function and existing standards for offsets.

i added them as requested.

**Comment by Huffie56** [comment]
Tested ready to be merge.

**Comment by Huffie56** [comment]
Tested ready to be merge.

**Comment by Huffie56** [comment]
Tested ready to be review/merge.
image

**Review by morrowwolf — CHANGES_REQUESTED** [review]
pass one

See picture for requested changes. I agree that this is a neat addition for sure! Very creative use of the space.

**Comment by Huffie56** [comment]
> pass one
> 
> See picture for requested changes. I agree that this is a neat addition for sure! Very creative use of the space.

fixed all the naming and spacing errors.

**Comment by Nanu308** [comment]
This will conflict with #2140 and vice versa.

**Comment by Huffie56** [comment]
> This will conflict with #2140 and vice versa.

can't really solve this conflict on my side.
but as i say to him if he could reduce the PR to just moving DCC bunk-room in the blue area it would resolve the conflict but i can't do it on my side....

image

**Comment by Huffie56** [comment]
yep tried and fucked it up again....

**Pull request closed without merging**
