### PR TITLE
Indestructible splints for UPP vs USCM gamemode

### PR DESCRIPTION
**Pull request by cuberound**
# About the pull request

steel wants splints to be (or in this case act as) nanosplints in UPP vs USCM events, this PR relies on  #6966 being added first

# Explain why it's good for the game

breaking splints in HvH is extreamly annoying with all the random bullets flying your way, event only change taht was asked for

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl:
balance: splints act as and look like nanosplints in faction clash
/:cl:

### CODE REVIEW

**Comment by Nanu308** [comment]
Should be a toggle setting for HvH similar to the other options we have, I'll balance approve it then so event runners can run their events as they wish.

**Review by Nanu308 — APPROVED** [review]
le balance approved

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Review by harryob — APPROVED** [review]

**Pull request merged**
