### PR TITLE
Drastic Changes to the USS Almayer research department

### PR DESCRIPTION
**Pull request by spartanbobby**
# About the pull request

This PR changes research onboard the USS Almayer to something I hope is better to use and visually better

I'd like to see this test merged to gauge community feedback/what needs changing

# Explain why it's good for the game

I believe this is an improvement to the research department making containment an actually secure area and making the research part of the department more open and closer together hopefully making it easier to move around

this PR adds alot of shutters and blastdoors to research one major blastdoor acts as a master lockdown basically shutting down the entirety of the department, no one in, no one out

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl:
maptweak: heavy changes to the research department
/:cl:

### CODE REVIEW

**Comment by Nanu308** [comment]
lgtm

**Review by Nanu308 — APPROVED** [review]
👍

**Comment by Segrain** [comment]
I will make a more detailed review later, but one thing makes itself outrageously evident even at a passing glance: that massive W-Y logo _does not_ belong there.

**Comment by spartanbobby** [comment]
> I will make a more detailed review later, but one thing makes itself outrageously evident even at a passing glance: that massive W-Y logo _does not_ belong there.

It's there because it looks cool will remove on maptainer request

**Comment by Segrain** [comment]
I am being reminded to cease being lazy, so here are at least some thoughts.
shutters
These shutters could probably use more indicative names. Speaking of shutters, it would be nice to have a button to control external shutters on the outside of the main entrance as well, so that you are not locked out the moment somebody inside decides to close them.
CMO
CMO's office still has a button labelled as Research Interior, but it does not seem to be linked to anything?


Now, room by room on the inside.

Containment is mostly fine and I am not going to object to vents if they really are locked and selfcontained, but a couple notes there.
door control
Standing in front of this door controller, you cannot actually see the door in question. Any way to move it to the southern wall and maybe add a window there?
image
This room is a nice addition, but it could probably use a more distinct name than "containment 5". It is less of a containment room and more of a surgical theatre.
image
The purpose of this room eludes me. It is half a breakroom with some food amenities, half a workplace. The door says "medical research wing", but everything here is research - would be nice to have a more indicative name.
The table in the middle _looks_ like a place to have meetings or talk or simply sit down and eat, but it is instead dominated by a microwave. It probably belongs in a corner along with the rest of the equipment.
Doc starts here, but unlike previous design that gave him his own corner, he is completely uncontained and crawls everywhere. In a room with all the food equipment, no less.
A fridge with milk is a good addition.
Beakers and syringes tossed in between cooking equipment and food vendors are less so. This room really wants to be split into two.
Why is there a camera console? At least it should be for research network and not for Almayer's.
Speaking of cameras, terminal in CMO's office is still named "Containment cameras", but it now has a general research network and can probably be renamed accordingly.
image
Main room is mostly fine, though it feels strangely cluttered.
The phone at the front is all that remains of the old study room. It was _good_ to have a separate room with cabinets for paperwork, corner with computers and a table with some chairs where you could sit down with, for example, chemical ERT and discuss the matters in civilised manner. Why remove it?
Not pictured in the posthijack screenshot, but in the corner with synthesiser (the two-tile wide machine) there are two cabinets next to it. The synthesiser itself is offset onto a wall and has zero density. The cabinets are similarly offset and look like you should be able to walk through them, but they _do_ have density of 1. Feels like an oversight.
image
The room with all the lathes and the chemical batteries (again not pictured) is awfully cluttered again. Everything is piled together with barely any room to approach it. Tools, spare vials and beakers, vendors with clothes - everything is thrown together and I cannot find enough rhyme or reason to warrant this change.
The door to this room, again, needs a name indicating what that room is actually meant to be.
image
Hydroponics corner is awfully tiny. It is less of a room and more of what spare space was left, filled with all the remaining equipment that still needed a place. Previous design was much better. The arrangement of trays is especially painful, as that is where most of hydroponics work is going to be, and it is completely ruined.
Previous design allowed, with only two trays moved a single tile each, rearrange it so that for each tray there is an individual empty floor tile to dump its harvest without mixing different trays together. Here there is nowhere near enough space, and some trays are outright stacked on top of each other.
It also allowed, without even any movement, splitting the room into two, either for two researchers to handle their own sides separately, or for six trays to be dumped onto a single tile in the centre if you have a plant you want to produce en masse, in opposite to the previous point.
And even after doing all of that, there still was plenty of empty floor tiles to leave the tools and keep separate general piles of harvested fruits not associated with any adjacent trays (I am routinely keeping at least three general piles besides those for the trays themselves). Now there is nowhere to fit anything.
The trays stacked onto the same tile might look nice on an editor screen, but try to use them in practice, and...
trays
Sprites get into the way of each other, obscuring the indicators on the top trays and preventing the clicks getting through. Imagine the bottom trays full of wheat instead.

There was probably more to say, but I forgot it already and I am being reminded to make this comment before taking too long. Might revisit it later.

**Comment by LC4492** [comment]
One idea that I would like to give is that, the hall corners from both starboard and port are misaligned, you could try on getting a little more of internal space to Research if you alligned them and made them 3x3 instead of...3x5 or 3x4. maybe that would help you solve how...crumpy the hydroponics room is

**Pull request merged**
