### PR TITLE
New Spray Sprites

### PR DESCRIPTION
**Pull request by Youtubeboy139**
## About The Pull Request

Adds in new spray sprites for `pestspray` the `weedspray` and `plantbgone`. It also replaces the legacy `chemsprayer` with a new custom sprite based on the M240t sprite to keep it semi-lore freindly.

Sprite-0001

## Why It's Good For The Game

Out with the old and in with the new. This PR brings better coherency to the art style of the game.

## Changelog

:cl:
imageadd: New pest spray sprite
imageadd: New weed spray sprite
imageadd: New plant-b-gone sprite
imageadd: New chem sprayer sprite
imageadd: New generic spray bottle
imageadd: New cleaner bottle
imageadd: New hydrospray bottle
/:cl:

### CODE REVIEW

**Review by FransFeiffer — CHANGES_REQUESTED** [review]
Please edit the outline of the plantbgone so that it's not true black (rgb 0,0,0) and make it so that it matches the rest of the sprite. Similarly, there's true black on the tops of the other two sprays.

Otherwise the sprites are good. If you have any questions, let me know.

**Comment by Youtubeboy139** [comment]
> Please edit the outline of the plantbgone so that it's not true black (rgb 0,0,0) and make it so that it matches the rest of the sprite. Similarly, there's true black on the tops of the other two sprays.
> 
> Otherwise the sprites are good. If you have any questions, let me know.

Spray bottles in-game have the same outline. The Plant-b-gone is a recolor of the standard spray bottle. All I did was alter the height of the sprite and the hue of the colors. If you want I can edit the rest of the spray bottles, but I don't want to do that without permission.

**Comment by Youtubeboy139** [comment]
May I have permission to change the current spray bottle sprites in-game?

**Review by FransFeiffer — APPROVED** [review]
Sprites are solid, let's get this MERGED

**Pull request merged**
