### PR TITLE
Allows medics to purchase the IO expedition pack

### PR DESCRIPTION
**Pull request by s5nt**
# About the pull request

Just allows medics to purchase the expedition pack, which has the size of a backpack but allows for instant opening like a satchel for 30 out of 45 of their vendor points.

# Explain why it's good for the game

Allows for medics to hold more items. Recently, changes have been made that make it so medics are effectively less supplied than they were before. This allows the average medic to still have room for long games at the cost of being able to purchase pretty much nothing else of impact in their vendor such as armour if they wish to stray from the light armour meta.

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl: S5nt
balance: Changed medic prep vendors to allow purchasing of the expedition backpack
/:cl:

### CODE REVIEW

**Comment by morrowwolf** [comment]
LET'S GOOOO, WE CAN THEN REMOVE IT IN ANOTHER SIX MONTHS, AND THEN WE CAN RE-ADD IT IN SIX MONTHS, THEN WE CAN- *gunshot*

**Comment by s5nt** [comment]
I am a fucking moron and closed it accidentally I'm not gonna lie.

**Comment by cuberound** [comment]
medics who want shitload of supplies just carry backpack in hand with them tbh

**Comment by Drulikar** [comment]
It is intentional that there is more attrition in supplies than there was. This does not need to be compensated with bigger bags; especially not if its going to eliminate almost all choice from your loadout.

**Pull request closed without merging**
