### PR TITLE
Pick-Say Macro

### PR DESCRIPTION
**Pull request by Geevies**
## About The Pull Request

Instead of binding your say battlecry say macros to your entire keyboard, you can now assign it to one macro, using this format:
`pick-say TEXT HERE, SPACES AND COMMAS WORK.;SEMI-COLONS ACT AS THE SPLITTING POINT!;MEANING YOU CAN GET A LOT OF BANG FOR YOUR BUCK.`

There is a 1.5 second delay between sending messages this way, to try and reduce spam. It might be increased a lot more if you abuse it for shenanigans.

## Why It's Good For The Game

https://tenor.com/view/aliens-paxton-gif-20600480

## Changelog

:cl:
add: Added the pick-say macro, which can assign a lot of battlecries to one button. Check the PR for instructions on how to use it.
/:cl:

### CODE REVIEW

**Comment by c4xmaniac** [comment]
Erm, epic?

**Comment by Git-Nivrak** [comment]
> c4xmaniac

yes

**Comment by Shad0vvs** [comment]
What if I wanted it to work with *warcry

**Comment by ghostsheet** [comment]
instant merge now

**Comment by JohnDoe50974** [comment]
How does this actually work? Does it just randomly pick one of the messages you pre-inputted when you press the pick-say macro?

**Review by Shad0vvs — APPROVED** [review]

**Pull request merged**
