### PR TITLE
Change Queen to King in Solidarity with the Royal Family

### PR DESCRIPTION
**Pull request by PhantomEpicness**
## About The Pull Request
Change Queen to King in Solidarity with the Royal Family

## Why It's Good For The Game
Change Queen to King in Solidarity with the Royal Family

## Changelog

:cl:totalepicness

qol: Change Queen to King in Solidarity with the Royal Family

/:cl:

### CODE REVIEW

**Comment by AGasCanister** [comment]
kneel emoji

**Comment by morrowwolf** [comment]
Please re-read the contributor guidelines. I will be closing this unless overruled.

**Comment by Diegoflores31** [comment]
no fun allowed fr

**Comment by Boopideedoo** [comment]
> Please re-read the contributor guidelines. I will be closing this unless overruled.

But the queen is dead so this kinda does need updated

**Comment by DylonBR** [comment]
no fun allowed!!!

**Comment by hotimep** [comment]
my life for the king!!!

**Pull request closed without merging**
