### PR TITLE
Removes MPs

### PR DESCRIPTION
**Pull request by Geevies**
## About The Pull Request

Lowers all Military Police slots to 0. They can still be spawned in manually by admins.

## Why It's Good For The Game

MPs currently exist in a pseudo IC-OOC blend of RP moderation, where they're often at odds with their own team. Marines don't have many ways to thwart them as they would in any other SS13 server, due to the many OOC protections granted to them.

Additionally, there exist many MP mains who try their darndest to 'fish' the biggest 'catch' (wait for a CO to make a mistake and then arrest them), this isn't really against the rules, but I'd classify it as bad faith gaming.

As such, I think it'd be best to remove them from the equation temporarily until we rethink how we want them to be managed. I'm not the greatest literary beast, so I'm sure a gigabrain megamind will provide a thesis statement greatly overshadowing my own thoughts in the comments below.

## Changelog

:cl:
del: Removed MPs by lowering their job role slots to 0.
del: Command roles no longer need MP hours.
/:cl:

### CODE REVIEW

**Comment by Joelampost** [comment]
Hard +1 until MPs can be re-worked as you stated

**Comment by joookschad** [comment]
Good PR. MP's honestly deserve a rework or  actual moderation to weed out the bad faith players, who only play for arresting and do not care about roleplay.

**Comment by BKryth** [comment]
First VC, now MP, removing the bad roles so awesome

**Comment by moltoretardo** [comment]
MPs as they are now cripples alot of RP opportunities I've seen. I only ever witnessed a couple of them actually acting in good faith rather than robots trying to get their awesome reward (The salt of players getting removed for a round).
The only instance of griefing I've seen during the No-Mp week was an MP main breaking in the brig to LARP as an MP, which is very ironic in my opinion. 

Let admins deal with griefers/lrp

**Comment by JediKing112** [comment]
+1 agreed.

**Comment by AntoineXYZ** [comment]
might be a terrible idea but how about creating a MP whitelist? It would probably be easier to moderate in the long run (smaller pool of people to moderate, dedicated people to get stuff in order). It would gate the job behind real motivation and knowledge of ML and It could (maybe big question mark?) ease up tensions with the marine (Old MP to get a notch on their vs actually someone who just want to keep a round peaceful)

**Comment by PhantomEpicness** [comment]
### LITTERALLY THE MOST BASED PR IN EXISTENCE 

speed merge ASAP + mp skill issue + incoming false flags + mp cope + massive marine buff

_**Disclaimer**_

CM-SS13 is not related to the Disney-owned "Aliens" Franchise and IP This is an entirely fan-made project. In case of an investigation by any federal entity or similar, I do not have any involvement with this group nor with the people in it, I do not know how I am here, probably added by a thrid party, I do not support any actions by the members of this group. Any and all content made by this account were made without my permission and I have no knowledge of the usage of this github ©️  account to contribute to CM-SS13.

**Comment by Superreallycoolguy** [comment]
I barely trust staff to moderate with MPs, if crimes become OOC, good luck -1.

(MPs do need a rework though on god)

**Comment by Bram-KEP** [comment]
I love u geeves unless crime becomes ooc

**Comment by Bram-KEP** [comment]
Based PR

**Comment by Don2137** [comment]
This will be blocked by management so can we consider the previous rework idea instead?
https://docs.google.com/document/d/1hXWIfIKfiXvbhE_fUfQKyebSpd19dy2xRt7je1a9evg/edit?usp=drivesdk

**Comment by Chainsawicus** [comment]
> This will be blocked by management so can we consider the previous rework idea instead? https://docs.google.com/document/d/1hXWIfIKfiXvbhE_fUfQKyebSpd19dy2xRt7je1a9evg/edit?usp=drivesdk


This also got blocked by management, it was tested with only a few MP players' knowledge, they all obviously disliked it, and it was silently scrapped.


> I barely trust staff to moderate with MPs, if crimes become OOC, good luck -1.
> 
> (MPs do need a rework though on god)

They'll never get a rework because all the people in a position to approve one are complacent in the current state of MPs or deliberately brought them into this state, so they might as well get removed.

**Comment by PalJohnson** [comment]
Geeves I love you but I don't think its right to temporarily remove stuff like MPs without providing some plan or timeline to help resolve the issues facing MPs. This can quickly become a thing of "We will get to it eventually". I understand that the role of MP is a complex one given the current conditions and the communities opinions but I don't want to see this just get left to the wayside. There are very few people who can pull off a rework of the role and even then you can't force a developer or contributor to work on it. It is an undertaking and it takes a long time to get PRs like this done. When I re-worked brig it took months of back and forth just to get the design and execution done. I cannot support a PR that doesn't provide a plan to resolve the issue at hand.

The Implications of the MR are huge

- Marine law enforcement will go directly to staff instead of trying to handle it in RP making everything an OOC issue. Resulting in more notes, bans, and in general work for the staff.
- Staff is not always available to help police these issues and people are somewhat reluctant to report bad behavior without facing some sort of pushback from the community at large.
- Ship security will be further strained against hostile foreign invaders given that once marines deploy only a skeleton crew is onboard such as (req, xo, and some if any medical staff). Who is to stop greenos or the CL growing Xenos of his own?
- This will provide less RP engagement leaving the role to admin spawns if they choose to do events.
- No more honor guard for CO
- Large portions of the ship become utterly useless. Even in the case of events (which generally involve very few people shipside) would make no sense to have the brig as large as it is.
- All the code and mapping hours put into the role become wasted if no considerable effort is made to rework it.
- Old code not being used becomes code bloat.

**Comment by novaepee** [comment]
Over at TGMC, admins deal with griefers. In fact, players will often get admins' attention to griefers. Here is the PR for the discussion on removing MP in TGMC: https://github.com/tgstation/TerraGov-Marine-Corps/pull/3928

The one point I must make is that if there is an active shooter in TGMC, it is okay for the marine players in self-defense to shoot down the active shooter. TGMC admins permit this. My personal experience with this is being in the same prep with griefers shooting up prep, I proceed to go get cover and ahlep fast, then blast down the active shooter.

**Comment by IngloriouslyBad** [comment]
Great PR. After the MP fiascos lately I am 100% on board. They abused the role and the OOC protection enough. 

Command roles requiring MP hours was such a discouraging thing to anyone with some self respect wanting to pursue leadership roles without feeling scummy by actively being told to grief their own team. Another good change to see.

**Comment by PhantomEpicness** [comment]
Incoming neverplayers suddenly giving their opinions like they play the game daily.

**Comment by Pyrodes** [comment]
THIS IS OUR CHANCE TO DEFEAT THE RED MENACE
ONCE AND FOR ALL

**Comment by PhantomEpicness** [comment]
TBH it's gonna be a massive overstep if management intervenes on a game architect matter like this. And I will watch the uproar with popcorn in my hand when it eventually does happen.

**Comment by ondrej008** [comment]
Keep them in, but allow them to deploy, I think that would be cool, they are **military** police after all and should be on the field as well.

**Comment by ZAB909** [comment]
Be sure to buff xenos after. As this is a massive marine buff. 1+

**Comment by c4xmaniac** [comment]
Holy shit lois its finally happening

**Comment by AGasCanister** [comment]
🆑
del: Removed MPs by lowering their job role slots to 0.
del: Command roles no longer need MP hours.
/🆑

Greeves, if you think that will work by simply disabling the slots, you're stupid, staff will just roll MT and take MP gear and keep griefing as they did previously. And no I did not read the whole MR I just read the first 2 lines along the CL. Clown emoji

**Comment by Nanu308** [comment]
Closed till I'm returned from vacation and probably a bit more :D

**Pull request closed without merging**
