### PR TITLE
Code maintenace of Stats Entities

### PR DESCRIPTION
**Pull request by fira**
# About the pull request

 * Removes extraneous `= null`
 * Adds `Destroy` with proper clearing to all entities
 * Fixes up some single-letter vars and incorrect proc signatures
 * Transforms some comments to DMDoc
 * Generally tries to clear up the usage of the entity lists (they're MOSTLY indexed)

# Explain why it's good for the game
Code maintenance

# Testing Photographs and Procedure
Didn't see anything wrong but best tested in TM

# Changelog

Nothing player facing

### CODE REVIEW

**Review by Drulikar — APPROVED** [review]
Code changes appear fine. Only thing that may come up in testing is if something is nulled that something still tries to access.

**Comment by fira** [comment]
It is mostly a safety net due to GC errors in death statistics being deleted, otherwise entities are very rarely deleted

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Review by harryob — APPROVED** [review]

**Pull request merged**
