### PR TITLE
Marine Cat Ears Helmet Attachment

### PR DESCRIPTION
**Pull request by Diegoflores31**
## About The Pull Request

Adds a new Helmetgarb for marines : Cat ears currently unobtainable by nyormal means.

## Why It's Good For The Game

they look cool + helmet attachments soul .

## Changelog

:cl:
add: Added Cat ears Attachment for marine helmets.
imageadd: Added sprites for Cat ears.

/:cl:

### CODE REVIEW

**Comment by Shad0vvs** [comment]
🍿

**Comment by PhantomEpicness** [comment]
based PR

Now xenomains can play marine comfortably

**Comment by memesky117** [comment]
get this man a permanent ban from https://github.com/cmss13-devs/cmss13

👍 👍 👍

**Comment by morrowwolf** [comment]
Unless overruled I will be closing this. Please re-read contributor guidelines: https://cm-ss13.com/wiki/Contributing_to_the_Game

**Comment by monkeysfist101** [comment]
Re-opened

**Review by monkeysfist101 — CHANGES_REQUESTED** [review]
Looks like you didn't rebase before pushing and overwrote the changes to the helmet garb. 

image

**Comment by monkeysfist101** [comment]
Also denied.

**Pull request closed without merging**
