### PR TITLE
Boots! PDT/L Battle Buddy Kit

### PR DESCRIPTION
**Pull request by Geevies**
## About The Pull Request

Adds the PDT/L system, and the kit box to acquire it in the loadout menu. Also adds a desc_lore system so we can add flavour to items without bloating the item descriptions.

## Why It's Good For The Game

It's neat and builds lore.

## Changelog

:cl: Geeves, Youtubeboy139, Triiodine
add: Added the Boots! PDT/L Battle Buddy kit to the custom gear loadout and Requisitions vendor (under the Misc section). It's a watch / locator tube kit that allows you to track your battle buddy up to five times before needing a cell swap.
/:cl:

### CODE REVIEW

**Comment by ghostsheet** [comment]
Soo this is an metabudddy device
that helps you keep track of one marine?!? AWESOME

**Comment by thwompa** [comment]
OBJ sprite does not fit the artstyle, needs to be remade to fit perspective and styling.

Onmob is fine.

The tracker is too flat and does not have highlights, (aka no contrast). 

Box is good.

**Review by nauticall — APPROVED** [review]
denied!!!!!!

jk sprites lgtm

**Review by stanalbatross — CHANGES_REQUESTED** [review]
needs a better CL entry

**Review by stanalbatross — APPROVED** [review]
approved but the PR is a lie, the bracelet does not fit on your hands

**Pull request merged**
