### PR TITLE
Deletes Legacy LV-624 Nexus Lockdown Button

### LINKED ISSUE #1549: LV-624 Nexus Lockdown
## Description

This has been an issue for as long as I have played, the Nexus building has a button called "Nexus Lockdown" in the admin office, which doesn't actually do anything since there are no shutters.

## Difference between expected and actual behavior

A button which has no shutters to activate. The Nexus needs shutters (CL Office variant, not Research Dome blast doors) placed at all the areas I marked in red.
LV-new

Celebrate a new era of CM with me, with Hookers, Blackjack and shutters to keep the rabble out.

## Steps to reproduce

1. Play LV
2. Power the Nexus
3. Hit the "Nexus Lockdown" button

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

### PR DESCRIPTION
**Pull request by ItsVyzo**
# About the pull request
fixes #1549

# Explain why it's good for the game
mapfix

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl: LTNTS
del: Removed unused Nexus Lockdown Button
/:cl:

### CODE REVIEW

**Review by Agameofscones — CHANGES_REQUESTED** [review]
seems like you have a dict key swap. Why are you replacing key abl with key syA? The differences being a whole bunch of bushes getting deleted.

**Comment by ItsVyzo** [comment]
> seems like you have a dict key swap. Why are you replacing key abl with key syA? The differences being a whole bunch of bushes getting deleted.

that was StrongDMM I believe, didn't touch any bushes while changing stuff

**Comment by ItsVyzo** [comment]
fix i hope

**Comment by Nanu308** [comment]
Mapping lgtm, in the future if someone wants to try adding a lockdown function to Nexus i'd be fine with testing that.

**Review by Nanu308 — APPROVED** [review]
lgtm

**Pull request merged**
