### PR TITLE
surv loot spawners

### PR DESCRIPTION
**Pull request by stanalbatross**
## About The Pull Request

easy to use spawners for survivor loot - big mapper qol! 

## Why It's Good For The Game

makes surv looting more engaging and random

## Changelog

:cl: Stan_Albatross, Triiodine
add: added random spawners for survivor loot items (guns, sentries, stims, thermals, etc). These random spawners come in a few types - stimulants, thermals, shotguns, rifles, smgs, special weapons, and pistols. They also come in four rarities - 100%, 80%, 50%, and 20%. These all have unique icons and can be further configured with how many additional mags they spawn for gun spawners, if they move around, etc.
add: added more double doors to sci annex
add: coded in and added inhands for the ar10, sprites by Triiodine
add: coded in and added inhands for the laser UZI, sprites by Triiodine
soundadd: added sounds for the ar10 firing and cocking, by Triiodine
soundadd: added a new sound for laser firing, from tg
imageadd: added some new laser sprites from tg
imageadd: added back sprites for the m16 and ar10, by Triiodine
balance: changed most of the survivor loot on science annex to random spawners
add: made the claymore spawners on the lv destroyed hydro nightmare insert random
balance: the m79 can now fit on your back
/:cl:

### CODE REVIEW

**Comment by c4xmaniac** [comment]
0 need for this change. It’s a nerf to the already weak roaming Survs on a map that equally already deincentivizes survivor roaming. With the loss of yard, getting to the medbay pill bottle, chapel loot, and blue dorms loot is far more difficult - often times impossible. Medbay is almost immediately weeded, and has xenos spawn just north of it who usually hang around. There is a reason people rarely get meds on this map if they don’t get a Surv who spawns as a doctor.

**Comment by MusselMain** [comment]
This change is really silly, Florina annex has always been a map that punishes survs for roaming, and has two or three hold locations that I see being used 9 rounds out of 10, the way to fix this map is by adding MORE items that (and by moving more loot away from the LZ's) force survs to choose weather they want to take a massive risk and get better loot that's farther out, or go without it and risk dying because they lack said items. Simply removing things instead of relocating them to a more difficult location will encourage players to continue the hold heavy playstyle that seems to happen almost every round and means there's less reward for survs who are willing to take risks.

**Review by Nanu308 — CHANGES_REQUESTED** [review]
Create and use Landmarks that select from a list of options (Ultrazine, better weapons, stims, etc.) so the location is no longer static and guaranteed.

**Comment by c4xmaniac** [comment]
You get under two minutes to loot, find an area to defend, and get the first cades up. Randomizing the loot not only weakens you, but more importantly wastes your extremely limited time. If this was intended to be a compromise it’s worse than the nerf this PR originally was.

**Comment by stanalbatross** [comment]
> You get under two minutes to loot, find an area to defend, and get the first cades up. Randomizing the loot not only weakens you, but more importantly wastes your extremely limited time. If this was intended to be a compromise it’s worse than the nerf this PR originally was.

survs should not be able to rely on meta-knowledge of where ultrazine pill bottles etc are
general area knowledge (ie - stims are likely near medbay) is fine but when survs can pinpoint the exact location of every single stim pill and mk221 on the map it's just bleh

**Comment by c4xmaniac** [comment]
>survs should not be able to rely on meta-knowledge of where ultrazine pill bottles etc are
general area knowledge (ie - stims are likely near medbay) is fine but when survs can pinpoint the exact location of every single stim pill and mk221 on the map it's just bleh

Yeah I agree you shouldn't have to rely on meta-knowledge of gear, but you have to due to things like time restraints I've mentioned before. I am unsure as to how the current survivor loop is negatively effecting gameplay as it has been this way since its outset. It's apart of the skill curve to learn where the items are and how to budget your time, adding ambiguity to it or outright wasting people's time is not a positive change to this system and unfairly punishes people for choosing to sacrifice certain items (like meds) for combat enhancing gear or vice-versa only to be rewarded with nothing for this sacrifice. 

Maybe a better system would be a loot-scaling system where items of the same "type" spawn in that area. So if I go to grab the mk221 maybe its a type 23, or a regular marine shotgun with attachments, or maybe its even the HC kit mk221 but there's always an item at least of slightly better value than the HG in that same place. That way when I sacrifice getting meds I _know_ that I will be receiving some kind of item in return for the opportunity cost.

**Comment by stanalbatross** [comment]
> > survs should not be able to rely on meta-knowledge of where ultrazine pill bottles etc are
> > general area knowledge (ie - stims are likely near medbay) is fine but when survs can pinpoint the exact location of every single stim pill and mk221 on the map it's just bleh
> 
> Yeah I agree you shouldn't have to rely on meta-knowledge of gear, but you have to due to things like time restraints I've mentioned before. I am unsure as to how the current survivor loop is negatively effecting gameplay as it has been this way since its outset. It's apart of the skill curve to learn where the items are and how to budget your time, adding ambiguity to it or outright wasting people's time is not a positive change to this system and unfairly punishes people for choosing to sacrifice certain items (like meds) for combat enhancing gear or vice-versa only to be rewarded with nothing for this sacrifice.
> 
> Maybe a better system would be a loot-scaling system where items of the same "type" spawn in that area. So if I go to grab the mk221 maybe its a type 23, or a regular marine shotgun with attachments, or maybe its even the HC kit mk221 but there's always an item at least of slightly better value than the HG in that same place. That way when I sacrifice getting meds I _know_ that I will be receiving some kind of item in return for the opportunity cost.



> > survs should not be able to rely on meta-knowledge of where ultrazine pill bottles etc are
> > general area knowledge (ie - stims are likely near medbay) is fine but when survs can pinpoint the exact location of every single stim pill and mk221 on the map it's just bleh
> 
> Yeah I agree you shouldn't have to rely on meta-knowledge of gear, but you have to due to things like time restraints I've mentioned before. I am unsure as to how the current survivor loop is negatively effecting gameplay as it has been this way since its outset. It's apart of the skill curve to learn where the items are and how to budget your time, adding ambiguity to it or outright wasting people's time is not a positive change to this system and unfairly punishes people for choosing to sacrifice certain items (like meds) for combat enhancing gear or vice-versa only to be rewarded with nothing for this sacrifice.
> 
> Maybe a better system would be a loot-scaling system where items of the same "type" spawn in that area. So if I go to grab the mk221 maybe its a type 23, or a regular marine shotgun with attachments, or maybe its even the HC kit mk221 but there's always an item at least of slightly better value than the HG in that same place. That way when I sacrifice getting meds I _know_ that I will be receiving some kind of item in return for the opportunity cost.

if you look at the map changes you can see that _most_ of the spawners are 100% chance spawners which will alway spawn an item of the same type

there are some new spawners with a chance of spawning nothing but these are less prevalent#

will expand in cl to make this clearer

**Comment by Agameofscones** [comment]
I cannot review this since these are my sprites :))

**Comment by Nanu308** [comment]
Balance thingy fine and better

**Review by Shad0vvs — APPROVED** [review]
Code looks good needs sprite and mapping review.

**Comment by SideCat** [comment]
> > You get under two minutes to loot, find an area to defend, and get the first cades up. Randomizing the loot not only weakens you, but more importantly wastes your extremely limited time. If this was intended to be a compromise it’s worse than the nerf this PR originally was.
> 
> survs should not be able to rely on meta-knowledge of where ultrazine pill bottles etc are general area knowledge (ie - stims are likely near medbay) is fine but when survs can pinpoint the exact location of every single stim pill and mk221 on the map it's just bleh

If that's the case, likewise xenos should not rely on meta-knowledge to camp survivors on their meeting/looting spots. Why this change is negative in the first place is because of the current xenomain playerbase, that are very enthusiastic about hunting down survivors.  Of course this is not the case always, because those specific playerbase is not online 24/7, but they play majority of the time. If this change would've been added year+ ago, when maturity was still a thing, then yes this would've been a positive change where survivors had all the time to prepare themselves against xenos, but as if right now, having merely 2 minutes of no intervention is already asking too much on majority of the round. Imo this change will give nothing, but a negative impact on the gameplay and overall feeling of some of cm13's dev team direction that it is going for survivors. I would like to ask you personal question, have you played a lot survivor recently?

**Review by monkeysfist101 — APPROVED** [review]
Sprites LFTM

**Comment by FrogZeke** [comment]
Take LV, it is one of the smaller play areas.  That small power change on hydro road has had massive consequences:  Before the power change, on average, the time it takes to push the med vendor to the original spot allowed 3 (4 if you get a close spawn like fitness) to vend their supplies before the first xenos are on the survivors.  Now trying to get power up in north cargo to use the vendor means often fighting while the first person is getting supplies.  This area has no defenses. During high pop, that is a swarm of 3 to 7 T1 xenos.  TLDR: Even small changes to survivor have a massive effect.

If survivor loot is too OP, there are 3 easy options:
1 - Remove the loot completely.
2 - Move the loot to a location that survivors cannot get to (IE LV PMC supplies in north barrens)
3 - Reduce the ammo for weapons (the OP ones I guess)

The foreknowledge of studying maps is not metaknowledge, it is the result of study and trial and error gameplay of the hardest role in the game.  And justified IC as actually being from the colonies:  "Where are the sentries?"  "Bob and Mike were getting them, they said they were going to loop through LZ1, they never came back."  "The warden's secretary was a pill popper, I'm going to check her desk because I'm afraid of falling asleep."

100%, 80%, 50%, and 20% spawners, so clearly xenos are use meta knowledge and still larva rush in spite of the rule now, but survivors cannot be sure where anything is.  HINT: IT CAN BE CODED THAT LARVA CANNOT EVOLVE UNLESS THEY ARE ON WEEDS AND THAT WOULD FIX IT.  But of course, survivor cannot know the locations of items.

**Comment by stanalbatross** [comment]
> The foreknowledge of studying maps is not metaknowledge, it is the result of study and trial and error gameplay of the hardest role in the game. And justified IC as actually being from the colonies: "Where are the sentries?" "Bob and Mike were getting them, they said they were going to loop through LZ1, they never came back." "The warden's secretary was a pill popper, I'm going to check her desk because I'm afraid of falling asleep."

This would be a somewhat good argument if they actually did this to learn where stuff is on maps, but they don't. They just look up where stuff is on the webmap, etc.

image
image
image

>If survivor loot is too OP, there are 3 easy options:
1 - Remove the loot completely.
2 - Move the loot to a location that survivors cannot get to (IE LV PMC supplies in north barrens)
3 - Reduce the ammo for weapons (the OP ones I guess)

not a fan of these + I've already made the PR

if survs are impacted too much by this (which I doubt), I will consider making their "prep timer" longer

**Comment by BKryth** [comment]
awesome, as a surv player, you are more incentivized to roam the colony instead of sitting in a spot entire round after you're given free time to loot all OP gear.

Rather than find where specific loot are you're gonna have to look through different areas instead to find something and adapt your playstyle to the item you got

Survs playstyle to me is supposed to be always adapting, this is a good change

Hider survs will be punished by making these funny loot harder to find and roamer survs will be incentivized to go around the colony

**Review by Agameofscones — APPROVED** [review]
Mapping looks good

**Pull request merged**
