### PR TITLE
Dead Spider Sprite Fix

### PR DESCRIPTION
**Pull request by blackdragonTOW**
# About the pull request

Dead spiders had white pixels where there should be transparent pixels.

# Explain why it's good for the game

Sprite bug fix gud

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
fix: fixed spider dead sprite to not have white space (is transparent instead)
/:cl:

### CODE REVIEW

**Review by sleepynecrons — APPROVED** [review]
good fix

**Review by sleepynecrons — CHANGES_REQUESTED** [review]
actually i was a little too hasty on approving, sorry for that. after checking the other spiders they also have stray white pixels. please fix those along with the dead hunter

**Comment by blackdragonTOW** [comment]
I come in here and fix these sprites and THIS IS THE THANKS I GET? Do you have ANY idea how long it took me to remove those pixels??? At LEAST ten seconds.  Do you think anyone has ten seconds just LAYING around? Do you think -I- have ten seconds laying around? ...oh, I do actually.  Yeah that's valid. New spiders up.

**Review by blackdragonTOW — COMMENTED** [review]
New spooders up!

**Review by sleepynecrons — APPROVED** [review]
thank you for cleaning up the other two. approved [again]

**Pull request merged**
