### PR TITLE
Adds Scottish and Welsh flag support to the OOC country flag system

### PR DESCRIPTION
**Pull request by stanalbatross**
## About The Pull Request

title

## Why It's Good For The Game

Lets people from said devolved nations of the uk celebrate their regional identity 

## Changelog

:cl:
add: Added Scottish and Welsh flags to the OOC country flags system
/:cl:

### CODE REVIEW

**Comment by ondrej008** [comment]
This sends two requests instead of one, surely it could be a bit better optimized to just use one request? Though I suppose that is a minor detail.

**Comment by stanalbatross** [comment]
> This sends two requests instead of one, surely it could be a bit better optimized to just use one request? Though I suppose that is a minor detail.

probably but the code for this in IP API was stolen from a person who stole it from another person who stole it from sonewhere I don't even know so tldr I do not know how to optimise this

**Comment by stanalbatross** [comment]
> This sends two requests instead of one, surely it could be a bit better optimized to just use one request? Though I suppose that is a minor detail.

optimisation done, also this was a good thing because the service is limited to 45 requests per minute

**Comment by hotimep** [comment]
scotland buff

**Review by JeserTheFox — APPROVED** [review]

**Pull request merged**
