### PR TITLE
Hivelord repairing and QOL

### PR DESCRIPTION
**Pull request by Git-Nivrak**
# About the pull request
Hivelords now have x-ray vision and can repair doors & walls.

# Explain why it's good for the game
X-ray vision:
When building in tight spaces you can lose track of what you were trying to do in the bigger scale due to your vision range being limited, Being able to always see the entire screen makes it much easier and less of a headache.

Repairing:
It always seemed weird that you have nothing to do when walls are being shot down except wait for them to break to rebuild them, Well, now you don't have to! If this turns out to make walls and doors unbreakable cooldown / windup / plasma cost / repair amount can be adjusted accordingly.
# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl:
qol: Hivelord now has x-ray vision to make it easier to build in tight spaces.
/:cl:

### CODE REVIEW

**Review by morrowwolf — CHANGES_REQUESTED** [review]
No active heal for resin structures. It's just gonna be annoying for everyone.

I'm open to slow repair/decay of resin structures on/off weeds though but I'm talking real slow (and probably out of scope).

As long as resin whisperer can only build with regular vision/line of sight then Xray vision is fine. Otherwise, no.

**Comment by Git-Nivrak** [comment]
Removed repairing
Removed x-ray for resin whisperer as that would just be weird having to guess if something is in your LOS or not

**Comment by blackcrystall** [comment]
I have idea, make all weeds like core/cluster work like... plasma == weeds, structure have internal plasma value and use it to replace weeds, like 1 weed tile = 10 plasma and etc
and repair same, like place a new one wall, but plasma cost += cost * damage/maxhealth structure and some cd, like 5 sec, for abuse safety

**Comment by morrowwolf** [comment]
Eeeh, I've thought about this some more and I think it's strange to just have it on the one strain and not the other.

**Pull request closed without merging**
