### PR TITLE
Forest/preds/medicomp

### PR DESCRIPTION
**Pull request by realforest2001**
## About The Pull Request
Adds a medicomp to Yautja bracers, this includes a built in suture ability, and acts as a surgery tray.

## Why It's Good For The Game
Improves the dynamics of fighting with a Yautja, they no longer heal everything instantly and are disassociated with human medical equipment. Using a medicomp takes time and gives away your position afterwards.

## Changelog

:cl:
qol: Mobs with a max health over 100 will no longer appear 150% healthy, calculations are now more accurate and max out at 100%
add: Added the Medicomp to hunter bracers. It can be used to treat wounds like surgical line, and acts as a container for a full hunter surgery kit with some Thwei crystals and a medical scanner.
add: Added a version of tendwounds for the medicomp exclusively, it won't fail due to pain, but causes pain in turn. Each finished step will cause a grunt of pain from a human, or clicking from a hunter. The final step will cause a scream, or a loud roar from a hunter.
add: Added a new emote for hunters, loudroar, this is a very slightly louder version of roar, except it projects a longer distance and gives a text indicator of direction to anyone who hears it. Misuse of this emote may see it curtailed or placed on a cooldown.
del: Removed access to most hunter medical supplies outside of the medicomp. Moved the remaining supplies to the huntership medical bay.
del: Thwei no longer heals brute or burn damage.
qol: Thwei injectors now check for TRAIT_YAUTJA_TECH instead of being a Yautja.
add: Hunters now naturally heal 0.2 points of brute & burn damage per lifetick. Whilst under 50% health this increases to 0.5, and when under 20% health increases to 1. Natural heal does not function from crit.
add: Human medical supplies (Ointment, BurnKit, Gauze, TraumaKit) no longer work on mobs with TRAIT_FOREIGN_BIO.
qol: Thwei crystal verb has changed from Self-Heal Crystal to Stabilising Crystal.
fix: WARNING: The above change will break any macros made by hunter players to dispense thwei crystals. They will need to be updated.
/:cl:

### CODE REVIEW

**Comment by realforest2001** [comment]
Some bits left to do from https://gitlab.com/cmdevs/colonial-warfare/-/merge_requests/2330

**Comment by johnravioliUSA** [comment]
Speedmerge for HRP

**Comment by Shad0vvs** [comment]
Set to open when ready :)

**Comment by realforest2001** [comment]
I dearly hope that doesn't break everything

**Comment by stanalbatross** [comment]
you still have issues 
image

**Comment by realforest2001** [comment]
Aware. Wonderful rebase shit. Sigh.
Will be working on it over the weekend.

**Review by Nanu308 — APPROVED** [review]
Mapping lgtm

**Pull request closed without merging**
