### PR TITLE
Trenchcoats to CL Vendor

### PR DESCRIPTION
**Pull request by thevandie**
# About the pull request

Adds trenchcoats from Hybrisa to the CL's vendor. There's a beige and grey one. Also adds the fedoras.
I tested it thoroughly with every single role that can use the CL vendor.

# Explain why it's good for the game

More drip = more gooder, plus I've been planning this for months
# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

image
image

</details>

# Changelog
:cl:
add: Grey and Beige trenchcoats to the CL vendor
add: Brown and Black fedoras to the CL vendor
/:cl:

### CODE REVIEW

**Comment by thevandie** [comment]
merry trenchmas!

**Comment by efzapa** [comment]
61oNCVO-AFL _AC_UY350_

i'm literally him

**Comment by thevandie** [comment]
image

literally you now

**Review by kiVts — CHANGES_REQUESTED** [review]
undocumented survivor drip changes, remove or changelog them.

**Review by kiVts — APPROVED** [review]
nvm

**Pull request merged**
