### PR TITLE
linking gaining blood passively with loosing nutrition.

### PR DESCRIPTION
**Pull request by Huffie56**
# About the pull request
Renamed a variable behind the scene max_blood to normal_blood because is define is NORMAL_BLOOD.
linking gaining blood passively with loosing nutrition.
when your blood level is below normal you will :
when your nutrition >=400 you will gain 0.3 blood and loose 9 nutrition.
when your nutrition <=250 you will gain 0.1 blood and loose 3 nutrition.
before that being low on blood will make you loosing nutrition without it being link to passive regeneration...

# Explain why it's good for the game
linking nutrition to gain of blood will make more sense than just loosing nutrition and gaining blood be separated...

# Testing Photographs and Procedure
need to test it...

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
balance: when your blood level is below normal you will :
balance: when your nutrition >=400 you will gain 0.3 blood and loose 9 nutrition.
balance: when your nutrition <=250 you will gain 0.1 blood and loose 3 nutrition.
balance: when your nutrition <50 you will stop gaining blood....
/:cl:

### CODE REVIEW

**Review by BeagleGaming1 — CHANGES_REQUESTED** [review]
These are not just "code" changes, and fix your changelog.

**Comment by Huffie56** [comment]
> These are not just "code" changes, and fix your changelog.

i change them to balance:
is that ok?

**Comment by Huffie56** [comment]
forgot to test it before putting it up for review...

**Comment by Huffie56** [comment]
passive blood gain isn't working with this PR and your temperature is weird.

**Pull request closed without merging**
