### PR TITLE
Synthetron3000

### PR DESCRIPTION
**Pull request by Diegoflores31**
## About The Pull Request

This PR reworks the legacy Borg transformer and readds it to the DME making it spawnable.

The new Synthetic Generator 3000 turns resting humans forcibly into Synthetics (specifically working joe model) with weapon restrictions and no additional skills. this is clearly for Event purposes only.

Sprites will be remade after code approval.

## Why It's Good For The Game

Fixes old legacy features and makes them work with CM . 

## Changelog

:cl:
add: reworked Transformator.dm to work and changed robotization for synthetic transformation and readded it to the game.
/:cl:

### CODE REVIEW

**Comment by Geevies** [comment]
i'm not so sure about adding LRP features to the game

**Comment by stanalbatross** [comment]
conflicts

**Comment by stanalbatross** [comment]
this isn't a refactor : refactors are backend ONLY and do not change frontend functionality in any way

**Comment by Diegoflores31** [comment]
conflicts fixed 💪

**Pull request closed without merging**
