### PR TITLE
[WORK IN PROGRESS] Drone tier three [reaper is a placeholder name]

### PR DESCRIPTION
**Pull request by InsaneRed**
# About the pull request
Adds a drone tier three, this is work in progress so nothing is certain or set in stone

special building: Shield pillar, gives you 200 shield after you rest around it for x duration or so, max is 200 and it gives you 50 per x seconds it decays overtime.
ability one : 1x3 resin wall that decays overtime, temporary but unbreakable.
ability two : lob resin, throws a ball that spreads weeds around it.

# Explain why it's good for the game

drone line is the only thing without a proper tier three, this will fill that gap and give the hive more tools to deal with problems.
i'll write a better one once the project reaches its end code wise

# Testing Photographs and Procedure

https://github.com/cmss13-devs/cmss13/assets/47158596/31ab0e3c-e07e-4434-9155-d108463ff619

https://github.com/cmss13-devs/cmss13/assets/47158596/ca77ed88-4320-48f6-b7fa-55b563200de2

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl:
adds: Drone tier three, WIP
/:cl:

### CODE REVIEW

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by ihatethisengine** [comment]
Acid grenades? Movable walls?

**Comment by InsaneRed** [comment]
will be reopened once the sprites are ready

**Pull request closed without merging**
