### PR TITLE
sensortowers can now be broken by xenos

### PR DESCRIPTION
**Pull request by stanalbatross**
## About The Pull Request

xenos can now break the trijent/kutjevo sensortower

plus code cleanup

## Why It's Good For The Game

it is not good to rely on RNG for these to break if they are in xeno territory

very bullshit that xenos can retake the ground they are on but not break them

## Changelog

:cl:
add: xenos can now break the trijent/kutjevo sensor tower, it can still be repaired after being broken
code: improved the sensor tower's code for readability
/:cl:

### CODE REVIEW

**Comment by DylonBR** [comment]
maybe make it so it can only be broken by tier 3s so a marine isn't forced to waste cades and babysit the tower

**Comment by stanalbatross** [comment]
> maybe make it so it can only be broken by tier 3s so a marine isn't forced to waste cades and babysit the tower

no

**Comment by DylonBR** [comment]
> no

are marines allowed to wall the sensor tower then?

**Comment by RadiationFan** [comment]
> > no
> 
> are marines allowed to wall the sensor tower then?

Probably, sensor tower is a waste to set up 4+ Rwalls to keep out a lurker

**Comment by stanalbatross** [comment]
> > no
> 
> are marines allowed to wall the sensor tower then?

No

**Review by morrowwolf — APPROVED** [review]
Code LGTM

**Pull request merged**
