### PR TITLE
Zipcuff pouch

### PR DESCRIPTION
**Pull request by Diegoflores31**
# About the pull request

adds a zipcuff pouch for Squad Leader , it can hold 5 zipcuffs

# Explain why it's good for the game
SL.s spawn with a box of zipcuffs but they dont really have nowhere to store them . this PR aims to allow them to bring the cuffs to the AO in a more efficient way if they choose to. 
 

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl:
add: adds Zipcuff pouch for Squad leader.
imageadd: added sprites for zipcuff pouch.
/:cl:

### CODE REVIEW

**Comment by SirLambini** [comment]
Hi, may i ask if it is possible to add this to MPs vendor? It would be very usefull

**Review by harryob — CHANGES_REQUESTED** [review]
address failing ci

**Comment by Wintermote** [comment]
SL's can't sacrifice a pouch to store zipcuffs. The cuffs aren't particularly useful, and definitely not more useful than any other kind of pouch you could use.

With a toolbelt you can also store electrical wiring that can be turned into a zipcuff if necessary. Most SL's don't use toolbelts, but that's probably the best option for anyone who wants to have a zipcuff on hand without taking up extremely important storage space.

Other alternatives would probably be similar - allow cables to go in helmets, or as suit/armor attachments that can be removed. 
But a dedicated pouch just isn't going to work for SL's. This makes more sense as an option for MP's if anything.

**Comment by harryob** [comment]
ci fail not addressed, pr seems to be stale. feel free to open newly if you want to work on this again

**Pull request closed without merging**
