### PR TITLE
Brings back a number of legacy CM-SS13 features with modern takes, along with other changes

### PR DESCRIPTION
**Pull request by Binbers**
Hello. This PR is a release of a bunch of changes I played around with on my own time. I don't expect this to be merged but I'm rather leaving it up for people to take a look at. If it gets merged, great. More details below.

## About The Pull Request
Mostly made most of these while I'm hammered on weekends and when emoney reminded me CM-SS13 exists. CM13 today is NRP, feels like a top-down COD or an aliens themed MOBA, not interesting and unpaced other than the shoot em up part (or cade/cave hugging), entirely TDM focused, and incredibly predictable and linear in the gameplay loop; with playing it just entirely coming down to: for the marines "land, make a front, kill xenos, get wiped and pushed all the way back to FOB after first contact, ghost when tackled, or cadehug" and for the xenos "evo, rush and kill/cap survivors, brainlessly fortify front that gets irrelevant in minutes of marines landing unless its indestructible corners, camp in caves or hive until caps, siege FOB rinse and repeat" and most of the map staying irrelevant other than cades, tcomms, cave entrances, or resin depending on which side rushes and wipes the other's numbers out early on first.

A lot of these changes seek to bring back asymmetric gameplay, randomness (without significantly being retardedly random) as well as interesting gameplay loops along with slowing down the regular gameplay loop to ensure each rounds are meaningful, relevant, and non-linear for both marines and xenos and everything in a round not being focused on the front which is always either the FOB or caves. By bringing back some features that were originally in the game that made it so.

List of changes:

-Facepaints now cost 1 points. They're literally everywhere on the ship, and unlike every other pref gear some of which are 1 pts and actually have functionalities & kept for more than 3 seconds from spawn, are instantly thrown out after spawn

-Added latex gloves options for squad corpsmen vendors like there used to be

-Squad Technicians now get a regular helmet and welding goggles from their essential equipment, technician helmets are available to buy for 5 points (same as formerly welding goggles) replacing welding goggles. The helmet's literally better in every way, didn't make sense that worse options are avail to buy for points you need just if you wanted to go with hat drip.

-You can't multihand medical (defib, green and orange kits, bandages, ointments, and splints) anymore. Was apparently never an intended feature but nobody went to correcting it.

-Removed xenomorph spawn pooling chestbursted bodies

-Xenos can now eat chestbursted corpses (new "Consume" verb), providing 250 health and 30 evolution for a total of 4 times before the bursted body gets gibbed. Canon from avp. Right click chestbursted mob then Consume.

-Weeds will now stay even if resin nodes are destroyed. Doesn't make sense that the environment suddenly and completely changes just because one thing is destroyed, resin is supposed to change the environment not just be a gameplay thing that changes instantly. That only helped rush rounds. This will also prevent the few viable frontline for xenos being only the caves.

-Hiveweeds now have same slowdown as regular weeds

-Eggs can now be planted anywhere on weeds. Time to plant them increased (8s for all, 6s for drones, 3s for carriers)

-Removed queen gib cooldown, takes 30 seconds instead of 8 though (good luck not getting mowed down by the superspeed marines and their massive DPS that will chase you through 5 layers of resin forts to save their precious npc spec, but when ground is secured at the point where they won't be recovered you can gib everyone)

-Multiburst readded (max 4, instead of 7 as it was in old multi burst. 4 bursts are ultra rare). 40% chance of single larva, 35% chance of dual larva, and 20% chance of tri larva and 5% chance for quad larva. 3 or more larva bursts will gib the mob

-Delimb chances are slightly raised (12%) similar to pre-2020 but 2% higher to account for the fact that those times had insta delimb on first hits, otherwise now needs to be heavily damaged first since 2020. Change to 10% otherwise.

-Xeno maturity system. All xenos except the Queen which is exempt from maturity entirely, will start out young with 80% their default healths, with the first maturation being 800 ticks. However xenos can boost ticks by being active (moving around, each tiles traversed will grant an additional tick), using any abilities that cost plasma (except filling construction nodes), and slashing enemies. Being matured for the first time will put the xeno at the default stats, and upgrades so on for 2 more stages granting additional health, plasma, some attack damage, and slight movement boosts. All tiers have the same maturation counter, each stages being 800 ("Young" to default), 1600 (default to "Aged"), and 2400 ("Aged" to "Hardened").

-Grab system revamped to match old days, neck & choke grab readded. CQC skills now determine your chances at successful resist attempts. Unlike original PR/MRs its not QTE and rather the resist attempts themselves depend entirely on CQC skills (it works this time)
Original PR/MR links: https://github.com/cmss13-devs/cmss13/pull/105
https://gitlab.com/cmdevs/colonial-warfare/-/merge_requests/2849
https://gitlab.com/cmdevs/colonial-warfare/-/merge_requests/2561

-Nest resist re-added. Unlike old days where it was 2 static minutes from resist action to unbuckle, it's now RNG and how long it might take is a minimum of 8m and a maximum of 14m (basically no chance or light chance depending on your luck at mid-late stage), and unlike old days xenos in view are notified if a person resisting AND when they are able to resist out. Literally one xeno staying in the hive with reasons other than to AFK is now relevant.

This is bound to hella shake up the balance and the gameplay loop of the game, so take this PR for what you will and roast me for my undeveloped legacy coding skills :DDDD

## Why It's Good For The Game

Refer to the first ~~wall of text~~ paragraph in About The Pull Request section

## Changelog

:cl: Binbers
balance: Facepaints (except skull facepaint at 3 points) now costs 1 point in preferences gear
balance: Latex gloves added for squad corpsmen vendors. Squad technicians now get a regular helmet and welding goggles from their essential equipment, technician helmets are available to buy for 5 points
fix: Medical actions now can not be multi-handed
removed: Chestbursted corpses can not be melted down by spawn pools anymore
add: Xenos are now able to eat chestbursted bodies ("Consume" verb) which will grant health and 30 evo points per use. Bodies will be gibbed after being eaten 4 times
balance: Weeds will now stay even if Resin Nodes are destroyed
balance: All weeds now have the same slowdowns as regular weeds
balance: Xenomorph eggs now may be planted on any regular weeds
balance: Removed queen gib cooldown, takes 30 seconds instead of 8 though (good luck not getting mowed down)
balance: Multi-burst re-added, maximum of 4 larva
balance: Adjusted delimb chances
balance: Different levels of grab offer different chances for successful resisting and different CQC skillsets offer different chances for attempting resists
balance: Choke grab now deals less oxygen damage per ticks (from 3 to 2)
balance: Choke grab will not pull the puller and pullee onto the same time anymore (because you don't fireman carry someone you're choking on your shoulders). Only carry grab will now overlap the puller and pullee onto the same tile
add: Added xenomorph maturity
fix: Choke grab can now move mobs over to other tiles
balance: Warriors now have a slightly higher movement delay when they have a target lunged
balance: Warriors now can not move mobs by clicking while they are grabbed in lunge
add: Re-added resisting from xenomorph nests, resisting time being random between 8 minutes and 14 minutes. Mobs in view will be notified when someone is resisting, and when they are ready to break out
/:cl:

### CODE REVIEW

**Comment by morrowwolf** [comment]
First atomize these into smaller, individual PRs. Trying to push these all through in one pull request is going to be a huge pain for everyone involved. Second, get with a dev, preferably a game architect. Lots of these changes should have some sort of discussion beforehand on thought process.

**Comment by carlarctg** [comment]
cool shit though

**Comment by Thesoldier84** [comment]
Per our dm conversation break these up into smaller ones

**Comment by Huffie56** [comment]
please don't add resist nest it's annoying as possible to watch over caps it's mindless tackling spam work......just please don't put that back i beg of you

**Pull request closed without merging**
