### PR TITLE
Fixes xeno QDELing "currently transported" marines after missing hijack

### LINKED ISSUE #2148: Getting deleted instead of turned Forsaken on hijack takeoff deletes any mob you swallowed as well
### Testmerges

#1795, #1767, #2045

### Description of the bug

As the description says, in the rather exotic case of:

- A xeno having swallowed someone and transporting them
- The Queen taking off and triggering the hijack mechanic
- The xeno not passing a Forsaken check, meaning they get deleted instead

It the xeno happens to be transporting a marine, the Marine will be deleted as well even if they were alive and not capped. This just happened during a round and was ahelped and after some debubbing, present staff nailed it down to the above mechanic.

### What's the difference with what should have happened?

I would expect that a xeno getting deleted would just dump out its stomach contents, whatever they may be, the same they do when they get put into crit or whatever.

### How do we reproduce this bug?

1. Swallow someone
2. Get deleted by the hijack/Forsaken mechanic while having someone in your stomach

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

### PR DESCRIPTION
**Pull request by moltoretardo**
# About the pull request
Made a condition checking the content of the xeno and forcing it to throw up if not empty

# Explain why it's good for the game
Fixes #2148
I'm a free GBP enjoyer (if I did it right)

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl: Molto
fix: fixed marine qdel on hijack
/:cl:

### CODE REVIEW

**Review by harryob — CHANGES_REQUESTED** [review]
should be done in mob/living/carbon/Xenomorph/Destroy()

**Comment by moltoretardo** [comment]
> should be done in mob/living/carbon/Xenomorph/Destroy()

I globalized it like asked, but since it now applies to every instance of xeno getting QDEL'd it looks a bit silly when one jumps into the ASRS pit while holding something, since it'll jump, throw up, get deleted, marine get deleted.

**Comment by harryob** [comment]
> > should be done in mob/living/carbon/Xenomorph/Destroy()
> 
> 
> 
> I globalized it like asked, but since it now applies to every instance of xeno getting QDEL'd it looks a bit silly when one jumps into the ASRS pit while holding something, since it'll jump, throw up, get deleted, marine get deleted.

i always forget about that infernal pit. feel free to revert - that's goofy. i'll uhh refactor it later

**Comment by moltoretardo** [comment]
Reverted as asked

**Review by harryob — APPROVED** [review]

**Pull request merged**
