### PR TITLE
Resin marker for needing weeds

### PR DESCRIPTION
**Pull request by carlarctg**
## About The Pull Request

Title

## Why It's Good For The Game

I've heard people wishing they had this, it seems perfectly reasonable and will let hive leaders easily tell drones and hivelords where to weed

## Changelog

:cl: Carlarc_Kugamo
add: Added a new resin marker for needing weeds in an area.
/:cl:

### CODE REVIEW

**Comment by DylonBR** [comment]
great feature, hopefully we'll see it added within 60-90 business days

**Review by stanalbatross — APPROVED** [review]
code é fine

**Comment by carlarctg** [comment]
> Reference in new issue
> Report content

no they stay offweeds for a bit

**Review by Agameofscones — APPROVED** [review]
sprites r good

**Pull request merged**
