### PR TITLE
Shotgun Shell Pouches

### PR DESCRIPTION
**Pull request by FoxyStalin**
## About The Pull Request

Adds Large Shotgun Shell Pouches to  the vendors of Vehicle Crewmen,  Pilot Officers, DCCs, and Senior Enlisted Advisors

## Why It's Good For The Game

It's weird that these rolls don't have even the small shotgun pouches available in their vendors.  I made it large because all three of these jobs get Large Magazine Pouches for free, so,  I felt that giving them Large Shell Pouches as an option was fair.

If requested I can bump them down to normal sized, though.

## Changelog

:cl: FoxyStalin
add: Added Large Shotgun Shell Pouches to vendors for Drop-ship Pilots, DCCs, Vehicle Crewmen, and Senior Enlisted Advisors.
del: Removes Duplicate Large Pistol Mag Pouch from SEA vendors

/:cl:

### CODE REVIEW

**Comment by JeserTheFox** [comment]
Right now it adds pouch to Pilot only, you need to also add it in DCC's
`GLOBAL_LIST_INIT(cm_vending_clothing_dropship_crew_chief, list(`
at line 171

**Review by stanalbatross — CHANGES_REQUESTED** [review]
add to DCCs for consistency

**Review by stanalbatross — APPROVED** [review]
all good but can you put them in alphabetical order?

**Comment by FoxyStalin** [comment]
> all good but can you put them in alphabetical order?

Done. I also noticed SEA had two Large Pistol Mag pouches in their vendor, so I went ahead and nixed one.

**Review by stanalbatross — APPROVED** [review]

**Pull request merged**
