### PR TITLE
Rewrites burrower tremor code

### PR DESCRIPTION
**Pull request by Red-byte3D**
# About the pull request

rewrites the burrower code to be more up to date

# Explain why it's good for the game

code better better code

# Testing Photographs and Procedure
<details>

image

</details>

# Changelog

:cl:
code: rewrote tremor code
/:cl:

### CODE REVIEW

**Comment by Red-byte3D** [comment]
image

**Comment by Blundir** [comment]
make a proper CL, code improvement is still a code improvement

**Comment by cuberound** [comment]
looks like code improvement preaty good, just wonder how tremor_cooldown = 450 became xeno_cooldown = 30 SECONDS?

**Comment by Red-byte3D** [comment]
> looks like code improvement preaty good, just wonder how tremor_cooldown = 450 became xeno_cooldown = 30 SECONDS?

couldnt remember how byond ticks worked, so i mentor helped and they told me 30 seconds. i dont really play burrower but 45 seconds came off absurd for an ability like that so i just went with what mentors said

**Comment by Red-byte3D** [comment]
back to 45

**Comment by cuberound** [comment]
> > looks like code improvement preaty good, just wonder how tremor_cooldown = 450 became xeno_cooldown = 30 SECONDS?
> 
> couldnt remember how byond ticks worked, so i mentor helped and they told me the cooldown is 30 seconds. i dont really play burrower but 45 seconds came off absurd for an ability like that so i just went with what mentors said

jeh it is fine, the cooldown is quite absurd tbh, you can try changing it and mark it in the pr as balance, it would prop be fine

**Review by harryob — APPROVED** [review]

**Pull request merged**
