### PR TITLE
new dummy tablet sprite

### PR DESCRIPTION
**Pull request by ItsVyzo**
# About the pull request
adds new dummy tablet sprite - medical themed

# Explain why it's good for the game
soul and no more CO Tablet skin for Dummy Tablet

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

dreamseeker_mb8nbuL3xy

</details>

# Changelog

:cl: LTNTS
add: new dummy tablet sprite
/:cl:

### CODE REVIEW

**Comment by Birdtalon** [comment]
What's the `geiger_on` sprite that you changed?

**Comment by ItsVyzo** [comment]
> What's the `geiger_on` sprite that you changed?

I didn't even touch that q-q

**Comment by ItsVyzo** [comment]
Yeah, I never touched that aside from opening it up to check frame change seconds

**Review by nauticall — DISMISSED** [review]
Few things. See picture below comapred to the defibrillator sprite, which shares a color palette.

1. Colors (yellow) need to be consistent. In this case I think you should make the body of the sprite and the LCD screen both lighter to match the defib and provide better contrast.
2. The outline (blue) should also change in regards to lighting - it should be lighter around the top than the bottom rather than being uniform.
3. It looks too flat. You should add more prominent shading around the edges to make the tablet more 3-dimensional. Look at how the CO tablet does it in regards to the lighting towards the top - try something similar.
4. The handle (red) is too thin. I think you should make the handle similar to the CO tablet in that it's thicker and sturdier, as well as sharing a color. It would do a lot to make it look more rugged too.

I think it'd look good after these changes are made.

image

**Review by Blundir — APPROVED** [review]

**Comment by Blundir** [comment]
will merge after sprite freeze

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Pull request merged**
