### PR TITLE
Synthetic Smartgun Gadget

### PR DESCRIPTION
**Pull request by Geevies**
# About the pull request

Adds a Skeletonized Smartgun gadget to the synthetic vendor. The intent is that this weapon is given to a PFC who will be able to use it until the ammo runs out, as it cannot be reloaded.

# Explain why it's good for the game
it's good for roleplay, also it's cool as hell and i'm stealing it from A:CM, see here: https://youtu.be/8k3ivQiJa24?t=4689
# Testing Photographs and Procedure
i tested it ingame by spawning in as a pfc and using the gun

# Changelog
:cl:
add: Added a Skeletonized Smartgun kit to the Synthetic gadget vendor. This Smartgun kit can be used without training, batteries, or a harness, however, it cannot be reloaded. It's intended to be given to a PFC.
/:cl:

### CODE REVIEW

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by Detective-Google** [comment]
Could you walk me through the RP utility & intended gameplay niche of this? I keep looking over and I just don't "get" it.

**Comment by Drulikar** [comment]
The concept of unreloadable guns (as long as they don't have exceptionally more snoop capacity) may be okay, but:
- Not SG right now. It's already undergoing changes because people on both sides are unhappy with it.
- Not interested in more IFF options for marines when watchtowers are likely
- Not interested at all in this involving synths

**Comment by irakligabunia** [comment]
> Could you walk me through the RP utility & intended gameplay niche of this? I keep looking over and I just don't "get" it.

This PR was made only for high-level roleplays, keep moving.

**Pull request closed without merging**
