### PR TITLE
Provost sprites and code cleanup

### PR DESCRIPTION
**Pull request by realforest2001**
# About the pull request
Gives the provost uniforms their own sprites as only the Enforcer used the provost uniform sprite, and all others used MP sprites which contrasted with the provost jackets/armour.
Also removes a lot of duplicate code where things were subtyped and really didn't need to be.

# Explain why it's good for the game
Having all the duplicate entries, especially in the preset lists, is really clunky and useless. The only things that were being used were specially named uniforms and suits, which is unnecessary.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
imageadd: Added sprites for provost senior and marshal uniforms.
spellcheck: Gave unique names to the provost armour subtypes.
balance: Prevented most provost armour from being able to fit inside bags.
balance: Returned provost armour to the same slowdowns as MP armour.
code: Removed a lot of duplicate code in Provost presets and uniform/suits.
/:cl:

### CODE REVIEW

**Review by BeagleGaming1 — APPROVED** [review]
Code good, they spawn properly.
Someone smarter will have to look at the armor stats though

**Comment by morrowwolf** [comment]
Needs sprites, don't care about balance for admin spawn stuff, hopefully not of this is used for stupid shit (impossible with Provost)

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Review by harryob — APPROVED** [review]

**Pull request merged**
