### PR TITLE
New Weapon Sprites

### PR DESCRIPTION
**Pull request by Youtubeboy139**
## About The Pull Request

Overhauls the `weapons.dmi` file with a boatload of custom CM style sprites as well as a bonus rework of the legacy energy cutlass purely because old energy cutlass bad. Also adds the new Cutlass for the upcoming Space Pirates. Also, there were some minor code improvements as I went.
Sprite-0001
Sprite-0003
Sprite-0003sfs
sss

(NOTE: GIFs are not reflective of the final in-game product as GIF files do not support varying alpha levels)

EDIT: Added the FUBAR tool that is carried by Working Joes in Alien: Fireteam Elite
cmss13-fubar

## Why It's Good For The Game

Brings better coherency to the art style of the game by adding sprites that are more like existing sprites. Also allows for a wider range of props to be used by both admins and map makers with the refined Harpoon and Energy Cutlass/Swords.

## Changelog

:cl:
add: Cutlass sword (includes a scabbard)
add: FUBAR Multi-tool (functions as a crowbar, has strong melee damage because it's also a hammer)
fix: Minor code improvements/fixes as I went
imageadd: New butterfly knife
imageadd: New ceremonial sword holster
imageadd: New classic baton
imageadd: New energy axe (Type-78 Energized Axe)
imageadd: New harpoon
imageadd: New claymore
imageadd: New cultblade
imageadd: New merc sword
imageadd: New HEFA sword
imageadd: New stunprod
imageadd: New baseball bats
imageadd: Various minor adjustments to some existing sprites
/:cl:

### CODE REVIEW

**Comment by frozentsbgg** [comment]
Beautiful!

**Comment by neroisvcute** [comment]
Consistent with dope sprites, thanks man

**Comment by Agameofscones** [comment]
image

**Review by Agameofscones — CHANGES_REQUESTED** [review]
See annotated screenshot from above

**Pull request closed without merging**
