### PR TITLE
Pizza Time Galaxy Version 

### PR DESCRIPTION
**Pull request by Nanu308**
# About the pull request
Mapping good, mapping awesome
Sprites by Wei aka Esselnek, Mapping by Nanu, Reviewed by Spartanbobby map wise

# Explain why it's good for the game
Better and more awesome

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

awesesomepizza

</details>

# Changelog

:cl: Nanu308, Sleepynecrons
imageadd: Added new sprites for diner things such as new sofas, stool, walls, floors, tables etc. which are made by Wei aka Sleepynecrons.
maptweak: Re-did parts of the Pizza ERT base for better aesthetic looks. Done by Nanu, reviewed by Spartanbobby.
/:cl:

### CODE REVIEW

**Review by sleepynecrons — CHANGES_REQUESTED** [review]
stop ignoring my DMs and fix the sprites

**Comment by spartanbobby** [comment]
Sprites look good, LGTM

**Comment by Nanu308** [comment]
> stop ignoring my DMs and fix the sprites

I require tailored instructions ehrm kiss the ring first

**Comment by Nanu308** [comment]
> stop ignoring my DMs and fix the sprites

sorted :3

**Comment by sleepynecrons** [comment]
> > stop ignoring my DMs and fix the sprites
> 
> sorted :3

requires a review from almighty sammy

**Review by Drulikar — CHANGES_REQUESTED** [review]
T style dividers are layered weirdly if you have a tall sprite.
Water coolers are layered under dividers.
(Just saw it now) Bottles just below the water cooler mentioned are clipped under the table too.
Minor: Empty plating under windows
image

Double wide airlocks animate weirdly:
doors

**Comment by Drulikar** [comment]
Also I dunno if this is intentional, did you mean to use the couch and stool subtypes that have no buckling implemented?

**Comment by Nanu308** [comment]
> Also I dunno if this is intentional, did you mean to use the couch and stool subtypes that have no buckling implemented?

stools i could do, but couches not so much, will need some help coding and dealing with the layer for those due to the sprite hides most of people, and idk how to make a structure have two buckle points with two offsets for both unless i split the sprite in two and make it two structures

**Comment by Drulikar** [comment]
Coolers are still layered weird, airlocks are unchanged, in general most layering is worse now than before for the dividers.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Review by nauticall — APPROVED** [review]
sproites

**Pull request closed without merging**
