### PR TITLE
Brings back Agility Mode to warrior, with tweaks.

### PR DESCRIPTION
**Pull request by usnpeepoo**
## About The Pull Request

Brings back the Agility Mode ability from warrior. It gives a minor speed increase, and allows you to slash and use the Punch ability. You cannot use fling, or lunge while it is toggled. The speed is comparable to an uncloaked lurker (the lurker is still slightly faster).

## Why It's Good For The Game

Warrior as of right now is performing below average. After the double shotgun removal, slugs have been in use more commonly showing how powerful they actually are. Warrior on the other hand, has eaten multiple nerfs over time, such as bone break on punch removal, losing 60 shield and 50 points of HP, etc. Firerates and damage (HPR) for marines have also increased, and combos with loadouts (double a-grip slug/m41a) can burst a warrior over a single stun. This PR hopes to improve warriors front lining ability by bringing back its movement/semi-escape option and allowing it to contest with slug users as well as allowing warriors a form of brawling without being as slow as they are.

## Changelog

:cl:
add: Agility Mode to warrior. The ability can be toggled on and off with a cooldown.
balance: Agility mode has been tweaked to be slower, you can now use Punch with it active.
/:cl:

### CODE REVIEW

**Comment by usnpeepoo** [comment]
https://streamable.com/k496om Video of it in action.

**Comment by DylonBR** [comment]
warrior is already the best tier 2 and can cap or kill a marine on most lunges

**Comment by Waseemq1235** [comment]
based and xenomained PR, speedmerge this

**Comment by Erawh** [comment]
this is a pretty good buff imo, woyers are slightly bad at the min, maybe could do with having a strain with the agility mode worked into it instead? one that doesnt focus on capping and lunging as much as the current one does

**Comment by PhantomEpicness** [comment]
> this is a pretty good buff imo, woyers are slightly bad at the min, maybe could do with having a strain with the agility mode worked into it instead? one that doesnt focus on capping and lunging as much as the current one does

yeah, a strain would be better

woyer is only slightly bad right now and that does not warrant an entire new ability

**Comment by usnpeepoo** [comment]
> > this is a pretty good buff imo, woyers are slightly bad at the min, maybe could do with having a strain with the agility mode worked into it instead? one that doesnt focus on capping and lunging as much as the current one does
> 
> yeah, a strain would be better
> 
> woyer is only slightly bad right now and that does not warrant an entire new ability

not an  entirely new ability and setting agility mode towards a strain would require coding skills from me, or anyone who could create a working xeno strain. Bringing it back but nerfed is the best option especially since base warrior lost its only other strain, and has received only nerfs thus far.

**Comment by The-Sun-In-Splendour** [comment]
ZenaSmile
me, xeno main, seeing this pr

**Comment by The-Sun-In-Splendour** [comment]
bad pr

**Comment by Waseemq1235** [comment]
good pr

**Comment by c4xmaniac** [comment]
Idk if warrior needs lurker movement speed, it’s already a decently mobile caste. Maybe something more akin to the defenders crest ability would be more fitting for the caste and help with the slug issue.

**Comment by Carnage068** [comment]
> woyer is only slightly bad right now and that does not warrant an entire new ability

You're acting like they're giving it another shield or a second grab or something. Agility is just a toggleable small increase in speed. Jesus why the fuck is everyone overreacting so hard to this PR lol.

**Comment by usnpeepoo** [comment]
For those concernced, and as a reference, the current speed gained from agility mode with this PR is -0.5. In June 2020 (a month before it was made unique to boxer/removed from base warrior), the speed that a Young Warrior could achieve was -0.7 (faster than uncloaked lurker) and upgraded to -0.9 (Runner tier speed).

**Comment by Carnage068** [comment]
> For those concerned, and as a reference, the current speed gained from agility mode with this PR is -0.5. In June 2020 (a month before it was made unique to boxer/removed from base warrior), the speed that a Young Warrior could achieve was -0.7 (faster than uncloaked lurker) and upgraded to -0.9 (Runner tier speed).

Uh, you mean it GIVES them -0.5 speed, or with agility mode activated, their total speed is -0.5? Because giving them -0.5 speed would be like, almost doubling their speed, lol.

**Comment by usnpeepoo** [comment]
> > For those concerned, and as a reference, the current speed gained from agility mode with this PR is -0.5. In June 2020 (a month before it was made unique to boxer/removed from base warrior), the speed that a Young Warrior could achieve was -0.7 (faster than uncloaked lurker) and upgraded to -0.9 (Runner tier speed).
> 
> Uh, you mean it GIVES them -0.5 speed, or with agility mode activated, their total speed is -0.5? Because giving them -0.5 speed would be like, almost doubling their speed, lol.

Yeah I meant that.. Essentially what I meant to say was the tweak to balance agility mode is to prevent it from being what it used to be during its existence, making warrior extremely fast and making them harder to kill. the difference between -0.5 speed and a young/mature/elder/ancient warrior from previous eras of CM (maturity) is quite large and I changed it accordingly.

**Comment by Carnage068** [comment]
> Yeah I meant that.. Essentially what I meant to say was the tweak to balance agility mode is to prevent it from being what it used to be during its existence, making warrior extremely fast and making them harder to kill. the difference between -0.5 speed and a young/mature/elder/ancient warrior from previous eras of CM (maturity) is quite large and I changed it accordingly.

Okay that's what I thought LOL, I just wasn't completely sure. How much does it actual increase movement speed by? The nerfed version in this PR I mean.

**Comment by Nanu308** [comment]
Aight so, I can't see agility making it's return on the base warrior caste in it's current form, as Warrior is still quite strong and have decent mobility.

Adding in agility even when nerfed the more i think of the less i like, as i can only see issues deriving from it unless a bunch of additional checks are added on top of it to hinder using it "too much" or making it into a xeno that can simply disengage at will without any good counter .

**Pull request closed without merging**
