### PR TITLE
Reduces the size of VC text in chat

### PR DESCRIPTION
**Pull request by Bram-KEP**
## About The Pull Request
VCs now have a normal text size.

## Why It's Good For The Game
VCs having VOICE_CRTICAL despite not being a commanding role is not only bad, but the fact they often use it to contradict CICs orders is worse. this remedies that.

## Changelog
🆑 Rem1
del: VCs no longer have VOICE_CRITCAL (the largest) sized text when speaking in chat.
/🆑 

:cl:
add: Added new mechanics or gameplay changes
add: Added more things
expansion: Expanded existing mechanics or gameplay
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by Bram-KEP** [comment]
I think I fucked something up involving the changelog, oh god.

**Comment by Bram-KEP** [comment]
how fix.

**Comment by Spircen** [comment]
You can edit your PR description. On the top right corner of where the text its at. 
image
and delete the other CL section.

**Comment by Bram-KEP** [comment]
ty

**Comment by Bram-KEP** [comment]
Fun fact this entire PR is wrong, closing for now I forgot to push commits from github desktop

**Comment by Spircen** [comment]
Update your changes on your current branch, and they will reflect on this PR. Last time i saw some one do a new PR for the same change he got called out for it. 

Here: https://github.com/cmss13-devs/cmss13/pull/133

"please do not close and re-open PRs. If you have issues resolving problems on your branch, get help on the discord and do not open another PR.

If you do this again, I will just close the second PR you make"

**Pull request closed without merging**
