### PR TITLE
Synthetic Generations And Parity

### PR DESCRIPTION
**Pull request by Katskan**
# About the pull request

Suggest a trial/test first, as this is a bit of a chonker and might need tweaks with exact balance. 

This PR does 2 main things, and contains a few tweaks.  

The first is by making synthetic generations mechanically different. Regardless of if you are ship or colonial, you can still choose your generation however generations are mechanically different with G1 and G2 having a more robust construction with G2 now having full customizable appearance, and G3 having greater speed but being more fragile. The generation types are what differentiate the physical characteristics, rather than ship vs colony.

The second main thing is that synthetics are represented as being competent and loyal, instead of simply having massive mechanical advantages in medicine over humans they are instead more able to deal with poor conditions but for example a doctor in ideal environment of an operating room has the same speed as a synthetic. 

To recap, a synthetic player can choose their generation 1, 2 or 3 regardless of being on the ship or a survivor and have the skills and physical traits based on generation rather than slot. Generation 1 and 2 are exactly the same except G2 has cosmetic choices like G3 has and G1 has the white skin and color changing eyes. G1/2 have more health, more damage resistance, slower speed, less stun resistance. G3 has less health, less damage resistance, faster speed, and more stun resistance.

# Explain why it's good for the game

This should help a bit with enabling people to RP as the character they want which will make playing survivor synthetic more interesting, and taking some of the focus off of being massively medical by changing medical/surgical skill to reflect being competent in the role instead of giving a magical bonus to medical 4 and surgery 3. Instead, there's tiered bonus given to medic and doctor level training which is lesser, and no extra bonus for medical 4, and surgery 3 no longer gives a 40% speed bonus but instead deals with the debuffs applied by improvised tools and poor surfaces. The end result is that the G1/2 won't have as noticeable difference in medical actions, and their primary purpose for tasks such as heavy construction, EVA work and hazardous engineering work is reflected in an increase to engi skills. 

# Testing Photographs and Procedure

Booted and tested on private server successfully.

# Changelog

:cl:
balance: Synthetic G1 and G2 now have colonial construction
balance: Synthetic G3 retains lighter construction
balance: G3 synthetic hp reduced from 150 to 125
balance: G3 synthetic brute resistance reduced from 50% to 35%
balance: G3 acid blood dodge chance increased from 25% to 35%
balance: G3 has a higher chance to bodyslam but weaker slam, G1/2 has a lower chance but a stronger slam
balance: G1/2 has leadership skill now
balance: G1/2 acid blood dodge chance reduced from 25% to 20%
balance: Gives body slam to G3 instead of G1/2, reflecting their superior agility instead of robust construction
balance: Gives medic level medical training 25% speed reduction
balance: Gives doctor medical level 50%
balance: Reduce medical level 4 speed from 75% reduction to 50%
balance: Removes surgery level 3 speed bonus, replaces with reducing penalties for poor tools/surfaces by 75%. A doctor in an OR is the same speed as a G3 synthetic in an OR, but slower when using portable beds or poor tools. 
code: Synthetic G2 now has customizable appearance like G3
code: Synthetic Generation now same between ship and colony
/:cl:

### CODE REVIEW

**Comment by Skatuk** [comment]
A synthetic should be worse than a the heads of their departments I.E CMO or CE

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by InsaneRed** [comment]
my only problem with this is i dont think G1 should lose pounce, if we're trading skills for basically no tankyness then what is the point?

**Comment by Zonespace27** [comment]
Thank you for the PR, but I will be closing it. This PR is massively unatomized and I am additionally uninterested in a large portion of the proposed changes.

**Pull request closed without merging**
