### PR TITLE
Fix eviscerate

### PR DESCRIPTION
**Pull request by kalazus**
# About the pull request

Forbids use of eviscerate without at least 4 rage. As alternative (to prevent it being "remove" pr), can make first 3 instant /almost instant (they have almost no damage and remove all available rage to stun in 3x3 range), but it will be buff vs small groups.
A bit of clean up of not used variable related to eviscerate.

# Explain why it's good for the game

Noobs like me would die less from accidental/just bad use of eviscerate.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
balance: removes levels of eviscerate below 4th (levels with mostly negative impact as ability)
/:cl:

### CODE REVIEW

**Comment by private-tristan** [comment]
This... isn't a fix??

**Comment by GoldenDarkness55** [comment]
Not a fix and attempted better in https://github.com/cmss13-devs/cmss13/pull/5156 since locking it till rage 5 makes more sense with better visual clarity for marines that the rav can eviscerate.
https://github.com/cmss13-devs/cmss13/pull/3992 was an attempt at getting rid of the selfstun trap and balancing it aswell.

**Comment by kalazus** [comment]
Wow, 3 attempts to remove cancerous mechanic and not approved... First 3 levels deal less than hand attack in range of hand attack and stuns yourself for at 1.5 seconds...

**Comment by Red-byte3D** [comment]
ever thought about looking at your rage counter or counting your slashes

**Comment by JustLat** [comment]
or better yet just look at the black outline around ur rav when ur max rage

**Comment by ihatethisengine** [comment]
I can't look at numbers mid-combat, color outline is not the greatest indicator either as a lot of things are happening on your screen and it's not very convenient to check if your color is dark enough or just red or whatever. 

Also missclicks genuinely happen and while it is indeed a skill issue, the punishment is way too harsh, only other comparable example of an ability that roots you in place and can fuck you over very badly is fortify (also annoying but arguably not as problematic since it's a fourth ability that people usually bind to something not so easily accessible).

**Comment by Nanu308** [comment]
This is not a fix so removed the label, this is a balance change and merely adds more handholding, if anything from the code perspective it's intended for you to use at all levels, of course then way less effective at the early ones.

Not in favor of this currently.

**Comment by kalazus** [comment]
> way less effective at the early ones

"First 3 levels deal less than hand attack in range of hand attack and stuns yourself for 1.5+ seconds to stun enemy for 1 second..."

They aren't less effective; they have negative impact as ability. So, what about setting windup as 1 instead of 2-(item from windup reduction list)? At least first already useless levels won't stun you for ~2 seconds.

**Comment by harryob** [comment]
this pr has been do not merge for 3 weeks, please discuss with nanu to remove the block and address any required changes, this can then be reopened.

**Pull request closed without merging**
