### PR TITLE
Removes hunter games code

### PR DESCRIPTION
**Pull request by Zonespace27**
# About the pull request

Removes all code associated with hunter games.

# Explain why it's good for the game

The gamemode is entirely broken and hasn't been properly touched in _years_. If someone wants to rework it, they can readd the code then. In the meantime, I'm removing the code to make adding the OD3203 pragma easier.

### CODE REVIEW

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Review by Nanu308 — COMMENTED** [review]
Mapping changes are lgtm

**Comment by Drulikar** [comment]
See all the config errors and runtimes

**Pull request closed without merging**
