### PR TITLE
Linked LZ Adjustments and Remote Queen Boosted Building Restrictions

### PR DESCRIPTION
**Pull request by Drulikar**
# About the pull request

This PR is a follow up to #7363 and #7376 where the linked_lz area var has been adjusted on all maps in rotation. This required area changes on Shivas (fix misplaced areas) and Trijent (cut tcoms area and made a new area).

Queen boosted remote building is now prevented in linked_lz areas. This can help with remote building being used heavily against survivors, but likely won't have a large impact unless the lz gas proves removeable (I will be exploring it next).

# Explain why it's good for the game

All maps need to have properly set up LZ linked weed restricted areas so that weeds can be properly removed/prevented when marines land. Chances Claim for example wasn't using the mechanic at all.

Queen remote building is primarily intended to establish a foothold when it is in its boosted state. If the LZ linked weed restricted areas mechanic would just be destroying her structures anyways, its best to prevent this while also letting up the queen's pressure on survivors at least on certain parts of the map.

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Chances
Chances2
Fiorina
Fiorina2
Kutjevo
Kutjevo2
LV624
LV624_2
Shivas
Shivas3
Solaris
Solaris2
Soro
Soro2
Trijent
Trijent2
Varadero
Varadero2

</details>

# Changelog
:cl: Drathek
balance: Queen remote building (while boosted) is now prevented in LZ linked weed restricted areas
balance: Adjusted/added LZ linked weed restriction areas on all maps in rotation
maptweak: Fixed misplaced areas on Shivas.
maptweak: Split the Telecoms Valley area to make a Security Valley area on Trijent.
/:cl:

### CODE REVIEW

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Review by Nanu308 — APPROVED** [review]
Good area tweaks and changes, plus good catches on the bugged areas 👍

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by BOBAMAx** [comment]
This doesn't prevent queen from remote weeding in `linked_lz` areas but from a sample size of 1 round queen seems to focus more on using boost to build backline defenses instead of focusing only on survs.

**Comment by Drulikar** [comment]
> This doesn't prevent queen from remote weeding in `linked_lz` areas but from a sample size of 1 round queen seems to focus more on using boost to build backline defenses instead of focusing only on survs.

I intentionally did not prevent remote weeding.

**Pull request merged**
