### PR TITLE
Changes old donator kit sprites.

### PR DESCRIPTION
**Pull request by SASoperative**
# About the pull request

This pull replaces extremely old outdated donator sprites with a new donator armor set.

# Explain why it's good for the game

Removes old sprites from years ago and replaces them with up to date sprites that are more in line with current marine armor.
Removed old sprites not in use, all sprites were owned by me and not in use.

# Testing Photographs and Procedure
<details>

VCNNiQYucAAAAASUVORK5CYII

</details>

# Changelog
:cl:
code: Updated donator items
imageadd: Added new donator sprites
imagedel: Removed old unused sprites
/:cl:

### CODE REVIEW

**Comment by TheManWithNoHands** [comment]
My guy, you made the fallout new vegas armor into a completly diffrent set of armor.
Like, donor armor is custom. Its not meant to fit regular gameplay but are a reward for kind people keeping the server afloat with money.

Like, its a good sprite. A very good one. Just doesnt look like a NCR ranger, that someone basicly paid for, at all.
At least ask em.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by SASoperative** [comment]
Yeah, I can do that once I change it, I have to update it for the merge conflict. I am just waiting to hear back from Forest on what they want/need before I make changes.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by SASoperative** [comment]
As per request, armor name has been changed, and old sprites, and unused sprites have been deleted per Forest2001 
Fixed merge conflict

**Comment by frozentsbgg** [comment]
Approved for donator sprite changes

**Review by Blundir — APPROVED** [review]

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Review by Zonespace27 — APPROVED** [review]

**Pull request merged**
