### PR TITLE
Expands LV Fog To Most Maps

### PR DESCRIPTION
**Pull request by Steelpoint**
# About the pull request

This PR adds LZ fog to most maps, akin to how it functions on Chances Claim. The fog will remain in place until 15 minutes have elapsed. 

This PR also adds a slight change to Big Reds' LZ1 to slightly expand the area that can be weeded by the main LZ, mostly to give attacking xenos more resin cover to assail the meta survivor hold area. 

All changes to maps, or lack of changes, are noted here.

- 624 : No fog changes due to the general design of the landing zones makes it either impractical or unnecessary to add fog. 
- Soro: North LZ has been fogged, south LZ has no fog due to its isolation and lack of defensive ability. 
- Fiorina: Eastern LZ has a set of fog covering comms area. 
- Solaris: Northern LZ has fog covering area, plus garage. 
- Trijent / Kutjevo / New Vara: Both LZ's have fog

# Explain why it's good for the game

Fog has two main factors, it helps discourage xenos from wanting to enter the LZ, and it discourages survivors from taking defence in the highly defendable, and unweedable, landing zones. This change expands this feature to cover most maps. 

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl:
mapadd: Most maps now have fog that covers the landing zones, dissipates after 15 minutes. 
mapadd: Slightly expanded the area weeds can be placed on Solaris near LZ1. 
/:cl:

### CODE REVIEW

**Comment by LC4492** [comment]
Why not make the fogs in desert maps be "sandstorms"? Would fit them well more

**Comment by fira** [comment]
ARgh, please no, have you ever heard of lockdowns

**Comment by Steelpoint** [comment]
Effected some changes based on feedback

Removed south LZ2 fog on Solaris, and expanded LZ1's fog to cover garage. 
Added fog to eastern LZ on Fiorina covering the comms area.

**Comment by Steelpoint** [comment]
I've moved the truck in garage out of there and into the nearby comms area, so survs can still access it if they get the chance.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Pull request closed without merging**
