### PR TITLE
Yautja Rework Holder

### PR DESCRIPTION
**Pull request by realforest2001**
**Please do not close without consulting myself or one of the maintainer managers.**
# About the pull request
**DISCLAIMER: This PR is solely for testmerging, it is an amalgamated version of all the atomized PRs in the milestone.**

- #3456 
- #3455 
- #3757 
- #3877 
- #3878 
- #3906 
- #3907 

# Explain why it's good for the game
# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl:
add: Adds many Yautja QOL updates. See above
/:cl:

### CODE REVIEW

**Comment by realforest2001** [comment]
Replacing 3879

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by realforest2001** [comment]
Can be closed on merge of #3906

**Pull request closed without merging**
