### PR TITLE
Changes briefing room chairs to squad themed, stationary ones.

### PR DESCRIPTION
**Pull request by silencer-pl**
## About The Pull Request
Adds sprites (recolored by ScarletReign) and definitions for squad themed comfy chair variants - these come with their own, squad themed descriptions, but behave like other comfy chairs otherwise - they are stationary, cannot be picked up, but can be wrenched and/or rotated.

Adds said chairs to construction options for metal sheets, costs 2 sheets like other comfy chair variants.

Replaces all chairs in the briefing room with said chair variants.

## Why It's Good For The Game
The aim of this PR is to amplify the more serious expected tone of Briefing Room briefings and removes one of the main sources of disruptive behavior during such. Officers who wish a looser, potentially chair fight including briefing can still opt to do them in the hangar or wherever else within SOP. This removes the ever present chair distraction from the Briefing room and is planned to go along with stricter OOC enforcement of order in briefing room briefings in particular.

As an added bonus adds more squad themed touches and a thematic wink towards all four squads which is good for overall atmosphere of the server.

## Changelog

:cl:silencer_pl, ScarletReign
imageadd: Added squad color themed comfy chair variants.
add: Squad themed chairs can now be constructed for 2 metal each.
add: The briefing room now uses squad themed, stationary chairs.
/:cl:

### CODE REVIEW

**Comment by hotimep** [comment]
LRP NERF???

**Comment by MusselMain** [comment]
> LRP NERF???

Naw, more like a LRP/HRP dividing, I think this will be better, as marines can still be funni LRP in the hanger, but HRP command can tell everyone about their cool operation in the briefing.

**Comment by silencer-pl** [comment]
> > LRP NERF???
> 
> Naw, more like a LRP/HRP dividing, I think this will be better, as marines can still be funni LRP in the hanger, but HRP command can tell everyone about their cool operation in the briefing.

Yes, this is it in essence, this PR and tightening of briefing room brief enforcement on the staff side is meant to achieve the same thing in essence - Commanders who want a quiet/orderly briefing pick the briefing room where decorum is enforced, by both removing the temptation and ooc consequence. Commanders who don't or want to try something different can hold briefing literally anywhere else where neither of the above holds true.

**Comment by c4xmaniac** [comment]
Super epic speed merge, massive reduction in me blowing peoples brains out for fucking around with chairs and finding out

**Comment by PhantomEpicness** [comment]
image
these chairs?

**Review by thwompa — APPROVED** [review]
sprites r good

**Comment by neroisvcute** [comment]
As much as I like briefing fights this is good for CO’s. Serious ones can have no chair shenanigans while fun ones can do hanger or basketball court.

**Review by Nanu308 — CHANGES_REQUESTED** [review]
Fix the Corner.
bilde

Rest is lgtm 👍

**Review by Geevies — APPROVED** [review]

**Pull request merged**
