### PR TITLE
Removes almost all silicon code

### PR DESCRIPTION
**Pull request by fira**
# About the pull request

Removes every non-synth non-organic mob code and any related items and backend. 

Okay i lied, we get to keep ARES..... ARES' cool.

# Explain why it's good for the game
Less code bloat. It was about time we did this...

# Testing Photographs and Procedure
Game isn't on fire when starting it. Does that mean everything works? We'll know in TM.

# Changelog
:cl:
del: Removed AIs.
del: Removed Cyborgs.
del: Removed Maintenance Drones.
del: Removed Camera chunking for AIs, and all associated dynamic updates.
del: Removed Robotic equipment items.
del: Removed Robotic and AI transformation tools.
del: Removed Robotic Transformation Disease.
del: Removed Nanites. Roburgers are now all safe to eat.
del: Removed functionality from AI machinery and AI card. They're props now.
/:cl:

### CODE REVIEW

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by Birdtalon** [comment]
Ideally we should TM this and see if anything unintended breaks.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Review by harryob — APPROVED** [review]
ss13 codebase free of borg code what a miracle

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Pull request merged**
