### PR TITLE
FIx Adding an ATM into brig.

### PR DESCRIPTION
**Pull request by Huffie56**
# About the pull request
add an ATM into brig so that MP can retrieve cash for prisoner to use in jail.
moved a medical vendor east of where ATM is.

# Explain why it's good for the game
Able prisoner to gain acces to cash.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

image

# Changelog

:cl:
add: Added an ATM in brig and move the med vendor that where at is place east
/:cl:

### CODE REVIEW

**Comment by Huffie56** [comment]
fixing issue https://github.com/cmss13-devs/cmss13/issues/1825

**Review by morrowwolf — CHANGES_REQUESTED** [review]
I don't oppose an ATM in the brig but I do oppose moving the nanomed into the brig airlock and away from the medical section. Throws the feng shui off. Find another spot for it please.

**Comment by Huffie56** [comment]
> I don't oppose an ATM in the brig but I do oppose moving the nanomed into the brig airlock and away from the medical section. Throws the feng shui off. Find another spot for it please.

image
i can remove the blue one and don't had it on another place since their is two other at the red spots....

**Comment by Huffie56** [comment]
closing and reopening a new one since i succefully bugged out the branch...

**Pull request closed without merging**
