### PR TITLE
Removes IO Squad Prep Access

### PR DESCRIPTION
**Pull request by joookschad**
# About the pull request

Removed IO squad vendor access.

# Explain why it's good for the game

Things in the limited vendors should go first and foremost to squad roles, not IO's who are too lazy to go to Requisitons. 
Sick of seeing IO's roundstart rush to marine prep to grab all the AP while they can go to req and get the same amount - they spawn in uniform and fed, so they can make their way there first anyway.

# Changelog
:cl:
del: Removed IO squad vendor access. They can still use standard vendors for cosmetics and uniforms.

/:cl:

### CODE REVIEW

**Comment by Tsurupeta** [comment]
They will lose access to uniform vendor, as well as 2 vendors with misc. things like fire extinguishers. Meaning, they won't be able to take any simple pouches, extra medicine, alternative armor, black gloves, etc.

**Comment by TheManWithNoHands** [comment]
As stated before, IO having prep access has reasons. Mainly being not having 20 million copys of he same vendor.
If you want to stop IOs from stealing Squad gear, expand the IOs private prep room/vendors as well.

**Comment by joookschad** [comment]
Squad gear belongs to the squad. IO's should use requisitons. I added back access to the basic vendors like the uniform one for cosmetic reasons.

**Comment by neeshacark** [comment]
feels like a better solution would just be to lock IO out of using the 6 actually important vendors in squad preps and only letting them use the gun/ammo + uniform vendors, which are both the farthest from limited in their contents

**Comment by joookschad** [comment]
I am not going to indulge in this conversation as you are unable of reading code

**Comment by TheManWithNoHands** [comment]
> I am not going to indulge in this conversation as you are unable of reading code

You mean the code change that allows IOs to access the uniform vendor and weapons rack in squad prep, wich you stated to be only a change for decorational purposes, wich i mentioned and why seeing it only as decorational is the problem?

**Review by harryob — APPROVED** [review]

**Comment by harryob** [comment]
he's right, this preserves access to the weapons racks and uniform vendors

**Pull request merged**
