### PR TITLE
Gromit Mug

### PR DESCRIPTION
**Pull request by Geevies**
## About The Pull Request

Gromit Mug

## Why It's Good For The Game

Gromit Mug

## Changelog

:cl: Reisyn, Geeves
add: Gromit Mug
/:cl:

### CODE REVIEW

**Comment by Joelampost** [comment]
YES YES YES

**Comment by spartanbobby** [comment]
gromit mug

**Comment by NuggetsOnToast** [comment]
This is a big W for the CM community. Speedmerge this now!

**Comment by SuprisedBaby** [comment]
717aBTetl8L _AC_SX466_
This MR btw

**Comment by ElFuente** [comment]
+1, its a game changing, immersive and it will increase the rp standards of the server.

**Comment by JohnDoe50974** [comment]
GROMIT MUG

**Comment by FlamermanGrills** [comment]
Whooo let's gooooooooo
Fucking love gromit mug!!!

**Review by stanalbatross — APPROVED** [review]

**Comment by Zangeiti** [comment]
MERGE QUICK, BEFORE NANU COMES BACK FROM VACATION

**Comment by stanalbatross** [comment]
LRP though

**Review by stanalbatross — CHANGES_REQUESTED** [review]
remove from almayer

**Comment by hotimep** [comment]
I HATE DUMB STUPID MUGS!!! IT'S NOT EVEN A CM MEME!!! This STUPID DOG has caused THOUSANDS of LRP minor events, led to A LOSS OF RP and resulted in MASS OOC IN IC. We cannot allow it to live on the repo  and as such I am asking you to DENY this pl and remove it ENTIRELY. Woe the day that yet another ooc meme is added to CM again.

**Comment by Nanu308** [comment]
too lrp mr geeves, i spokme with monky...

**Comment by LegateBebranius** [comment]
we should re-open it

**Pull request closed without merging**
