### PR TITLE
Synthetic Vendor Additions

### PR DESCRIPTION
**Pull request by Misttyy**
## About The Pull Request
Synthetic Vendor Additions.

Adds a number of items previously missing from the Synthetic Vendor. Items vary from engineering, medical and aesthetic choices. Points discussed with Stan, items reviewed through Jakks.

- Machete Pouch
- Tool-Vest
- Machete Scabbard
- M-M Pouch
- Small RTO Pack
- C4
- Hi-Cap Blowtorch
- USCM Medical Uniform
- RO Cap
- RO Jacket
- MP Ball-Cap
- SO Cap

## Why It's Good For The Game

Synths no longer have to steal req's C4.

Ball-Cap added since it is a common synthetic stylistic choice, and we already have the MP beret in our vendor. QOL change cutting down on time running to the brig for a hat.

RO apparel is already the default on WO, I thought I'd make it an option for normal maps too. SO cap is another common choice, this change makes it so synthetics don't have to grab one from SO lockers every round.

## Changelog

:cl: Mistfrag
add: C4 (3), Machete Scabbard (2), Machete Pouch, M-M Pouch, Small RTO Pack (12), RO Cap (12), SO Cap (12), RO Jacket (12), Ball-Cap (12), Hi-Cap Blowtorch (4), Industrial Blowtorch (2), USCM Medical Uniform
(Indicative of point cost)
/:cl:

### CODE REVIEW

**Review by Shad0vvs — APPROVED** [review]

**Comment by Misttyy** [comment]
Thanks to Shaddeh and Morrow for helping me fix a few VSC errors.

**Comment by usnpeepoo** [comment]
give it up for synth buff #3066548

(joking though synths are awesom)

**Review by Shad0vvs — APPROVED** [review]

**Review by Shad0vvs — CHANGES_REQUESTED** [review]
code/game/machinery/vending/vendor_types/crew/synthetic.dm, line 263, column 125:
error: got ',', expected one of: operator, field access, ';'

**Comment by Misttyy** [comment]
> code/game/machinery/vending/vendor_types/crew/synthetic.dm, line 263, column 125: error: got ',', expected one of: operator, field access, ';'

made another commit to try and fix

**Review by Shad0vvs — APPROVED** [review]

**Comment by AnCopper** [comment]
Use external programs like VSC and gitkraken in the future instead of webedits in order to avoid this and make it easier for yourself.

> > code/game/machinery/vending/vendor_types/crew/synthetic.dm, line 263, column 125: error: got ',', expected one of: operator, field access, ';'
> 
> made another commit to try and fix

**Comment by Misttyy** [comment]
> Use external programs like VSC and gitkraken in the future instead of webedits in order to avoid this and make it easier for yourself.
> 
> > > code/game/machinery/vending/vendor_types/crew/synthetic.dm, line 263, column 125: error: got ',', expected one of: operator, field access, ';'
> > 
> > 
> > made another commit to try and fix

Sounds good! I'm doing all on the job learning with coding so.

**Pull request merged**
