### PR TITLE
HPR Buff v2

### PR DESCRIPTION
**Pull request by Geevies**
## About The Pull Request

Lowered the HPR's fire delay to be the same as the SG, increased the burst amount by one, and upped the bass and lowered the treble of the firing sound.

## Why It's Good For The Game

HPR, as an LMG, should shoot fast and long like LMG.

## Changelog

:cl:
balance: The HPR now has the same firedelay as a smartgun, and has one more bullet in its burst fire.
soundadd: Increased the bass and lowered the treble of the HPR shoot sound.
/:cl:

### CODE REVIEW

**Comment by FlamermanGrills** [comment]
💪💪💪💪💪

**Comment by JohnDoe50974** [comment]
The smartgun with no iff?!?!?!
(Looks fine to me)

**Comment by usnpeepoo** [comment]
ok now nerf bipods 😈

**Comment by Sargeantmuffinman** [comment]
Do you mind adding this PR code https://github.com/cmss13-devs/cmss13/pull/22 to yours?

I'd make the HPR more viable.

**Review by stanalbatross — APPROVED** [review]
code é fine

**Pull request closed without merging**
