### PR TITLE
M4 Synthetic PMC 'armor' changes

### PR DESCRIPTION
**Pull request by QuickLode**
# About the pull request

Basically M4 PMC Synthetic 'armor' stated it offered 'maximum protection' even though it offers quite literally 0. Furthermore this complete lack of protection does not constitute the 20% slowdown netted.

So I'm fixing the description to state clearly that there is NO ARMOR OFFERED and furthermore, lowering it to a 10% slowdown(Justified by having 1 extra storage space?). I think this is a step in teh right direction for now.

10% comes from a new category called SUPERLIGHT which will be used for this only atm. May go to other stuff later.

# Explain why it's good for the game
Description should match what an item offers and not be misleading. If it says it has armor - it should have armor. If it isn't gonna have armor, it shouldn't say so.

Next, 20% slowdown is A HUGE price for 1 single storage slot. Its almost ridiculous. Hopefully 10% is better :) 

Next, people said the armor looks fat on the side so I slimmed it by 4 pixels.(1 column)

# Testing Photographs and Procedure
<details>
<summary>[Screenshots & Videos](https://cdn.discordapp.com/attachments/777257424590995466/1165287130080215060/image.png?ex=65464d35&is=6533d835&hm=7124d336618ce31ead8398615fcf3903c4ecc1cc8d646aa2604d877e89ff2276&)</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl:
add: SUPERLIGHT armor category.
balance: M4 Synthetic Armor slows by 10% to justify having 1 extra storage slot.
spellcheck: Clarifies M4 Synthetic Armor description that it does not have any armor whatsoever.
/:cl:

### CODE REVIEW

**Review by Zonespace27 — APPROVED** [review]
Balance fine. Will not approve this for the utility vest for USCM synths.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Pull request closed without merging**
