### PR TITLE
Revert "Changes to EZ Autoinjectors (#4167)"

### PR DESCRIPTION
**Pull request by Git-Nivrak**
This reverts commit 49e512e5391707b1e1ad71181c9c170ec72acedc.
# About the pull request

# Explain why it's good for the game
The original PR had no proper reasoning
Either way waiting 5 seconds to use an injector is not good for the game and does not add anything and being able to use it without delay isn't incredibly broken either.

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl:
balance: Reverts changes to EZ Autoinjectors
/:cl:

### CODE REVIEW

**Comment by Drulikar** [comment]
> The original PR had no proper reasoning

It is in line with the project direction: https://forum.cm-ss13.com/t/maintainer-update-jun2023/2922
> First, we’d like to see rounds “slowed down”. Speed rounds are generally not satisfying for anyone. The average length we’d like to see is around 90-120 minutes. Thankfully, we already do a fairly good job on this but keeping it consistent and minimizing speedruns is going to be a priority. Giving time for more roleplay elements to thrive and evolve is important.

> Second, any additions to complexity for medical are likely to be approved. Our current system is pretty barebones and the skill/knowledge ceiling gives something to be desired for our more veteran players. This doesn’t explicitly need to be in the form of “realism.” The goal is to give more without making it impossible to understand. We plan on slowly introducing these new concepts and ideas so community knowledge can propagate nicely.

Also its goofy to be capturing a marine and then its injection sfx, injection sfx, injection sfx, injection sfx, injection sfx. Still other ways to easily OD, and a medic could still do the same, but its still a step in the right direction.

How does this increase medical complexity/roleplay? Well it increases the reliance on medics taking care of marines rather than marines just self medicating themselves. Its only 3 shots per though: except they're refillable groundside in many locations.

> Being able to use it without delay isn't incredibly broken either.

Then you should be indifferent to the change. This really needs to be a more compelling argument.

**Comment by Git-Nivrak** [comment]
> Then you should be indifferent to the change. This really needs to be a more compelling argument.

I don't see the reasoning here, Maybe I wasn't clear - I meant that being able to use it without delay doesn't hurt the game so the delay is redundant.

The project direction lines you quoted are rather ambiguous and can fit in both how the game stands and how it will be after this revert.

As for the goofy part, yeah it might seem weird to see someone injecting quickly but "goofy" is not what the game is balanced around - It doesn't mean this has to be fully reverted, but it in it's current state it's just bad.

**Comment by Cthulhu80** [comment]
this pr will start a civil war.

**Comment by Steelpoint** [comment]
Not even a day and people are trying to revert Morrow's changes.

**Comment by Superreallycoolguy** [comment]
morrow leaves and the vultures swarm! so sad!

**Pull request closed without merging**
