### PR TITLE
Almayer Mapping:  Psychiatric Care Unit

### PR DESCRIPTION
**Pull request by spartanbobby**
# About the pull request

This PR adds a new room to the upper medical "Psychiatric Care Unit" deeply inspired by alien Dark descent this area aims to provide a place for the stressed marine to unwind

This RP also rearranges the upper medical to accommodate this new room

jRi0vtt
https://i.imgur.com/QIYsiOz.png
https://i.imgur.com/MGY6GTe.png

# Explain why it's good for the game

The room serves as both a neat nod to dark descent as well as a place for potential roleplay to accure, CMO conducting psychological evaluations for the MPs, marines stressed from the retreat from the planet trying to unwind quietly or just somewhere to relax before briefing 

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl: SpartanBobby
maptweak: Rearranges Almayer Upper Medical to accommodate a Psychiatric Care Unit
/:cl:

### CODE REVIEW

**Comment by vero5123** [comment]
brilliant.

**Comment by cuberound** [comment]
jungle room with white walls white lights and xneo plushie, I would go crazy in there even when sane

**Review by Drulikar — CHANGES_REQUESTED** [review]
Please find a place to move the `/obj/structure/closet/secure_closet/professor_dummy` to. There is now no longer one mapped into the Almayer w/ the removal of the CMO office.

**Review by Drulikar — APPROVED** [review]

**Review by Nanu308 — APPROVED** [review]
rp update

**Pull request merged**
