### PR TITLE
Replaces the MK-221 Riot shotgun with the ES-7 V2

### PR DESCRIPTION
**Pull request by IroquoisLou**
# About the pull request

Second attempt at https://github.com/cmss13-devs/cmss13/pull/6836, accidentally closed it.

# Explain why it's good for the game

The MK221 riot gun is just a blue coloured version of the Mk221 that can only fire 20ga beanbags very slowly, a Mk221 with 12ga beanbags could fulfil it's use and would be much more useful, the Mk221 riot gun also has a UGL meaning that the MP's have no use in using the special grenade launcher meant for them, the ES-7 on the other hand is faster firing and has more ammo but can't have an underbarrel grenade launcher, encouraging MP's to use the Special grenade launcher and giving MP's a more unique riot gun.

# Testing Photographs and Procedure

<details>

image
image
image
image
image

</details>

# Changelog

:cl:
add: Added the ES-7, a fast firing Non-lethal shotgun and it's sprites
del: Removed the MK221 Riot gun.
imageadd: added ES-7 ammo and gun sprites
imagedel: Replaced MK221 Riot gun sprites and 20ga beanbag ammo sprites with ES-7 ammo and ES-7.
maptweak: Changed the nightmare inserts with MK221 shotguns to having the updated ES-7
/:cl:

### CODE REVIEW

**Review by realforest2001 — APPROVED** [review]
Code is fine

**Review by Blundir — CHANGES_REQUESTED** [review]
Find some better sprite for the projectile, otherwise looks fine

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Pull request closed without merging**
