### PR TITLE
Cbrn marines

### PR DESCRIPTION
**Pull request by Moonshanks**
# About the pull request

# Explain why it's good for the game
# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl:
add: Added something
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
spellcheck: fixed a few typos
ui: changed something relating to user interfaces
code: changed some code
refactor: refactored some code
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
mapadd: added a new map or section to a map
maptweak: tweaked a map
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by Moonshanks** [comment]
to add:

> CBRN suit stops ignition on user, when hood and mask is equipped with armour
> CBRN suit variants force change the hood and mask icons to the right version
> Remove squad overlay on armour

**Comment by cm13live** [comment]
This pull request has been mentioned on **CM-SS13**. Please provide feedback here:

https://forum.cm-ss13.com/t/cbrn-marines/2635/12

**Comment by Moonshanks** [comment]
That cat larva fix I made months ago is still haunting my fucking repo for some god forsaken reason. I've pulled from master so many times WHY???

**Comment by Moonshanks** [comment]
Pulling from upstream does not fix the cat problem... please... please github

**Pull request closed without merging**
