### PR TITLE
Issacs Lament (WIP)

### PR DESCRIPTION
**Pull request by Warfan1815**
# About the pull request

Monkeyfist's Isaacs Lament map, now brought to life!

(I'll add a bunch more detail later)

# Explain why it's good for the game

# Testing Photographs and Procedure

# Changelog

:cl:
add: adds defines to the plain wood objects, the hedge, and slightly modifies wood mineral door code.
imageadd: added plain versions of the wood objects, updated the wood mineral door, and added a hedge sprite.
mapadd: adds Isaacs Lament
/:cl:

### CODE REVIEW

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by Warfan1815** [comment]
Once again forgot that the code CL does that... damnit.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by Nanu308** [comment]
I'll be closing this due to reasons you're probably aware of Warfan

**Pull request closed without merging**
