### PR TITLE
Underwear Expansion

### PR DESCRIPTION
**Pull request by Geevies**
## About The Pull Request

Adds a bunch of new underwear and undershirt sprites, as well as a new system to assign them to mobs, as well as selecting the camo type they have, based on the map.

image

## Why It's Good For The Game

More customization options within the realm of marine possibility are good.

## Changelog

:cl: Geeves, Nauticall
add: Added a new underwear and undershirt system, with many new underwear and undershirt variants being added, most of them being camo conforming if you choose.
/:cl:

### CODE REVIEW

**Comment by GoldenDarkness55** [comment]
Feels like a paid commission. More customization is good but why would a marine ever be in his underwear on CM aside from waking up in cryo? I dunno how can someone think CM needs this or that its a good thing to have here, considering what the ss13 community's like.

**Comment by JohnDoe50974** [comment]
> Feels like a paid commission. More customization is good but why would a marine ever be in his underwear on CM aside from waking up in cryo? I dunno how can someone think CM needs this or that its a good thing to have here, considering what the ss13 community's like.

Replacing ugly outdated sprites is good. This is a terrible excuse for not improving the spritebase.

**Comment by spartanbobby** [comment]
one of the pillars of cms next golden AGE

**Comment by moltoretardo** [comment]
This is what we meant by "We want HRP content"

**Review by FransFeiffer — APPROVED** [review]
Who am I to say no to Sammy's Magnum Opus? Sprites LGTM

**Review by Agameofscones — APPROVED** [review]
double sprite approval

**Review by stanalbatross — APPROVED** [review]

**Pull request merged**
