### PR TITLE
Boiler Rework Part 1: Railgun Boiler

### PR DESCRIPTION
**Pull request by PhantomEpicness**
## About The Pull Request
This is apart of my 3 part boiler rework, which will totally rework boilers as outline in the design doc below.

This introduces the "Striker" boiler strain which is a combination of the premoba "Railgun" and lesser-known "Acid Splatter" strains with modern CM aspects

Striker boiler, in particular, is more designed around general purpose use as it can be both used offensively and defensively, but not excelling in either.

Active 1: "Bombard"
Shoots selected projectile acids. Variable windup times based on the spit selected but all of them have the same cooldown.

Active 2: "Switch spits"
Switch between these three spits for Bombard

- "Acid Splatter"
This is essentially the old acid strain's bombard shooting a fragmentation shot of acid, that will release acid shrapnel on hitting. Medium/Low damage, but it sure is a nuisance. 
-"Sticky Splatter"
As by the name, its the same thing but "sticky" shrapnel that slows down anyone hit by it for a short period. 
-"Acid shot"
This is the railgun boiler's spit of old. A single fast moving projectile that deals massive damage. While it has a 3 second windup , with a telegraph being spawned at where its firing at the last half second, hitting three marines in a row within a minute will enable the "Rapid Fire" ability

Active 2: Toggle Zoom
As it says. Has the largest zoom out of all of the boilers here.

Active 3: Rapid Fire
This is essentially the "Ultimate" of Striker boiler. Upon hitting three marines in a row within a minute, this will be unlocked.
Upon activation, a massive volley of low damage, high scatter, and mediocre accuracy acid dot projectiles will be spit at the target location after a 3 second windup. Be warned though, this is short ranged and can't be fired out of a normal view.

Passive: 

This PR also adds slime, which is like spray acid, but instead of damaging, it slows. 
It is not used very much in this PR, but will be used extensively with the other boilers.

## Why It's Good For The Game
Design doc:https://github.com/cmss13-devs/cmss13-design-docs/pull/8

## Changelog

:cl:
add: Adds the "Striker" boiler strain. It is meant to be a general purpose boiler strain that is equally good at both defense and offense but does not excel in either.  It combines aspects from both the old pre-moba "Railgun" boiler and the lesser known "Acid-Splatter" boiler while adding a modern CM twist to it.
experiment: Active 1 bombard: Shoots selected projectile acids. Variable windup times based on the spit selected but all of them have the same cooldown.
experiment: Active 2 Switch between a powerful single shot, a fragmentation projectile and a neuro fragmentation projectile.
add: Active 3: Toggle zoom
add: Active 4: Rapid fire: Upon hitting 3 marines in a row with the railgun shot, this ability is unlocked and will spit a rapid fire spit when activated after a windup
add: Adds slime. This is just like spray acid, but does not do damage and instead slows people down.
/:cl:

### CODE REVIEW

**Comment by Bram-KEP** [comment]
Wow, cool changelog

**Comment by Carnage068** [comment]
Quite possibly one of the most based things in existence.

**Comment by stanalbatross** [comment]
code test tomorrow -> testmerge candidate -> testmerge

**Comment by PhantomEpicness** [comment]
hilariously put the wrong branch up for PR
gaming

**Pull request closed without merging**
