### PR TITLE
Research Biohazard Lockdown

### PR DESCRIPTION
**Pull request by realforest2001**
# About the pull request
Adds a unique lockdown system for research biohazards.

# Explain why it's good for the game
Adds some nice flavour to research.
# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl:
add: Added a new lockdown system to research.
add: Added an admin button to interact with above.
/:cl:

### CODE REVIEW

**Comment by frozentsbgg** [comment]
Pretty Dope. Tested in game.

**Review by morrowwolf — CHANGES_REQUESTED** [review]
No star wars sounds

**Review by harryob — CHANGES_REQUESTED** [review]

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Review by harryob — APPROVED** [review]

**Pull request merged**
