### PR TITLE
Marine HUD Updates

### PR DESCRIPTION
**Pull request by realforest2001**
## About The Pull Request
Some updates to role huds, and removes "Provost Officer" as a job as it's no longer used.

## Why It's Good For The Game
Some tidying in code, and makes it easier to tell apart the few roles that don't have visible icons to the majority of players.
Leaving only Civilians as those without squad huds,

## Changelog

:cl:
del: Removed Provost Officer job as it is now obsolete.
tweak: Changed how the HUDs draw their icon pools to allow for easier differentiation in file names.
tweak: Changed the Dropship Crew Chief HUD Icon to fit enlisted style rather than using junior officer style.
tweak: Changed the UAAC-TIS Special Agent HUD Icon to officer colors, leaving current icon for TIS Intel Officer.
add: Added HUD icons for Synthetic and Mess Technician.
/:cl:

### CODE REVIEW

**Comment by kugamo** [comment]
This is unsolicited, but I thought itd be nice to see the icon changes in an easy to view format. Right side is what this PR changes.
image

**Comment by realforest2001** [comment]
image
Mess Tech and Synth, also evidencing the change to filepathing for sec hud works.

**Review by Agameofscones — CHANGES_REQUESTED** [review]
USCM / Marine Synthetic HUD icon conflicts design wise with CLF Engineer icon. Keep it distinct and keep with the face theme that the medHUD and faction synthetic icons follow. 

CMP sechud needs rank pip. As does the RO and CE.

Other stuff is OK :+1:

**Review by Agameofscones — APPROVED** [review]
nice

**Review by fira — APPROVED** [review]

**Pull request merged**
