### PR TITLE
pump action UGLs + you can now unload the UGL

### PR DESCRIPTION
**Pull request by stanalbatross**
## About The Pull Request

makes UGLs pump action, makes them require their breeches to be open to reload them

a deserved UGL nerf as they have become quite powerful - to the point of almost eclipsing the spec GL

this PR seeks to tune them down by making the firing process a bit more engaging/difficult

also adds backend support for unique-action with attachments

https://cdn.discordapp.com/attachments/915349747550785588/1011683961434538146/-_LV624_2022-08-23_18-07-25.mp4

## Why It's Good For The Game

nerfs the somewhat overtuned UGL and is cool as fuck

## Changelog

:cl:
balance: the underbarrel grenade launcher is now pump-action! you must pump it TWICE to fire it (open and close the breech, this cocks it). To reload it you must open the breech. You open/close the breech (and thus pump it) via UNIQUE-ACTION while the attachment is activated
qol: you can now unload the UGL as you would with a normal gun, while it is activated
soundadd: added new sounds for opening and closing the UGL + reloading grenades into the UGL
/:cl:

### CODE REVIEW

**Comment by JohnDoe50974** [comment]
Ok idec about balance, this is genuinely cool as fuck

**Comment by AGasCanister** [comment]
"nerfs the somewhat overtuned UGL and is cool as fuck"
what a weird and over complicated way to say "it's soulful"
do that with the masterkey too :D

**Comment by stanalbatross** [comment]
> "nerfs the somewhat overtuned UGL and is cool as fuck" what a weird and over complicated way to say "it's soulful" do that with the masterkey too :D

sir this is a ugl pr masterkey and other attachies can be changed in later prs

**Comment by PhantomEpicness** [comment]
soul

**Review by Shad0vvs — APPROVED** [review]
Pending balance, sprite, and sound review.

**Comment by Superreallycoolguy** [comment]
Sovl

**Review by Agameofscones — APPROVED** [review]
sprites and sounds are good, but would also recommend doing same thing for masterkey and other UGL variants

**Comment by Lagomorphica** [comment]
Very cool PR.

**Pull request merged**
