### PR TITLE
Metal Foam rebalance.

### PR DESCRIPTION
**Pull request by private-tristan**
# About the pull request
Increases the xeno damage multiplier against foam from 0.8x to 1.75x (and decreasing iron foam hp from 85 to 70), meaning that combat t2s xenos will be able to 1shot aluminum metal foam, but only T3s can 1shot iron metal foam. 

makes damage consistent against foam so that the queen/crusher/basePrae don't randomly fail to smash it in a single hit.

aluminium foam now is cap'd at 300u.

iron foam is no longer able to be created by chemistry

foam grenades now use iron foam
increased amount of iron foam grenades in req
surplus explosives crate now contains 2 metal foam grenades

To make metal foam grenades (the ones that are bought from vendors/req) not completely useless, they now use metal foam, which (as said above) will be able to stop T1s and T2s in their tracks.

# Explain why it's good for the game

Currently, metal foam when detonated in a reagent tank is able to flood an entire area of the map with metal foam, causing it to be near impossible for xenos to get past without spending 10 minutes clicking on foam. Meanwhile, marines are able to 1shot all foam using either bullets or a BOOT KNIFE. a giant alien with **scythes for hands** is slower at clearing out a chunk of metal foam than a human with a boot knife.

With this PR, metal foam will be significantly worse at stopping T2s and T3s. Buffing iron foam allows
# Testing Photographs and Procedure
<details>
<summary>Testing </summary>
300u metal foam maxcap: (outdated, only aluminium foam can be created, but size should be the same)

image

foam changes (heavily compressed because github only allows 10mb)

https://github.com/cmss13-devs/cmss13/assets/54422837/bbadd8c5-06fe-4216-881d-38ec7b9eac14

</details>

# Changelog
:cl:
balance: Xenos do greatly increased damage to metal foam (0.8x to 1.75x)
balance: Iron metal foam hp decreased from 85 to 75, meaning that all T3s other than boiler can instantly break it.
balance: Metal foam grenades now create iron foam.
balance: Aluminum foam reactions are now cap'd at 300u
balance: amount of metal foam grenades in req doubled.
balance: Surplus explosive pack now contains 2 metal foam grenades
del: metal foam is no longer able to be created in chemistry
/:cl:

### CODE REVIEW

**Comment by cuberound** [comment]
you only issue seams to be with regent tank foam, do not know enough about chem but can not you just maxcap the foam spread? remove the xeno slash buff and keep the vendor nades as metal? they are already hardly stoping anyone, this just makes xenos able to walk straight thrue them without being slowed down basicly

**Comment by lunarflu** [comment]
Hello, user of maxcap foams here,

Like @cuberound says, your complaint is with the size and destructibility of foam. However;

1. The size is proportional to cost, in materials, and loss of convenience, in portability, requiring both offensive slots filled with uncommon containers (janitorial buckets, bluespace beakers) in order to produce a maxcap. 
- It is extremely expensive to produce maxcap foams and it sets all of medbay extremely behind for no obvious benefit, as opposed to the usual UNGA. 
- It is also expensive as it requires the absolute largest containers that are rare and heavily contested. 
- These tradeoffs are consistent with all other chems and can only be accomplished under extremely specific conditions (doctor/nurse deploys or instructs how to use). You are essentially saying "maxcap strong" - but not acknowledging how much it costs to make. 

2. Foams are one of the hardest utilities to use. 
- Firstly, you lose all other offensive capability. 
- Secondly, you cannot throw or remotely activate foam, you must be in the center to activate, putting yourself in danger. 
- Thirdly, marines are equally (if not more) vulnerable to being trapped in foam, given they excel in open spaces where they can use range and suffer in tight spaces where they can be comboed by xenos with little counterplay. 

You're demanding a nerf to one of the weakest and expensive utilities because you don't know how to play around it as xeno. It's clear you've never made it yourself, and want to fix a skill issue by changing some numbers in a PR.

**Comment by lunarflu** [comment]
And like we said, foam is not too strong https://github.com/cmss13-devs/cmss13/pull/3741

In fact, it's so underused that it was last given a *buff*

**Comment by private-tristan** [comment]
this change is mostly due to the usage of foam in hijack, almost always done with reagent tanks

1:
> It is extremely expensive to produce maxcap foams and it sets all of medbay extremely behind for no obvious benefit, as opposed to the usual UNGA.

it... doesn't? it takes roughly 110 energy to produce 600u iron 200u poly acid 200u foam agent, and can be done at any time (such as the 20 minute period of research where there's literally nothing to do but wait for IOs)

https://github.com/cmss13-devs/cmss13/assets/54422837/b9e74187-7705-4d80-94f5-3623a08c1a4a


> It is also expensive as it requires the absolute largest containers that are rare and heavily contested.

research spawns with 2 reagent tanks, OT spawns with 3 reagent tanks, adding to this, you can fill **any** reagent tank with any chemical, meaning that in roughly 30 seconds you can empty a welding fuel or water tank and fill it with any other reagent.

2:
> Firstly, you lose all other offensive capability.

marines can easily just break foam in specific spots where they want to push, or make a hole through and then call in CAS while xenos are slashing the foam.

> Secondly, you cannot throw or remotely activate foam, you must be in the center to activate, putting yourself in danger.

this doesn't really matter due to the RANGE of foam, detonating the foam in the middle of tcomms/engi hallway allows you to block the north and bottom parts despite them being more than a SCREEN away and blocking the hallway for 2 screen's worth.


https://github.com/cmss13-devs/cmss13/assets/54422837/e8298bfe-319c-4d0d-979b-ca72c69915f3



> Thirdly, marines are equally (if not more) vulnerable to being trapped in foam, given they excel in open spaces where they can use range and suffer in tight spaces where they can be comboed by xenos with little counterplay.

the point about getting trapped in foam is COMPLETELY false, currently a marine can instantly destroy a iron foam with a single click of a bootknife, or by 2 shots of a M41A, meanwhile, a ravager ,the tier 3 xeno with the highest slash damage, takes 3 slashes to destroy. 


I should note that, the time taken to produce the maxcap, move it to engi hallway, detonate, and have it all fill took around 1 minute and 45 seconds. the time it takes for a ravager to break through the top hallway was roughly a minute for a 1 tile tunnel.


https://github.com/cmss13-devs/cmss13/assets/54422837/9bd208a1-49b4-45ca-978c-46d4ad980619

**Comment by harryob** [comment]
github is for code review, not for balance insight ->>> https://forum.cm-ss13.com/w/pr-feedback

**Review by Drulikar — APPROVED** [review]

**Pull request merged**
