### PR TITLE
Adds a Unique Sprite for the Prescription MedHud and slight changes to base Prescription Glasses

### PR DESCRIPTION
**Pull request by SweaterKittens**
# About the pull request

This adds a custom set of sprites for the Prescription version of the Medical HUD, including both active and deactive, as well as a looping animation that occasionally plays while it's active. It was strange that a monocular HUD fixed your vision, especially when it was off and was not covering your eyes in any fashion. 

Additionally, this makes a minor tweak to the Prescription Glasses sprite to make it more in-line with the 3/4 view that we use for items, as well as changing all references to it from "hipster glasses" to "prescription glasses". This will make it more intuitive to find, and standardizes the way that unique prescription glasses (should we get more in the future) are named.

All changes have been tested on a private server to ensure the sprites are appearing correctly.

# Explain why it's good for the game

Having prescription eyewear that actually covers your eyes is more sensible. Additionally, this allows characters who want to visually appear with glasses to work in the medical department while still being able to utilize the critically important health hud.

The changes to the naming conventions of the existing prescription glasses (currently only "Hipster Glasses") will make it more intuitive to find and reference them in the future, as well as provides an obvious naming convention for future sprites (simply append "rx" to the beginning of the default sprite to reference the prescription version when sprites differ, such as "healthhud" vs. "rxhealthhud").

# Testing Photographs and Procedure

The new Rx Med Hud sprite worn and active, the base Prescription glasses item, the Prescription Med Hud glasses item (active), and the Prescription Med Hud glasses item (deactive).

<details>
<summary>Screenshots & Videos</summary>

image

</details>

# Changelog

:cl: SweaterKittens
add: Added unique sprites for the Prescription Medical HUD, with a unique description
code: Changed references to Hipster Glasses to Prescription Glasses, and standardized the naming convention for prescription versions of eyewear.
/:cl:

### CODE REVIEW

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Review by harryob — APPROVED** [review]
code

**Review by Nanu308 — APPROVED** [review]
repath is fine regarding mapping

**Comment by deathrobotpunch** [comment]
time to have far sightedness for the drip

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by Blundir** [comment]
let me know when you'd be interested in working on it again

**Pull request closed without merging**
