### PR TITLE
Break Up Secure Storage LV-624

### PR DESCRIPTION
**Pull request by Steelpoint**
Breaks open the secure storage on LV-624. 

# Explain why it's good for the game

Survivor holds on 624 are usually a case of either the survivors running and gunning or hiding in secure storage for 18 minutes until the xenos reach T3, then its a case of if the Xenos can breach secure storage before the Marines arrive. Secure storage is simply not a fun exercise for both sides, if survivors are going to survive there should be more effort than hiding in a pre-made bunker. 

I should note that this does not make Secure Storage a impossible hold, only that its now not 100% inaccessible to xenos until they reach T3. 

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl:
maptweak: Secure Storage on LV-624 has been broken open, making it far less defendable but easier to access. 
/:cl:

### CODE REVIEW

**Comment by Diegoflores31** [comment]
sincerely i dont think this is the way to encourage anything but making it a more solid meta or returning back to 24/7 LZ1 holds.

**Comment by Steelpoint** [comment]
> sincerely i dont think this is the way to encourage anything but making it a more solid meta or returning back to 24/7 LZ1 holds.
> 
> PD: also show images of before/after on your PR

The current situaton means once a survivor gets inside it becomes literally impossible for any xeno to be able to threaten them until the 20 minute mark when T3s can spawn, which puts huge pressure on the xenos since they risk being hit by the arriving Marines at any moment.

At least in this circumstance the xenos can still threaten the survivors.

If needs be I can break up more of the secure dome so there are multiple entrances so its not so simple.

**Comment by Steelpoint** [comment]
MapDiffBot shows the changes as well

**Review by Nanu308 — APPROVED** [review]
map lgtm

**Comment by Huffie56** [comment]
if your deleting secure storage blast door you should delete all the connect buttons to open it from the outside.
research and nightmare insert, armory and nightmare insert, commanding office, cl office.
@Steelpoint

**Comment by Steelpoint** [comment]
I hate merge conflicts, I'll re-do this PR when I have free time. Maybe one day I can get the hooks to work to stop this being a issue.

**Pull request closed without merging**
