### PR TITLE
Fixes throwing uniforms removing your armor

### PR DESCRIPTION
**Pull request by morrowwolf**
## About The Pull Request

Fixes the unintended behavior described in https://github.com/cmss13-devs/cmss13/issues/311

## Why It's Good For The Game

Bug bad UNGA

## Changelog

:cl: Morrow
fix: Fixes throwing uniforms removing your armor.
/:cl:

### CODE REVIEW

**Comment by MidwayAtom** [comment]
fixes #311

**Comment by MidwayAtom** [comment]
closes #311

**Comment by MidwayAtom** [comment]
Closes #311

**Comment by MidwayAtom** [comment]
closes #311

**Comment by MidwayAtom** [comment]
@morrowwolf Please link #311 for closure upon merge via keywords. Thank you R/S IM.

**Comment by fira** [comment]
Closes #311 

Though I don't think this is a good solution at all

Between cutting things arbitrarily to human, and the fact that check looks to be in the wrong place

You also probably can't suppress drop here because then the unequip signal will still fire, etc

**Comment by morrowwolf** [comment]
> Closes #311
> 
> Though I don't think this is a good solution at all
> 
> Between cutting things arbitrarily to human, and the fact that check looks to be in the wrong place
> 
> You also probably can't suppress drop here because then the unequip signal will still fire, etc

What other mobs that aren't in that human subtype would we be worried about with unequipping a uniform?  Predator/synths/monkeys are all under /mob/living/carbon/human.

Where would you like the check?

This functions as it should from testing in its current state.

**Comment by Spircen** [comment]
I hope this PR its merged soon cause right now its a pain to check on Webbings or even a missclick on the front its a dead cause you lost your armor.

**Comment by morrowwolf** [comment]
Other one looks better, closing this.

**Pull request closed without merging**
