### PR TITLE
SEA Skill Tweaks

### PR DESCRIPTION
**Pull request by stanalbatross**
## About The Pull Request

removes spec skills from SEAS

## Why It's Good For The Game

SEA is a role for teaching not powergaming spec / sg weaponry, you do not need to have spec / sg skill to teach someone how to use these weapons - just tell them IC or explain via LOOC if needed

this skill has NEVER been used to teach anyone and has only been used to make the SEA into a spare spec for hijack which is not their purpose nor role

other skills were already at an appropriate level

## Changelog

:cl:
balance: removed SEA spec skills
/:cl:

### CODE REVIEW

**Comment by hotimep** [comment]
chuck-faint

**Comment by JohnDoe50974** [comment]
Based

**Comment by anclandor** [comment]
What is wrong with SEA's getting to have some fun with spec toys during hijack?  Its not like its xenos lose often with larval surge anyways.  I feel like it is totally reasonable that the veteran person on the ship has some spec experience.

**Comment by MusselMain** [comment]
> What is wrong with SEA's getting to have some fun with spec toys during hijack? Its not like its xenos lose often with larval surge anyways. I feel like it is totally reasonable that the veteran person on the ship has some spec experience.

If we are considering in lore, then it's likely that if they are teaching about it, they probably know it's functions, meaning that removing that skill shows that they wouldn't know how it operates and therefore in lore cannot instruct a SG or Spec on how to use it. I'd recommend keeping it in, as it makes sense lore wise, and I almost never see SEA's front lining unless ordered to by the CO (as FOB is in terrible shape and they lack the manpower), or when the xenos crash on the almayer. I've only ever seen a single case of a SEA using a smartgun, and it was in a desperate last hold where 4 marines were fighting against 13 xenos, and as someone who's taught a fair amount of PVT's without being a SEA (this occurs when I see a PVT who clearly has no idea how to load their gun or where to find their clothing, and then spend the whole round teaching them how to use it, as the SEA I called never shows up) I can tell you that sometimes you want a break from teaching and what better way then to let off some steam in the end of a round where having a Smartgun isn't going to save you from 35+ xenos. Especially since by the time a crash occurs the marines have usually lost all their Spec's and SG's and I think allowing the SEA to be that one SG at the end of the round isn't going to ruin the round, if you don't want the SEA front lining, maybe make them like the MP's where they can only deploy on the CO/XO's orders.

**Comment by c4xmaniac** [comment]
SEA population decreases from 0 to negative -0 following this PR, strange

**Comment by stanalbatross** [comment]
> SEA population decreases from 0 to negative -0 following this PR, strange

if they were just playing sea to powergame the spec skills in hijack they should not have been playing sea at all

lole

**Comment by FlamermanGrills** [comment]
Yeah guys the extra spec slot that opens every 73 rounds needs to be gone bros...

**Comment by c4xmaniac** [comment]
> > SEA population decreases from 0 to negative -0 following this PR, strange
> 
> if they were just playing sea to powergame the spec skills in hijack they should not have been playing sea at all
> 
> lole

that was the joke :)

**Comment by FoxyStalin** [comment]
Yet another PR in the series of things that wern't issues being made into issues.

SEA getting to have a little fun in hijack when the stars align during a blue moon isn't a problem, it's a fun little thing that adds some variance to the round every now and again.   If you can say that it's 'never' been used to teach  then I can also say that it's 'never' effected the round in a meaningful way.

**Comment by Superreallycoolguy** [comment]
OPPA CHUNGUS STYLE

fucking super zased PR, I wonder how many "SEA mains" are gonna stick around after this one

**Review by JeserTheFox — APPROVED** [review]

**Comment by SuprisedBaby** [comment]
I've trained more PVTs as MP then some SEAs, excellent change

**Comment by Chainsawicus** [comment]
SEAs only playing to powergame spec gear during hijack is an embarrassment to the mentor system and the fact that devs had to fix it because the mentor manager wouldn't is sad.

Based PR.

**Comment by Joelampost** [comment]
Thank you stan, once again you prove yourself to be a pillar of hope for the community

**Comment by Chainsawicus** [comment]
> If we are considering in lore, then it's likely that if they are teaching about it, they probably know it's functions, meaning that removing that skill shows that they wouldn't know how it operates and therefore in lore cannot instruct a SG or Spec on how to use it. 

If we are considering in lore, then it's like that the specialist is already exceptionally trained in the usage of their weapon, meaning that them needing to be taught breaks lore.

Yeah, no. SEAs don't need the skill, it only encourages playing to powergame, and not to help new players. If a mentor doesn't find helping new players fun or rewarding enough on its own, they should never have been given the role in the first place.

**Comment by NuggetsOnToast** [comment]
Great PR. You absolutely do not need to be able to use the spec weapons to teach people how to use them. This will cut down on the "SEA mains" who only seek out spec gear and other items as such.

**Review by Geevies — APPROVED** [review]
I have arrived, and it is now that I perform my charge.
In fealty to the Gameplay-Architect (our undying Lord) and by the grace of the Linux Server, I declare Balance upon the Mentor role of Senior Enlisted Advisor.
I hereby sign the death warrant of an entire whitelist and consign a million souls to oblivion.
May Random Developer PRs account in all balance.
Merge Conflicts Protects.

**Pull request merged**
