### PR TITLE
Nerfs GAU damage by one fifth.

### PR DESCRIPTION
**Pull request by Birdtalon**
# About the pull request

Nerfs the GAU damage across the board by about 1 third.
I believe this weapon has become far too lethal since #5065 doubled the number of projectiles and is now any xeno caught in it has barely any chance of survival.
It seems silly that the Queen has to fear a GAU CAS more than the OB.

It is too strong with a good CAS pilot / JTAC deciding the game single headedly.

I want to reign it back in again.

# Explain why it's good for the game
# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl:
balance: Nerfs GAU damage of both ammo types by one third.
/:cl:

### CODE REVIEW

**Comment by iloveloopers** [comment]
Can we get a discussion thread opened on the forums?

**Comment by Birdtalon** [comment]
> Can we get a discussion thread opened on the forums?

https://forum.cm-ss13.com/c/development/pr-feedback-submissions/35

**Comment by blackdragonTOW** [comment]
This is actually a 40% reduction, for what it's worth.  While I am not a maintainer, I do have a healthy dose of PO hours under my belt, and if this brings it back to where it was before there's a real chance the GAU might just get shelved as noob bait once again.  

That said, even as the author of https://github.com/cmss13-devs/cmss13/pull/5065 I do agree GAU probably needs some tuning, though probably not so close to cutting it back down to half again.

**Comment by Birdtalon** [comment]
Updated the link.

**Comment by mullenpaul** [comment]
GAU heavy builds seem to be the meta approach and slightly busted. I would support this if it was around 10-15% damage nerf and then we can monitor it over the next few weeks. I agree that a 30-40% nerf would probably render it useless.

**Review by mullenpaul — APPROVED** [review]

**Comment by Birdtalon** [comment]
Closing due to #5410 making CAS have far more warning and become actually avoidable.

**Pull request closed without merging**
