### PR TITLE
Differentiates pylons in same area when spawning as lesser drone

### LINKED ISSUE #4424: Lesser Drone spawning issue when both pylons in same area
### Testmerges

The following pull requests are currently test merged: #4379: 'Science Annex Yard Readdition' by c4xmaniac2 at commit f6bedf65dc #4378: 'LV Intel Update' by c4xmaniac2 at commit 67b2ec461b #4063: 'Yautja Change Holder' by realforest2001 at commit fcc6c86cd3 #4410: 'Cloaked mobs don't give off visible messages (+cloak logic refactor)' by Zonespace27 at commit 1b5a288001 #4391: 'Hijack objectives' by morrowwolf at commit 263df75edf

### Description of the bug

Both pylons are active:
When trying to use the Join as Lesser Drone command, if both pylons are in the same area, the prompt to select which core/pylon to use will automatically highlight both pylons. One of the pylons cannot be joined through, as it defaults to one of them. The other pylon can still be manually clicked to spawn to.

### What's the difference with what should have happened?

Both pylons should have separate entries in the spawn location prompt.

### How do we reproduce this bug?

1. Have two comms towers both in the same area
2. Attempt to Join as Lesser Drone
3. See image
...
cm-pylon-bug

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

### PR DESCRIPTION
**Pull request by Birdtalon**
# About the pull request

Adds a (1) to duplicate named pylons if they reside in the same area when trying to spawn at pylon as lesser drone.
Fixes #4424 

# Explain why it's good for the game
# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl:
fix: Pylons now differentiated in the input list with a (1) if in the same area.
/:cl:

### CODE REVIEW

**Comment by morrowwolf** [comment]
(1) (1) instead of iterating, straight to jail

**Comment by fira** [comment]
Awww yeah you could add proper numbering if doing this

**Comment by Birdtalon** [comment]
So funny story I did actually add numbering which is what I overwrote with the force push after I found I couldn't actually spawn more than 2 pylons in the world.

**Comment by morrowwolf** [comment]
It's either 2 or the amount of comms towers, if a map had more than 2 for some reason iunno, something something maintainability, I don't know I don't work here where am I

**Comment by Birdtalon** [comment]
Someone post that quote about maintainability.

**Review by fira — APPROVED** [review]

**Review by harryob — APPROVED** [review]

**Pull request merged**
