### PR TITLE
adds two scrub colors: green and grey

### PR DESCRIPTION
**Pull request by coldironwarrior**
# About the pull request

adds truly green scrubs and grey scrubs

# Explain why it's good for the game

more scrub flavor stuff; grey is usually worn by receptionists
olive green isn't a typical color but i thought it was a cool homage to bookard; maybe researchers will like it
image

# Testing Photographs and Procedure
image
image

# Changelog
:cl:
add: adds olive green and grey scrubs
spellcheck: cleaned up scrub descriptions
/:cl:

### CODE REVIEW

**Comment by vero5123** [comment]
scrub bloat

**Comment by Katskan** [comment]
Very nice, would love some nice bright red too

**Review by nauticall — DISMISSED** [review]
image
The green scrubs look a bit too saturated and the gray scrubs look more like a light lavender/lilac than actual gray. I get that CM's style doesn't like totally gray colors but I do believe they could use a bit less saturation and should be darkened a bit. Adjust to your liking.

**Comment by harryob** [comment]
mark ready to review when sammy's review is addressed

**Comment by coldironwarrior** [comment]
im close because very sick and no energy to work; will work on again eventually maybe

**Review by harryob — APPROVED** [review]

**Pull request merged**
