### PR TITLE
Experimental Tank Return

### PR DESCRIPTION
**Pull request by Geevies**
## About The Pull Request

Returns the tank to the Vehicle Crew arsenal, with the only change being that it moves a bit slower. I'd like to see it in action to see how it should be balanced in the future.

Also fixed the overlay layers for the tank's equipment, so it should look less wonky now. Also made vehicle equipment lowercase and added a lot of full-stops.

For the vehicle crew gear vendor, I've removed some equipment I've found to be buggy, such as the artillery module, and against the balance idea, the overdrive enhancer.

## Why It's Good For The Game

The tank is considered "soul", but seems to be unbalanced. My first attempt at balance will be making the tank pretty slow, so it's a support vehicle that can be defeated by outmaneuvering it.

## Changelog

:cl:
add: Re-added the tank.
fix: Fixed tank equipment layers.
/:cl:

### CODE REVIEW

**Comment by Geevies** [comment]
Removed the APCs from the vehicle elevator until the testmerge cycle is complete.

**Comment by Huffie56** [comment]
Refactor the tank to use it in events is a good idea.
But re-implementing it in standard round on high pop and balancing it will be almost impossible good luck.

**Comment by stanalbatross** [comment]
Marking as DNM for now

**Comment by stanalbatross** [comment]
Also please provide a proper "why it's good for the game"

**Comment by ThePiachu** [comment]
It would be nice having the module name changes by themselves since it's a good change and it would make this PR a bit clearer to review.

**Comment by Aracino** [comment]
As someone who lived through the tank era. Please, god, no.

**Pull request closed without merging**
