### PR TITLE
Battlepass System

### PR DESCRIPTION
**Pull request by Zonespace27**
# About the pull request
Adds a battlepass system to the game.

# Explain why it's good for the game
M O N E Y

# Credits

A big thank you to the below people:

<details>
<summary>Credits</summary>

- Sleepynecrons aka Wei, for a massive amount of the sprites present in the battlepass
- Beagle, for good ideasguying and several premium battlepass gun sprites
- TG, for providing the particle effects I ~~stole~~ acquired

</details>

# Changelog
TODO

### CODE REVIEW

**Comment by The32bitguy** [comment]
Placing resin nodes as the Resin Whisperer strain of Hivelord does not count towards "Xeno Challenge - Plant Resin Nodes"

**Comment by The32bitguy** [comment]
The "Xeno Challenge - For The Hive!" may not actually trigger.

**Comment by ATP2333REAL** [comment]
add this to the game Permanently

**Comment by Zonespace27** [comment]
> Placing resin nodes as the Resin Whisperer strain of Hivelord does not count towards "Xeno Challenge - Plant Resin Nodes"

Low priority, it's not hard to get that objective done anyway

**Comment by Zonespace27** [comment]
> The "Xeno Challenge - For The Hive!" may not actually trigger.

Cannot repro

**Comment by Johannes2262** [comment]
You need to check your clock, the first of april is tomorrow

**Comment by ATP2333REAL** [comment]
helmet fire will disappear when you equip a gun or something

**Comment by Johannes2262** [comment]
On a serious note, of course some of the premium rewards (abon larva, health increase, spec token, the stim) would need to be removed but the gun textures look cool as hell, merge this already

**Comment by TheManWithNoHands** [comment]
I can only agree, keeping this in some form could be very healthy for the game in the long run.
Mainly the daily objectives, wich incentivises players to change up their playstyles.
I dont think i need to explain why that is VERY good.

**Comment by Zonespace27** [comment]
> helmet fire will disappear when you equip a gun or something

Low-priority, overlays are a fuck. Remove/readd the helmet to fix

**Comment by sl0w3st** [comment]
Please, change plushie sounds to `sound/voice/alien_pounce.ogg`

**Comment by Zonespace27** [comment]
https://discord.com/channels/150315577943130112/508399944986787850/1224952871678902282

**Comment by PhantornRU** [comment]
we need it...

**Comment by TheManWithNoHands** [comment]
> we need it...

It is planned to make a proper thing. Only thing missing are rewards for it.

**Pull request closed without merging**
