### PR TITLE
Three World Empire Squadies

### PR DESCRIPTION
**Pull request by Geevies**
## About The Pull Request

WIP Draft for a Three World Empire squad, currently contains a Seaman, Leading Seaman, and a Standing Officer, more to come probably.

Opening primarily so other devs can easily visualize the changes still needed, like missing names and descriptions.

## Why It's Good For The Game

TWE is another big player in this universe, so giving them some representation is good (also more people for me to use in HvH)

## Changelog

:cl:
add: Added a 3WE ERT squad.
/:cl:

### CODE REVIEW

**Comment by LilPenpusher** [comment]
If this is meant to be the actual ERT of the 3WE (i.e. the one that can randomly trigger via Hijack distress beacon) then you'd 100% want to make these boys the RMC (Royal Marine Commandos) Squad that has been talked about a bunch.

I'm all for a Navy ERT, but it shouldn't be the default 3WE one - make it Admin only, for events and such.

**Comment by hotimep** [comment]
semen

**Comment by tempelers** [comment]
For 3WE, make it either SAS or Royal Marines.

Some ideas for roles are; Royal Corpsman, Leading Rank, Sniper/Railgun operator, a version of a smart gunner, and maybe a spec ops guy for the final slot (would be similar to MARSOC and UPP).

Of course, 3WE would be naturally friendly, but wouldn't follow the ship's command like the other friendly ERTs.

**Comment by PhantomEpicness** [comment]
3WE SBS when

**Comment by c4xmaniac** [comment]
Once Royal Marines get added I will rule CM as my CO, make this FAST!!!

**Comment by cm13live** [comment]
This pull request has been mentioned on **CM-SS13**. Please provide feedback here:

https://forum.cm-ss13.com/t/three-world-empire-ert/1519/1

**Pull request closed without merging**
