### PR TITLE
Skinned gun resprites

### PR DESCRIPTION
**Pull request by Agameofscones**
## About The Pull Request

I actually finished this in 2021 and then never actually did the support code work, minimal as it was. This ~~MR~~ PR replaces all guns that use the map skin system and raises them to a newer standard. Other guns, less used, do not need to be adjusted as such. Affected items are:

- M41A Pulse Rifle
- L42A Battle Rifle
- M92 Grenade Launcher
- M39 Submachine Gun
- M42A Sniper Rifle (done by Nauticall, aka Sammy)
- MOU Break Action Shotgun
- R4T Lever Action Rifle (adjusted Thwomper sprite)

image
image

## Why It's Good For The Game

old funky sprites make my eyes bleed. L42A is now genuinely an FAL in heart, spirit, and appearance. M39 is now, finally, lore accurate.

## Changelog

:cl: Triiodine, Nauticall, Thwomper
imageadd: Resprited the following weapons: M41A, L42A, M92, M39, M42A, MOU, R4T
/:cl:

### CODE REVIEW

**Comment by Agameofscones** [comment]
TODO: after conferring with other spriters, overwrote some content changes and need to reapply patch.

**Review by FransFeiffer — APPROVED** [review]
Sprites lgtm

**Comment by Debossans** [comment]
looks great ingame but in this TM i cant se it well, like, i cant look at the sprites other that M41A

**Comment by stanalbatross** [comment]
image
 stray pixel in the jungle mateba

**Comment by Shirumic** [comment]
Comparing the old M39 sprite to the new one,
https://cdn.discordapp.com/attachments/604397850675380234/965562588622639186/unknown.png
https://cdn.discordapp.com/attachments/604397850675380234/965566802610495518/unknown.png
the gun seems to have lost it's silhouette and is physically more difficult to click on due to it's size.
Pistol grip seems a little over-exaggerated.
It might physically resemble the actual M39 more, seen here
https://static.wikia.nocookie.net/avp/images/d/dc/AM39SMGACM.png/revision/latest?cb=20200806133933
https://static.wikia.nocookie.net/avp/images/6/62/ACM_concept94.jpg/revision/latest?cb=20130817023608

But the sprite itself seems to have lost it's character, and seems like a bland single color 'matchstick' compared to the old M39 ingrained in CM from years of playing.
And if the M39 ingame is going to be continuously flipflopping between overpowered and useless, it should at least look good!
Additionally the L42 seems a little too thin, but that's really just me nitpicking.

**Comment by Agameofscones** [comment]
> image stray pixel in the jungle mateba

Fixed. Blame Frans.

**Review by stanalbatross — APPROVED** [review]
code is fine, it's just changing the attachment offsets so they work with the new sprites. no problems there.

**Comment by AvalonHunter** [comment]
Basically just echoing Shirumic's sentiment about the M39 sprite. I think the others are fine, but the M39 lost contrast and looks kinda blurry now. I really do not care for it.

**Pull request merged**
