### PR TITLE
Obliterates Skilless Autoinjectors

### PR DESCRIPTION
**Pull request by Diegoflores31**
## About The Pull Request

This PR intends to change Skilless autoinjector , refillable injectors pouch , First responder pouch , pill pouch and Nanomed vendors.

**Wall Nanomed** 
-Skilless autoinjectors can not be refilled into Wall vendors anymore.
-Wall Nanomed no longer refills Splints.

**Weymed plus**
Weymed plus no longer vends nor refill any Chem bottles . this feature now is exclusive to Weychem vendors.

**Refillable autoinjector pouch**
-Refillable autoinjector pouch is now treated as special gear and military personell will need to spend points in order to buy it (PFC , Enginner , IO , etc).

**First responder Pouch**
-Removed First responder pouches from squad prep vendor.
-All First responder pouches from vendors come full.
-Added First responder Pouch as a buyable option to roles that didnt had it available before
-reduced greatly Req spawns of First responder pouches.
-Increased First Responder Pouch from 4 to 5 
-Added an Improvaline injector to First responder Pouch
-Changed Mini Extinguisher for Medical Gauze.

**Pill pouch**
-Pill pouch now includes a packet of tricordrazine.

**vendors**
-Removed Refillable injectors from roles that already had medical Skill and Autoinjector pouch available for free

## Why It's Good For The Game

-This PR aims mostly to change the EZ autoinjector meta to make it less optimal and require marines to actually need to resupply in order to keep themselves fighting since Transport APC allowed them to keep themselves full on chems and splints. winout needing to actually pick the Medical APC.

-Revitalizes First responder pouch to be a viable options to non medics or medics that want to take the "mini medic" role recovering dead / crit marines and transporting them to safety winout having to add the Pamplet back

-Makes Weychem more important and consistent by  making it the only vendor that vends/refills chems in bottles

-Marines now need to take the choice of either expending points for receiving a Refillable supply of meds or getting the standard non refillable options (pills / gauze pouch)
## Changelog

:cl:
balance: Skilless autoinjectors can not be refilled into Wall vendors anymore.
balance: Wall weymed no longer refills Splints.
balance: Weymed plus no longer vends nor refill any Chem bottles . this feature now is exclusive to Weychem vendors.
balance: Refillable autoinjector pouch is no longer free on all ranks.
balance: All First responder pouches from vendors now come full.
balance: Reduced greatly Req spawns of First responder pouches.
balance: Pill pouch now includes a packet of tricordrazine.
balance: Increased First Responder Pouch from 4 to 5.
balance: Changed the contents of the First Responder Pouch and now contains (roller bed , stasis bag , bandage , inaprovaline , health analyzer).
removal: Removed First responder pouches from squad prep vendor.
removal: Removed Refillable injectors pouch from roles that already had Autoinjector pouch available.
/:cl:

### CODE REVIEW

**Comment by ThePiachu** [comment]
A pretty good change! Honestly I'm kind of baffled why you could even restock used up autoinjectors and bottles, it would be like restocking used up magazines and hoping for a refill...

I would probably eave the `pouch/firstaid/full` for the actual medical team (Nurse / Doctor / Medic / Synth). Medics specifically have the `reagent_container/glass/minitank` to technically refill those, and one of my PRs is giving it to the Synth as well. Then again, they can just make it themselves from what they can get so I guess it's not such a big deal...

Also, it looks like Requisitions has quite the supply of `pouch/firstaid/full`, so maybe Ungas will learn to just get it from there and we'd be back to square one?

**Review by ThePiachu — CHANGES_REQUESTED** [review]
Did you intend to leave the `pouch/firstaid/full` for Squad Leaders?

**Comment by Diegoflores31** [comment]
> Did you intend to leave the `pouch/firstaid/full` for Squad Leaders?

true i forgot to remove it

**Comment by ThePiachu** [comment]
We should probably wait until #1551 is tested and merged before we merge this one in.

**Comment by ThePiachu** [comment]
Added DNM until the other PR gets resolved not to cause further problems.

**Review by stanalbatross — COMMENTED** [review]
I will take a more indepth look at the balance of this later but I can tell you right now that this does not fix the problem of skillless autoinjectors by making them point cost items, rather it just makes them mandatory purchases for PFCs and the like

**Review by ThePiachu — CHANGES_REQUESTED** [review]
Please rebase and make sure everything is in order after the Vendor GUI PR got merged.

**Comment by stanalbatross** [comment]
`balance: Skilless autoinjectors can not be refilled into Wall vendors anymore.
balance: Wall weymed no longer refills Splints.`
remove as per #1758 
`balance: Refillable autoinjector pouch is no longer free on all ranks.`
as I said earlier this is not a good change
`balance: All First responder pouches from vendors now come full.`
why?
`balance: Changed the contents of the First Responder Pouch.`
can you say what you actually changed here

**Comment by Diegoflores31** [comment]
> `balance: Skilless autoinjectors can not be refilled into Wall vendors anymore. balance: Wall weymed no longer refills Splints.` remove as per #1758 `balance: Refillable autoinjector pouch is no longer free on all ranks.` as I said earlier this is not a good change `balance: All First responder pouches from vendors now come full.` why? `balance: Changed the contents of the First Responder Pouch.` can you say what you actually changed here

changed fire extinguisher for a inaprovaline injector and added 1 more slot with a bandage

**Pull request closed without merging**
