### PR TITLE
Almayer mapping, new lower medical

### PR DESCRIPTION
**Pull request by LC4492**
# About the pull request

"Long hall medbay is no more"
- Zenith

Now, lower medical have been updated to have some extra details, some new gadgets, and an overall better organized design that uses the original space as best as possible, ensuring (or at least trying to) better use of space. The original size have been preserved (only being one tile lengthier to the east).

# Explain why it's good for the game

Apart from being a newer design, will auxiliate on the addition of other rooms that involve the backside of medbay (given the repositioning of airlocks), though its not smaller than what currently exists.

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

image

</details>

# Changelog
:cl:
maptweak: Adds a new lower medical, with extra details and gadgets. Changes the position of the bodyscanner crate from the maints to the field equipment room, which is now locked behind a shutter.
/:cl:

### CODE REVIEW

**Comment by Strobia** [comment]
No syringe cases 💔 ( some marines / medics like taking them and theyre in the normal medbay )

**Comment by LC4492** [comment]
> No syringe cases 💔 ( some marines / medics like taking them and theyre in the normal medbay )

I've now added six of them to the medical storage.

**Review by Nanu308 — COMMENTED** [review]
I like some aspects of the design, while i dislike other parts of it, which makes me kinda neutral to it as a whole. Could it be tweaked to make it better? Yes, i do believe so, but see my next point.

The Almayer has a mapping freeze, and as far as i am aware you did not notify any maintainer or me for that matter saying you wanted to do changes and why if so. The new medbay you propose just changes it up, which as i've said in the past i do not see good enough of a reason to do Almayer changes.

You need to speak with a maintainer that does mapping prior next time. I'll be closing the PR for now.

Come next year in January, i do however plan to open up for Almayer changes for a limited time, wherein changes just for change will be accepted if it can be of a better design and aesthetic look.

**Comment by deathrobotpunch** [comment]
@LC4492 its February my dude

**Pull request closed without merging**
