### PR TITLE
React Migration - part 2

### PR DESCRIPTION
**Pull request by mullenpaul**
# About the pull request

Switches TGUI from Inferno to React.

Part 2 of the PR https://github.com/cmss13-devs/cmss13/pull/5435

Based heavily on the work from: https://github.com/tgstation/tgstation/pull/80044/files

# Explain why it's good for the game
React is a more suitable framework

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl:
refactor: switched from infernojs to react
/:cl:

### CODE REVIEW

**Comment by mullenpaul** [comment]
This seems to work fine locally, we need to TM it to see any issues

**Comment by Vicacrov** [comment]
I added a box of vials and a bucket into the `Turing Dispenser`, I clicked Run Program, and then I got this tgui error - I cannot access the Turing Dispenser again.

```
Error: Minified React error #62; visit https://reactjs.org/docs/error-decoder.html?invariant=62 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
   at ge (http://cdn.cm-ss13.com/live/51/asset.510921d6848feba589d94ba635f9c727.js:1:15121)
   at ql (http://cdn.cm-ss13.com/live/51/asset.510921d6848feba589d94ba635f9c727.js:1:86579)
   at jc (http://cdn.cm-ss13.com/live/51/asset.510921d6848feba589d94ba635f9c727.js:1:109486)
   at vc (http://cdn.cm-ss13.com/live/51/asset.510921d6848feba589d94ba635f9c727.js:1:109378)
   at xc (http://cdn.cm-ss13.com/live/51/asset.510921d6848feba589d94ba635f9c727.js:1:109245)
   at pc (http://cdn.cm-ss13.com/live/51/asset.510921d6848feba589d94ba635f9c727.js:1:109108)
   at lc (http://cdn.cm-ss13.com/live/51/asset.510921d6848feba589d94ba635f9c727.js:1:106225)
   at Wi (http://cdn.cm-ss13.com/live/51/asset.510921d6848feba589d94ba635f9c727.js:1:46865)
   at tc (http://cdn.cm-ss13.com/live/51/asset.510921d6848feba589d94ba635f9c727.js:1:103309)
   at Vc (http://cdn.cm-ss13.com/live/51/asset.510921d6848feba589d94ba635f9c727.js:1:118741)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; Tablet PC 2.0; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)
State: {"ckey":"vicacrov","interface":"Autodispenser","window":{"key":"[0x2004fe7]-main","size":null,"fancy":1,"locked":0}}
```

**Comment by Vicacrov** [comment]
The IC > View research objectives throws this error from the moment I spawned in (as a researcher):

```
ReferenceError: 'cotext' is undefined
   at t.ResearchMemories (http://cdn.cm-ss13.com/live/51/asset.510921d6848feba589d94ba635f9c727.js:1:867437)
   at _a (http://cdn.cm-ss13.com/live/51/asset.510921d6848feba589d94ba635f9c727.js:1:63019)
   at ks (http://cdn.cm-ss13.com/live/51/asset.510921d6848feba589d94ba635f9c727.js:1:120235)
   at vc (http://cdn.cm-ss13.com/live/51/asset.510921d6848feba589d94ba635f9c727.js:1:109311)
   at xc (http://cdn.cm-ss13.com/live/51/asset.510921d6848feba589d94ba635f9c727.js:1:109245)
   at pc (http://cdn.cm-ss13.com/live/51/asset.510921d6848feba589d94ba635f9c727.js:1:109108)
   at lc (http://cdn.cm-ss13.com/live/51/asset.510921d6848feba589d94ba635f9c727.js:1:106225)
   at Wi (http://cdn.cm-ss13.com/live/51/asset.510921d6848feba589d94ba635f9c727.js:1:46865)
   at cc (http://cdn.cm-ss13.com/live/51/asset.510921d6848feba589d94ba635f9c727.js:1:106735)
   at Anonymous function (http://cdn.cm-ss13.com/live/51/asset.510921d6848feba589d94ba635f9c727.js:1:124772)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; Tablet PC 2.0; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)
State: {"ckey":"vicacrov","interface":"ResearchMemories","window":{"key":"[0x21029f23]-main","size":null,"fancy":1,"locked":0}}
```

**Review by harryob — APPROVED** [review]
further bugs can shake themselves out in master

**Pull request merged**
