### PR TITLE
Returns Ice V2 to rotation for the Holiday Season 

### PR DESCRIPTION
**Pull request by private-tristan**
# About the pull request
thanks to Drathek and vilebeggar for their help with this PR.
Ice v2, with functional elevators and Intel, for the chilly season. this PR copies code and ice v1 from #5067 
Ice_Colony_2 low quality 
(quality a bit low because it needed to be compressed for github)

# Explain why it's good for the game

I want to play ice v2.

# Testing Photographs and Procedure
I tested elevators and elevator buttons, and they all seem to work fine.

### CODE REVIEW

**Comment by BadAtThisGame302** [comment]
How about we return CORSAT and prisonblocks back to rotation because it's the Holiday Season and we have to spread the cheer equally among all dropped maps? One Ice was bad enough.

**Comment by Googles-Hands** [comment]
Let's hope you manage to do what I couldn't, but I agree, one ice is enough.
Ask the maintainers to un-testmerge the other ice once this is ready. That seems like a reasonable solution to me.

**Comment by private-tristan** [comment]
all these runtime failures because I forgot how subtypes work 😭 I need to actually make a map for the maps ingame to work because I can't find one online

**Comment by private-tristan** [comment]
Pr is ready to be TM'd.

**Comment by harryob** [comment]
the holidays are over. jollyness completed

**Pull request closed without merging**
