### PR TITLE
new male scream

### PR DESCRIPTION
**Pull request by halworsen**
# About the pull request

what it says on the tin

# Explain why it's good for the game

cool new scream 👍 
# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl:
add: Added a new male scream
/:cl:

### CODE REVIEW

**Review by Zonespace27 — CHANGES_REQUESTED** [review]
Please state the sound's source and any applicable licensing

**Comment by halworsen** [comment]
Taken from [Apollo station](https://github.com/Apollo-Community/ApolloStation/blob/master/sound/voice/mscream2.ogg) but the file metadata suggests it's from the Johnson Brand Editing SFX Library.

I can't find the original source anymore (probably a dead free SFX site) but judging by [this SFX pack with the same name by the same author](https://freesound.org/people/JohnsonBrandEditing/packs/10915/) (which contains many other iconic SS13 scream SFX), it's very likely a CC0 license.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Review by Zonespace27 — CHANGES_REQUESTED** [review]
The scream is noticeably different than the rest of our scream noises. What to fix:
- The sound is fairly quiet in comparison to the others
- It sounds far further away from the microphone than the others
- It has reverb that the others lack

**Comment by harryob** [comment]
pr appears to be stale, feel free to make a new pr addressing the requested changes

**Pull request closed without merging**
