### PR TITLE
High Capacity Dropships

### PR DESCRIPTION
**Pull request by ItsVyzo**
## About The Pull Request
Attempts to revive #1065, however, instead of increasing the cap to 60, it's 48. There should be no clipping issues, in theory.

## Why It's Good For The Game
Makes the dropship use more convenient/realistic and less crowded and piling on other marines. Immersion. ~~Flashbangs even worse~~

image

## Changelog

:cl: LTNTS
qol: Remaps Normandy and Alamo to seat up to 48 marines each
/:cl:

### CODE REVIEW

**Comment by realforest2001** [comment]
Need to update the LZ areas on each map to reflect the change in dimensions of the dropship. Otherwise everything looks ok to me.

**Review by realforest2001 — COMMENTED** [review]
See above comment. Forgot to put it in the right place!

**Comment by harryob** [comment]
> See above comment. Forgot to put it in the right place!

CleanShot 2022-12-21 at 06 56 22@2x
dimensions are identical

**Comment by ItsVyzo** [comment]
> Need to update the LZ areas on each map to reflect the change in dimensions of the dropship. Otherwise everything looks ok to me.

The size/dimensions of the dropship were not changed -- only the interior

**Comment by Nanu308** [comment]
Conflicts

**Comment by ItsVyzo** [comment]
I think conflicts fixed, hopefully...

**Comment by harryob** [comment]
stale, ping for reopen

**Pull request closed without merging**
