### PR TITLE
fix remove items anchored and on the LZ's on fiorina

### PR DESCRIPTION
**Pull request by Huffie56**
# About the pull request

fixes: https://github.com/cmss13-devs/cmss13/issues/3427

# Explain why it's good for the game
just read the linked issue..

# Testing Photographs and Procedure

<details>

image

<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
fix: remove items anchored and on the LZ's on fiorina map.
/:cl:

### CODE REVIEW

**Comment by Drulikar** [comment]
I wouldn't consider this a fix to that issue. Landing lights are still incorrect, still many issues on other maps, and it's not simply that things that get crushed should be removed - they should be placed where they should not get crushed. The dropship will remove them for you by crushing them. If there's not enough room, then try using the newer ground lights a few maps use that can be walked ontop of.

**Comment by Huffie56** [comment]
> I wouldn't consider this a fix to that issue. Landing lights are still incorrect, still many issues on other maps, and it's not simply that things that get crushed should be removed - they should be placed where they should not get crushed. The dropship will remove them for you by crushing them. If there's not enough room, then try using the newer ground lights a few maps use that can be walked ontop of.

i going to work more on fiorina to make it look more ok...
but if you want a redo on all the LZ's you should ask it to be added to the roadmap not putting it as an issue i think...

**Comment by Huffie56** [comment]
LZ2
image
i didn't know what to do there beside rezise and cleaning the LZ...

**Comment by Huffie56** [comment]
@Watermelon914 thanks for the review/merge...

**Pull request merged**
