### PR TITLE
Adds a strain button to the Xeno HUD

### PR DESCRIPTION
**Pull request by TheManWithNoHands**
# About the pull request

*Ads a button in the Xeno HUD to select a strain.

# Explain why it's good for the game

Strains are a big part of the Xeno gameplay. Yet its a function hidden in the alien tab, something new players arent gonna look into for a while.
Something that plays such a big role for xenos, should not be something you need to be told about by others.
So, a nice button on the top for xenos to select their strain quickly.

I know its a big concern for many players to not clutter the screen too much. But all the ability buttons can be hidden and can be assigned hotkeys to. So i dont belive this is really an issue.

(code migth be weird af, but it do work.)
If you want to talk balance or other, my discord is NCH

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

grafik

</details>

# Changelog

:cl:NHC
ui: Added a Xeno Ability HUD button to select a strain
imageadd: added an icon for a strain button
/:cl:

### CODE REVIEW

**Comment by Butlerblock** [comment]
Not sure if this is applicable to github feedback but I believe that hud bloat is enough as it is. I feel that even evolve should not have been added to hud and that hud should be restricted to purely caste/strain abilities or abilities applicable to all xenos such as resting.

**Comment by TheManWithNoHands** [comment]
> Not sure if this is applicable to github feedback but I believe that hud bloat is enough as it is. I feel that even evolve should not have been added to hud and that hud should be restricted to purely caste/strain abilities or abilities applicable to all xenos such as resting.

Fun fact. You can fully hide the buttons at the top for your ability, with a button thats next to them. And you can assign hotkeys to ALL of those ability buttons as well. You can rigth now, make the screen more free ingame. And my Pr wont change that.

**Comment by Butlerblock** [comment]
> 
> Fun fact. You can fully hide all the ability buttons at the top, with a button thats next to them. And you can assign hotkeys to ALL of those ability buttons as well. You can rigth now, make the screen more free ingame. And my Pr wont change that.
> 
> I get your point, but there are optiosn to fully remove any blocking of your screen. This wont effect people that really care about sceen space.

Not within the scope of this PR, but ability icons should be able to be hidden individually. Currently abilities need to be unhidden to show coolodowns, which is where the original bloat concern comes from.(yes most cooldown refresh shows in chat but thats poor design to begin with)

**Comment by TheManWithNoHands** [comment]
> Not within the scope of this PR, but ability icons should be able to be hidden individually. Currently abilities need to be unhidden to show coolodowns, which is where the original bloat concern comes from.(yes most cooldown refresh shows in chat but thats poor design to begin with)

Your rigth that it is not in scope within this PR. Because that would be a fundemental change to a lot of things.
If you think that is something that should be done, make an ideasguys post about it, or do it yourself. I managed to do hud changes, so its not the hardest in the world if my dumbass can do it.
If you dont have any further notes regarding my pr, of a diffrent topic, i say rather continue this discussion on discord or the forums.

**Comment by TheManWithNoHands** [comment]
Closed because i just learned there is a hud rework deep in development.

**Pull request closed without merging**
