### PR TITLE
doubles facehugger generation rate

### PR DESCRIPTION
**Pull request by Detective-Google**
# About the pull request

doubles the facehugger automatic generation rate

# Explain why it's good for the game

every xeno I've heard feedback from since the change has said it's too low

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl: detectivegoogle
balance: morphers generate huggers twice as fast
/:cl:

### CODE REVIEW

**Comment by HeresKozmos** [comment]
lgtm

**Comment by Red-byte3D** [comment]
You could just make them generate huggers faster if you put bodies in them, this way you can afford a bigger buff by also adding a way of putting work in to get better rewards

**Comment by Nanu308** [comment]
Xeno captures goes

**Review by Nanu308 — APPROVED** [review]
Live check will commence later date and see if it has issues with carriers etc. being unneeded

**Review by Drulikar — CHANGES_REQUESTED** [review]
Do you think you could tie this to whether the queen is on ovi or not? As in buff is only active when she is ovi?

**Comment by Detective-Google** [comment]
> Do you think you could tie this to whether the queen is on ovi or not? As in buff is only active when she is ovi?

I think I could probably get something to that effect to work but making sure it only affects the correct hive, etc is bug fixing out of the scope for this PR, which was really just a webedit number tweak to shush the people decrying the PR adding this system as "ruining" carrier. 

in less words, I don't have any interest in devoting a lot of time to this and you're welcome to close it for someone else to change instead.

**Comment by Drulikar** [comment]
See above then

**Pull request closed without merging**
