### PR TITLE
Whiskey Outpost typo 

### PR DESCRIPTION
**Pull request by moltoretardo**
## About The Pull Request
Fixes the typo "Captian" in one of the WO announcement

## Why It's Good For The Game
Captain Naiche deserves it

## Changelog

:cl: Molto
spellcheck: fixed Captian
/:cl:

### CODE REVIEW

**Review by harryob — APPROVED** [review]
captain naiche salutes you

**Review by fira — APPROVED** [review]
oops... i still think it'd be great if someone wrote these with lore in mind, because this was literally written as filler

**Review by Shad0vvs — APPROVED** [review]
This code is looking very cool.

**Comment by hotimep** [comment]
fuck you captain naiche

**Pull request merged**
