### PR TITLE
[Solaris Ridge] Aesthetic Update

### PR DESCRIPTION
**Pull request by Steelpoint**
# About the pull request

Effects a significant aesthetic makeover over parts of Solaris Ridge. 

This PR focuses more on the Northern half of the colony. 

(please use MapDiffBot2 to view changes)

# Explain why it's good for the game

I feel a long term goal of mapping should be to enhance our older maps to make them look far more "alive", lived in and aesthetically pleasing. But keeping the spirit of the similar layout of the original map. 

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl:
maptweak: A significant amount of aesthetic upgrades to Solaris Ridge have been added. 
/:cl:

### CODE REVIEW

**Comment by Steelpoint** [comment]
This project might take longer since I'm going to be doing more of the colony up.

**Comment by Steelpoint** [comment]
I'll work on the southern half of the colony in a separate PR but I think this is a good place to work from with what I've done thus far.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by Steelpoint** [comment]
Likely going to have to re-do the PR since I can't solve map merge conflicts to save my life.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Pull request closed without merging**
