### PR TITLE
New Marine HUD Icons, HUD Icon standardization

### PR DESCRIPTION
**Pull request by Kitsunemitsu**
# About the pull request
This PR does a few things;
1. It standardizes the Tassels below the HUD Icons. Bronze for Non-Department Head Officers (PO, CE is below ASO now, Doc, SO, IO, Researcher, Doctor), and Gold for Department heads (CMO, CMP, ASO, XO.)
QM now gets the same bronze border of the SEA, for being a senior NCO, and now has a bronze tassel.
I believe that's how it was originally intended to be, and I'm just standardizing it.

2. It gives a new icon to the ASO, something different than a silver star, it's now a gold triangle,  made of 4 shades, one for each department (Flight, Requisitions, Engineering and Intelligence.

~~3. It brings CM-SS13 in line with the geneva conventions; the Doctor, CMO and researcher icon have all been changed to remove all Red Crosses. They are now officers, so I've given them the officer color scheme and bronze tassel. You can see it below.~~
No Longer true. Medical Icons are unchanged, with a recommendation put below.

4. IO icon has been moved back with the other marine huds.

# Explain why it's good for the game
Some standardization among Marine Hud icons, adds back in the gold tassels, removes a pair of geneva convention violations, and adds in a new ASO icon to remove that old placeholder one 

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>
New ASO Icon:  image

</details>

# Changelog

:cl:
imageadd: added a new Marine hud icon for some officers.
/:cl:

### CODE REVIEW

**Comment by Kitsunemitsu** [comment]
image

Here's some old ideas I had for Squad Leader without ASL status and the gunship pilot

**Review by ItsVyzo — CHANGES_REQUESTED** [review]
Kindly revert the color of the medical doctors back to red.

It does **NOT** violate the Geneva Conventions.

https://www.icrc.org/en/document/video-games-get-real

https://discord.com/channels/150315577943130112/746325423289401395/928276150948601866

**Comment by Kitsunemitsu** [comment]
> Kindly revert the color of the medical doctors back to red.
> 
> It does **NOT** violate the Geneva Conventions.
> 
> https://www.icrc.org/en/document/video-games-get-real
> 
> https://discord.com/channels/150315577943130112/746325423289401395/928276150948601866

Is it only on a white background?

**Comment by Kitsunemitsu** [comment]
Reverted back, Will toss a few ideas in a sec
image

**Comment by Kitsunemitsu** [comment]
This is the current set:

image

This is a set I recommend to standardize it with other officer roles
image

**Comment by ItsVyzo** [comment]
> Reverted back for now, Here's an idea to standardize it with other officer This is the current set:
> 
> image
> 
> This is a set I recommend to standardize it with other officer roles, CMO with gold to match the CMP, XO, CE, etc and Doctors with the bronze tassel like other non-department head officers. image

That should be fine. Not sure how to feel about the gold. That aside, you have duplicate icons which is why Linters is going off.

**Comment by Kitsunemitsu** [comment]
I might have accidentally pushed again, GH has been a bit fuckey with CM code.
I'll review it in the morning

**Comment by Blundir** [comment]
Thank you for your pr, but we don't need to make current icons for non WO modes to look more like WO ones, also i don't think that these listed changes are needed.

**Pull request closed without merging**
