### PR TITLE
Rosary and Character Creation Stuff

### PR DESCRIPTION
**Pull request by Geevies**
## About The Pull Request

Makes rosaries an accessory, so you can wear it on your uniform. You can also wear it on your mask slot to hang it around your neck.

Additionally, adds a Show Vanity Gear option to Character Creation, your equipped custom loadout items will now render on your character's preview if this option is selected.

image

image

image

## Changelog

:cl:
add: Made rosaries into an accessory, so you can attach it to your uniform now. You can also wear it on your mask slot to hang it around your neck.
add: Made vanity items (loadout items and prescription glasses) appear in the character creation menu, under the Show Vanity Gear option.
/:cl:

### CODE REVIEW

**Review by harryob — APPROVED** [review]
lgtm, i think we can have faith that your two lines of mapping changes are okay, but code monkeys are literally incapable of reading .dmms

**Review by fira — APPROVED** [review]
looks good at a glance to me too, need sprite check

**Review by nauticall — APPROVED** [review]
yep, sprites look good 👍

**Comment by monkeysfist101** [comment]
Please revisit the description. As I understand it, Catholics do not consider the rosary to be a necklace and it is frowned upon to wear it as such.

**Review by Agameofscones — APPROVED** [review]
lgtm

**Comment by Geevies** [comment]
> Please revisit the description. As I understand it, Catholics do not consider the rosary to be a necklace and it is frowned upon to wear it as such.

i did some research on this when it was originally raised, and as far as i could see it's "iffy" but not really bad to do, especially if you're wearing it as a reminder to pray to it and not just as a fashion accessory. this makes sense especially for a marine who might want it close-at-hand during a combat drop

**Comment by Geevies** [comment]
ok i contacted a Catholic friend of mine and they say no so i'll revise it in a hot minute

**Pull request closed without merging**
