### PR TITLE
Ravager and Hedgehog changes

### PR DESCRIPTION
**Pull request by GoldenDarkness55**
# About the pull request

Nerfing base ravager by trimming the excess power without changing how the kit plays at its core. Buffing hedge rav and slightly fleshing out the management of shards unique to the strain.

# Explain why it's good for the game

Balance good.

Base rav changes pretty straightforward - maintaining current empower combo, but nerfing excess shield and stun. +1 slash per cd reset to force rav to stay longer to pull it off - should have significantly less leeway against large groups and be easier to punish.
Empower cd buff to compensate for second empower cast nerf, since the cooldown for empower starts counting on first cast and experienced players used the long timer to empower twice in rapid succession/skip a portion of the cooldown - the cooldown is effectively longer now than it was before.
Scissor cut felt rather underused and this buff should help make it more relevant, especially against static marines/sieges now that the shield is weaker.

As for Hedge - speed reduction to this extent without any dashes just doesn't work whatsoever, (for more evidence look at oppressor prae suffering the same issue) so this has to go as a prerequisite for this strain ever being good. Slash damage cut to reduce excessive power and punishment in 1v1 and put more emphasis on this being a tank/support/debuff strain (ideally it would get slash damage or slash speed during shard lockout to reward risky aggressive play and not just an escape tool, but im gonna leave that to someone who can code if someone likes the idea).
Shield duration feels a bit too low currently, but this might end up making it overtuned, unsure. Shard damage raised cause shield isn't threatening enough and marines - myself included - often happily magdump into it even PB to kill the hedge faster.
Shed and slow durations reduced because they're horrendously excessive. Slow on 3 might be too short though, considered 4-5 instead but best to test first.
Shard toss range increased to help with engagements, likely still needed despite the speed buff, rest of abilities has separate ranges.
Shard "economy" changes to put more emphasis into this unique system being a thing - currently it might aswell not exist, the shards regenerate nigh instantly so the ability costs do not matter. These changes should put more importance on managing it and reward marines for good play - for example if they didn't feed the shards back up by shooting during the shield timer, it's going to take the hedge longer to recover its armor, making it take slightly more damage. Shard per slash gain to help out with rare situations where it's doing well yet struggles to recover shards due to marines either not shooting at all or using exclusively low RoF weapons.

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl:
balance: Base rav cooldown regain per slash reduced (4 to 3), empowered charge stun duration reduced (2 to 1.3), empower duration increased (5 to 6.5), empower cooldown reduced (22 to 18), duration window for second empower cast reduced (15 to 6), base shield gain reduced (75 to 50), shield gain per marine reduced (80 to 50), maximum empower targets increased (5 to 6), scissor slash cooldown reduced (10 to 6), and damage reduced (45 to 40)

balance: Hedge rav doesn't lose speed anymore, but loses 10 slash damage instead. Shield duration increased (2 to 2.5), Fire Spikes shard range increased (5 to 6), Spike Shed shard lockout duration reduced (30 to 15), shard lock speed reduced to maintain same speed as previously. Shard damage increased (5 to 8), shard slowdown duration reduced (8 to 3), shard gain per tick reduced (10 to 5), shard gain per bullet reduced (20 to 10), added shard gain per slash (15)
/:cl:

### CODE REVIEW

**Comment by cm13live** [comment]
This pull request has been mentioned on **CM-SS13**. Please provide feedback here:

https://forum.cm-ss13.com/t/whats-with-all-the-xeno-overhauls-lately/2753/59

**Review by morrowwolf — CHANGES_REQUESTED** [review]
Drop the shield from empower a bit more.

Otherwise, willing to TM.

**Comment by GoldenDarkness55** [comment]
Would rather test before reducing it further - might be better to continue lowering strength and raising max targets so it's less oppressive vs smaller groups but doesn't become too glass vs murderballs.
Hopefully the code that checks for targets doesn't start lagging if more is permitted.

**Comment by morrowwolf** [comment]
If I haven't gotten to this by this coming Monday remind me.

**Comment by GoldenDarkness55** [comment]
Got rid of the charge cd reduction (14 to 13), dunno why I added that in the first place since it made no sense, brainfart.

**Comment by GoldenDarkness55** [comment]
> If I haven't gotten to this by this coming Monday remind me.

bump.

**Comment by GoldenDarkness55** [comment]
Knockback change was a bit excessive, reverted. Gave a little bit of stun back and extended empower by half a second to further compensate the extra slash.
Raised hedgehog shard damage a bit more since magdumping it wasn't spicy enough and added shard gain per slash to help out in rare situations where it was doing well but running low on shards due to guns with low RoF.
Gonna update CL and descript when these get pushed onto tmerge.

**Comment by GoldenDarkness55** [comment]
Bumped the empower cd up by 2.
Some concerns about base rav shield being overnerfed a bit but might be just people needing to adjust. Hedge possibly needing +1s slow duration or some similar minimal tweaks but will have to see in long run.

Think it's pretty much fine now unless new issues surface/feedback over the next few days or you wanna tweak things.

**Comment by harryob** [comment]
> > If I haven't gotten to this by this coming Monday remind me.
> 
> bump. While im at it, can changes be made while it's Tmerged? Will they just be applieded next round?

no, they need to be manually updated. when this happens, you get the "[cm13-github](https://github.com/cm13-github) added a commit that referenced this pull request [16 hours ago](https://github.com/cmss13-devs/cmss13/pull/3729#ref-commit-6f81d6f)" thing

**Comment by morrowwolf** [comment]
I'm generally OK with these changes. We'll do tweaking as needed.

**Pull request merged**
