### PR TITLE
Xeno Crit Health Indicator

### PR DESCRIPTION
**Pull request by Geevies**
## About The Pull Request

Added a Xeno Crit Health Indicator.
Demo: https://cdn.discordapp.com/attachments/915349747550785588/982657881092534313/2022-06-04_16-48-51.mp4
Ported (and tweaked) from: https://github.com/tgstation/TerraGov-Marine-Corps/pull/9930

## Why It's Good For The Game

More info for allies is good.

## Changelog

:cl:
add: Added a xeno crit health indicator.
/:cl:

### CODE REVIEW

**Review by Shad0vvs — APPROVED** [review]

**Comment by hotimep** [comment]
+2 should keep in the guts song when a xeno goes into crit

**Comment by novaepee** [comment]
Sometimes, you must watch in despair when your sisters lose all their crit health so fast.

**Comment by FosterGrime-Heymynameslouie** [comment]
clicking on the video automatically downloads something and it gives me a mini heart attack

cool pr

**Review by thwompa — APPROVED** [review]
yummy sprites

**Pull request merged**
