### PR TITLE
CE APOLLO PDA

### PR DESCRIPTION
**Pull request by Blundir**
# About the pull request

Adds the same PDA working joes have to CE, but with a unique sprite and loading screen. A unique tool for CE to interact with AI and working joes, not to mention CE doesn't have many unique items to begin with, for a job that has to oversee the AI, having such tool is merely a qol.

Sprites by me.

sMDwrn0E0K

dreammaker_NLdfLnLh6O

# Changelog
:cl:
add: adds unique APOLLO pda to CE vendor
/:cl:

### CODE REVIEW

**Comment by deathrobotpunch** [comment]
We are so fucking back…

**Comment by Blundir** [comment]
> We are so fucking back…
> 
> edit: CE can access lockdown and nerve gas using the normal console, why not the PDA?

No idea, in pda CE just can't, I haven't edited the code regarding it

**Comment by Blundir** [comment]
Updated it to be able to do nerve gas and lockdown.

**Review by nauticall — APPROVED** [review]
sprites 👍

**Review by harryob — APPROVED** [review]

**Pull request merged**
