### PR TITLE
Floor Fixes

### LINKED ISSUE #1054: Plasteel Rods turn into Metal Rods
## Description

Plasteel rods are turned into metal rods upon recovery from flooring process.

## Difference between expected and actual behavior

Such alchemy shouldn't be possible.

## Steps to reproduce

1. Use plasteel rod on floor tile (tested on Almayer) to reinforce the floor.
2. Use a wrench on the new floor.
3. Get metal rod back.

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

### LINKED ISSUE #1055: Reinforced floor has wrong tool in description
## Description

The description of a reinforced floor (the one created by using rods on a tile) states that it can be removed with a crowbar, but you actually need a wrench to remove it.

## Difference between expected and actual behavior

Descriptions should be accurate.

## Steps to reproduce

1. Use crowbar on reinforced floor (doesn't work).
2. Use wrench on reinforced floor (works).

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

### PR DESCRIPTION
**Pull request by PhantomEpicness**
## About The Pull Request
Fixes #1054
Also makes the to_chat when reinforcing floors better

someone please make a new turf sprite for reinforced floors 

## Why It's Good For The Game
bugbash

## Changelog

:cl:totalepicness5
fix: Fixed plasteel rod to metal rod alchemy with reinforced floors
spellcheck: Fixed some awful to_chats in reinforced floors.
/:cl:

### CODE REVIEW

**Review by morrowwolf — CHANGES_REQUESTED** [review]
Change the tool_flags rather than the tool to do the task

**Comment by Watermelon914** [comment]
I'm also pretty sure this isn't a fix. Using a wrench to remove reinforced floors is actually how you're supposed to remove reinforced floors.

**Comment by Diegoflores31** [comment]
balance tag for a chance on how reinforced floor works lmao ? (its useless)

**Comment by Diegoflores31** [comment]
> I'm also pretty sure this isn't a fix. Using a wrench to remove reinforced floors is actually how you're supposed to remove reinforced floors.

-the text description says remove with crowbar thats is why is being changed likely.
-also if you forgot to read the issues on the PR the floor turns plasteel rods into metal rods and this PR does fix that.

**Review by morrowwolf — CHANGES_REQUESTED** [review]
Change the tool flag to wrench and revert the change of using a crowbar to bring the cover up.

**Review by stanalbatross — APPROVED** [review]

**Pull request merged**
