### PR TITLE
Adds Sensor Towers To All Maps

### PR DESCRIPTION
**Pull request by Steelpoint**
# About the pull request

Adds sensor towers to all maps.

The towers are placed in generally xeno controlled areas, but not too far back to be impractical for Marines to take and hold,

# Explain why it's good for the game

Consistency.

Furthermore, sensor towers give both sides a general area to fight over. The current towers are generally in xeno controlled areas but are forward enough to encourage both sides to realistically fight over it.

Furthermore this should help in Marine end-games by letting them track the last remaining xenos faster instead of relying on blind searching.

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl:
mapadd: Sensor Towers have been added to all maps. 
/:cl:

### CODE REVIEW

**Comment by morrowwolf** [comment]
Haven't forgotten this but I'm thinking about it.

**Review by morrowwolf — CHANGES_REQUESTED** [review]
image

These warning stripes on Solaris should be contiguous so like remove them from the pathway.

Fiorina looks fine.

Remove Shivas changes as that whole map is being reworked right now.

Put LV624's tower somewhere in the lake area. Everywhere else it's like smack dab in the middle of a hive and once things starting going marine favored the lake area is usually opened up anyhow just by how the map plays.

New varadero move it north to here-ish: 
image

Again we don't really want it right outside a hive location like that.

Soro: image

You'll want to move it off the wall as it's clipping through pretty bad here.

Otherwise, I think we'll go ahead with this idea. Objectives gameplay is a goal.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by Steelpoint** [comment]
Changes made

**Review by morrowwolf — CHANGES_REQUESTED** [review]
Looks like some accidental changes left on New Varadero and LV624

**Comment by Steelpoint** [comment]
I'll do a new PR for the change since I hate map merge conflicts.

**Pull request closed without merging**
