### PR TITLE
If ice is so good why isn't there

### PR DESCRIPTION
**Pull request by private-tristan**
Ice v2?
# About the pull request
Ice V1 and Ice V2 are back for the holiday season!

Ice V2 and V1 are now playable maps with voteweight 0.5 and a min player count of 130

I've fully tested that the elevators work. This PR builds off of beagle's Ice PRs

# Explain why it's good for the game
The mood is right
The spirit's up
We're here tonight
And that's enough

Simply having a wonderful Christmas time
Simply having a wonderful Christmas time
# Testing Photographs and Procedure
Tested the elevators, and buttons, they work.

# Changelog
:cl:
add: Ice V1 and Ice V2 are back for the holiday season!
/:cl:

### CODE REVIEW

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by private-tristan** [comment]
I'll fix linters tomorrow

**Comment by vero5123** [comment]
ice is nice

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by private-tristan** [comment]
it's so over

**Pull request closed without merging**
