### PR TITLE
Changed pulse_line for more realisml

### PR DESCRIPTION
**Pull request by Lengord**
## About The Pull Request
1) Changed pulse line sprites in human_dark hud
2) Now they show approximate damage, heart damage, and time left to revive. Works only if marine wear helmet.

    Ps. code is Frankestein from what i could understand.

## Why It's Good For The Game
1) For the sake of realism
2) Now pulse line is useful and not just decoration. No need to buy hud as marine to know if he damaged. More reasons to wear helmet.

## Changelog

:cl:
add: Changed pulse line sprites and function in dark hud, now they show approximate damage, heart damage, and time left to revive. Works only if marine wear helmet.
/:cl:

### CODE REVIEW

**Comment by Strobia** [comment]
what.

**Comment by Kuusday** [comment]
the fuck.

**Comment by Superwelder** [comment]
If this PR only alters the dark UI for humans, why would we want to give a tactical advantage to people using dark UI over others? We have this item in CM called a health analyzer that takes a few seconds to use without moving, if you are not trained, to obtain medical information. This PR would give even more information(heart damage and brain death timer) than a scan would give you without the time investment. I can understand wanting to encourage wearing a helmet but this aint it chief.

**Comment by Lengord** [comment]
As you said, you can do same with scanner so not much advantage. It takes part of the screen kind of disadvantage. It just always bugged me that this pulse line was in the game but had no use.

**Comment by Shad0vvs** [comment]
> If this PR only alters the dark UI for humans, why would we want to give a tactical advantage to people using dark UI over others? We have this item in CM called a health analyzer that takes a few seconds to use without moving, if you are not trained, to obtain medical information. This PR would give even more information(heart damage and brain death timer) than a scan would give you without the time investment. I can understand wanting to encourage wearing a helmet but this aint it chief.

It already has a tactical advantage.

**Comment by Superwelder** [comment]
> As you said, you can do same with analyser, so not much advantage. It takes part of the screen, kind of disadvantage. It just always bugged me that this pulse line was in the game but had no use.

Not having to use the analyzer is an extreme buff. More than half of human players in a typical round do not have medical training to scan instantly. The scanner is an item you have to carry to provide this information. Yes, the scanners are easily acquired on the Almayer but the space it occupies is not free. The time it takes to scan is not free.  This would be the single largest buff to humans medical-wise since the sensor-mate was added. Furthermore, why would a standard marine have access to their heart damage in character? A medic could maybe understand relevant info about their heart but PVT Boot would have no idea about how to interpret data about their heart beyond "!Cardiac arrest!"

**Comment by Superwelder** [comment]
> > If this PR only alters the dark UI for humans, why would we want to give a tactical advantage to people using dark UI over others? We have this item in CM called a health analyzer that takes a few seconds to use without moving, if you are not trained, to obtain medical information. This PR would give even more information(heart damage and brain death timer) than a scan would give you without the time investment. I can understand wanting to encourage wearing a helmet but this aint it chief.
> 
> It already has a tactical advantage.

I am not sure if you are being cheeky here but with midnight UI at least, there is no more information conveyed from Dark UI that midnight UI does not have.  I can't speak to all the UIs, but these two at least convey the exact same info. I am not comfortable with actively giving medical info beyond the basics in one specific UI without applying it to all officially supported UIs.

**Comment by Lengord** [comment]
Yeah i agree its buff, but le me explain my point. Health shows red when you have more than 70 dmg, meant just to give marine a hint that they need see medic (what oxycodoned baldie may not realise), still 130 health to go and without analiser you can't tell how bad you damaged. Heart dmg shows two stages bit damaged heart (again better see doc and not just die and be revived 6 times in push and then become heartbroken), and heartbroken ( so peridaxoned doesn't rush to sertain death. if he have no peridaxon he will die anyway). And if marine doesn't know anything about their heart, why pulse line was there at all?

**Comment by Superwelder** [comment]
> Yeah i agree its buff, but let me explain my point. Health shows red when you have more than 70 dmg, meant just to give marine a hint that they need see medic (what oxycodoned baldie may not realise), still 130 health to go and without analiser you can't tell how bad you damaged. Heart dmg shows two stages bit damaged heart (again better see doc and not just die and be revived 6 times in push and then become heartbroken), and heartbroken ( so peridaxoned doesn't rush to sertain death. if he have no peridaxon he will die anyway). And if marine doesn't know anything about their heart, why pulse line was there at all?

Ok, given we are discussing a UI change, it would help loads to have some screenshots to compare and contrast. As to why does the pulse line exist? When Dark UI was added, it was cool to have the pulse 'animated' back when, as you can see today by using older UIs, there is not much animation. That is your answer. People thought it looked 'cool'. Not that people thought Dark UI conferred real tangible advantages to gameplay over other UIs.

**Comment by nauticall** [comment]
While it's nice, and there's some nice medical accuracy involved, I honestly don't see the point of this. The HUD is only visible to the person in question and 99% of people won't know what their abnormal ECG even means. For those that do, however, this gives an actual advantage over other HUD styles and encourages people to use dark HUD over, say, Midnight (stock SS13), as it instantly allows them to pull up a reference chart (or memorize the patterns) and determine for sure if their heart is damaged, something that not even medics can ascertain with 100% certainty, as all they can see is the deoxygenation symptom. 

Not to mention it makes no sense for the Marine to tell the medic/doctor that their heart rate is abnormal. The medic should be able to figure it out.

Overall, nice attention to detail. I can tell there's a lot of juice that went into this PR. But unless this is either added to the medic's side instead of the marine side somehow (by integration into the health analyzer perhaps), or added universally for all HUDs, this gives an unrealistic advantage and I'm against its implementation as-is.

**Pull request closed without merging**
