### PR TITLE
Optional Squad Briefing Rooms: Or, why I learnt to stop req queuing and love the squad

### PR DESCRIPTION
**Pull request by Warfan1815**
# About the pull request

Adds optional briefing rooms in place of long-rest bunks (moved closer to hangar) that don't replace standard briefing.

# Explain why it's good for the game

Gives SLs a platform where they can host anything they want. As well , if command wants to brief the SLs and then have the SLs brief command they can also do that.

The old squad briefing room PR was cool, its just it was replacing instead of adding. Here I hope to satisfy both camps.

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>
map

</details>

:cl:
mapadd: New Squad Briefings south and north of normal briefing! Feel free to use them to your heart's content.
maptweak: Moved long-rest bunks further north and further south of where they were originally
/:cl:

### CODE REVIEW

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by Warfan1815** [comment]
Merge Conflict Fixed

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by Warfan1815** [comment]
Should no longer conflict with #4440,

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Pull request closed without merging**
