### PR TITLE
CIC Revamp - Mark One

### PR DESCRIPTION
**Pull request by LC4492**
# About the pull request

This PR is part of a an "Almayer Revamp" plan that I've been trying to put into action, for today, the changes will cover the CIC area, trying to make it more efficient gameplay-wise and more coherent, while still being conservative and using the same approach as before. The changed area have been debugged and Im 98% sure it will work properly.

# Explain why it's good for the game

The changes made aims on keeping things more efficient by keeping working tools closer and more separated, while keeping a clean and good area of movement.

# Testing Photographs and Procedure

Captura de Tela (14)

</details>
 A photo of the changes made.

# Changelog
Fill out below or remove tags such as add: or code: if you did not do any such things. - Nanu

:cl: LCMS1
maptweak: Gave the guard post on the CIC entrance a extended table and a set of cameras. Installed doors to the CIC armory. Extended the Command Bubble to hold two Commanding Officers. Gave all overwatch consoles their own crew monitors and ash trays (Other small changes).  Removed the "medical records" console. Removed the "Tac-map" table (Other small changes).
/:cl:

### CODE REVIEW

**Comment by LC4492** [comment]
...I can repost one if necessary, but...that's not enough?

**Comment by LC4492** [comment]
:cl
add: Gave the guard post on the CIC entrance a extended table and a set of cameras. Installed doors to the CIC armory. Extended the Command Bubble to hold two Commanding Officers. Gave all overwatch consoles their own crew monitors and ash trays (Other small changes).
del: Removed the "medical records" console. Removed the "Tac-map" table (Other small changes).
/:cl

**Comment by LC4492** [comment]
That works?

**Comment by Nanu308** [comment]
> That works?

CL goes in the main PR Desc. I'll edit your desc. so you can see, but fill it out yourself.

**Comment by Nanu308** [comment]
Mapping itself is fine, but i am concerned about the design itself. The table seems a bit off with how it is now towards the "lobby" of the CiC. Secondly, the CiC bubble seems to be further away and out of range from viewing the SO consoles. Check this out a bit further and answer my comment made in Discord.

**Pull request closed without merging**
