### PR TITLE
Readds skull facemask and facepaint

### PR DESCRIPTION
**Pull request by irakligabunia**
# About the pull request
It readds two items that were removed in the past for no valid reason (in my opinion), since it was a targeted PR against a specific player I do not think it should've been removed.

# Explain why it's good for the game

It looks nice and fits the atmosphere, adding it will help players customize their characters without being too loud. 
The removal reason of "You'd get laughed at for wearing it IRL" is invalid, a lot of military and law enforcement people wear skull masks, punisher emblems and etcetra - this is especially evident in America (We're UA)
https://discord.com/channels/150315577943130112/746325423289401395/1168350579307860078
https://discord.com/channels/150315577943130112/827156857566265375/1145494273568022588
https://files.catbox.moe/4o3ag1.png
https://discord.com/channels/150315577943130112/604397850675380234/1094357565317586964 -- the person who made it admitting it was targeted.

# Testing Photographs and Procedure
I don't think it needs testing
</details>

# Changelog
:cl: stalkerino
add: readds skull facepaint and skull balaclava (blue and black)
/:cl:

### CODE REVIEW

**Review by harryob — APPROVED** [review]
repenting for my sins in the removal pr

**Comment by irakligabunia** [comment]
> repenting for my sins in the removal pr

you should speedmerge it then

**Comment by irakligabunia** [comment]
we ball

**Comment by Chrismmar** [comment]
I FUCKING KNEW IT I KNEW IT WAS REMOVED TO FUCK WITH ME, and now you bring it back less than a month after my cryo post huh. either this is ONE BIG COINCEDENCE, or I wasn't crazy. still not coming back either way.

**Comment by irakligabunia** [comment]
hi @Chrismmar , whilst i never agreed with its removal the return is not because of you or your cryopost its actually because of a bee plushie
and i forgot to make it the correct filepath
💀

**Comment by Chrismmar** [comment]
real interesting coincidence then huh, there seems to be a lot of those in this server

**Pull request merged**
