### PR TITLE
Adds NVG Auto Response

### PR DESCRIPTION
**Pull request by Birdtalon**
# About the pull request

[Request from Ethan](https://forum.cm-ss13.com/t/lack-of-mentors/4696/20)

Adds auto response to the Mentor AutoResponses on 

> "How to Recharge NVG Optics" with the following description. "NVG Optics can be toggled via a helmet visor. To switch between HUDs, simply click the icon in the upper left-hand portion of your screen. The Night Vision optic has roughly five minutes of use before needing to be recharged. To recharge the optic, use a screwdriver on your helmet to remove. This will remove all attached HUDs/optics. Take the Night Vision optic and place it in a recharger to recharge its battery."

# Explain why it's good for the game
# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl:
add: New auto response for how to recharge Night Vision Goggles for Mentors
/:cl:

### CODE REVIEW

**Comment by fira** [comment]
I'mt not sure this is the right "fix", it's very specific for a mentor reply, i'd argue the NVGs need some description added or be made more intuitive instead

**Comment by ihatethisengine** [comment]
or just revert them :100:

**Comment by Wintermote** [comment]
NVG's straight up need a revert back to how the used to work, not help tips

**Review by realforest2001 — CHANGES_REQUESTED** [review]
Please address comment from Fira.

**Comment by Birdtalon** [comment]
As changing or reverting the actual NVG item falls outside of what I was doing here which was just PRing a request from someone then I'll close this PR.

**Pull request closed without merging**
