### PR TITLE
Adds a new Gin Bottle design, visually different than that of the Vodka.

### PR DESCRIPTION
**Pull request by Kaboomkat**
# About the pull request

This PR adds a new Gin Bottle design, as the one currently in game is visually identical to the Vodka Bottle design, it is inspired in the Tanqueray London Dry Gin, and reflects the items' description, which states: "A bottle of high-quality gin, produced in the New London Space Station." Sprites made by me.

# Explain why it's good for the game

These Changes would benefit the game in a visual manner, as the gin bottle would be easier to identify from a vodka bottle.

# Testing Photographs and Procedure
  
<details>

https://i.imgur.com/ovpUNab.png

https://i.imgur.com/437rSGS.png

<summary>Screenshots & Videos</summary>

The old Vodka and Gin bottles side by side, and then, the new Gin bottle

</details>

# Changelog

:cl: Kaboomcat
imageadd: Updated the gin bottle sprite
/:cl:

### CODE REVIEW

**Comment by thwompa** [comment]
awesome first pr

**Review by nauticall — CHANGES_REQUESTED** [review]
image

here's a list of what I think you should change to match the artstyle more:

WHOLE SPRITE: Design's great! But you need to work on your coloring a bit. CM's artstyle uses limited, desaturated colors and has a specific style for how to use them.

🔴 RED: Make shading consistent. I'd recommend looking at existing drink bottles for reference on the shading guide for them. Key points: Use a limited amount of colors and keep it symmetrical.
image

🟡 YELLOW: Try to avoid using shades that blend together too well with each other. Try to 'checkerboard' them so that shades of the same color will only touch diagonally on corners. Again, look at preexisting drink bottles to see what I mean.

🔵 BLUE: Try to avoid using pure grays and whites, as CM's artstyle really doesn't like those. I'd recommend hue-shifting them to a more yellowish-white (like a cream color).

🟢 GREEN: Try to keep colors symmetrical and avoid having rogue dots like this.

**Comment by Kaboomkat** [comment]
Changed the design to this Frans F. Feiffner one: 
Tanqueray TRUE new by fran

**Review by nauticall — APPROVED** [review]
muuuuch better!

**Pull request merged**
