### PR TITLE
Adds Xeno QOL improvement by allowing for snow layers to be autocleared

### PR DESCRIPTION
**Pull request by Youbar**
To clear snow on Shivas Snowball and the likes, Xenos have to manually click for each layer of snow removed. This PR makes it so that one single click will continue to clear additional layers if they exist, thus serving as a small QOL boost.

Serves as a QOL boost for Xenos without fundamentally impacting game balance, similar to the automatic filling of sandbags mechanism.

## Changelog

:cl: Youbar
qol: Xenos can now clear several layers of snow with one click
/:cl:

### CODE REVIEW

**Review by harryob — COMMENTED** [review]
changelog needs to be structured like:
:cl: (your ckey)
qol: Xenos can now clear several layers of snow with one click.
/:cl
in order for the PR to be tagged properly + the changelog to generate correctly

**Review by stanalbatross — CHANGES_REQUESTED** [review]
fix your CL

**Comment by MusselMain** [comment]
Change is cool, but hopefully this doesn't destroy the effectiveness of snow tarps.

**Comment by Youbar** [comment]
> fix your CL

Done (I think)

**Pull request closed without merging**
