### PR TITLE
Pred buff

### PR DESCRIPTION
**Pull request by s5nt**
# About the pull request

Buffs pred armour a good bit, making them much less squishy. Also gives elites ceremonial capes because thats the price catto had to pay for this PR

# Explain why it's good for the game

makes pred more scary and not a free loot pinata

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl:
add: Allows pred elites to use the ceremonial cape
balance: Buffs pred armour
/:cl:

### CODE REVIEW

**Comment by Red-byte3D** [comment]
preds dont need more melee armor, its already extremly hard to kill them as xeno due to the buffs they received

**Comment by Red-byte3D** [comment]
also preds are supposed to be weak to flames, not resistant

**Comment by s5nt** [comment]
> preds dont need more melee armor, its already extremly hard to kill them as xeno due to the buffs they received

true tbh they were mainly squishy to bullets

**Comment by s5nt** [comment]
> also preds are supposed to be weak to flames, not resistant

getting hit by a flame shouldn't remove 50 percent of your health as it currently does

**Comment by Red-byte3D** [comment]
that doesnt matter, preds weakness is flames its the weakenss for a reaosn

**Comment by RainbowStalin** [comment]
You are changing melee armour from medio low, to high.

Its so over xeno bros. We will never be able to kill a pred again.

**Comment by s5nt** [comment]
TBH i thought damage from xenos used some other var than melee for some reason but ill revert it because the intention wasnt to buff pred against xenos (which is pretty fair rn)

**Comment by TheManWithNoHands** [comment]
If you want to make Preds stronger against marines, you need to give them a higher stat in the ``var/armor_bullet``

**Comment by Diegoflores31** [comment]
oh my god why is this PR even real ? 
the PR has less than 1 line of "why is good for the game"
pumps pretty much all the armors to TWICE the resistance. no videos , no photos no tests .

**Comment by Butlerblock** [comment]
> oh my god why is this PR even real ? the PR has 1 line of "why is good for the game" pumps pretty much all the armors to TWICE the resistance. no videos , no photos no tests . on top of that i am certain we have a "No exclusive number change" clause on the guidelines

not taking sides on this PR but why do you need photos or videos for a balance and apparel availability change

**Comment by Drulikar** [comment]
Nothing changed here is needed.

**Comment by wshuwshuwshi** [comment]
Hi man, this comment is genuinely trying to help you out!
I did some testing on a local host with an M4A3 pistol using normal and AP damage both to test the differences
A naked predator already takes 1/4 of the damage that a naked human would take from bullets
Human vs Normal ammo: ~40 damage per shot
Predator vs Normal ammo: ~10 damage per shot
Human vs AP ammo: ~25 damage per shot
Predator vs AP ammo: ~7 damage per shot

Now, this all is without any armor, so testing with armor
Against normal ammo, default clan armor reduced the damage taken by 1/2, so instead of taking ~10 damage per shot, they would take ~5 damage each time
Against AP ammo, the damage taken was not affected by armor as compared to nude, where-in they took ~7 damage per shot, with or without armor.

I hope this helps!

**Pull request closed without merging**
