### PR TITLE
Additional WO HUD Icons (by Kitsunemitsu)

### PR DESCRIPTION
**Pull request by nauticall**
# About the pull request

Additional WO Squad HUD icons for folks.

**Made by Kitsunemitsu, not me!!**

The icons added are for the following roles:

- Ground Commander (CO)
- Lieutenant Commander (XO)
- Honor Guard Squad Leader
- Honor Guard Weapons Specialist
- Veteran Honor Guard
- Honor Guard
- RO (bronze border instead of gold)
- Mortar Crew
- Head Surgeon (CMO)
- Field Doctor
- Chemist

# Explain why it's good for the game

More visual distinction is always good right???

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

taa daaaaa!
image

</details>

# Changelog

:cl: Kitsunemitsu, nauticall
add: Added WO HUD icons for several WO roles. See PR for more details.
/:cl:

### CODE REVIEW

**Comment by Troontjelolo** [comment]
I like most of these but (and this will hopefully not be ignored despite my Nobody (2021 starring Bob Odenkirk) status) I am not a big fan of the mortar icon. The border is fine, obviously, but the actual icon itself is not good. I kind of see where you were going with it, but it looks more like the end of a stream and it splashing back up. Now I get that it's difficult to make it look good seeing the sprite size limitations, but perhaps a bit more experimenting should be done.

**Comment by Kitsunemitsu** [comment]
Nope! I'm here. I don't want to be a pain to naut, but I don't think a single hud icon change will bother her too much. What do you recommend?
It's supposed to be a mortar arc and explosion.

**Comment by Troontjelolo** [comment]
> Nope! I'm here. I don't want to be a pain to naut, but I don't think a single hud icon change will bother her too much. What do you recommend? It's supposed to be a mortar arc and explosion.

I made some 'ideas', I'm not going to say they are objectively better but to _myself_ at least (sample size of 1) they look more 'mortar-like', so to speak.

From left to right:
Mortar shell, mushroom cloud, mortar firing a shell, close-up of a mortar (I do not like this one), mortar shell alt
image

**Comment by Kitsunemitsu** [comment]
First one looks great <3 I'll fix up and send it out

**Review by harryob — APPROVED** [review]
the code (23 lines) is fine

**Pull request merged**
