### PR TITLE
Resprites Tactical shotgun stock +  stock now comes standard on all tactical shotguns (yes you can remove it)

### PR DESCRIPTION
**Pull request by spartanbobby**
# About the pull request

See title

Remember: something that is self-evident to you might not be to others. Explain your rationale fully, even if you feel it goes without saying. -->

# Explain why it's good for the game

It's there, sitting, unused for years, yes it kinda sucks but the sprite is good and it makes the shotgun look cooler so we might as well let it be used

https://i.imgur.com/erbgUaK.png

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl: SpartanBobby, esselnek
add: tactical shotguns now come standard with their stock. Yes you can remove it if you dont want it
add: new tactical shotgun stock sprite done by esselnek
/:cl:

### CODE REVIEW

**Comment by c4xmaniac2** [comment]
says that it looks cooler yet doesn't include it in test and photographs, curious.

**Review by Zonespace27 — CHANGES_REQUESTED** [review]
add screenshot to PR

**Review by morrowwolf — CHANGES_REQUESTED** [review]
image
https://discord.com/channels/150315577943130112/964684928161808384/1156170132608012298

**Review by FransFeiffer — APPROVED** [review]
Awesome Sprote.

**Pull request merged**
