### PR TITLE
Attachable Riot Visor, alternative to #6843

### PR DESCRIPTION
**Pull request by IroquoisLou**
# About the pull request

Alternative to https://github.com/cmss13-devs/cmss13/pull/6843, this version gives the MP riot helmet item slots and better fire protection against fire, additionally it adds a riot visor to the Riot tech in brig, this version is an actual headgarb.

# Explain why it's good for the game

Makes MP riot helmets seem like actual riot gear.

# Testing Photographs and Procedure

<details>

image
image
image

</details>

# Changelog
:cl:
add: Added a riot visor headgarb to MP riot vendor and changed the MP riot helmet to being allowed to have slots
balance: Gave the MP riot helmet better protection against fire
maptweak: changed all instances i could find of the old (not vintage) Marine riot helmet to the one here.
/:cl:

### CODE REVIEW

**Review by Blundir — APPROVED** [review]
sprites look good

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Pull request closed without merging**
