### PR TITLE
Medical Re-Work

### PR DESCRIPTION
**Pull request by Pyrotechnics2**
# About the pull request

This P.R. is entirely aimed at making Medical quicker at what they do best, allowing for them to have everything they need right at their finger tips. It is also meant to reduce crowding that happens with mass causality events that require all hands on deck. By separating the most crucial pieces of equipment vertically leaving room for doctors both north and south in the Medical Bay instead of huddling in the middle. In addition to this is also creates some quality of life changes such as a nurses station for triage before doctors arrive, slightly extra field surgery supplies, better O.R. ergonomics, and easier chemical access for medics at briefing.

# Explain why it's good for the game

This P.R. not only cleans up the Medical Lobby but also stream lines the Medical Bay and processes for surgery, recovery and chemicals. Allowing for high efficiency when it counts most. In addition it will also allow any medics to place an order for meds right when they wake up, so they can gear up and grab the meds while still at the briefing

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Capture5

</details>

# Changelog

:cl:
PYRO MEDICAL RE-WORK; P.R. NOTES
;
; Mission Statement - Make medical more efficient, inviting and smooth flowing, improve surgery flow, chemical delivery to medics, and improve equipment locations
;
; NURSES OFFICE P.R.(#3054 26-APR-23) * IS MAINTAINED * 
;
- mapadd: AUXILIARY STORAGE
- mapadd: NURSES STATION; CENTRAL LOCATION ALLOWS NURSE TO HELP WOUNDED IN LOBBY
- mapadd: SMARTFRIDGE EAST MEDICAL; ALLOW MEDICS TO GRAB MEDS FROM BRIEFING
- maptweak/add: CHEMISTRY FLOW IMPROVED; EXTRA SMARTFRIDGE, ALLOWS MEDICS TO GET MEDS AT BRIEFING
- maptweak/add: SECOND SURGICAL WEBBING TO FIELD SUPPLY STORAGE; OCCASIONALLY 2 FIELD DOCS ARE UTALIZED
- maptweak/add: SECOND SURGICAL SUPPLIES CLOSET IN AUX STORAGE; OCCASIONALLY 2 FIELD DOCS ARE UTALIZED
- maptweak: CHEM, WHITE, AND BIOHAZARD CLOTHING TO AUX. STORAGE
- maptweak RECOVERY WARD; ALLOWS EASY SCANNING AND TREATMENT OF WOUNDED
- maptweak: RELOCATED CRYO; TO MAKE WAY FOR MORE CRITICAL INFRASTRUCTURE
- maptweak: SURGICAL FLOW IMPROVED; SLEEPER DIRECTLY IN O.R. TO LESSEN DRAGING RELATED BRUTE DAMAGE AND SCANNING TIME, BETTER POSITION FOR ASSISTING NURSE TO STAND AND ADMINISTER BLOOD OR PRINT LIMBS
- maptweak: RELOACTED FIELD SURGERY SUPPLY; EASIER ACCESS, CONVIENT LOCATION
- maptweak: RELOCATED SCANNER CRATE TO AUX. STORAGE; EASIER TO MOVE ONTO ALAMO
- maptweak: REDUCED TOTAL BEDS FROM 12 TO 10
:cl:

### CODE REVIEW

**Comment by ItsVyzo** [comment]
You didn't keep the new lobby changes it seems. recommend keeping it since it was just changed (the lobby).

Also, what the hell is this?
image

**Review by ItsVyzo — CHANGES_REQUESTED** [review]
You didn't keep the new lobby changes it seems. recommend keeping it since it was just changed (the lobby).

Also, you seem to have forgotten something... 😅
image

**Comment by Huffie56** [comment]
> You didn't keep the new lobby changes it seems. recommend keeping it since it was just changed (the lobby).
> 
> Also, you seem to have forgotten something... 😅 image

personaly to avoid that i create an empty map
copy the part of the map i want to modify
then i put back the modification on the original map.

**Comment by Pyrotechnics2** [comment]
> You didn't keep the new lobby changes it seems. recommend keeping it since it was just changed (the lobby).
> 
> Also, you seem to have forgotten something... 😅 image

Thanks for the catch mate, remerged and that oopsie is now fixed, but I believe all the changes happened to the nurses office, which I did not touch, if I missed something I am happy to remerge

**Comment by Nanu308** [comment]
Your changelog is written wrong in its entirety, format wise that is.

Look at other pr's or follow the draft outlined when you make a PR

**Comment by Nanu308** [comment]
Also, the entire map format is wrong.

 Use TGM map formatting

**Comment by Pyrotechnics2** [comment]
> Your changelog is written wrong in its entirety, format wise that is.
> 
> Look at other pr's or follow the draft outlined when you make a PR

Apologies for that, first real P.R. , this has been remedied.
Beginning the reformat of the map to TGM

**Comment by Pyrotechnics2** [comment]
Map has been formatted in TGM

**Comment by Pyrotechnics2** [comment]
Updated screenshot of medical
Capture5

**Comment by Pyrotechnics2** [comment]
Going to close this and reopen it as I think I messed up quite poorly by merging the master to re-sync my fork and have to re-brank my fork for this project and pull request from that branch...do this the correct way

**Pull request closed without merging**
