### PR TITLE
Adds USCM Patch to Uniforms

### PR DESCRIPTION
**Pull request by MobiusWon**
# About the pull request
Adds the USCM ~and Falling Falcons~ patch automatically to vended uniforms.

**EDIT: Per the Technical Manual as @morrowwolf shared, only the USCM patch is added now.**

# Explain why it's good for the game

Get on the ready line Marines!

This is a straightforward PR imo, it looks cool and is lore accurate.

Like rank pins, the ~unit patch~ and USCM patch are a standard part of the USCM uniform and all Marines aboard the Almayer would be wearing one. This can be found in the movies as well as technical manuals for the Marines. It also adds some “esprit de corp” for the Falling Falcons USCM, now every player down to the newest one can take pride fighting for liberty.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

image

</details>

# Changelog

:cl:
NervanCatos
add: Uniforms vend with USCM patch.
/:cl:

### CODE REVIEW

**Comment by MobiusWon** [comment]
> I don't see the "why its good for the game part" you can already vend it and choose it in loadout, why force it?

Like rank pins, the unit patch and USCM patch are a standard part of the USCM uniform and all Marines aboard the Almayer would be wearing one. This can be found in the movies as well as technical manuals for the Marines. It also adds some “esprit de corp” for the Falling Falcons, now every player down to the newest one knows what unit they fight for by examining their uniform.

**Comment by Birdtalon** [comment]
I think this should stay as it is - a customisation option. I don't think your "Why it's good for the game" is strong enough to make this a mandatory thing.

**Comment by GrrrKitten** [comment]
I feel like this would be good for the PR feedback forum but there are two things I want to state: 1, if you use armor with shoulders, these dont show up. same if you roll up your sleeves, so most people wont be having it still.

2) after rewatching the movie yesterday, I really feel like this is part of the outfit we are missing. our basic USCM uniform is really one of our worst aesthetic choices that I feel this PR helps significantly

**Comment by Skatuk** [comment]
You can remove patches anyway, don't see the problem.

**Comment by irakligabunia** [comment]
> You can remove patches anyway, don't see the problem.

"most people already dont use this cause it just adds even more work to the round start, I think this is a really good addition" wouldnt this apply then lo

**Comment by MobiusWon** [comment]
> > You can remove patches anyway, don't see the problem.
> 
> "most people already dont use this cause it just adds even more work to the round start, I think this is a really good addition" wouldnt this apply then lo

The logical path is that the vast majority of players, like with rank pins, will not care about the patches being there or not. However, for the small percentage that do care, they still have an ability to remove it. If that small percentage somehow turnsout to be a large percentage then the PR can be reverted.

**Comment by morrowwolf** [comment]
image

Tech Manual quote. I think a solid middle ground that remains consistent and allows for customization still would be *just* the USCM patch.

**Comment by MobiusWon** [comment]
> image
> 
> Tech Manual quote. I think a solid middle ground that remains consistent and allows for customization still would be _just_ the USCM patch.

Thanks morrow, I have change the PR to reflect this lore.

**Review by Drulikar — APPROVED** [review]

**Pull request merged**
