### PR TITLE
Additional Visual Effect

### PR DESCRIPTION
**Pull request by BlackCrystalic**
# About the pull request

Port of some funny visuals from TGMC

# Changelog

:cl: BlackCrystalic
add: additional visual effects for explosions & bullet hits
/:cl:

### CODE REVIEW

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by deathrobotpunch** [comment]
need picturesss

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by Blundir** [comment]
Bullet impacts look fine, but not everything, not all effects were ported or not all are working, also the circle of light looks very buggy and old

dreamseeker_CBr4Gd5cls
dreamseeker_lRGJqotqHv

**Comment by Blundir** [comment]
Wall bullet impacts are working fine, but mob ones are either not working or not ported

dreamseeker_SN04JZ4LMo

dreamseeker_QEiPtQRmhh

**Comment by Blundir** [comment]
The shock wave effect ends too soon and the light remains for too long, also i think explosion power doesn't change the explosion effect size, like on tgmc
dreamseeker_xYtbtZxyU8

**Comment by Blundir** [comment]
The splatter and wall impact looks fine
dreamseeker_o4NjrEpwFe

dreamseeker_0ZWc3lsjZC

**Comment by Blundir** [comment]
Also there is rocket launcher back blast and gun fire smoke effects, in case you want to port them too.

**Comment by Blundir** [comment]
Also i think this was added by mistake
chrome_Yv4TN0YKyd

**Review by Zonespace27 — CHANGES_REQUESTED** [review]
Fill out your changelog correctly (you aren't mentioning everything you're adding) and add videos of the effects you're adding.

**Pull request closed without merging**
