### PR TITLE
Fix MRE Matchbook and Cigarrete

### PR DESCRIPTION
**Pull request by Spircen**
## About The Pull Request
Adds the MRE Matchbook and Cigarrete on the list of items with sprite to put on your helmet, and changes the weight size of the Matchbook to Tiny like the others.

Fix for Issue: https://github.com/cmss13-devs/cmss13/issues/194

## Why It's Good For The Game
Makes more easy to store your MRE Cig and Matches
image

## Changelog

:cl:
fix: MRE Matchbook and Cigarrete now can be store on helmets
fix: MRE Matchbook weight its now tiny
/:cl:

### CODE REVIEW

**Comment by MusselMain** [comment]
I wanted to mention that the MRE matchboxes are larger than the Smoke vendor matchboxes, (in inventory, a normal matchbox is tiny size, however the MRE matchboxes are considered small) this seems kind of silly.

**Comment by Spircen** [comment]
> I wanted to mention that the MRE matchboxes are larger than the Smoke vendor matchboxes, (in inventory, a normal matchbox is tiny size, however the MRE matchboxes are considered small) this seems kind of silly.

Thanks, going to change that for consistency.

**Review by Agameofscones — APPROVED** [review]
psoule

**Review by stanalbatross — APPROVED** [review]
code good

**Pull request merged**
