### PR TITLE
adds helmet camera viewing consoles to research and OT

### PR DESCRIPTION
**Pull request by iloveloopers**
# About the pull request
adds helmet camera viewing consoles to OT and Research
adds new camera console type that uses the overwatch network

# Explain why it's good for the game
its very frustrating not being able to see your creations on the battlefield without ghosting.
lets them spectate when they have nothing to do.

# Testing Photographs and Procedure

https://github.com/cmss13-devs/cmss13/assets/140007537/bf31802f-355f-4f1f-830b-e92dd7f5e156

# Changelog
:cl:
add: Added helmet camera viewing consoles
maptweak: Added helmet camera viewing consoles to research and OT
/:cl:

### CODE REVIEW

**Comment by iloveloopers** [comment]
seems to work

**Comment by Segrain** [comment]
...so, for no reason whatsoever, random PFC in ordnance workshop has better overwatch console than anybody in CIC? How does it _possibly_ make any sense?

**Comment by iloveloopers** [comment]
can I get a second opinion?

**Comment by iloveloopers** [comment]
I got an invite to a server so this is no longer an issue

**Pull request closed without merging**
