### PR TITLE
Hostile Survivor Rework

### PR DESCRIPTION
**Pull request by Steelpoint**
# About the pull request

Survivor players can no longer roll for a Hostile Survivor job role. 

All maps, with the exception of Chances Claim, have an ~10% chance to spawn all survivors as CLF operatives onboard a crashed CLF ship. 

The LV-624 CLF spawn has had its spawn odds increased. 

# Explain why it's good for the game

The current iteration of hostile survivor is a role that is detrimental to the survivor experience. They typically have an extraordinarily low impact on the round, are often likely to abandon the regular survivors to try to hide (thus depriving the survivors of vital aid), and most of the time are killed by the Marines with no real impact. 

My proposed change adds a new dimension to the survivor and groundside gameplay loop. Marines can no longer be 100% certain that the survivors are all going to be neutral (and xenomorphs who now have a risk to contend with more organised and armed survivors). This will also boost survivor cooperation in all scenarios, as regular survivors won't have to worry about a CLF who runs away, and if the survivors spawn as CLF, they all now work towards a common goal.

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl: Steelpoint, Drathek
del: Survivors can no longer select the Hostile Survivor job role. 
add: All maps, except for Chance's Claim, have an approximately 10% chance to spawn all survivors as hostile survivors. 
add: All players are automatically opted-in to being a hostile survivor by default. 
add: Players can opt-out of being selected for a hostile survivor spawn, or to only roll for a hostile survivor and not a regular survivor, via your Personal Preferences settings page. 
maptweak: All maps that feature hostile survivors have a spawn area for a crashed CLF ship, that spawns alongside the hostile survivors. 
balance: The odds of the CLF crashed ship spawn on LV-624 occurring has been increased slightly per this.
fix: Fixed trolly vehicle hard deletes
/:cl:

### CODE REVIEW

**Comment by JOHNBALD123** [comment]
DONT TAKE MY CLF ROLL AWAY I GOTTA GUN MARINES DOWN😭

**Comment by cuberound** [comment]
cool I wanted to say that it might need some touchup in the survivor intel point area but they already give little ...

**Comment by Skatuk** [comment]
I'd say leave the choice to roll CLF survivor, locker hiding will happen no matter what role, it all depends on the player. Its litterally at maximum 2 CLF that can spawn and the second slot unlocks at like 130 marines. If you die its skill issue you can still be recovered since you appear on the tacmap but it depends on the CLF if they remove the uniform..

**Comment by JOHNBALD123** [comment]
actually now when i think about it 10% is really good if it means all the survivors can be clf with a common goal to kill marines more clf brothers!

**Comment by Steelpoint** [comment]
> cool I wanted to say that it might need some touchup in the survivor intel point area but they already give little ...

I don't know the code for survivor intel but I suspect Marines will still get points for either recovering their bodies, or bringing them shipside as prisoners. A little challenge never hurt the Marines, and I believe the intel gain for survivors is currently minor.



> I'd say leave the choice to roll CLF survivor, locker hiding will happen no matter what role, it all depends on the player. Its litterally at maximum 2 CLF that can spawn and the second slot unlocks at like 130 marines. If you die its skill issue you can still be recovered since you appear on the tacmap but it depends on the CLF if they remove the uniform..

I appreciate this thought process, however, my personal view is that it would be better for the game if hostile survivors are an all or nothing affair as described in my OP. Perhaps this PR is just a mere stop-gap until someone with better game-sense and coding knowledge can create a better survivor system.

**Comment by Diegoflores31** [comment]
Not all maps are supposed to spawn CLF . Tridjent and sorokyne are meant to have UPP as the antagonists.

**Comment by Diegoflores31** [comment]
> Not all maps are supposed to spawn CLF . Tridjent and sorokyne are meant to have UPP as the antagonists and fiorina could use another faction too.

**Comment by Steelpoint** [comment]
> Not all maps are supposed to spawn CLF . Tridjent and sorokyne are meant to have UPP as the antagonists.

Sorokyne hosts a political refugee camp and Trijent is just another colony, and since they are all colonial outposts there remains the chance of a CLF presence being there, also the UPP spawns are neutral, not antagonistic.

**Comment by Steelpoint** [comment]
Main issue of review will be ascertaining how defendable the CLF ship should be. Some of the versions I mapped offer multiple bypass route for xenos/marines to enter that are not covered by the CLF barricades/sentry guns, whereas some others don't have these weaknesses.

**Comment by Steelpoint** [comment]
Stale comment

**Comment by Drulikar** [comment]
Stale exempt until it can get reviewed. For note I am fine w/ the concept of this, just don't have time at the moment to evaluate or test it.

**Comment by RainbowStalin** [comment]
This is just a personal prefrence, but could the hostile survs on fiorina just be a prison riot that somehow survived? Adding more flavour to hostile survs when they happen would be neat.

**Review by Drulikar — CHANGES_REQUESTED** [review]
Mentioned on discord, but I may as well make it an official request here since several people have requested and talked about how they aren't comfortable with being forced to be hostile so a preference for it should resolve that. Let me know if you have any issues with the code patch I provided and I can amend it as needed.

**Review by Drulikar — APPROVED** [review]
Code changes seem fine. Not exhaustively tested the map scenarios or anything though.

**Comment by coldironwarrior** [comment]
are the shuttle walls used in this indestructible since they're just turf/closed/shuttle/ert?

**Comment by Steelpoint** [comment]
Fixed it that all the plasteel cade entrances now start closed instead of open.

**Comment by Steelpoint** [comment]
Updated changelog to reflect some additional changes and adding credit for some code help

**Comment by Steelpoint** [comment]
I will likely set up a hostile survivor spawn for the new map, Hybrisa, in a separate PR presuming both it and this PR are merged.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Review by Nanu308 — CHANGES_REQUESTED** [review]
Not really a fan of copy pasting the same ship onto all the maps with very minor adjustments, try looking into building some of your own ships if you intend to go for this; Cargo, Transport, Captured USCM vessel, and so forth!

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by Steelpoint** [comment]
If newly made ships are required for every map it will take me a quite some time to do this. Though I'd aim to keep the equipment options identical which adds constraints. I'll see how I feel once I get free time but don't expect this to be done anytime soon.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by Steelpoint** [comment]
I don't have the time to commit to mapping custom ship maps for every map barring 624. Considering the rising merge conflicts, I'm not inclined to fix them due to this. Ergo, if the requirement for custom maps stands, I'll have to shutter this PR at this stage.

**Pull request closed without merging**
