### PR TITLE
[s] Return Ice Classic to CM for the Holiday Season

### PR DESCRIPTION
**Pull request by BroseidonMOO**
# About the pull request

We bring back Ice V1 for all of December, so we can enjoy the holiday spirit and suffering. It will be an example to all of how things used to be, and why they should love the glorious new maps.

# Explain why it's good for the game

Ice is Nice(tm)

# Testing Photographs and Procedure

Beagle probably tested it.

### CODE REVIEW

**Comment by Googles-Hands** [comment]
Any chance we could switch this to Ice v2 halfway through December?
Playing it right now shows how it used to be at it's beginning, not during it's peak popularity with the lower levels which inspired New Varadero and the caves connected to the predator ship.

**Comment by HeresKozmos** [comment]
can we unmerge this shit already

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by harryob** [comment]
the holidays are over

**Pull request closed without merging**
