### PR TITLE
anti CL powergame

### PR DESCRIPTION
**Pull request by stanalbatross**
## About The Pull Request

stops CLs from giving marines le op gear predrop 

## Why It's Good For The Game

turns out being able to give one guy pills that make him super fast are a bit unbalanced, especially doing so predrop

this should make it so that you have the chance to roleplay a bit more before spamming out your op stim pills

## Changelog

:cl:
add: added green pens, the CL gets a green pen in their briefcase
balance: upped the price of ultrazine in the CL briefcase to 25 points
balance: you can no longer buy ultrazine or neurostimulator implants from the CL briefcase before 12:25
code: made the code for update_icons on pens much nicer
add: added DCC spawn landmarks to the uss runtime
/:cl:

### CODE REVIEW

**Comment by kiVts** [comment]
Im sorry but it looks like a cope pr, it been this way years and never been a problem - Now somewhy it is? . Its more of a admin issue then a dev issue, If CL gives ultra pill to everyone pre drop they should be jbanned. they shouldn't be giving it away for free.

**Comment by Diegoflores31** [comment]
> Im sorry but it looks like a cope pr, it been this way years and never been a problem - Now somewhy it is? . Its more of a admin issue then a dev issue, If CL gives ultra pill to everyone pre drop they should be jbanned. they shouldn't be giving it away for free.

Bro you literally cant give ultra to everyone . Have you ever played CL ? You only get 5 pills and they last about 10 minutes ... if you give it to more than 1 people they are basically suiciding

**Comment by PhantomEpicness** [comment]
There is a reason why you don't see marines rushing to get ultra roundstart on 99% of rounds. The ludicrous side effects essentially mean you have 1 life and are hilariously easy to kill with the random passing out. 

Yeah sure you may robust a few unsuspecting xenos but you'll get ass blasted to hell and back when you are have a seizure on the frontlines or die because you likely won't come back.

**Comment by FoxyStalin** [comment]
Pre-drop is about the only time you get to RP with marines as a shipside job.

**Comment by RadiationFan** [comment]
Ultra and Implant are pretty bad right now, ultra is barely better than drinking runner plasma, and the implant is not particularly strong considering you can give at most two of them out before drop, maybe three on a late drop. Considering CL is an rp role, and giving out horribly crippling combat stimulants is one of the few ways they can really motivate the marines to engage with them in a tangible way, I do not think a mechanical restriction should be put on the CL briefcase.

**Comment by stanalbatross** [comment]
Recently CLs have been spamming out ultra predrop, primarily to scout specs, with minimal roleplay (as it makes scout spec significantly stronger due to the increased speed and pull speed)

This is the best dev solution to this particular problem, if you think it's necessary to up the timer until 12:25 then I can definitely do so

**Comment by Kraseo** [comment]
it's been a single liaison giving ultra to a single scout, this feels more like a player issue than a code issue

timelocks aren't going to help enforce rp either

**Comment by Diegoflores31** [comment]
> Recently CLs have been spamming out ultra predrop, primarily to scout specs, with minimal roleplay (as it makes scout spec significantly stronger due to the increased speed and pull speed)
> 
> This is the best dev solution to this particular problem, if you think it's necessary to up the timer until 12:25 then I can definitely do so

so the whole focus in this PR is to nerf one of the weakest specs currently that cant use guns while cloaked and will just eventually die when he runs out of pills ? (AKA at most 30 minutes with a full bottle just for him)

**Review by Nanu308 — CHANGES_REQUESTED** [review]
Up Timer till 12.25

**Comment by stanalbatross** [comment]
> Up Timer till 12.25

rog

**Review by Shad0vvs — CHANGES_REQUESTED** [review]
Fix pens as they don't update sprite at all.

**Review by Shad0vvs — APPROVED** [review]

**Review by JeserTheFox — APPROVED** [review]

**Review by Agameofscones — APPROVED** [review]
not sure why you're changing the runtime map, but the maps and sprites check out

**Comment by stanalbatross** [comment]
> not sure why you're changing the runtime map, but the maps and sprites check out

someone forgot a dcc landmark

**Pull request merged**
