### PR TITLE
Sapper Burrower Strain

### PR DESCRIPTION
**Pull request by TheKillfish**
# About the pull request
[Still WIP, everything in square brackets will be removed for proper PR]

This strain turns Burrower into an aggressive siege-breaker with greater offense and improved durability but lessened mobility and inability to provide for Xeno infrastructure, more or less making it discout Rajang from Monster Hunter. Much like Acid Runner, the Sapper builds up a point pool with attacks called Tension [WIP name] that is used in some form by all the new abilities, mostly as an additional resource to be consumed (Maximum 1000 Tension, 20 Tension on slash and 1 Tension per tick passively). The new abilities are predominantly offensively geared but almost all carry long cooldowns and need both a lot of plasma and a lot of Tension to use, thus requiring more careful thought on if or when to use the abilities. All this is to make the Sapper a force that can apply significant pressure to Marine defences and can hold it's own better in combat than before, thriving better on the frontlines, but still being fragile enough and high maintenance enough so as to not be able to simple unga into Marines.

**Gains**
- Directional armor (20 frontal, 10 side)
- Sharp claws, which allows for damaging normal walls with slashes
- Mob Size Bulky: an inbetween of normal Xeno size and Large which provides the strength feats of Large (like full APC destroying and expanding holed walls) but does not provide the durability feats (like enduring shotgun knockback)
- New Abilities
- New Sprites

**Loses**
- Direction lock (because directional armor)
- All non-universal abilities
- Half of plasma (From 600 to 300)
- Some armor (From 25 to 15)
- Ordinary Tail Stab

**Abilities**
_Punch_
A slightly modified Warrior Punch with slightly faster cooldown but no step back on hit. Damage variance max scales with Tension.
- Cost: None
- Damage: 20, potentially up to 40 when Tension is max
- Cooldown: 4

_Demolish_
A self-buff that increases attack speed very significantly and ups claw sharpness to very sharp, allowing one to damage Reinforced Walls.
- Cost: 100 plasma, 300 Tension
- Duration: 15 seconds
- Cooldown: 45 seconds

_Earthquake_
Essentially a slower but stronger form of Tremor, being able to knock down and knock away mobs too close and slowing those further away after a 1 second wind-up.
- Cost: 100 plasma, 200 Tension
- Range: 6 Tiles slowed, 4 tiles knocked down and knocked away
- Cooldown: 40 seconds

_Boulder Toss_ [Name kinda fluid atm, may change]
The Sapper's main siege tool, a ranged projectile that features a very high damage multiplier against barricades and deals a shitload of damage to mobs. [Also most WIP part, can be improved but functional skeleton is present]
- Cost: 100 plasma, 500 Tension
- Range: 8 Tiles
- Damage: 80 with daze and knockdown on carbon targets (x6 mult when hitting barricades)
- Cooldown: 90 seconds

# Explain why it's good for the game

More variety is fun, Burrowers could use with more variance, and provides the Hive a unit more capable of breaking sieges and cracking marine chokepoints.

# Testing Photographs and Procedure
Still WIP, drafted to gather opinions, criticism and possible ideas.
Todo:

- [ ] Clean up abilities in need of cleaning
- [ ] Improve sprites (Change head, change forearms, add boulder sprites)
- [ ] Balance based on reviewer input
- [ ] Provide screenshots of final product (If/when I reach that point)

# Changelog

:cl:
add: Added new strain for Burrower, "Sapper"
imageadd: Added sprites for Sapper Burrower
/:cl:

### CODE REVIEW

**Comment by TheKillfish** [comment]
Had some input on Discord, consodering a very different route, although will keep some of the elements already present

**Comment by Diegoflores31** [comment]
Ngl this feels a little more fittings for a warrior Strain rather than a burrower since Defender is usually the tankiest and wall breaker

**Comment by TheKillfish** [comment]
Thanks to input and inspiration from Discord, Sapper strain has new life and purpose; as an oblique referance to Rajang from the Monster Hunter franchise. PR description will be updated with the new changes.

Seeking input once again on opinions, ideas and places for improvement as while I feel it is closer to finished codewise, I also feel it could have a lot of improvement done that my unga brain can't figure out. Also sprites needed, but those can come when code is more complete.

**Comment by TheKillfish** [comment]
Currently distracted with another idea, closing and putting this PR on hold until I can get more opinions and maybe get sprites done

**Pull request closed without merging**
