### PR TITLE
SG-rework

### PR DESCRIPTION
**Pull request by BasilHerb**
# About the pull request

I suppose I should put a disclaimer here that I have absolutely no coding background whatsoever. This PR is mainly just a rehash of https://github.com/cmss13-devs/cmss13/pull/4723 by ihatethisengine, which itself is a port of morrow's Alt IFF from PvE. Special thanks to ihatethisengine, cuberound, kiVts and tristan for helping me out during this PR- you guys are heroes. 

This PR reworks the current IFF system for the M56B smartgun from one where it shoot over all friendlies, to one where the gun won't fire when a friendly is blocking the way. 
In order to compensate for the loss of IFF stacking for SGs & such, the SG has been buffed in terms of damage and effective range in order to make it roughly on-par with a MK2 Rifle.
Basically, the M56B becomes a Mk2 that refuses to shoot whenever PVT Stanley is blocking your way, instead of a Mk2 that plugs PVT Stanley with 27 bullet wounds. This is frankly, a step up from the M56B being a BB gun that could shoot at targets behind PVT Stanley, but tickled the targets lightly instead of hurting them.

This **only touches the M56B SG, and it's variants**. It does not affect the B8 smartscope, M56D, SU-6, or other weapons in any way.

I've tested all the stuff that got Alt IFF added and nothing has exploded (yet).

# Explain why it's good for the game

The current iteration of IFF has been a balancing dilemma for a decade now. Originally, the dev team wanted to implement the SG as something that would fit the canon pointman tip-of-the-spear role of the SG, but then gave up and just made SG IFF go through friendlies. This was not particularly a problem way back when in 2015-2016, but over the years we've seen a lot of IFF powercreep, where more weapons with IFF are added (M56D, SU-6, B8), causing IFF deathstacking to become a significant issue that's plagued the game's balancing discussion.

This has resulted in two main issues, which I hope this PR will address.

1) The SG must be nerfed into the ground to compensate for IFF stacking. As a result, weapons with IFF are very weak relative to their non-IFF counterparts, to the point where they're effectively peashooters that don't really feel good to play with. For example, the SG was overbuffed a few months back following years of stagnation, only to massively nerfed to the point it was worse than it was before the buff. These weapons shouldn't feel like they aren't doing damage to the enemy, they should feel good to use. 
By buffing the power of the SG, this should make it feel actually good to use, and rightfully so considering it will go from a backline support weapon to the intended vanguard heavy MG role they were always meant to be a decade ago.

2) 4 SG IFF deathstacking is a frustrating mechanic to play against. Concentrated IFF weapons mean that marines can deal significant amounts of damage 24/7, completely disregarding positioning and LoS. This can make pushing marines a challenging endeavour even when they have no prepared defensive positions. Marines should be punished for having poor positioning- And xenomorphs should be rewarded for thinking tactically about how to best suppress marines by minimising how many can fire at a time. Because of the power of IFF deathstacks, this directly feeds into IFF weapons being nerfed in order to regain some sense of balance, which ends up making the marine and xenomorph gameplay experience worse.
By limiting the ability of IFF weapons to fire over friendlies, IFF deathstacking shouldn't be as much of an issue in regular XvH gameplay. 

I've left the damage values for the SG the same as they were in ihatethisengine's PR, because I believe now that on-screen falloff is no longer a factor, it now performs decently well in a frontline role. At the time of that PR, SG falloff was still 1, and starting from 0 tiles. This meant that SGs would be dealing a pitiful 13 AP damage and 23 precision damage at 7 tiles, compared to a MK2's 33 AP and 44 precision damage. Even with the 20% damage buff, the SG would deal 17 AP and 29 precision at 7 tiles, which was simply insufficient to justify implementing alt IFF. Due to this, the PR was effectively a nerf to the SG itself, rather than a sidegrade.

As such, I have changed the effective range from 0 to 7. This means the SG now deals full damage up to 7 tiles, allowing it to deal 24 AP and 36 precision damage. Combined with the SG's RPM of 300 vs the MK2's 240, this equates to a firearm that is a bit weaker than a MK2 in frontline combat. However, I believe the SG's NVGs will balance this out, such that the SG is overall still the stronger candidate (given SG is a limited, competitive roll anyways, I think that's justified).

I've changed falloff to 4 across the board, so that it falls in line with the rifle.

Overall, I believe this makes the SG a decent weapon suitable for frontlining, and while removing the ability to shoot at everything on screen is a bit sad, it's for the best.

I'd be happy to hear any thoughts on balance via. discord or the CM forums. My discord tag on the CM13 discord is BasilHerb.

# Testing Photographs and Procedure

https://github.com/user-attachments/assets/56af87e2-cae3-4c08-a5d3-b74b28caeee4

Alt IFF in action for the SG.

# Changelog

:cl:
add: Alt IFF framework so Alt IFF can be added painlessly for other guns
add: Alt IFF to M56B, M56C
balance: M56B damage buffed by 20%, effective range changed from 5 to 7, falloff is now 4
del: Many, many mispellings of the word 'gun' in gun.dm (seriously, what is a 'gub?')
soundadd: the noise the M56B makes when it refuses to fire because someone is blocking you
/:cl:

### CODE REVIEW

**Comment by DorfGuy1** [comment]
IDK about this man. This is gonna throw out YEARS of stuff. IMO you could make sgs more powerful, and keep the IFF and be fine. Not too much more powerful, just a little. There's counters. Xenos can make smoke, stun, stun, stun, and stun some more. Or they can just leave. A sg risks getting stunned and capped if they chase, same for any marines. If xenos do a straight up fight, it's because they are either winning and it's not a concern, or they're loosing bad because they are cornered. Anything else they can just hit the bricks. Agree with the p-shooter thing, but its more a support weapon anyway.

**Comment by BasilHerb** [comment]
> IDK about this man. This is gonna throw out YEARS of stuff. IMO you could make sgs more powerful, and keep the IFF and be fine. Not too much more powerful, just a little. There's counters. Xenos can make smoke, stun, stun, stun, and stun some more. Or they can just leave. A sg risks getting stunned and capped if they chase, same for any marines. If xenos do a straight up fight, it's because they are either winning and it's not a concern, or they're loosing bad because they are cornered. Anything else they can just hit the bricks. Agree with the p-shooter thing, but its more a support weapon anyway.

The problem with just buffing the SG is that it’s just going to get nerfed again afterwards. We’ve been going through a cycle of SG buffs and nerfs for a while. Your suggestion to buff SG and let xenos deal with it doesn’t solve the root cause of the issue, which is the fact that IFF stacking breeds discontent on both sides. Xenomorphs feel it’s a bad mechanic, and SGs feel like their guns are worthless. 

The SG is unfortunately the worst it’s ever been in years- It’s even weaker damage-wise than it ever was, and lacks far sight. We might think we can revert the SG nerf with a buff, but that’s what we thought last time too. The current approach isn’t working- we need something new.

Regarding “throwing out years of stuff”, I think this is misleading. I haven’t removed anything that isn’t either redundant or a typo. If you mean SG IFF itself, it should be noted that current SG IFF was actually meant to be a temporary placeholder until something like this came along (which it did, 7 years later with PvE.)

I’ve been playing mostly SG since 2016, and as someone with a ridiculous amount of playtime in the role, I can confidently say that I believe Alternate IFF is the way forwards.
Everyone else working on SG-related PRs is trying to ditch the current IFF system and bring SG to a frontline role anyways.

I hope this illustrates more of my thought process to you.

**Comment by Blundir** [comment]
Reminder that it was tried a year ago, and wasn't recieved well at all https://github.com/cmss13-devs/cmss13/pull/4723

**Comment by BasilHerb** [comment]
> Reminder that it was tried a year ago, and wasn't recieved well at all #4723

I’m aware, I talk about it in the PR description. Main reason was due to the damage output being far too low, which is not the case here.

**Comment by Blundir** [comment]
Also since it becomes much more easier to die as sg (no ability to have better armor, no better helmet provided, not enough burst damage or stuns in point blank (no sidearm shotguns, no flamers (hi Aliens movie), no underbarrels)), you should consider either making more slots or adding scaling to it, so it's not locked to 1

**Comment by BasilHerb** [comment]
> Also since it becomes much more easier to die as sg (no ability to have better armor, no better helmet provided, not enough burst damage or stuns in point blank (no sidearm shotguns, no flamers (hi Aliens movie), no underbarrels)), you should consider either making more slots or adding scaling to it, so it's not locked to 1

I get you what you mean with not wanting SGs to frontline, but the reality is that if you play SG you already have to frontline. The recent nerf pretty much undid the buff and forces everyone to shoot within warrior lunge range to actually do damage. This doesn’t actually change SG play style that much. 
If I’m given the green light to buff SG directly to rework the nerf I’ll do it instead of this PR, of course- but there’s no indication of that, so this PR is really the best I can come up with when I have no coding experience.

I think your points regarding making SG more durable sound valid- I’d be happy to add stuff like allowing for stuff to be put on your back slot like guns and flamers, or giving SG pounce resistant armour. Regarding modifying roundstart slots, I don’t think I have the coding expertise for that- Last time I tried to do anything like it, I basically crashed my game.

**Comment by BasilHerb** [comment]
Alright, after talking to a lot of other people, seems like it'd be for the best if Alt IFF is an optional toggleable option. I've always really liked the idea of a frontline mode for SG, but it seemed like a lot of work and I had no idea where to start, so I never tried. Unfortunately, I've committed a bunch of hours to doing this one so I'm basically just gonna submit to the sunk cost fallacy and crack my hand at toggleable Alt IFF. Thank you to everyone for the feedback, and wish me luck I guess💀

**Pull request closed without merging**
