### PR TITLE
l'intelligence est la clé - 1 / New Intelligence Office

### PR DESCRIPTION
**Pull request by LC4492**
# About the pull request
The changes have been cited on the changelog and are meant to be part of a bigger project, preparing the grounds for a new medical area that is on my personal archive have some months now.

# Explain why it's good for the game

Separated rooms for officers, repairs of miscellaneous, missplaced stuff and other preparations, that can't be bad, ain't I right?

# Testing Photographs and Procedure

Captura de Tela (418)

Captura de Tela (417)

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl:
maptweak: Changed the AI core position by one tile to the east and gave it more detailing. Changed the IO Intelligence Office and gave the IOs their own, separated rooms, of which now contain their uniform and gear vendors. Lots of missplacement repairs to the ship. Shortened vent and disposal pipes, making use of features that were forgotten on Whiskey Outpost and that could have been used on the Almayer a long time ago.
add: Gave the CL office, the CC office and the CIC the first toner cartridges in all history, for re-filling photocopiers.
fix: Repairs tons of piping bugs involving all parts of the ship, such as pipes going through walls unnecessarily and other overly complicated pipe junctions. Bug Report #4213 have also been fixed. 
/:cl:

### CODE REVIEW

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by morrowwolf** [comment]
I'm happy with the current IO set up.

**Pull request closed without merging**
