### PR TITLE
Gau rework this time for real ;)

### PR DESCRIPTION
**Pull request by cuberound**
# About the pull request

removes the whole bullet thing from the the GAU. 
Makes all the shots impact at the same time.
Reduces spread to 3 from 4 (hits 49 instead of 81).
Reduces FM delay to 1. (means you can fire each tile in FM, quite easy to set up with new UI, thanks for that) 
Ammo 400->600 (to keep the same fm lenght with the new FM delay)
Uses 30 shots per burst
Makes each bullet impact unique tile, just like laser to prevent some rng instagibs (do not want the chance that someone gets impacted by 10 gau bullets from single burst and stops existing, however unlikly it is.)
Adds max holo effect to each bullet.
Adds 10 toxic to each bullet that maxcaps at 1/5 of enemy armor
Adds 3 sec superslow to impacted mob
Reduces traveling time of the ammo to 2 sec 
Gives hit xenos interference effect that maxes out at 10
Gives hit xenos healing_reduction, no maxcap, was told it is shit anyway

# Explain why it's good for the game

GAU needs rework. A lot. I am trying to place it into suppressive role with this PR as it mini stuns and mini slows enemies hit and aplies holo effect (before you get mad about that... max holo is like taking 10% of enemy health and it does not stack, so 100 from queen max...). It mainly aims to make it work with other guns with bigger damage, so I might add more negative effects (smoke??) to fit more in the role, as those effects do not stack so if you are being shot at by 1 or 4 gau they will be the same.
This also aims to make GAU usable with new UI that does not support diferent FM lenghts... they exist only for GAU anyway.
Also the reduced travel time combined with the negative effects applied on impacted enemies and lower price per shot might make it useful transport gun.

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl:
balance: GAU ammo aplies 10 toxic up to 1/5 of target armor
balance: GAU spread 4 ->3
balance: GAU FM delay 2->1
balance: GAU ammo 400 -> 600
balance: GAU ammo applies max holo effect
balance: GAU ammo aplies short super slow
balance: GAU ammo damage 105 -> 80 
balance: GAU AP ammo removed
balance: GAU explosions removed
balance: GAU gives 10 interference
balance: GAU gives healing_reduction
code: removes shrapnel from GAU

/:cl:

### CODE REVIEW

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by cuberound** [comment]
do not merge or TM for now, numbers need some changes and testing, too strong for now, looking for more debuffs to replace damage with

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by Zonespace27** [comment]
Reopen when you want to work on this

**Pull request closed without merging**
