### PR TITLE
Egg morphers now generate facehuggers on their own [CODE BOUNTY]

### PR DESCRIPTION
**Pull request by VileBeggar**
# About the pull request
### CODE BOUNTY: https://forum.cm-ss13.com/t/proposed-eggmorpher-change-code-bounty-30usd/10466
removes the whole body decomposing aspect of egg morphers and replaces it with timed generation.
every 2 minutes, a facehugger will get generated until it reaches 6 huggers stored.  you can still refill egg morphers with eggs and facehuggers, though.

adds the ability for carriers to refill egg morphers with eggs automatically
stops light fixtures from preventing egg planting
eggs can now get planted under nested mobs
egg morphers can no longer be built in tall grass

# Explain why it's good for the game

### ORIGINAL POST:
I think eggmorphers in current state suck, allow me to explain why.

So: An egg morpher consumes bodies, deleting them and their contents from the game, in return for some huggers.

But, in all Aliens media the Aliens have areas with just tons of fucking burst bodies embedded in the walls, and that’s a huge soulful thing to see all your dead comrades instead of >corpse blender

Therefore my suggested change is have burst bodies do nothing at all for the hive, and eggmorphers simply produce huggers at a rate of like 1 per 2 minutes or something.

This also makes eggmorphers have a point at the front, and eases on the actual suffering that is standard Carrier reloading.

----
some personal thoughts: i actually don't see egg morphers on the front that often mostly because it's a chore to keep them filled, especially if the hive is lacking a hive tunnel. this might help xenos cap more often which would be a pretty nice addition

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

works fine from my testing. cooldown was shortened here just to speed things up. the "will grow in X seconds" message disappears when max capacity is reached.

https://github.com/user-attachments/assets/ef1b83ab-8682-4a9a-83c4-12fe397d449e

</details>

# Changelog
:cl:
balance: Egg morphers now generate facehuggers on their own, up to 6 in total every 2 minutes. Bodies can no longer be fed to egg morphers. Eggs can now get planted beneath light fixtures and nested mobs. Egg morphers can no longer be built in tallgrass.
qol: Carriers can now automatically fill egg morphers with their own egg supply by using the Retrieve Egg ability on them.
/:cl:

### CODE REVIEW

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by zzzmike** [comment]
Your goal to see a bunch of perma bodies conflicts with https://github.com/cmss13-devs/cmss13/pull/3644 doesn't it? I think you would have to revert that PR too for this to work out?

**Comment by zzzmike** [comment]
> burst bodies don't get eaten up by weeds afaik

Yeah but the reason for that is so that bodies can be put in the morphers - if this PR goes through there's no more reason for the exemption and I assume someone will remove the exemption. Which leads back to what I was saying about this PR not fulfilling the goal of seeing burst bodies. 

And if the exemption is left in, what happens when a xeno wants to build stuff on the tile with the body? You can't plant eggs on tiles that have things that 'obscure it' - even light fixtures which is silly - are we expecting xenos to now move the bodies out of the hive into some trophy room or something?

**Comment by Nanu308** [comment]
There are some good questions posed by zzzmike, I'd like you to give an answer to them and how you expect to see egg morphers be used with this change.

Besides that, i do agree seeing burst bodies are soulful in general.

**Comment by VileBeggar** [comment]
repeating the points i made on discord here:

1. i want the pr to make egg morphers a bit more commonplace on the frontline to make captures easier. from my personal anecdotes i've rarely seen them on the front, most frontline hugs happen due to player huggers, a carrier or traps. xenos can really feel the difference in power if they get and use the chance to cooperate with a good carrier but sometimes you're shit out of luck and don't have that opportunity. i'm also not a carrier player but i've seen some of them switch to egg carrier once they run out of huggers because going back to the hive to pick up more huggers is an annoying proccess.
2. xenos are supposed to be incentivized to use these things. the fact they're not used that much outside of the hive and maybe some mini-hives proves that they're not that useful compared to other clusters and pylon. they're special structures that are _limited_. they should be played around, just like how hive clusters present a big challenge to marines.
3. i'll admit that 12 huggers for free might be too much. that's why i have reduced it down to 6.
4. you can now plant bodies beneath nested mobs. i think the issue before was that nested mobs soaked up bullets but now that got it got fixed i don't particularly see a problem with this. in addition you can now plant them under light fixtures
5. regarding the weeds eating burst corpses, i still don't have really have an opinion on it. them being eating by weeds doesn't ruin the point of the PR because the bodies are still there. it's just that instead of seeing them immediately, you'll see them once the weeds get broken. seeing a huge wave of corpses rise from the weeds once the hive core gets destroyed would be pretty cool imo.

**Comment by Nanu308** [comment]
See Drathek's comment on Discord, once that is done seems fine balance wise. We'll see if captures/numbers skyrocket or not on live after and tweak it from there.
image

**Review by harryob — APPROVED** [review]

**Comment by Nanu308** [comment]
I forgor to finish my comment on here, but I am fine with this and will balance approve it on the assumption you can make it so EGG morphers can not be hidden under tall grass.

Besides that, tweaking numbers after will be needed potentially.

**Pull request merged**
