### PR TITLE
Removes inferior m39 holster from squad vendor

### PR DESCRIPTION
**Pull request by GoldenDarkness55**
# About the pull request

Noticed we've a new m39 holster thats plain better than the old one, made me wonder why and why do we have the old one still. As per #3825 the old one was supposed to be gone from the vendor.

Dunno why PMCs use the old one either, isn't their equipment supposed to be better? No clue why this was added to normal play in the first place - OG reasoning makes no sense since m39 is a proper primary. Would happily expand scope to swap these and give PMCs the better one while marines have the older weaker one - or at least upgrade PMCs to use this - but can't be arsed to bother unless I get dev consent first.

# Explain why it's good for the game

Removing obsolete noobtrap good. Bloat bad.

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl:
del: Removed old inferior m39 holster belt from squad prep vendor
/:cl:

### CODE REVIEW

**Comment by cuberound** [comment]
the reson why PMC ERT has the od one is that none bothered to change it

**Comment by Red-byte3D** [comment]
https://github.com/cmss13-devs/cmss13/pull/3825#issuecomment-1671699337

He just messed up making it PMC only, although if you want a better solution to make it more of a consideration albeit a bit more work, i think you should make these work in a manner where the belt that hold ammo cant hold an m39 with attachements that make the weapon bigger, while the one without ammo can, this would allow a choice and prevent powercreep even further.

**Comment by TheManWithNoHands** [comment]
My guy, you do know the mag holster cant hold a M39 with stock and shit. Rigth?
Its a compromise.
One you can put some mags in, and in exchange you cant store an SMG thats too long.
The other one cant store mags, but store SMGs of any size.

It aint a flat upgrade, its a side grade.

**Comment by GoldenDarkness55** [comment]
> My guy, you do know the holster with mag slots cant hold a M39 with stock and shit. Rigth? Its a compromise. One you can put some mags in, and in exchange you cant store an SMG thats too long. The other one cant store mags, but store SMGs of any size.
> 
> It aint a flat upgrade, its a side grade.

It actually allows the base folding stock either folded or unfolded. It's a straight upgrade.

**Comment by TheManWithNoHands** [comment]
> It actually allows the base folding stock either folded or unfolded. It's a straight upgrade.

It really is not.

````
/obj/item/storage/large_holster/m39
	name = "\improper M276 pattern M39 holster rig"
	desc = "The M276 is the standard load-bearing equipment of the USCM. It consists of a modular belt with various clips. This holster features a larger frame and stiff backboard to support a submachinegun. It's designed for the M39, but the clips are adjustable enough to fit most compact submachineguns. Due to its unorthodox design, it isn't a very common sight, and is only specially issued."
	icon_state = "m39_holster"
	icon = 'icons/obj/items/clothing/belts.dmi'
	flags_equip_slot = SLOT_WAIST
	max_w_class = 5
	can_hold = list(
		/obj/item/weapon/gun/smg/m39,
		/obj/item/weapon/gun/smg/mp27,
		/obj/item/weapon/gun/smg/mac15,
		/obj/item/weapon/gun/pistol/skorpion,
	)
	///Guns have a hud offset that throws the vis_contents alignment off.
	var/gun_offset = 0
	///Whether the gun had pixel scaling set before being holstered.
	var/gun_scaling = FALSE

/obj/item/storage/belt/gun/m39
	name = "\improper M276 pattern M39 holster rig"
	desc = "Special issue variant of the M276 designed to holster a M39 submachine gun and two spare magazines. Uncommonly issued to USCM support and specialist personnel."
	icon_state = "m39_armor"
	item_state = "s_marinebelt"
	storage_slots = 3
	max_w_class = 5
	can_hold = list(
		/obj/item/weapon/gun/smg/m39,
		/obj/item/ammo_magazine/smg,
	)
	holster_slots = list(
		"1" = list(
			"icon_x" = -11,
			"icon_y" = -5))

#define MAXIMUM_MAGAZINE_COUNT 2

**Comment by Red-byte3D** [comment]
> > It actually allows the base folding stock either folded or unfolded. It's a straight upgrade.
> 
> It really is not.
> 
> ```
> /obj/item/storage/large_holster/m39
> 	name = "\improper M276 pattern M39 holster rig"
> 	desc = "The M276 is the standard load-bearing equipment of the USCM. It consists of a modular belt with various clips. This holster features a larger frame and stiff backboard to support a submachinegun. It's designed for the M39, but the clips are adjustable enough to fit most compact submachineguns. Due to its unorthodox design, it isn't a very common sight, and is only specially issued."
> 	icon_state = "m39_holster"
> 	icon = 'icons/obj/items/clothing/belts.dmi'
> 	flags_equip_slot = SLOT_WAIST
> 	max_w_class = 5
> 	can_hold = list(
> 		/obj/item/weapon/gun/smg/m39,
> 		/obj/item/weapon/gun/smg/mp27,
> 		/obj/item/weapon/gun/smg/mac15,
> 		/obj/item/weapon/gun/pistol/skorpion,
> 	)
> 	///Guns have a hud offset that throws the vis_contents alignment off.
> 	var/gun_offset = 0
> 	///Whether the gun had pixel scaling set before being holstered.
> 	var/gun_scaling = FALSE
> 
> /obj/item/storage/belt/gun/m39
> 	name = "\improper M276 pattern M39 holster rig"
> 	desc = "Special issue variant of the M276 designed to holster a M39 submachine gun and two spare magazines. Uncommonly issued to USCM support and specialist personnel."
> 	icon_state = "m39_armor"
> 	item_state = "s_marinebelt"
> 	storage_slots = 3
> 	max_w_class = 5
> 	can_hold = list(
> 		/obj/item/weapon/gun/smg/m39,
> 		/obj/item/ammo_magazine/smg,
> 	)
> 	holster_slots = list(
> 		"1" = list(
> 			"icon_x" = -11,
> 			"icon_y" = -5))
> 
> #define MAXIMUM_MAGAZINE_COUNT 2
> ```

i tested this on live server with forest, it does not matter it will allow either of them

**Review by Drulikar — CHANGES_REQUESTED** [review]
Feel free to explore making it more a sidegrade if you like, as well as swap it out for:
- PMCs
- `/datum/equipment_preset/uscm/specialist_equipped/load_gear(mob/living/carbon/human/new_human)`
- `/datum/equipment_preset/uscm/specialist_equipped/sniper/load_gear(mob/living/carbon/human/new_human)`

But currently its fine sitting in the extra uniform supply vendor as a higher quantity stock of item to the other belt. So can close if you don't want to also do above.

**Comment by GoldenDarkness55** [comment]
> Feel free to explore making it more a sidegrade if you like, as well as swap it out for:
> 
> * PMCs
> * `/datum/equipment_preset/uscm/specialist_equipped/load_gear(mob/living/carbon/human/new_human)`
> * `/datum/equipment_preset/uscm/specialist_equipped/sniper/load_gear(mob/living/carbon/human/new_human)`
> 
> But currently its fine sitting in the extra uniform supply vendor as a higher quantity stock of item to the other belt. So can close if you don't want to also do above.

Gets the honk icon when PMC m39 is inserted, would need to be told how to fix that to replace it for PMCs.
Otherwise close.

**Comment by Drulikar** [comment]
> Gets the honk icon when PMC m39 is inserted, would need to be told how to fix that to replace it for PMCs. Otherwise close.

Belts.dmi would need probably the `s_m39` state duplicated to be named `m39b2`

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by GoldenDarkness55** [comment]
hm. Seems I messed something up with that master merge. More trouble than it's worth at this point.

**Comment by Drulikar** [comment]
Not sure the error with the dme file has much to do with your PR

**Pull request closed without merging**
