### PR TITLE
refactor multiple files concerning robot and mechs.

### PR DESCRIPTION
**Pull request by Huffie56**
# About the pull request
Also refactored a lot of the code to be more clear and clean...

# Explain why it's good for the game
# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl:
del: Removed "security robot module" from robot_module.dm
refactor: change the name of Ripley in game to P-1000, gygax to MAX, Durand to MOX, Odysseus to Alice to be more in line with the lore.
/:cl:

### CODE REVIEW

**Comment by Huffie56** [comment]
checking if the test all go green...

**Review by Nanu308 — APPROVED** [review]
mapping lgtm, just filepath replacements there

**Review by Drulikar — CHANGES_REQUESTED** [review]
These changes are fine other than I don't see the point of repathing `/obj/structure/prop/mech` to `/obj/structure/prop_mech` They are props no? So why no longer consider them props? Its fine to keep them in a pop_mech.dm file; just if something wanted to say delete all /obj/structure/prop in a tile, now they'd have to also look for prop_mech.

**Comment by Huffie56** [comment]
> These changes are fine other than I don't see the point of repathing `/obj/structure/prop/mech` to `/obj/structure/prop_mech` They are props no? So why no longer consider them props? Its fine to keep them in a prop_mech.dm file; just if something wanted to say delete all /obj/structure/prop in a tile, now they'd have to also look for prop_mech.

it's because is was thinking /prop/ did nothing... i can put it back...

**Review by Drulikar — APPROVED** [review]

**Pull request merged**
