### PR TITLE
Adds a Spec to the Foxtrot Cryo Squad.

### PR DESCRIPTION
**Pull request by LynxSolstice**
# About the pull request
Adds a Squad Weapons Specialist to the Foxtrot ERT bought through DEFCON.

# Explain why it's good for the game
Foxtrot as it currently stands is in a poor spot, hence the meme "Foxtrot gets called, it's 3 guys, 2 of which cryo immediately", hopefully the inclusion of a Foxtrot Spec will increase the number of people signing up for it, as it is a pretty big incentive.

# Testing Photographs and Procedure
Compiles and runs, ERT can trigger fine, still.

# Changelog

:cl:LynxSolstice
balance: Adds a Squad Weapons Specialist to the Cryorines.
/:cl:

### CODE REVIEW

**Review by morrowwolf — COMMENTED** [review]
We might have to discuss how sets are going to work with foxtrot specs and I'm not 100% sold on this yet but let's give it a try.

**Comment by Mister-moon1** [comment]
If all spec occupations are filled then new spawns cannot pick from any options, i would advise that you allow them to spawn with /obj/item/spec_kit as this is able to go around the issue

**Comment by LynxSolstice** [comment]
> If all spec occupations are filled then new spawns cannot pick from any options, i would advise that you allow them to spawn with /obj/item/spec_kit as this is able to go around the issue

Thanks for the suggested fix, it should solve the issue.

**Review by morrowwolf — APPROVED** [review]
GA approval.

Finally makes cryo marines worth the point cost.

**Pull request merged**
