### PR TITLE
[WIP] Roombas are coming... Add Roombas as Playable Ghost Role.

### PR DESCRIPTION
**Pull request by Venuska1117**
# About the pull request

This PR focus on adding roombas to game as playable Ghost Role.

If you want to help with project or want more information, here:
https://discord.com/channels/150315577943130112/1267141771284975647/1267141771284975647

*(i am in need of people who know how to code, i need help with code to make this project true)*

Thanks to @cuberound and @GrrrKitten in helping me code this to life, i am really grateful for your help.

# Explain why it's good for the game

- Clean battlefield and marines mess.
- Decrease players lagging caused by rendering blood, bullet magazines etc.
- Give ghost something else to do than just float around and wait in xenos queue or wait for game to end.

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

 **THIS PR DESCRIPTION WILL BE UPDATED AFTER I FINISH IT (or get closed if i abandon it)**

# Changelog
:cl:
add: Add Roombas as playable Ghost Role.
imageadd: Add Roombas Sprites.
/:cl:

### CODE REVIEW

**Comment by Blundir** [comment]
With all the benefit it can bring, I don't think it's a good idea for the setting and aesthetics, roombas scooping battlefield is too wacky and non serious.

**Comment by zzzmike** [comment]
My first reaction to this was good - but depending on what can be roomba'd it's gonna affect balance. Like as a marine, finding an MRE on the battlefield has been a lifesaver, and as a carrier I'm sure I've used it to hide a hugger trap. And glancing at the code, it looks like MRE is specifically allowed to be roomba'd. It might be good to have a separate allow list for what can be roomba'd on ship vs on planet. I do like it as another option for ghosts to get back in the game somewhat, and as a way to reduce server load. I don't see it as any more wacky than a working joe janitor really.

**Comment by Venuska1117** [comment]
> My first reaction to this was good - but depending on what can be roomba'd it's gonna affect balance. Like as a marine, finding an MRE on the battlefield has been a lifesaver, and as a carrier I'm sure I've used it to hide a hugger trap. And glancing at the code, it looks like MRE is specifically allowed to be roomba'd. It might be good to have a separate allow list for what can be roomba'd on ship vs on planet. I do like it as another option for ghosts to get back in the game somewhat, and as a way to reduce server load. I don't see it as any more wacky than a working joe janitor really.

The MRE code is temporary, i used it to check vaccum, because for some reason "crubled" ones just "dissapear" or get deleted after you empty them (because i have extended gamemode instead of distress it just crash my game)

**Comment by Zonespace27** [comment]
> as a way to reduce server load

A bunch of random, non-processing objects lying around will not affect server perf in any meaningful way

Overall against the concept. I like there being more things for ghosts to do, but this isn't it.

**Comment by Venuska1117** [comment]
> > as a way to reduce server load
> 
> A bunch of random, non-processing objects lying around will not affect server perf in any meaningful way
> 
> Overall against the concept. I like there being more things for ghosts to do, but this isn't it.

it do not affect server but it affect players, i didnt have once or twice where my game started to slowing down caused by rendering 100 tiles of blood in sight (not counting bodies, magazines and stuff)

**Comment by efzapa** [comment]
> With all the benefit it can bring, I don't think it's a good idea for the setting and aesthetics, roombas scooping battlefield is too wacky and non serious. Also remembering tgmc, they had roombas only in very specific areas (preps), because roombas can scoop important items, and now it opens a pass for player to do that, which brings a lot of new problems.

iirc TGMC had a PR about a month-ish ago that made roomba-scooped items go back in vendor

**Comment by Drulikar** [comment]
I'm sorry to shut down a bunch of work, but I don't think this fits for CM. You surely could implement this for another ss13 codebase though if they don't already have it.

**Comment by Jerrody** [comment]
@Blundir 
> wacky and non serious
At the same time King was added. Ha-ha.

**Pull request closed without merging**
