### PR TITLE
Lesser Drones & Facehuggers can no longer speak

### PR DESCRIPTION
**Pull request by 567Turtle**
# About the pull request

This removes the ability for lesser drones and facehuggers to speak.

# Explain why it's good for the game

Now, Lesser Drone/Facehugger meta gaming isn't something you see every game, and it's not something that's extremely obvious, but it is something that is possible and it is something that is done every few games.

https://forum.cm-ss13.com/t/remove-the-ability-to-speak-of-facehuggers-and-lesser-drones/5106

I'd like to add, personally, I don't think facehuggers or lesser drones really need the ability to talk.  The lesser drones purpose is to be a nuisance to marine, minor support to the larger castes, and set up the hive.

Facehuggers role is to run up to bigger bugs and stick with them to hug people they stun. Alternatively, they sit in the shadows and wait to capitalize off of traps.

Neither of these two roles require talking. Them being able to talk barely assists their intended purpose, if at all. The reason that only the lesser drone and the facehugger are an issue with talking and metagaming is the fact how quick and easy it is to pump these bugs out en masse.

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

lesserdrone

facehugger

sillyimage

image

</details>

# Changelog
:cl:
balance: Facehuggers and Lesser Drones can no longer speak.
/:cl:

### CODE REVIEW

**Comment by HeresKozmos** [comment]
This is really good, I hope it gets merged.

**Comment by fira** [comment]
Code OK

**Review by Birdtalon — APPROVED** [review]
Code is fine on this PR. You may want to ask zonespace for a final decision since it's marked as balance.

**Comment by Birdtalon** [comment]
> > Code is fine on this PR. You may want to ask zonespace for a final decision since it's marked as balance before it's autoclosed.
> 
> Should I just DM them?

You could ping them on discord in #development

**Comment by 567Turtle** [comment]
> You could ping them on discord in #development

dev channel banned, DMs it is

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by Zonespace27** [comment]
Ping me for a re-open when this is ready

**Pull request closed without merging**
