### PR TITLE
refactor : divide survivor preset base on maps.

### PR DESCRIPTION
**Pull request by Huffie56**
# About the pull request
The idea is to divide this file into multiple files base on the maps.

# Explain why it's good for the game
# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl:
refactor: divide preset into different file for each map.
/:cl:

### CODE REVIEW

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by Huffie56** [comment]
i just conflicted with myself i think.....

**Review by morrowwolf — CHANGES_REQUESTED** [review]
Move forcon_survivors.dm to LV-522 folder

There are some synth surv types in synth.dm that should be moved to their new homes in the nightmare survs. I can remember: LV-522 FORCON synth, UPP 173/RECON synth, probably a PMC synth? I can't remember.

**Comment by Huffie56** [comment]
UPP and PMC synth move to nightmare insert 
CLF synth is used for spawned of CLF that aren't survivor...
most of synth.dm preset gear is used for different variation of survivor synths.

**Pull request merged**
