### PR TITLE
Sweeping perf changes to Area/Sound/Weather, targeted for Sorokyne

### PR DESCRIPTION
**Pull request by fira**
## About The Pull Request

Peformance on Soro always has been subpar but we never quite found why. It was clearly linked to the weather but despite so many attempts at fixing this, that still wasn't quite it. This is yet another attempt.

This PR targets several key points:
 * **Rendering method for Weather objects** - weather rendering has been done via `vis_contents` so far, to mirror an existing VFX over every turf indivdually. This now instead uses **overlays** on the **areas** as this is hopefully faster, and being the method the lighting system uses we are more familiar with it.
 * **Area handling for `/area/Entered`** - lighting subareas cause duplicate updates for Sound and Weather every time something steps (Xeno) between light levels. Having them properly handled (with `/area/var/master` and `/area/var/related`) cuts on that
 * **Duplicate sound updates** - In general, `update_ambience` was prone to sending empty updates. It's now much more aggressive at avoiding that.
 * **Proc Overhead Cleanup** - The Weather system is overly modular and does a lot of ping-pong with things that aren't actually being used otherwise. This cleans up a number of odd such calls/procs to lessen overhead.

## Why It's Good For The Game

Straighforward: more perf less lag less bloat

## Changelog

:cl:
refactor: Optimized several aspects of Sound Ambiences, Areas, and Weather
/:cl:

### CODE REVIEW

**Comment by Carnage068** [comment]
Running Sorokyne with less lag would be a dream ♥

**Comment by stanalbatross** [comment]
testing will take place specifically on sorokyne

**Comment by fira** [comment]
Don't merge this without a TM

**Comment by fira** [comment]
Was TM'ed, apparently nobody could tell the difference, but it also was a short round
.... so probably that's not conclusive

**Comment by stanalbatross** [comment]
I've got substantial feedback that this improved performance

**Review by stanalbatross — APPROVED** [review]

**Pull request merged**
