### PR TITLE
New UPP/UA sprites and new satchels

### PR DESCRIPTION
**Pull request by BadAtThisGame302**
# About the pull request

Adds a UPPA Patch and a UPP Naval Infantry Patch, along with a UPP table flag and a large UA flag

Also adds two new leather satchels, blue and black aswell as an updated red armband

Fixed the insulated gloves not using the insulated sprites but lightbrowngloves

Lastly adds the above mentioned UPP Patches to all current UPP presets, adding more soul

# Explain why it's good for the game

I felt like the UPP over here lacks some soul, has one patch which has no onmob sprite, to which now it has an equal amount of patches to the USCM

Also added a UPP table flag and a large UA flag, able to be placed anywhere same as the current banners/flags

Two new satchels I've been meaning to add for a while, but kept putting it off, so bundled it here.

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl:
add: Added the new UPPA and Naval Patches to all UPP inserts.
fix: Fixed the insulated gloves not having the insulated sprite.
imageadd: added a black and blue satchel, also an updated red armband sprite courtesy of AmoryBlaine
imageadd: added a big UA flag, a UPP table and two new UPP patches all thanks to the folks over at PVE. AmoryBlaine, Morrow and AndroBetel
/:cl:

### CODE REVIEW

**Comment by sleepynecrons** [comment]
please post sprite previews in sprite-related PRs. you've also gone over the "soul" use counter by 2

**Review by sleepynecrons — CHANGES_REQUESTED** [review]
satchel sprites themselves are fine besides the blue one needing to start open like our current one and the black satchel

the black shading around the star on the UA flag has a few unnecessary shades that just make the palette messier than it needs to be. it can just be one solid color or they need more contrast to make sense being used

the vdv and naval patches need to be redone/cleaned up into the more modern patch look like below. would make things simpler to just use the palette you already have from the generic UPP patch 
image

**Comment by BadAtThisGame302** [comment]
Made the black around the UA star one color

Made the blue satchel start open

Nothing I can do about the vdv patch, since that is the only patch the game had before I added the UPP patch and I personally think them having their own style than the USCM patches is fine, but I can remove the naval patch if you want

**Comment by sleepynecrons** [comment]
> Made the black around the UA star one color
> 
> Made the blue satchel start open
> 
> Nothing I can do about the vdv patch, since that is the only patch the game had before I added the UPP patch and I personally think them having their own style than the USCM patches is fine, but I can remove the naval patch if you want

them having their own style of patch is fine, but i more specifically meant reworking how the borders are done and the weird shades of green. they shouldn't need more than 4 shades of red and 4 shades of gold maximum

**Comment by BadAtThisGame302** [comment]
> > Made the black around the UA star one color
> > Made the blue satchel start open
> > Nothing I can do about the vdv patch, since that is the only patch the game had before I added the UPP patch and I personally think them having their own style than the USCM patches is fine, but I can remove the naval patch if you want
> 
> them having their own style of patch is fine, but i more specifically meant reworking the shading and the weird greens used in the palette. they shouldn't need more than 4 shades of red and 4 shades of gold maximum

How about these? I'm not a spriter so.

image

**Comment by sleepynecrons** [comment]
> > > Made the black around the UA star one color
> > > Made the blue satchel start open
> > > Nothing I can do about the vdv patch, since that is the only patch the game had before I added the UPP patch and I personally think them having their own style than the USCM patches is fine, but I can remove the naval patch if you want
> > 
> > 
> > them having their own style of patch is fine, but i more specifically meant reworking the shading and the weird greens used in the palette. they shouldn't need more than 4 shades of red and 4 shades of gold maximum
> 
> How about these? I'm not a spriter so.
> 
> image

if you're fine with those then i am. you could keep the golden border but if you're not up for it then it's fine

**Comment by BadAtThisGame302** [comment]
> if you're fine with those then i am. you could keep the golden border but if you're not up for it then it's fine

Uploaded the new ones, kept the old ones incase someone wants to change them.

**Review by sleepynecrons — APPROVED** [review]
sprites approved

**Review by Drulikar — CHANGES_REQUESTED** [review]
Is it intentional that you want `/obj/item/clothing/gloves/marine/insulated` to be still the light brown icon?

Is it intentional that nothing uses the new flags or satchels?

Please update the missing changes in your changelog.

**Comment by BadAtThisGame302** [comment]
> Is it intentional that you want `/obj/item/clothing/gloves/marine/insulated` to be still the light brown icon?
> 
> Is it intentional that nothing uses the new flags or satchels?
> 
> Please update the missing changes in your changelog.

Made the marine gloves also use the insulated sprite

I didn't want to add map changes aswell to the PR, but I was planning on adding some UA flags to the Almayer and UPP table flags in the ERT station in another PR. And about the satchels, well they are there and I can give them to the CL aswell, but if you have any suggestions on how to implement them feel free.

Updated the insul changes to the changelog

**Comment by Drulikar** [comment]
> And about the satchels, well they are there and I can give them to the CL aswell, but if you have any suggestions on how to implement them feel free.

Sure. And or combat correspondents. But up to you.

**Review by Drulikar — APPROVED** [review]

**Pull request merged**
