### PR TITLE
CC's Room Buff

### PR DESCRIPTION
**Pull request by HeresKozmos**
# About the pull request

Increases the size of the Combat Correspondants room and adds a few things requested by a friend of mine.

# Explain why it's good for the game

Expands the cramped CC room and adds a few QOL additions.

# Changelog

:cl:
add: added flashlight, donk pocket box, interview table, folder, taperecorder, ink toner, extra lights and expanded the size of the CC's room.
/:cl:

### CODE REVIEW

**Comment by HeresKozmos** [comment]
Whoops looks like I accidentally added a pipe under a wall, fixing now.

**Comment by HeresKozmos** [comment]
random pipe has been evaporated, CM is saved 🙏

**Comment by LC4492** [comment]
Please, could you try on also adding extra toners for the photocopier? Its very hard to mass-produce newspapers with such a short ink limit

**Comment by HeresKozmos** [comment]
holy shit toner cartridges arent a myth they're real

**Review by harryob — APPROVED** [review]

**Pull request merged**
