### PR TITLE
Synthetic Prototype Smartpack Glow Up (IAMTHEGUY EDITION)

### PR DESCRIPTION
**Pull request by QuickLode**
# About the pull request

Big thanks to iamtheguy for spriting these! 
SUPER Resprite Synthetic Smartpack
Adds Dark Blue Synthetic Smartpack
Resprite Dispatcher Uni, WJ Uni, Synth Uni, Old Synth Uni, Janitor Uni), Councilor Uni
Small vendor change(PMC/UPP chooses relevant smartpack colors, adds smartpack & dispatcher back to USCM Synthetic)

# Explain why it's good for the game
Up to date sprites which include excellent exoskeleton preference(can be toggled) for visibility. Generally speaking, updating sprites is important to keep aesthetic.

# Testing Photographs and Procedure
Tested in a series of 4 rounds to check for bugs, and misplaced pixels. 

New Uniforms and Smartpacks image

New Smartpacks
https://cdn.discordapp.com/attachments/777257424590995466/1259490241719435264/image.png?ex=668dd971&is=668c87f1&hm=289930f08f819190205745f66f76d7b2a67d07ea23606930b09af245c3445964&

New Smartpacks onmob back
image

Exoskeletons
https://cdn.discordapp.com/attachments/777257424590995466/1259482307153362985/image.png?ex=668dd20e&is=668c808e&hm=31b04ac872c1ea675b52722bf137aff423ad97fa48a5fcf24c8b45e5b40ad482&

Comparison of before and after (DIFFERENT COLORS)
https://cdn.discordapp.com/attachments/1042176396711170119/1259490343536296006/image.png?ex=668e824a&is=668d30ca&hm=09dfb6007c7fba8f40e5e10f81d22e2ab518f0c28f8b503d0b6dc4c8b5ab660f&
</details>

# Changelog
:cl:
add: Adds darkblue Synthetic Smartpack & dispatcher uniform for Synthetics
imageadd: Adds several BEAUTIFUL Synthetic Smartpack sprites made by iamtheguy, giving a new flair and updated aesthetic.
imageadd: Adds updated WJ uniform, dispatcher uniform, synth uniform, old synth uniform, synth pristine uniform, made by iamtheguy. Old sprites overwritten.
del: limits UPP/PMC Synthetic vendors to choose from relevant smartpacks
del: removes skull balaclavas from synthetics
spellcheck: changes Wey-Yu to Weyland Yutani in smartpack reference, clarifies 'synthetic' prototype smartpack
spellcheck: corrects a typo where surgical cap blue was mentioned twice
/:cl:

### CODE REVIEW

**Review by Drulikar — APPROVED** [review]
Code changes look fine

**Comment by Drulikar** [comment]
Stale exempt until sprite reviewed

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Review by Blundir — CHANGES_REQUESTED** [review]
Multiple uniforms resprites are worse than the current ones, multiple backpack colors are off and multiple mistakes with sprite positions. Elaborated on discord.

**Pull request closed without merging**
