### PR TITLE
Adds a dedicated IO Prep Room

### PR DESCRIPTION
**Pull request by efzapa**
# About the pull request
IOs now have their own dedicated prep room, with all the same vendors as they had in the Intel Processing Room, their Spawn location has also been moved.

# Explain why it's good for the game
Mostly QOL for ASOs but it's a combination of not wanting to have to deal with IOs leaving heaps of gear in Intel and not cleaning up after themselves, and just that in my opinion, a prep area and work area shouldn't really be merged together as it usually leads to problems with one or the other causing problems for each other, be it one side lying gear on the floor or the other throwing it away.

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

image

</details>

# Changelog
:cl:
mapadd: Added an IO Prep Room
/:cl:

### CODE REVIEW

**Comment by thevandie** [comment]
does this replace the armorer's workshop and the little cafe with the stuff in it?

**Comment by efzapa** [comment]
> does this replace the armorer's workshop and the little cafe with the stuff in it?

yes, as far as I am concerned if Officers or Enlisted want to have a hangout RP spot for eating, they have the Officers Mess and Mess Hall respectively

armorers shed isn't really used either and is just maint fluff with gun boxes, if Nanu wants I can stuff it back in somewhere else

**Comment by thevandie** [comment]
Alright thats a -1 from me

**Comment by SASoperative** [comment]
Why not change the IO 'lobby' area that is only really used to store crates that have not been processed yet? 
I can't remember the last time it has been used for anything that is not just crate storage, or where trash from the crates normally go, if it even is used at all.

Even than, picking up the gear of three people and just throwing it into a rack so its out of sight is also maybe 30 seconds. IO's are not super messy in comparison to whole squads.

I won't deny, IO's having their own dedicated prep would be nice, but I don't think it should come at the cost of two parts of the ship, one of which I know is used on a frequent basis by marines (Or at least the L42s in the armory are)

**Comment by efzapa** [comment]
will re-map this eventually

**Pull request closed without merging**
