### PR TITLE
NERFS scout's engineering skill to NOVICE

### PR DESCRIPTION
**Pull request by ihatethisengine**
# About the pull request
Scout now have SKILL_ENGINEER_NOVICE instead of SKILL_ENGINEER_TRAINED.

# Explain why it's good for the game
The only reason for this PR is to fix the situation where it is too easy for scouts to repair the sensor tower.
 
Scouts used to carry engineers in the tarp in order to repair the sensor tower which was pretty funny. But then they found out that all they needed were tools. Anyway it's pretty lame that an invisible entity can repair the tower with little to no risks. Checking the tower every two minutes to look if it was sneaky repaired really brings me to pre-perma nesting times. It's lame. And bringing an engi was way cooler and soulful, and required some actual teamwork. I don't think scout really needs engineering skills for anything else, C4 is useable with SKILL_ENGINEER_NOVICE.

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl: ihatethisengine
balance: scout's engineering skill is now 1.
/:cl:

### CODE REVIEW

**Comment by HeresKozmos** [comment]
lgtm

**Comment by JackieEstegado** [comment]
This will also prevent scout from being able to shock doors :(

**Comment by ihatethisengine** [comment]
> This will also prevent scout from being able to shock doors :(

Not my intention to nerf this exact thing, but I don't think I've ever seen scouts do this, so that's kinda irrelevant. On another note, scout's gloves are not insulated as far as I know, so I am not sure if this ever was intended.

**Comment by Unknownity** [comment]
Reccomendation for a different approach if your issue is solely the sensor tower.

Change the skill check in fixing it to ENGI instead of TRAINED, could apply the same to comms towers.
Buff engi skill to all proper engineer presets to ENGI (mainly CLF, UPP,PMCs and IOs) except survivor ones (synthvivor currently has trained, you could buff it to ENGI or keep it if you don't want survivors being able to fix comms and sensors)

This way scout keeps his engi skill but isnt able to secretly repair comms and sensor towers behind xeno's backs. also makes survivors unable to fix comms and sensor towers for marines to INSTANTLY know the hive location and that xenos exist before even landing.

**Review by harryob — CHANGES_REQUESTED** [review]
i enjoy the above suggestion, do that

**Comment by Nanu308** [comment]
i enjoy the above suggestion, do that

**Comment by ihatethisengine** [comment]
> Reccomendation for a different approach if your issue is solely the sensor tower.
> 
> Change the skill check in fixing it to ENGI instead of TRAINED, could apply the same to comms towers. Buff engi skill to all proper engineer presets to ENGI (mainly CLF, UPP,PMCs and IOs) except survivor ones (synthvivor currently has trained, you could buff it to ENGI or keep it if you don't want survivors being able to fix comms and sensors)

This is what I did initially and if I made so neither SL nor FTL nor even IO would be able to repair the tower. And if I am to buff their engineering skill, this will also affect their cade repairing speed, which is obviously not something we should pursue. 

I think nerfing scout's skill is the least invasive thing to do (well other than hardcoding scout inability to repair the tower lol). Another thing I can do is to change the skill required to construction, as both FTL and SL have it, although IO has not, which is not very cool.
<details>
Also opinion of the guy who added the skill. Not like it's up to him to decide, but still worth looking at.
https://discord.com/channels/150315577943130112/964684928161808384/1299128122687619145
</details>

**Comment by ihatethisengine** [comment]
So after all barricade repair speed is not scaled with engineering skill, so I guess it doesn't really matter and we can just give SL, FTL and IO ENGI level. Although I am still not sure if this is the best solution.

**Comment by cuberound** [comment]
as far as I can see ENGI level skill right now does not allow for any other stuff that TRAINED and speeds up from multiplier of 0.5 to 0.36 1)fixing reactors 2) disarming nuke 3)fixing cammera 4)taking apart machinery 5) hacking vendors 6)loading DS ammo 7) fixing m2c 8) moving m56d 9) fixing tank parts 10) reloading sentry but who cares 11) fixing senzors 12) fixing apc . in conclusion none of this is done in battle but I feel like engi should be faster then them at it buuut ehh whatever, the only other level is master that is 0.1 and giving that to engi would make them three times fiaster at stuff listed above

**Comment by Diegoflores31** [comment]
scout should not have the ability to fix neither comms nor sensor tower . thats engineer stuff.

**Comment by Diegoflores31** [comment]
> i enjoy the above suggestion, do that

the current engi skill is not the old engi skill . new engi skill makes repairing cades and stuff faster and is intended to be something only for comtech and MT to differentiate them from non engineers that build barricades .

having to give this skill to SL , IO and other roles just so scout cant do it is kinda weird and its an easier solution to just reduce the scout skill since they arent supposed to be engies anyways

**Comment by Venuska1117** [comment]
(Sugestion) Alternative solution: make custom trait/skill for repairing tcomms/sensor rower, sk you can assign it to aby role that should do that.

**Comment by Diegoflores31** [comment]
> (Sugestion) Alternative solution: make custom trait/skill for repairing tcomms/sensor tower, so you can assign it to any role that should do it.

unnecesary solution to a simple problem

**Review by harryob — APPROVED** [review]
bit boring of them to do it themselves isnt it. the tarp thing is funnier

something something promoting teamwork social game dynamics cohesion yep

**Pull request merged**
