### PR TITLE
Fixes lifeboat launch console being slashable / acidable

### PR DESCRIPTION
**Pull request by zzzmike**
# About the pull request

Lifeboat launch console is clearly meant to not be slashable / acidable (especially since it already has breakable=false flag and the lifepods are already properly flagged unacidable / unslashable. This fixes the problem.

# Explain why it's good for the game

Fixes a bug.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
fix: lifeboat launch console is no longer slashable / acidable
/:cl:

### CODE REVIEW

**Comment by zzzmike** [comment]
(I didn't mean for this to be flagged as feature)

**Review by Drulikar — CHANGES_REQUESTED** [review]
You need to also implement the proc `ex_act` and return (do nothing) since it currently can be destroyed that way too.

**Comment by zzzmike** [comment]
thanks :)

**Review by Drulikar — APPROVED** [review]

**Comment by HaultyAnonie** [comment]
Why doesn't `breakable = FALSE` account for all types of damage? What's it used for then?

**Comment by Drulikar** [comment]
> Why doesn't `breakable = FALSE` account for all types of damage? What's it used for then?

`breakable` only applies to some structure's implementation of `attack_animal` and `attack_alien` But in general there isn't much standardization to defines like `breakable`, `unslashable`, `unacidable`, etc. You just need to look at their references in code to see what they do.

**Pull request merged**
