### PR TITLE
adds a tgui for the pred preferences menu

### PR DESCRIPTION
**Pull request by harryob**
title

https://github.com/user-attachments/assets/d415d1ad-1805-4e36-a590-1e8ea3e58cfc

:cl:
ui: adds a pretty tgui for pred prefs
/:cl:

### CODE REVIEW

**Review by Blundir — APPROVED** [review]

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Review by realforest2001 — APPROVED** [review]

**Pull request merged**
