### PR TITLE
adds 1 hour human roles timelock to nurse

### PR DESCRIPTION
**Pull request by stanalbatross**
## About The Pull Request

adds a 1hr human roles timelock to nurse

## Why It's Good For The Game

nurse has _somewhat_ higher responsibilities than a PFC or MT and should require at least a tiny tiny bit of game knowledge before you play it!

also it is mentioned NOWHERE in quickstart etc and is pretty hard for new players to learn

another reason to add this is that nurse is also very easy for multikeyers to grief with so this should stop them a bit

## Changelog

:cl:
code: nurse now has a one hour human roles timelock
/:cl:

### CODE REVIEW

**Comment by Shad0vvs** [comment]
Goblin slayer

**Comment by pedr69** [comment]
noooo my lexorin!

**Comment by DylonBR** [comment]
cringe, stinky goblin was a fun griefer and never ceased to amuse marines

**Comment by SirVerbsAlot** [comment]
stop metanerfing stinky goblin just bcuz they r good.

**Comment by PhantomEpicness** [comment]
-1 racist against goblins
reported for rule 1 break
have a cm day

**Comment by Blithering** [comment]
You taste chloral hydrate.

**Comment by Oshuka1997** [comment]
whats the point of adding 1 hour timelock? instead of new players being able to play the role in the first round they now they have to play the role in their second round

**Comment by stanalbatross** [comment]
> whats the point of adding 1 hour timelock? instead of new players being able to play the role in the first round they now they have to play the role in their second round

Please read the PR description :)

**Review by Shad0vvs — APPROVED** [review]

**Pull request merged**
