### PR TITLE
Removes superslow and instant movement from the lurker's crippling strike ability

### PR DESCRIPTION
**Pull request by NewyearnewmeUwu**
# About the pull request
In this PR, I remove the superslow and instant movement that the base lurker's Crippling Strike provides for the simple fact that it's redundant. I however did also buff the damage multiplier you get to 1.4, with a successful crippling strike dealing a base 49 damage. I removed most of the superslow and instant movement code (slashing lets you move immediately with the latter), but I **kept in** the stun on a pounced target. If needed I can buff this damage more or add in a non-superslow. I've tested this and it causes no errors.

# Explain why it's good for the game

Lurker is already a quite deadly caste, and as someone who plays both sides the crippling strike feels a little excessive. This still allows you to get kills, you just need to work harder for each kill. If slugs had their superslow removed, I believe that the lurker's crippling strike deserves the same. In addition, the fact that you can instantly move after slashing with this ability in addition to the aforementioned slug nerf means that you deal with hordes of lurkers- base lurkers, mind you -fighting in the open every round, using the slows and instant movement to fight with minimal risk. I do not believe an ambush caste should be able to fight in the open quite like normal lurkers can at the moment.

In addition as I said in the 'about' section, the slow is redundant- by doing damage and quite possibly breaking someone's foot, you're already slowing them down. It's just not needed. The instant movement also allows for overzealous lurker players to avoid punishment in situations where there are marines nearby to shoot, ie. PB with a shotgun. It's not as if the pounce locks you in place for a long time, either.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
balance: removed the superslow and instant movement from the base lurker's Crippling Strike.
/:cl:

### CODE REVIEW

**Comment by NewyearnewmeUwu** [comment]
I fully expect that this is a controversial PR, and I will accept any feedback.

**Comment by carlarctg** [comment]
all of the feedback that u can't see..... wah this system sucks!

neutral on pr myself

**Comment by NewyearnewmeUwu** [comment]
> all of the feedback that u can't see..... wah this system sucks!
> 
> neutral on pr myself
Basically, lurkers will still do more damage than they did before, they just don't get superslow and instant movement. They still get the knockdown effect just to keep pouncing somewhat viable (testing with it removed showed it resulted in people almost instantly getting up, which is not the intention). Making lurker more risky to play is the intention.

**Comment by Chainsawicus** [comment]
> If slugs had their superslow removed, I believe that the lurker's crippling strike deserves the same.

They didn't, it was reduced and not removed. #2472

**Comment by NewyearnewmeUwu** [comment]
> > If slugs had their superslow removed, I believe that the lurker's crippling strike deserves the same.
> 
> They didn't, it was reduced and not removed. #2472

Still, the superslow is redundant- You usually are so slow from the broken limb that you inevitably get that you can't really escape.

**Comment by Nanu308** [comment]
Gonne go ahead and deny this on a design level in its current iteration after reading the feedback and making my own conclusions based on it and gameplay seen/done

**Pull request closed without merging**
