### PR TITLE
Marked_admin and ckey.

### PR DESCRIPTION
**Pull request by Segrain**
# About the pull request

Byond is being Byond. Key and ckey are not the same thing.

# Explain why it's good for the game

Selfevident.

# Changelog

:cl:
admin: Marking tickets properly recognises your ckey.
/:cl:

### CODE REVIEW

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Review by harryob — APPROVED** [review]
i could’ve sworn i changed some of these but i am probably misremembering

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by Segrain** [comment]
> i could’ve sworn i changed some of these but i am probably misremembering

I forgot to fetch the latest master first, should be all good now.

**Pull request merged**
