### PR TITLE
Officer Amenities Revamp

### PR DESCRIPTION
**Pull request by Mechanelize**
## About The Pull Request

Before:
old

After:

## Why It's Good For The Game

Makes Staff Officer bunks and Cafeteria more central to the CIC area, with a door to the main CIC hallway, this should promote more use of the area.

Brings Officer's Study from north of upper Medbay to directly under CIC, might add some _soul_ to the area, otherwise just to fill in otherwise empty space.

Moved XO bunks, given wood floor, a little more space, and a few more amenities 

## Changelog

:cl:
add: Moved and improved XO's Quarters
qol: Moved Staff Officer bunks, Officer's Study, Officers' Mess, and CIC SMES.
/:cl:

### CODE REVIEW

**Comment by NuggetsOnToast** [comment]
You can literally walk through the bottom maintenance hall to bypass the entire CIC lockdown shutters in your new design which is not good.

If an XO is ACO its not ideal for them to ditch the op to RP in their office, also why is the XO office bigger than the COs?

Just a few issues I've noticed from a first glance at this PR

**Comment by Mechanelize** [comment]
> You can literally walk through the bottom maintenance hall to bypass the entire CIC lockdown shutters in your new design which is not good.

Fixed.

> If an XO is ACO its not ideal for them to ditch the op to RP in their office, 

Ditching the op is a problem (which I don't see happening) that can be dealt with ICly with ML or OOCly, if an XO really wants to ditch the op to RP they can do it office or not. Offices can also be used to deal with serious issues shipside while the leading the op is delegated down to SOs.

> also why is the XO office bigger than the COs?

Its not, the main office is about 30 tiles smaller whole the whole area is about 40 tiles smaller.

**Comment by stanalbatross** [comment]
> Makes Staff Officer bunks and Cafeteria more central to the CIC area, with a door to the main CIC hallway, this should promote more use of the area.

does it need to be more used? why is this good for the game

> Brings Officer's Study from north of upper Medbay to directly under CIC, might add some soul to the area, otherwise just to fill in otherwise empty space.

utterly meaningless, please expand on this as to why this merits disrupting the current layout

> Replaces the XO's never touched bunk with a proper office opposite the CO's right below the CIC. Should promote more roleplay opportunities for the XO, especially as aCO.

the XO is not the CO, they do not need an office. They have an entire conference room for any purposes an office might serve

please fully explain why this PR is good for the game or it will be closed

**Comment by Mechanelize** [comment]
> does it need to be more used? why is this good for the game

I think it will promote round-start and round-end gathering of the SOs in the area, talking over some drinks, donuts, and cigs. Its also now viewable to anyone walking into the CIC, opposed to the only window being below the cafe. This adds to the feeling that the ship is actually used outside of rounds.

> utterly meaningless, please expand on this as to why this merits disrupting the current layout

Three things, first off I originally moved it to take up space that the XO's office would've expanded into, making it just as large or larger than the CO's office, which wouldn't have made sense. Second, with the room being in somewhat direct view of the CIC it should encourage SOs who only sit in the CIC to check out the new area and learn some lore about the current map, besides these two computers the only one accessible to SOs in the CIC area is next to the brig entrance, an area plenty of SOs never visit. Third, I don't think it really disrupts the area, these rooms are already seldom used and out of the way, so these changes should only encourage more roleplay opportunities in those areas.

> the XO is not the CO, they do not need an office. They have an entire conference room for any purposes an office might serve

This is the change that I'm not totally in love with, and that I wanted more input on, hence the draft. If nobody has a better idea I'll  convert the main office area back into the XO's bunk and foam the empty space.

**Comment by c4xmaniac** [comment]
SO barracks room had a door with no blast doors allowing you to enter directly into the CIC hallway during lockdown

also why does the XO get almost as good of a room as the CO. I’d recommend looking at submarine and ship layouts to see how space is accommodated based off rank.

**Comment by Mechanelize** [comment]
> SO barracks room had a door with no blast doors allowing you to enter directly into the CIC hallway during lockdown

You can still get into that same hallway and CIC during lockdown from the new bunks, its just a little bit longer of a walk.

> also why does the XO get almost as good of a room as the CO. I’d recommend looking at submarine and ship layouts to see how space is accommodated based off rank.

I will look into this and adjust accordingly.

Solid feedback. Same with @NuggetsOnToast

**Comment by Mechanelize** [comment]
After reviewing the layout of some ships and subs I've decided to shrink the XO's quarters to just a bunk with no office. Changes reflected in about section.

**Comment by Mechanelize** [comment]
Closed because wasn't branched properly, conflicted with master.

**Pull request closed without merging**
