### PR TITLE
increases bullet hit accuracy to  CL’s ES-4

### PR DESCRIPTION
**Pull request by deathrobotpunch**
# About the pull request
this PR increases the hit accuracy of the CL’s Sidearm, with this change the bullets it fires will have hit accuracy tier 4.

# Explain why it's good for the game
Due to CL being a pleb and having 0 firearms skill, the accuracy of the ES-4 was severely decreased causing most of your shots missing due to RNG making it almost useless when compared to pepper spray. additionally the ES-4 was advertised as being very accurate in its description when that wasn’t the case.

By the way I am completely open to change so if you have any complaints I’ll take them to heart ❤️.
# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl:
balance: buffed the stun subtype of rubber bullets to have hit accuracy tier 4
/:cl:

### CODE REVIEW

**Comment by deathrobotpunch** [comment]
why did it add the feature label?

**Comment by Diegoflores31** [comment]
> why did it add the feature label?

after CL weapon was added , support was added to make some weapons need no weapons training to be shot . you could add that

**Comment by deathrobotpunch** [comment]
> after CL weapon was added , support was added to make some weapons need no weapons training to be shot . you could add that

really? where could I find this

**Comment by BOBAMAx** [comment]
> 
> really? where could I find this

civilian_usable_override from #2766, however I do not think that it has an effect on accuracy, only scatter.

**Comment by zzzmike** [comment]
> why did it add the feature label?

because the first version of your PR didn't have changelog done properly - it didn't change the label after you edited it for whatever reason

**Comment by deathrobotpunch** [comment]
> civilian_usable_override from #2766, however I do not think that it has an effect on accuracy, only scatter.

read the code and this is already applied to all pistols and SMG’s

**Comment by Nanu308** [comment]
this is fine

**Review by kiVts — APPROVED** [review]

**Pull request merged**
