### PR TITLE
TESTMERGE ONLY: Experimental Canteen Changes

### PR DESCRIPTION
**Pull request by spartanbobby**
# About the pull request

# Explain why it's good for the game
# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl:SpartanBobby
maptweak: Maptweak
/:cl:

### CODE REVIEW

**Comment by efzapa** [comment]
No Briefing Area? Or am i missing something on the mapdiff

**Comment by Nanu308** [comment]
Test went amazing, must be repeated at some point...

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by Nanu308** [comment]
Closed. Msg if need to be re-opened for tests.

**Pull request closed without merging**
