### PR TITLE
hair gradient free

### PR DESCRIPTION
**Pull request by irakligabunia**
# About the pull request

makes the hair traits free in character traits

# Explain why it's good for the game

hair gradients are an amazing addition to cm, graying hair and darker colors make most hairstyles/colors look nicer
i don't think it should be limited at all
if hair colors aren't limited, we shouldnt limit gradients too

# Testing Photographs and Procedure

number change

# Changelog

:cl: stalkerino
balance: fixes the balance of the game by making hair gradient trait free
/:cl:

### CODE REVIEW

**Comment by HeresKozmos** [comment]
pretty nice

**Comment by irakligabunia** [comment]
extremely good PR, continue like this and you'll get maintainer

**Comment by irakligabunia** [comment]
> extremely good PR, continue like this and you'll get maintainer

thanks, will keep grinding 🙏

**Review by Birdtalon — APPROVED** [review]
I'm not even sure what this counts as.

**Pull request merged**
