### PR TITLE
Requisition Centralization [Part 1]

### PR DESCRIPTION
**Pull request by ItsVyzo**
# About the pull request
Adds a bolted version of the blood and medical vendors
Only the Field Equipment Vendors can down be taken down for FOB
Adds new pill bottle crate to requisitions
Makes medical crates ordered via req cheaper to compensate

# Explain why it's good for the game
Centralizes requisition gameplay and increases its overall importance in the gameloop. This is just part 1 of a requisitions centralization update. I highly advise TMing this, to properly balance overall requestion prices and perhaps add more medical crates as needed

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl: LTNTS
add: bolted version of blood and medical vendors
add: pill bottle crate
balance: cheaper medical crates from req
balance: less items in med vendors, mainly pill bottles
/:cl:

### CODE REVIEW

**Comment by Staykeu** [comment]
it always bugged me that the vendors actually meant for groundside deployment went untouched for most rounds, other features are cool too

good pr

**Review by Drulikar — DISMISSED** [review]
Please also incorporate your changes with the changes from #5280 (will likely conflict with this PR)

**Comment by ItsVyzo** [comment]
> Please also incorporate your changes with the changes from #5280 (will likely conflict with this PR)

Mapping did not conflict somehow and #5280 changes are still there which is awesome

**Review by Drulikar — APPROVED** [review]
Code changes are fine and not seen any feedback regarding this during TMs.

**Comment by ItsVyzo** [comment]
#5677

**Pull request merged**
