### PR TITLE
update wo clothing surplus vendor to the more modern distress mode.

### PR DESCRIPTION
**Pull request by Huffie56**
# About the pull request

# Explain why it's good for the game
# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl:
balance: update wo clothing surplus vendor to the more modern distress mode.
/:cl:

### CODE REVIEW

**Review by Drulikar — CHANGES_REQUESTED** [review]
Just simply copy pasting the inventory to these vendors is not going to work - the only edits I see made is removal of the drop pouch, and an increased scaling of the shoulder holster. For example, the headsets are just common channel (when it used to provide each squad's) and you're providing telephone packs when there are no telephones to use.

Also worth mentioning there are 2 more of these vendors on WO than there are on the Almayer.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by Drulikar** [comment]
Single argument round should be floor now.

**Comment by Huffie56** [comment]
it's been a while since i was on this PR and with the var name change and drak comment i think it's better to start fresh with a new PR.

**Pull request closed without merging**
