### PR TITLE
minor tacmap ui change

### PR DESCRIPTION
**Pull request by Cthulhu80**
# About the pull request
it's kind of been bothering me for a bit, just some minor tacmap ui changes.

# Explain why it's good for the game

I got ocd, please merge. 

# Testing Photographs and Procedure
Screen Shot 2023-12-20 at 3 24 17 PM

Screen Shot 2023-12-20 at 3 27 20 PM

# Changelog
:cl:
ui: tacmap ui tweaks
/:cl:

### CODE REVIEW

**Review by Drulikar — APPROVED** [review]

**Review by Drulikar — CHANGES_REQUESTED** [review]
https://github.com/cmss13-devs/cmss13/blob/master/code/controllers/subsystem/minimap.dm#L822
Must also be updated with this change.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Review by Drulikar — APPROVED** [review]
Undraft when you're happy with the changes.

**Pull request merged**
