### PR TITLE
Fireman Carry Pamphlet for Riflemen

### PR DESCRIPTION
**Pull request by TheKillfish**
# About the pull request

New pamphlet that teaches the fireman carry skill. Does not prevent from reading JTAC or standard Engineer pamphlets . Avaliable in Rifleman prep vendors for 15 points and Req line armament vendors. It is also an item that can be requested during the Req tutorial.

# Explain why it's good for the game

Fireman carry is a pretty handy and soulful skill that everyone can do except for riflemen. Hearsay I've seen is they don't have it due to balance concerns, but they're also the ones most likely to get regular use out of it and level 1 carry is still slower than a roller bed in terms of moving people, so making it a pamphlet is my proposed middleground. I also made it not interfere with using standard engineering pamphlets and JTAC pamphlets because it's a bit silly to lock people out of those more useful skills just because you want to dramatically carry someone.

# Testing Photographs and Procedure
Added trait that pamphlet teaches, added pamphlet. Checked in rifleman prep and Req, made sure it didn't cause runtimes anywhere. Used it as rifleman and could lift someone on my back.

# Changelog

:cl: Killfish
balance: Adds Fireman Carry pamphlet.
add: Adds the Fireman Carry pamphlet to Rifleman prep vendors and to Req line storage. Carry your fellow marine away from danger in dramatic fashion!
/:cl:

### CODE REVIEW

**Comment by ihatethisengine** [comment]
Problem with fireman carry is that you don't have reliable means to break it unlike roller bed. If you don't have CC (or it's on CD) there is nothing you can do.

**Comment by TheKillfish** [comment]
Because HM's already have it.

There are infact only 3 USCM roles that don't have any skill in fireman carrying; Riflemen, Nurses and Researchers. Not sure about Combat Correspondants, so they might also be on the list, but point is; everyone else has it.

As for breaking out of it; you can literally just walk to insantly break out being carried and spamming resist, while not instant, is also an option.

**Comment by TheKillfish** [comment]
Sounds more like a thing that grabbing in general needs changing then, which is out of scope for what this PR is for.

Idk, maybe make xeno slashes have a 50/50 chance to force grabs to drop, since at the end of the day fireman carry is just a fancy grab.

**Comment by Red-byte3D** [comment]
This is a balance change and needs the balance tag, also powercreep

Thing added for one role only > thing spread to role > thing spread to even more role. Not something we need

**Comment by TheKillfish** [comment]
> Thing added for one role only > thing spread to role > thing spread to even more role.

Except as I've already said, a majority already can do the fireman carry, with Nurse, Researcher and Combat Correspondant being the only other ones without the skill. And this is a pamphlet, not a new default; if you want it, get it from Req if they still have them or spend loadout points for it.

**Comment by GoldenDarkness55** [comment]
> Except as I've already said, a majority already can do the fireman carry, with Nurse, Researcher and Combat Correspondant being the only other ones without the skill. And this is a pamphlet, not a new default; if you want it, get it from Req if they still have them or spend loadout points for it.

just remove it from majority again and restore it to what it was meant to be in the first place then.

**Comment by CABSHEP** [comment]
People have misconceptions about fireman carry, because all they see is Synth doing that. A PFC doing that is barerly faster than just dragging, but dragging doesn't have a windup like fireman carry does. 

That being said 15 points is not worth it. For that price I can have MD, or miniengi skills. Nobody will buy that, it is much better to buy cheaper stretcher and carry it somewhere.

**Comment by private-tristan** [comment]
Steelpoint made a comparison video between rollerbeds and fireman carry back in 2023.

https://github.com/user-attachments/assets/e5c73409-b93a-4c4b-a028-3bb66fb86d62

**Comment by ihatethisengine** [comment]
> Steelpoint made a comparison video between rollerbeds and fireman carry back in 2023.

Really irrelevant as you can break the bed forever, and only some CC abilites let you break the fireman carry.

Also I really missed when we gave fireman carry to HMs, powercreep as its finest. Not like I am completely opposed to the change but I think you should address the issue first. Maybe let xenos break fireman carry with slashes, maybe with some rng or dmg threshold.

**Review by Nanu308 — CHANGES_REQUESTED** [review]
I do believe fireman carry is quite strong still, so I'll want you to increase the cost price to 25, I'll balance approve after.

If it's too much, we can lower it at later date, but I wish to observe it's effects when multiple marines have it relatively easily accessible.

**Comment by chefoxara** [comment]
this would be really nice for backliners, hate having to drag back my friend's corpse being slow as fuck when i cant carry a stretcher (limited space)

**Comment by harryob** [comment]
pr has been stale with requested changes for two months, let us know when you're ready to work on this and we can reopen it / just make a new pr

**Pull request closed without merging**
