### PR TITLE
USCM ERT Station | USS Kurtz

### PR DESCRIPTION
**Pull request by Steelpoint**
# About the pull request

Adds a USCM ERT station that can be used for ERTs. The station consists of the entire lower-deck and a tiny snap-shot of the upper deck based off of the Sulaco. 

The name of the ship is the 'USS Kurtz', this is based off of the character from Joseph Conrad's novel 'Heart of Darkness', this is meant to follow the criteria of USCM ships being named off of concepts, people or places from his novels. 

Currently only the CBRN ERT will use this.

# Explain why it's good for the game

Bit odd the CBRN were coming from a WY ship. More roleplay options as to being rescued by a USCM warship, or for admin events

Nice Nostalgia to see the ole Sulaco back in action as well. 

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

</details>

# Changelog
:cl:
mapadd: The USS Kurtz has been added as a USCM affiliated ERT station. The design off the USS Kurtz is based off of the USS Sulaco, from older versions of CM-SS13. The USS Kurtz features the entire lower-deck and a snapshot of the upper deck.
mapadd: The USCM CBRN ERT will use the USS Kurtz as their homebase. 
/:cl:

### CODE REVIEW

**Comment by DexterDude** [comment]
Narcissus is the name of the escape pod in Alien.

**Comment by Steelpoint** [comment]
> Narcissus is the name of the escape pod in Alien.

Damn. I'll pick another name out of the Conrad hat.

**Review by harryob — CHANGES_REQUESTED** [review]
i like a lot of this - but you'll want the USCM semiotics (https://docs.google.com/document/d/1fONsGxSfF_ZvSZZygxMxAAofvLY_FdEBRgrhXgEQPfI/edit) on the walls, and consider popping pipes/disposals under the catwalks - even just for flavour, they suggest a larger vessel

**Comment by Steelpoint** [comment]
I've expanded the lower deck to cover most of the original layout, and I've added piping, vents and semiotics. If more semiotics are needed just let me know.

**Comment by Steelpoint** [comment]
Ok, did some more aesthetic work, few more semiotics, I've added two fake upper-deck areas so that the ladders actually work and I've added a 'USS KURTZ' spraypaint near a window.

**Comment by Steelpoint** [comment]
stale comment

**Comment by Drulikar** [comment]
Stale exempt until map/sprite review.

**Review by harryob — CHANGES_REQUESTED** [review]
this is looking nice with the added polishing

CleanShot 2024-07-08 at 07 40 11@2x
this font doesn't match the almayer's - is that intentional? the almayer uses Stencil Std Regular

**Comment by Steelpoint** [comment]
> Stencil Std Regular

I've been unable to find that font, nor do I have the ability to use this font now that its origin is revealed to me, so I used a close approximation. 

I'd either have to remove the words or have someone else make it for me.

**Comment by Steelpoint** [comment]
> this font doesn't match the almayer's - is that intentional? the almayer uses Stencil Std Regular

I was unaware as to what the font was, I'll remedy that issue shortly.

**Review by harryob — APPROVED** [review]
i like it!

**Pull request merged**
