### PR TITLE
Cooked mortar shell explosion is now fixed

### PR DESCRIPTION
**Pull request by Git-Nivrak**
# About the pull request
Fixed as in static, doesn't change for different mortar shell types
Makes the explosion when setting mortar shells on fire fixed and small

# Explain why it's good for the game
This was supposed to be a niche feature like ammo boxes exploding and instead it is being used to blow up inside pylons \ caves or even on shipside. This is why we can't have nice things.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
del: Mortar shells no longer blow up their payload, instead they will create a small fixed explosion.
/:cl:

### CODE REVIEW

**Comment by ihatethisengine** [comment]
Maybe just limit the throw range to like 4 (you can also do this just to OT shells, or even nerf OT shells even further) and just make the explosions weaker, like 0.75 strength of what you would get from launching it via mortar

**Comment by cuberound** [comment]
do NOT add old explosion code it does not behave like you would expect, I think this just spawns cell_explosion 120 power with fallof 40

**Comment by Pyrodes** [comment]
Removing intuitive gameplay one feature removal at a time

**Review by Drulikar — CHANGES_REQUESTED** [review]
Please check whether there even is ordinance that can explode (namely customs). Up to you if you want a different kind of handling for liquids (napalm). Also please use the other explosion proc since https://github.com/cmss13-devs/cmss13/pull/6497 intends to refactor out what you're using.

**Review by Drulikar — APPROVED** [review]

**Pull request merged**
