### PR TITLE
Shaman Removal (Pending Rework)

### PR DESCRIPTION
**Pull request by MaximusRexCM**
# About the pull request

In this PR, I have removed every instance of the Shaman strain from the code.

# Explain why it's good for the game

Shaman has been slated for a major overhaul for months now, and the last series of tests were unsuccessful in producing good results for a replacement design. It is a primary server goal to rework/phase out shield gameplay entirely, and Shaman is the biggest offender in this regard. In light of how severely shaman is affecting the game, and how long it's been under the knife for reworking, I am removing it pending a better strain design. 

# Testing Photographs and Procedure

Booting into a local copy of the game, I was unable to spawn or evolve into a shaman at all. I also tested Queen screech to be sure, and found the behavior was normal. No runtimes, errors, or otherwise unintended behavior was found. Please contact me ASAP if an issue occurs. 

</details>

# Changelog

:cl: MaximusRex

balance: Removed shaman strain from carrier.
spellcheck: Changed a minor entry in the Carrier.DM to reflect the above changes.

/:cl:

### CODE REVIEW

**Review by morrowwolf — COMMENTED** [review]
From a balance perspective:

Shaman carrier shield is intensely unfun to play against and shouldn't be as powerful as it currently stands. Shaman carrier has been attempted to be reworked (with failure) and it continues to be a problem in game. Without a clear and ready rework I think it should be removed.

**Comment by MaximusRexCM** [comment]
I've attempted to fix the merge conflict, hopefully it went through correctly.

**Comment by Ultimate-Fluff** [comment]
I'm curious as to what the maintainer consensus is on this matter.

**Comment by MaximusRexCM** [comment]
Second merge conflict resolution attempt

**Review by morrowwolf — APPROVED** [review]

**Pull request merged**
