### PR TITLE
3WE Rank Rework

### PR DESCRIPTION
**Pull request by IroquoisLou**
# About the pull request

Removes the japanese names from the 3WE ranks, adds the new rank of colour sergeant to the RMC.

# Explain why it's good for the game

Consistency, the RMC officer ranks don't have japanese hybrid names so the enlisted shouldn't either, as for the colour sergeant rank it's to expand on the RMC ranking system, as currently they don't have an equivalent to staff sergeant, i've also changed all ranks to their IRL equivalent.

In addition, i've added IASF ranks for future use in IASF Erts, these use japanese navy ranks for officers and japanese army ranks for the enlisted.

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

Removed Japanese title's from the RMC, instead RMC will use the Real RMC's ranks while japanese ranks go to the IASF.

:cl:
add: Added the rank of colour sergeant to the RMC, to give the RMC, a Staff Sergeant equivalent
del: Removed the japanese title's from the RMC ranks
/:cl:

### CODE REVIEW

**Comment by thevandie** [comment]
Wait, can you please re add the Japanese ranks but comment them out? I plan to use those titles for the IASF later, so having all the names on hand would be useful later incase I forget

**Comment by efzapa** [comment]
should probably get lore approval tbh, considering 3WE includes Great Britain *and* Japan, removing them (Japan) almost entirely from the game apart from the "Emperor" rank is odd to say the least.

**Comment by cuberound** [comment]
the correct reasoning is not "officers do not have it so standard should not either" but "standards have them and they are the only roles that apper in gameplay, officers should have them too" at least in my opinion

**Comment by Lukas-Seltz** [comment]
If I remember correctly Japan is the primary faction of the TWE and should follow Japanese rank system. As well as TWE is missing many officer ranks as they follow naval.

**Comment by IroquoisLou** [comment]
> should probably get lore approval tbh, considering 3WE includes Great Britain _and_ Japan, removing them (Japan) almost entirely from the game apart from the "Emperor" rank is odd to say the least.

3WE also includes india but we don't have indian ranks, the UPP includes Germany and Spain as founding countries along with china but i only see russian ranks, factions usually take the ranks of the predominant force, only the 3WE is stuck with this weird rank system, the UPP isn't.



> the correct reasoning is not "officers do not have it so standard should not either" but "standards have them and they are the only roles that apper in gameplay, officers should have them too" at least in my opinion

Officers in lore are only the british ranks, this is because the RMC is based off the british Royal Marines, the only japanese ranks should be in the IASF, which is the more japanese focused part of the 3WE military.



> If I remember correctly Japan is the primary faction of the TWE and should follow Japanese rank system. As well as TWE is missing many officer ranks as they follow naval.

No it isn't, the 3WE was formed by japan and britain (along with the commonwealth) merging, neither is really above the other, but the 3WE mainly takes from britain, their flag is more union jack inspired then inspired by the japanese flag, they have a parliament and a prime minister like the UK, so if anything the 3WE is more british.



> Wait, can you please re add the Japanese ranks but comment them out? I plan to use those titles for the IASF later, so having all the names on hand would be useful later incase I forget

No because the RMC ranks don't even fully conform with japanese ranks.

**Comment by IroquoisLou** [comment]
> > > should probably get lore approval tbh, considering 3WE includes Great Britain _and_ Japan, removing them (Japan) almost entirely from the game apart from the "Emperor" rank is odd to say the least.
> > 
> > 
> > 3WE also includes india but we don't have indian ranks, the UPP includes Germany and Spain as founding countries along with china but i only see russian ranks, factions usually take the ranks of the predominant force, only the 3WE is stuck with this weird rank system, the UPP isn't.
> 
> 3WE was formed from Great Britian and Japan, the rest are simply allies that were merged in and would not have the bargaining power to have a say in the military as much as the main two.
> 
> Same could be said for the UPP, where it can be assumed both Russia is vastly larger AND most of the military would be Russian

And Britain's military is bigger then Japan's, oh and also china has more people in it's military and is just as large, if not larger, then russia, so i guess we should change UPP's ranks to chinese right?

**Comment by cuberound** [comment]
> > > > should probably get lore approval tbh, considering 3WE includes Great Britain _and_ Japan, removing them (Japan) almost entirely from the game apart from the "Emperor" rank is odd to say the least.
> > > 
> > > 
> > > 3WE also includes india but we don't have indian ranks, the UPP includes Germany and Spain as founding countries along with china but i only see russian ranks, factions usually take the ranks of the predominant force, only the 3WE is stuck with this weird rank system, the UPP isn't.
> > 
> > 
> > 3WE was formed from Great Britian and Japan, the rest are simply allies that were merged in and would not have the bargaining power to have a say in the military as much as the main two.
> > Same could be said for the UPP, where it can be assumed both Russia is vastly larger AND most of the military would be Russian
> 
> And Britain's military is bigger then Japan's (which only has a self defense force), oh and also china has more people in it's military and is just as large, if not larger, then russia, so i guess we should change UPP's ranks to chinese right?
> 
> oh and also spain and germany should have just as much bargaining power as the UPP in that case given they're literal founders of it.

oh and they do, UPP ship has german name and guns technicly use type stuff generly used for chinese designs

**Comment by IroquoisLou** [comment]
> > > > > should probably get lore approval tbh, considering 3WE includes Great Britain _and_ Japan, removing them (Japan) almost entirely from the game apart from the "Emperor" rank is odd to say the least.
> > > > 
> > > > 
> > > > 3WE also includes india but we don't have indian ranks, the UPP includes Germany and Spain as founding countries along with china but i only see russian ranks, factions usually take the ranks of the predominant force, only the 3WE is stuck with this weird rank system, the UPP isn't.
> > > 
> > > 
> > > 3WE was formed from Great Britian and Japan, the rest are simply allies that were merged in and would not have the bargaining power to have a say in the military as much as the main two.
> > > Same could be said for the UPP, where it can be assumed both Russia is vastly larger AND most of the military would be Russian
> > 
> > 
> > And Britain's military is bigger then Japan's (which only has a self defense force), oh and also china has more people in it's military and is just as large, if not larger, then russia, so i guess we should change UPP's ranks to chinese right?
> > oh and also spain and germany should have just as much bargaining power as the UPP in that case given they're literal founders of it.
> 
> oh and they do use names from other faction, UPP ship has german name and guns technicly use "type" stuff generly used for chinese designs. the reason why UPP have russian ranks is that someone bothered to change them form the english ranks thay had to the only rank system of UPP that they knew. UPP uses names from other factions too where it is possible, you do not even bother and make a step away from the correct path. the reason why UPP do not have more chinese stuff is the firewall and that we have super few players from china.

Yes and the 3WE does use Japanese names and indian names when possible, but they don't have hybrid ranks, anyways here's confirmation off Kaga on the RMC ranks.

image

**Comment by IroquoisLou** [comment]
Alright, i'm expanding this even further, i'm changing the RMC's officers ranks to be more accurate to the real RMC, while also adding in Japanese ranks for the IASF.

The plan for the IASF is for them to have ground self defence force for enlisted and naval self defence force ranks with officers, this way if you want Japanese ranks you can add in IASF to use those ranks.

**Comment by IroquoisLou** [comment]
I'll add descriptions to the IASF tomorrow

**Review by harryob — APPROVED** [review]

**Pull request merged**
