### PR TITLE
CL vendor cash is now legal

### PR DESCRIPTION
**Pull request by deathrobotpunch**
# About the pull request
changes the CL’s 1000 dollar cash incentive from unmarked bills to legitimate money.

# Explain why it's good for the game
1. it doesn’t make sense for the CL to be given illegal cash as an incentive.
2. unmarked bills was able to be converted into marked bills by combining two stacks of cash together anyways.
# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl:
balance: The Space IRS has sued W-Y for offering counterfeit cash to their employees, All cash incentives offered are now legitimate.
/:cl:

### CODE REVIEW

**Comment by Diegoflores31** [comment]
This will make Black market go BRR . 
the only reason CL money is "counterfeit" is so you cant load it on BM

**Comment by deathrobotpunch** [comment]
> This will make Black market go BRR . the only reason CL money is "counterfeit" is so you cant load it on BM

The cash stack combining bug has been around for years at this point, if someone wanted to abuse the BM then they would already have.

and anyways if someone was abusing it then you could make that an RP situation by sending a Provost Inspector or the like.

**Comment by RainbowStalin** [comment]
If BM is being overused, we already have the CMB to come in and punish REQ for doing so.

**Comment by harryob** [comment]
i'm not really interested in the blackmarket getting this broken

**Pull request closed without merging**
