### PR TITLE
Adds a way to change GL firing levels

### PR DESCRIPTION
**Pull request by stanalbatross**
## About The Pull Request

Slight grenade launcher buff by letting them change their firing level between high toss and no high toss (the latter lets agms detonate on contact, etc)

Added high toss back to the mk1 UGL to negate use of the above on it.

## Why It's Good For The Game

the m79 especially has been underperforming a bit lately, this should help it.

The mk1 UGL should not be better with agms than the m79

## Changelog

:cl: Stan_Albatross, Nauticall
add: you can now toggle the firing level of the m79 and the m92 grenade launchers between high toss and no high toss using a HUD button or unique-action. Sprites by Nauticall.
balance: added back high toss to the mk1 UGL.
/:cl:

### CODE REVIEW

**Comment by GoldenDarkness55** [comment]
Just give them high toss by default? Unsure why would anyone ever use standard, even for AGMs aside from making a mistake/forgetting the toggle. Noobtrap "Press X to make your gun better" toggle.

**Comment by stanalbatross** [comment]
> Just give them high toss by default? Unsure why would anyone ever use standard, even for AGMs aside from making a mistake/forgetting the toggle. Noobtrap "Press X to make your gun better" toggle.

they already have high toss by default.

**Comment by GoldenDarkness55** [comment]
> they already have high toss by default.

I c, I misread thinking UGL gets the toggle aswell. derp

**Review by FransFeiffer — APPROVED** [review]
Sprites LGTM

**Review by Shad0vvs — APPROVED** [review]

**Pull request merged**
