### PR TITLE
scuffed diagonal movement

### PR DESCRIPTION
**Pull request by BeagleGaming1**
# About the pull request

I probably did this terribly

# Explain why it's good for the game
Diagonal movement makes moving feel more smooth

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl:
balance: added diagonal movement
/:cl:

### CODE REVIEW

**Comment by morrowwolf** [comment]
Wheelchair diagonal movement seems to allow for teleportation
Tacmap broken
Dragging seems to be slower than usual, especially xenos dragging marines
Lag is up, move is using a significant chunk of CPU

**Comment by private-tristan** [comment]
moving diagonally on weeds is extremely quick, probably from the "speed increase on weeds" that xenos have activating twice. the opposite is true for walking on other weeds, moving diagonal is ABSURDLY slow on it.

**Comment by morrowwolf** [comment]
Not today diagonal movement. We'll think about it again next year.

**Comment by PhantornRU** [comment]
> Not today diagonal movement. We'll think about it again next year.

Well. Next year?

**Pull request closed without merging**
