### PR TITLE
Almayer: Dirty Up The Ship (Lower Deck)

### PR DESCRIPTION
**Pull request by Steelpoint**
# About the pull request

Transforms the lower decks maintenance areas into a far more dirty, disorganized, area to be in. Emphasizing how many areas of the ship are in dire need of drydock repairs. 

Sees the addition of a old 'tank repair bay' in one of the empty hanger rooms. Featuring a broken tank. 
Also sees the addition of a 'ammo storage room' north of briefing. Featuring all of the ships remaining HEAP magazines and SADARs. 

I hope to get to the upper deck in a separate PR. 

(There should not be any actual real hidden HEAP ammo or anything akin to that.)

Major Things Worth Mentioning

- The 'ammo store room' contains a lot of empty HEAP magazines and several SADARS and L42A's, the SADARS and guns are props and are non-functional. There is a single "HEAP" magazine with 5 bullets in it, but the bullets are standard rounds, with the magazine explicitly stating this.
- There are two damaged sentry guns in maintenance. These guns contain a single rubber bullet, are set to fire on anyone, and can not be deconstructed or used by the marines in any way. 
- The items in the Tank bay are all props, no tank gear is useable except for the Tanker helmet. 
- There's a single 'empty space' tile in maint that will kill you if you walk into it. However it is sectioned off by a lot of barriers and warnings, it is set up to make it unlikely someone will accidently run into it. 

# Explain why it's good for the game

Aesthetics. 

The Almayer is intended to be a ship in very desperate need of repairs. Transforming the unused areas of the ship into a more derelict apperance may help impart this to the player. 

No major balance change has been effected to these maint areas. Aside from being more cluttered and dank. 

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Screenshot 2023-07-31 15 46 16
Screenshot 2023-07-31 12 04 17
Screenshot 2023-07-31 11 57 42
Screenshot 2023-07-31 00 02 18
Screenshot 2023-07-28 23 46 33
Screenshot 2023-07-28 10 11 58
Screenshot 2023-07-31 17 35 48

</details>

# Changelog
:cl:
maptweak: Lower deck maint of the Almayer is significantly more run down. 
maptweak: Tank repair bay has been placed in the north-east of hanger. Behold the Tank in all its glory. 
maptweak: Ammo storage room can be found north of briefing. All the remaining HEAP magazines can be found there. 
/:cl:

### CODE REVIEW

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by Steelpoint** [comment]
All right, I think we're good.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by Steelpoint** [comment]
Merge conflicts are painful

**Comment by morrowwolf** [comment]
TM'ing this because this is cool. I have some vague concerns regarding effects being always on but we'll see and our playerbase is bound to find anything hidden ASAP

**Review by morrowwolf — CHANGES_REQUESTED** [review]
Alright a few things off the bat:

The ammo room needs toned down a bit, less just stuff

The hole that leads to ASRS pit is neat but is too much

Only one meme turret

More to come I'm sure. There are some concerns about just general object density but I'll need to run it by others.

**Comment by Steelpoint** [comment]
Requested changes made

**Comment by Steelpoint** [comment]
100% going to get back to this, but likely in a week or so. Just need to clear some time to fix it.

**Pull request closed without merging**
