### PR TITLE
Revert #2320   vehicles are removed

### PR DESCRIPTION
**Pull request by ThiccFucc**
# About the pull request

Reverted all changes to code made, as documented in https://github.com/cmss13-devs/cmss13/pull/2320/files
**Spare restoration of one deletion in "USS_Alamayer.dmm". The file was too large to open, and I couldn't figure out how to edit the raw file. This may still need to be reverted for the PR to properly work.**
The purpose of the PR was to act as a reversion of PR 2320. I merely traced back all the edits/deletions to the code done in correlation to that PR, and reverted them to their old form. One reversion still needs to be made. I have not tested this. I have no idea if this will work, or even how to code. I learned to use github like an hour ago, so please forgive any oversights ( ͡° ͜ʖ ͡°)

# Explain why it's good for the game

As stated previously in discord, a large portion of players in the community currently desire the APC back in the game. After being told at least one person of that majority had to do the "bare minimum" of opening a revert PR, I've made an attempt to do so. I know that the maintainers have removed the APC for various reasons, and as it stands the current APC doesn't align with their vision for moving forward with CM and improving the game. However, there have been other ideaguys posts opened to determine how to rework the APC from the ground up and tackle any issues it may have. I hope the APC can be redesigned and be brought back better than before, although I imagine that may take a hot minute, and it certainly goes beyond my skillsets to address the issues developers have voiced regarding it. However, I believe other people with the proper skillsets are willing to undertake that endeavor. All I'm asking for with the introduction of this revert is to bring back the old APC until that day comes, to allow those players who enjoy it to continue doing so until such a time that it can be reworked. Thank you for your consideration, and apologies again if I just screwed this PR up royally!

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl: ThiccFucc
add: Added several deleted lines of code in numerous files across the entirety of the gamecode

/:cl: ThiccFucc

### CODE REVIEW

**Comment by DarkLordCabbage** [comment]
I agree with the revert, but don't have the coding experience necessary to help make sure it works, sorry!

**Comment by Geevies** [comment]
for one like i will return to CM and remove the APC again

**Comment by Unknownity** [comment]
In the future, If you wish to revert a PR, there is one simple way to do it.
Head to the PR that you wish to revert, scroll down to the comment that merged the commit/PR and you will see a lovely "Revert" button on the right. The way you did it can seriously cause unexpected issues.
Screenshot_3

**Comment by ThiccFucc** [comment]
If this pr brings geeves back, I would still consider this an absolute win

**Comment by ThiccFucc** [comment]
And thank you so much Unknownity!!!!
I will DEFINITELY keep that in mind in the future lmao
I uh
Yeah, I definitely wish I'd asked first instead of trying to learn how to sift through code from scrathc..

hehe

he

ಥ ͜ʖ ͡ಥ

**Pull request closed without merging**
