### PR TITLE
Armor Naming Revamp

### PR DESCRIPTION
**Pull request by Misttyy**
## About The Pull Request

This is a little thing I've talked with SergeantMuffin and Monkey on the lore team about - We have quite a lot of armor right now within the USCM, with a lot not being used or simply being bloat. This thins out a number of those items, and condenses things where able in order to reduce bloat - As well several bug fixes are included.

## Why It's Good For The Game

These new description and names are based off AvP Extinction, The Technical Manual & RPG in order to bring us closer towards the movie. They're a small thing that give off more flavor about the world. Some bloat items are removed, like the various MP armors that were never used - And officer armor, which incentivized officers to deploy to frag rather than doing their job, and didn't make much sense.

## Changelog

:cl: Mistfrag
add: New descriptions for armors.
del: Removed PADLESS MP, warden, CMP, officer, B18 and M4 armor. These've all been simplified to reduce bloat. Instead warden and CMP get standard M3-Peacekeeping Pattern Armor. Officers get M3 standard configuration.
fix: Fixed CO not spawning in his armor on WO
fix: Should have fixed Marine Raiders not spawning in their proper armor.
spellcheck: Standardized M3 naming conventions.
refactor: Added better path name for CO armor.
:cl:

### CODE REVIEW

**Comment by Shad0vvs** [comment]
QOL has nothing labeled and compile maps has 2 errors.

**Comment by Misttyy** [comment]
@Shad0vvs You can remove QOL, not sure why that was left in, blame my bad eyesight.

**Comment by harryob** [comment]
fix for fiorina

**Comment by Misttyy** [comment]
> fix for fiorina

done :)

**Review by stanalbatross — CHANGES_REQUESTED** [review]
Changes are already being made to MP armour so you can drop these, there's also very little reason for them as "armour bloat" is not a thing

CL is inaccurate regarding IO/RTO armour changes

Also there's no need to nerf SO armour as it's not majorly better than marine armour and really isn't a factor in making them want to deploy - it's mainly the gun and the fact they don't want to sit in cic

**Review by morrowwolf — CHANGES_REQUESTED** [review]
Make sure when you change the inheritance of something you verify you move everything it was inheriting over.

Specifically for the CO armor, you've changed values.

**Comment by Misttyy** [comment]
I'm going to close this and completely rewrite this

**Pull request closed without merging**
