### PR TITLE
Removes flame particles

### PR DESCRIPTION
**Pull request by morrowwolf**
# About the pull request

This is a paid PR.

Allegedly fire was lagging the player. I assume the particles are the issue.

# Explain why it's good for the game

Given the vast range of people who play CM with varying levels of computer hardware it would be prudent to remove anything that may be lagging players. Game feel good.

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl: Morrow
del: Removed flame particles. Possibly increases performance for some players.
/:cl:

### CODE REVIEW

**Comment by SabreML** [comment]
If the particles only affect a small number of players, would it be worth putting them behind a 'Fancy Graphics' preference or something similar? That would solve the issue, and also allow other similar effects to be added to it in the future.

**Comment by fira** [comment]
I wish but I don't think you can easily put them behind a toggle short of maybe rendering doubled to a second optional plane ? That's going to be a lot of logistics for just that

Would normally be against such PRs but the effect is pretty subtle to begin with

**Comment by ihatethisengine** [comment]
I can confirm fire lags a lot

**Comment by morrowwolf** [comment]
Honestly it still looks fine without it, the effect here is sorta minimal.

I think you can add particles to client images but it'd be kinda weird iunno.

**Comment by Nanu308** [comment]
Gonen throw on the sprite label for le spriters to judge the funny visual looks

**Review by harryob — APPROVED** [review]

**Comment by harryob** [comment]
lummox keeps saying he'll make particles perform better eventually. maybe one day

**Pull request merged**
