### PR TITLE
donation alerts

### PR DESCRIPTION
**Pull request by AndroBetel**
# About the pull request

image

allows fans to send donations to their favorite streamer (Combat Correspondent) through the TV Set

# Explain why it's good for the game

while watching and hearing CC on TV is cool and all, it's a little underwhelming since you can't really interact with them in any meaningful way. this adds this "meaningful way" while also giving some use to money apart from RP and vendors and shit

if maintainers feel like it's too memey, i can remove nickname choosing

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

yep...

</details>

# Changelog
:cl:
add: Added donations mechanic for Combat Correspondent. Just hit your local TV with cash.
/:cl:

### CODE REVIEW

**Comment by ihatethisengine** [comment]
should add another field for the sender's name

**Comment by AndroBetel** [comment]
>should add another field for the sender's name

added

**Comment by Drulikar** [comment]
This just isn't the direction we want to take the roleplay. Nor do I think what has been coded is salvageable for something else.

Internally a suggestion that was made though if people want to explore more features for combat correspondent would be to make basically a spotter kit where you can try to get a private to be your camera man. This could be the way the military version gets a camera, but I don't know.

The image they shared from Starship Troopers: 
image

**Comment by LC4492** [comment]
Conclusion: Keep it for the next April Fools, and is prank 100% approved (For the 1st April)

**Comment by Diegoflores31** [comment]
No way twitch streamer job is real . Based

**Pull request closed without merging**
