### PR TITLE
Lv 624 junglification

### PR DESCRIPTION
**Pull request by LynxSolstice**
# About the pull request

I thought LV624 wasn't jungle-y enough for being a jungle planet, so I was talking to harryob and he told me I can just, map it myself, so I did.

# Explain why it's good for the game

Adds more vines and shrubs and trees and greenery, makes the place feel less like a desert as soon as you cross the river.

# Testing stuff

It runs and initializes and loads, it's a map edit.

# Changelog

:cl:LynxSolstice
maptweak: Makes LV624 more jungle-y and less desert-like. North of the river changed to reflect this. All grass turfs (turf/open/gm/grass) replaced with their weedable variant (turf/open/gm/grass/weedable)
/:cl:

### CODE REVIEW

**Comment by NewyearnewmeUwu** [comment]
pics?

**Comment by Unknownity** [comment]
What's with the undocumented changes (removal of all colony phones) you made?

**Comment by harryob** [comment]
> pics?

its current year use the diffbot

**Comment by LynxSolstice** [comment]
> 

what? I didn't touch the phones

**Comment by LynxSolstice** [comment]
phones are now back in, my fork was out-dated.

**Pull request merged**
