### PR TITLE
Limits colossal sandwich to 15 layers

### PR DESCRIPTION
**Pull request by Blundir**
# About the pull request

Title, you can't put more than 15 items on it

# Explain why it's good for the game

Let's be real here, i know that it's fun, but it's also lrp, causes lag, entire server was lagged out because of it on multiple occasions, not to mention that it blocks vision and is generally buggy.

Discord_SyKShw3YhY

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

The maximum size of it

dreamseeker_5U2ZSwuGaM

</details>

# Changelog
:cl:
del: limits colossal sandwich to 15 layers
/:cl:

### CODE REVIEW

**Comment by Git-Nivrak** [comment]
How about you optimize it instead of removing soul

**Comment by Blundir** [comment]
Doesn't mitigate other things

**Comment by fira** [comment]
Assuming there's no way to remove ingredients (i don't see any?) there might be an easy optimization which is just storing the sandwich top overlay and removing it instead of rebuilding the whole overlays

But i don't know if that's enough and that doesn't really solve the other issues

**Comment by cuberound** [comment]
jeh, rebuilding it from bottom up every time is kinda silly, but reducing layers solves more then just performance issue

**Review by realforest2001 — APPROVED** [review]

**Pull request merged**
