### PR TITLE
Xenos can eat food to regain health (lore accurate)

### PR DESCRIPTION
**Pull request by ihatethisengine**
# About the pull request

Xenos can eat not packaged food. Nutriments from food now heal xenos and restore their plasma. 

# Explain why it's good for the game

It's lore accurate (I've been told so, my source is @Diegoflores31).

Gives a way for marines to heal friendly xenos. Gives shipside runner a way to heal off weeds. Massive mess chief buff.

# Testing Photographs and Procedure
<details>

https://github.com/cmss13-devs/cmss13/assets/115417687/3ec00ec5-1bf6-4f38-893c-4f8e421bb7bc

</details>

# Changelog
:cl: ihatethisengine
add: Xenos can eat food to regain health and plasma.
/:cl:

### CODE REVIEW

**Comment by morrowwolf** [comment]
Initial thoughts: weird

Fact checking with lore team.

**Comment by Diegoflores31** [comment]
In all the alien videogames xenos feed on the human corpses or animals to regain health . But since we do not allow hurting corpses i think this is the nearest ( btw would be cool if aliens only ate raw/cooked meat)

**Comment by ihatethisengine** [comment]
Also added plasma regaining because some castes are quite useless without plasma.

This shouldn't affect game balance in general because xenos usually have no way to find enough food (and they cannot move it) and healing on weeds usually suffice. It's mostly for situations when xeno is either off weeds and have to find other ways to regain health (fun task for shipside, imagine breaking into mess hall as a wounded lurker) or when xeno is allied to marines. Plus if my renegade PR gets merged, chances are we'll see a single xeno hive allied to marines with no convenient access to weeds. It would be an interesting task for marines to keep it alive with constant feeding. I do agree it feels a bit weird, but I don't think it's weird in a bad way.

**Comment by morrowwolf** [comment]
Spoke with lore team.

While some media do have xenos eating bodies/food we don't want to go this way for the server's lore. Apologies, I do appreciate the work you put into this.

**Pull request closed without merging**
