### PR TITLE
Flexible Job Icons

### PR DESCRIPTION
**Pull request by realforest2001**
# About the pull request

This PR makes editing job hud icons mid-round much more flexible, and will allow staff events to modify them without a lot of clunky cheating by trying to trick the game into displaying certain other icons.

I have also cleaned up a chunk of duplicate code in the USCM rank hud proc.

# Explain why it's good for the game

Makes events easier, also standardises how job hud is picked.

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl:
add: Added variables staff can use to override job hud. This will not alter security hud at this time.
code: Removed unused and duplicate code from the USCM faction hud.
/:cl:

### CODE REVIEW

**Review by harryob — APPROVED** [review]
whoever gets rid of that big ass switch() and puts it on the datum gets a cookie

**Review by harryob — CHANGES_REQUESTED** [review]
need to make compatible w #6490

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Pull request closed without merging**
