### PR TITLE
Médicale Révolutionnaire

### PR DESCRIPTION
**Pull request by LC4492**
# About the pull request

This Pull Request presents to you a complete rebuild and reconstruction of Almayer's upper and lower medbay on its entirety, Focusing on organization, attention to detail and proper...alligment, this PR have been made to solve most of the problems that our doc docs face nowadays, we may begin.

# Explain why it's good for the game

Lets start with how the design have been...designed. First we shall take a look at the lower deck, and then we may move to the upper.

>LOWER DECK:

 The design had in mind an organized setup to the three steps for a good day in medical (Triage, Wait and Surgery), the triage have been setup at the entrance, and the lobbies have been prepared at the halls facing the surgery rooms, which will easily facilitate the waiting of medical care. 
 The lobby have been shortened and the Chemistry/Medical Storage have been set up on the EAST of Medbay, making it easier for any marine personnel to collect any supplies from the medical department. The medical storage have now been fitted to also be a supply distribution room, staying side by side with chemistry and having its own line. 
 When those two rooms have been moved, the whole medbay on itself (Triage and surgical theaters) have been moved WEST, making a much smaller walking time from the dropships to the nearest doctor on the spot. 
 A reception have been properly made, together with a room specifically made to hold the ladders, making them much safer and providing much more mobility because of its position. The CMO office have been transferred and updated, now holding a divan for mental evaluations and a private cryosleep chamber for the man himself. 
 The field medical equipment are now storaged inside an enclosed room, which is protected by a shutter controlled by a button in the CMO office, meaning that now the CMO can properly protect the field supplies and only open them when he think its necessary. 
 Because of the expansion, the MP posts needed to be removed (I will make a PR solving that later) and instead, two new rooms assigned to the command have been created to only accomodate the ladders. As an extra, I've decided to add some chairs to the echo squad, the poor boys will finally have a place to sit!

>UPPER DECK;

 The Morgue room have been updated and expanded, now being able to hold 22 bodies! (wow) and now having its autopsy and processing rooms on a same room in the entrance, apart from economizing space, it also is actually much more logical and practical to use. 
The Armory have been properly set in a much more strategic position, close to the ladders and to the main hall, making it much easier to access, it have been expanded and some new utility tools have been added.
Now the Medical department finally have its own bunk room! Located where the armory once was, it fits all the medical uniform vendors, their beds and, of course, their shower! 
 The ladders on the upper deck also received its specific room, being *much* more easier to use now.

Any questions about the design or object emplacement shall be directly sent to me!

# Testing Photographs and Procedure
Captura de Tela (120)
Captura de Tela (121)
Captura de Tela (122)
Captura de Tela (118)
Captura de Tela (123)

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
fix: Fixed some yummy-tummies wrongly placed along the years by a ton of different people that didn't really pay attention to what they were doing.
maptweak: Completely refurnished the Almayer's Medbay Upper and lower decks.
/:cl:

### CODE REVIEW

**Review by harryob — CHANGES_REQUESTED** [review]
CleanShot 2023-03-10 at 22 15 44@2x
you can't varedit areas, it makes the tests fail - please make a subtype in code/game/areas/almayer.dm

**Comment by LC4492** [comment]
For now I will remove the edited area, still need to do some tinkering on the areas but in overall I believe that will clean it of problems.

**Comment by Agameofscones** [comment]
image
These pipes are probably going to break unit testing. Use the old pipe layout, remove the extra segment that's there.

image
These blast doors are doubled up, they shouldn't be (unless they were before, in which case who let that happen??)

image
Consider moving this phone, its hard to spot.

image
these should be renamed to 'North door release' and 'South door release'. Also buttons should only be put on reinforced tables, otherwise there's the potential to have 'em floating and that looks bad.

image
when stacking duplicate items like this, offset them all slightly so its easier to tell that it is a pile, and to make them easier to pick up.

image
consider splitting the contents across multiple lockers, this will be a right click or alt click nightmare to sort through in game. Lag tile.

image
Remove these plush dolls. They're easter egg items for the CL and that one Sgt. Huggs in the extended bunks. You can leave a single barricade plush since iirc its no where else atm.

image
People don't actually use clipboards. Please cut down on the stacked object spam, this is just extra junk that'll clog up the MC the next time a projectile or explosion hits this tile.

image
This is ripe chat-spam bait. Remove these. Leave it at one megaphone in the CMO's office, and that's it.

**Comment by Agameofscones** [comment]
Wrong button, did not mean to close, my apologies!

**Comment by Agameofscones** [comment]
image
Put these into a locker and reduce the quantity.

image
Seriously, reduce the object spam. Its all over. Maybe 1/3rd of this is ok.

image
bruh, this will probably kill a craptops byond client with a right click.

image
wrong manifold object, should be hidden subtype, not visible.

image
There are more latex gloves than there are possible doctors on the ship here.

image
offset this water cooler to be snug against the wall and set the density to 0

**Review by Agameofscones — CHANGES_REQUESTED** [review]
See previous comments.

**Comment by LC4492** [comment]
Well, I may do the required changes but I may first explain myself on some of the problems:

1. I've already had complaints about those pipes making the place uglier, so I tried to duck them below the objects for better appearance, now that you mentioned it, I may try to get those pipes to go through behind the objects, much like in the same design as before, but much more subtle.

2. They aren't really doubled, its because there's the medbay lockdown and the hangar lockdown, making them overlap in the same tile, it is the exact same style as before.

3. The idea for the phone is to put it between the chairs, making it easier to use, I can put it *in* the table, but may look uglier.

4. The idea I had in mind was that the plushies were property of the Chief Medical Officer, and he shared them with those he thought were suffering from some type of trauma, that's why its close to the freshly-placed divan. In general, Im just trying to get a replacement to the ol' toys and other shenanigans that the therapists had on the original SS13, with the objective of giving more opportunities to RP.

5. The clipboards are in the same amount as they were in the ol' reception, but instead they were in a file cabinet before, and now are in the table.

6. The quantities are basically the same from their original counterparts, with a little higher number than before.

For the rest, there are no explanations. The changes will be made accordingly for all fo them.

**Comment by LC4492** [comment]
...But really, the cooler was already like that before.

**Comment by LC4492** [comment]
Re-Merged and updated to the current map.

**Comment by LC4492** [comment]
...The mapdiff is failing, but both master and this PR map have been properly merged.

**Comment by LC4492** [comment]
YES!

**Comment by LC4492** [comment]
Still need to solve the merge conflict, will take a while

**Comment by LC4492** [comment]
Very well, must be up to date now, may any of the maintainers take a proper look at it to see if it will run?

**Comment by brjoaoed** [comment]
don't forget the 3x syringe cases that always had on medbay triage area, those cases can hold 3x injectors each, and fit inside webbing vests, useful for medics that wish to carry extra epi pens, i consider those essential for my medical loadout, and for sure having them at almayer med spares me the time to ask a researcher to print one

**Comment by LC4492** [comment]
Those syringes have been added to the medical storage/distribution and can be found above one of the tables. you may be able to it in one of the photos above.

**Comment by harryob** [comment]
superseded by #3106

**Pull request closed without merging**
