### PR TITLE
Allow SOs to perform basic surgeries

### PR DESCRIPTION
**Pull request by 567Turtle**
# About the pull request

gives so surgery 1

# Explain why it's good for the game

\> give SO surgery tools
\> dont give them the capability to use them

It was probably an over sight but despite having the tools to do surgery SOs don't know how. They aren't able to properly fulfill their role as medics in a time of crisis.

<details>
<summary>Screenshots & Videos</summary>

i didnt test this at all lol, probably works

</details>

# Changelog
:cl:
balance:  SO can now do basic surgeries
/:cl:

### CODE REVIEW

**Comment by Git-Nivrak** [comment]
Balance, not add in CL

**Comment by HeresKozmos** [comment]
This seems somewhat pointless and unneeded.

**Comment by 567Turtle** [comment]
> This seems somewhat pointless and unneeded.

YOURE somewhat pointless and unneeded

**Comment by MobiusWon** [comment]
> > This seems somewhat pointless and unneeded.
> 
> Currently as an SO it's neigh impossible to act as a corpsman, because you have to go and find an actual corpsman anytime you get a patient with IB. Which is a lot. IB is very common.

It is neigh impossible because SOs are not medics, they are leaders.

**Comment by ihatethisengine** [comment]
Should mention that this skill level only let them cure IB and suture, just like your regular medic

**Comment by 567Turtle** [comment]
> It is neigh impossible because SOs are not medics, they are leaders.

They're meant to be capable of being effective medics you GOOBER... Giving them a surgery kit and then not giving them surgery skill is like giving them the engineering kit but no engineering skill.

**Review by Drulikar — APPROVED** [review]

**Pull request merged**
