### PR TITLE
Fixes the Hive Status error when the Queen dies

### LINKED ISSUE #4330: Xeno Hive Status Screen Error
### Testmerges

N/A

### Description of the bug

The screen shows a TGUI error when the queen dies if you keep the xeno hive status panel open.
I have been able to reproduce locally as both a xeno and a ghost, as long as the screen is open when the queen dies (it does not error if the queen is deleted).

### What's the difference with what should have happened?

Either the screen to close, or continue to function correctly, instead of runtiming.

### How do we reproduce this bug?

1. Have the xeno hive status screen open
2. Have queen die, but not get deleted
3. Hive status panel runtimes

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

### PR DESCRIPTION
**Pull request by SabreML**
# About the pull request

Fixes the Hive Status window showing an error message when the Queen dies.

For xeno players, the interface just closes.
For observing players, the interface will show 'The Hive has no Queen!' where the queen's location was previously.
(The bug actually causing the error should be fixed too now)

(Note: I'm not quite sure what the `tgui-panel.bundle.css` diff is from, but it kept modifying itself whenever I compiled so I figured it was something related to this.)

# Explain why it's good for the game

Fixes #4330

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

**Testing queen spawn and death as the queen, as an observer, and as a xeno:**

https://github.com/cmss13-devs/cmss13/assets/57483089/ba3b2960-d4ce-4be4-af6b-6daae2d10ac1

</details>

# Changelog
:cl:
fix: Fixed the Hive Status window showing an error message when the Queen dies.
/:cl:

### CODE REVIEW

**Review by Birdtalon — APPROVED** [review]

**Review by Drulikar — CHANGES_REQUESTED** [review]
The hive status is accessed by more than just players in the game. So if anything the observer check should be before this UI_CLOSE return

(Testing not using this PR):
For example, a hive with a lone xeno viewed by observer: 
image
But of course the player can't access it: 
image

Tested on this PR: Nothing happens when an observer clicks view hive status.

You'd be better off simply adding a null check in the TGUI than this.

**Comment by SabreML** [comment]
> The hive status is accessed by more than just players in the game. So if anything the observer check should be before this UI_CLOSE return (but that won't prevent a crash)
> 
> (snip)
> 
> You'd be better off simply adding a null check in the TGUI than this.

For some reason, I had thought that observers couldn't see the hive status either if there was no queen.
I'll move the `ui_status()` check down so that it doesn't get closed for observers, and add something to the frontend.

**Review by fira — APPROVED** [review]

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Review by Drulikar — APPROVED** [review]

**Pull request merged**
