### PR TITLE
Refactors gun, attachment, ammo, and ammo box icons to be held in separate folders per faction.

### PR DESCRIPTION
**Pull request by carlarctg**
# About the pull request

# Explain why it's good for the game

This will help mantainability and with merge conflicts by splitting up all these thoroughly bloated dmis into bunches. It will also make it significantly easier to sift through the sprites for what you need instead of sifting through an awful 12 year old jumble of sprites in a single dmi.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
refactor: Refactors gun, attachment, ammo, and ammo box icons to be held in separate folders per faction.
/:cl:

### CODE REVIEW

**Review by harryob — APPROVED** [review]
this looks all good to me, but i think we might wanna tm for a couple rounds just in case…

**Comment by Nanu308** [comment]
Mapping lgtm

**Comment by Segrain** [comment]
Whatever this is, it is probably this TM's fault.
image

**Comment by carlarctg** [comment]
fixed

**Pull request merged**
