### PR TITLE
Minor Globber Nerf (Temporary)

### PR DESCRIPTION
**Pull request by BeagleGaming1**
# About the pull request

Removes long range from Globber Boiler

# Explain why it's good for the game

Morrow:
Glob is too powerful right now. Testing this to see if this solves some of the issues. This should make the more vulnerable to counterplay.

# Changelog

:cl:
balance: Removes the long range ability from Globber Boiler
balance: Bombard cooldown increased by 5s (20 -> 25). Bombard shot speed halved (1 -> 0.5)
/:cl:

### CODE REVIEW

**Comment by PhantomEpicness** [comment]
lgtm
- globber creator

**Comment by Ultimate-Fluff** [comment]
B r o we went from super long range to long range to no range. 

Make me cri.

**Review by Zonespace27 — APPROVED** [review]
Code good; no comment on balance

**Review by morrowwolf — COMMENTED** [review]
This is a stopgap while Bengus gets his nerfs ready.

**Pull request closed without merging**
