### PR TITLE
Fix Shuttle Landing Lights and Looming Shadow

### PR DESCRIPTION
**Pull request by Drulikar**
# About the pull request

This PR restores the hyperspace ripple effect for shuttles that are landing, as well as their landing lights getting stuck on (though will be more obvious when #3305 is merged because it fixed its lingering references to landing lights when it gets crushed by the shuttle). A debug message should also be logged whenever an anchored thing is crushed by the shuttle: There's a few maps where they have stairs and such that either should get whitelisted here too, or just the map adjusted to have a properly cleared landing zone.

# Explain why it's good for the game

- Better indication where its not safe to be (else get gibbed)
- It looks fancy again (see below section)

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

dark

</details>

# Changelog
:cl: Drathek
fix: Fix shuttle landing lights getting stuck on
imageadd: Added a transparent gray sprite to act as a shadow when a shuttle or something is looming over that tile
/:cl:

### CODE REVIEW

**Comment by Huffie56** [comment]
this will fix the issue of having no indication when the shuttle is landing when you get deaf...
https://github.com/cmss13-devs/cmss13/issues/2712
@Drulikar
the sound part is in this specific issue.
https://github.com/cmss13-devs/cmss13/issues/498

**Comment by Drulikar** [comment]
This PR doesn't address any issue with audio, so that's why I didn't link it. But it should *mostly* solve the issue for them.

**Comment by Huffie56** [comment]
> This PR doesn't address any issue with audio, so that's why I didn't link it. But it should _mostly_ solve the issue for them.

my idea was more to close the issue specific to having no warning when DS land and open a more general one concerning sound and being deaf...
The more clear an issue is the easier it is to investigate and fix it...
anyway your choice...

**Comment by Drulikar** [comment]
Changed it to be a shadow now.

**Review by sleepynecrons — APPROVED** [review]
sprites

**Review by harryob — APPROVED** [review]

**Pull request merged**
