### PR TITLE
APC and SMES TGUI

### PR DESCRIPTION
**Pull request by stanalbatross**
## About The Pull Request

image
image

ported TGUI APCs and SMESes from TG station

changed APC wires UI to tgui as well (somewhat annoying to make this work with the original tgui too but eh worth it)

changed a CI flow

slight refactor of SMES var names to make them make more sense

## Why It's Good For The Game

makes these machines use not a literal piece of shit laggy UI

also good stat checking etc

## Changelog

:cl:
ui: area power controllers, more commonly known as APCs, now use TGUI.
ui: SMESes also now use TGUI
/:cl:

### CODE REVIEW

**Comment by spookydonut** [comment]
You're going to want to port wire datums at some point too.

**Comment by stanalbatross** [comment]
need to fix smes input and output available

**Comment by stanalbatross** [comment]
> need to fix smes input and output available

fixed

**Review by Nanu308 — APPROVED** [review]
Map change fine

**Review by spookydonut — APPROVED** [review]

**Pull request merged**
