### PR TITLE
fixes setting up m2cs while inside a tarp

### LINKED ISSUE #113: scout and m2c bugs
## Description

guys in tarps can use m2cs

## Difference between expected and actual behavior

they should not be able to do this

## Steps to reproduce

obvious

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

### PR DESCRIPTION
**Pull request by stanalbatross**
## About The Pull Request

Title.

Thank you to Braden Bunten for helping me find this bug!

## Why It's Good For The Game

closes #113 

## Changelog

:cl:
fix: fixed being able to set up the m2c inside tarps, among other things.
/:cl:

### CODE REVIEW

**Comment by usnpeepoo** [comment]
-1 this is normal

**Review by Shad0vvs — APPROVED** [review]

**Comment by Shad0vvs** [comment]
Fixes #113

**Comment by stanalbatross** [comment]
> Fixes #113

you can edit the pr desc if you want....

**Comment by Shad0vvs** [comment]
> > Fixes #113
> 
> you can edit the pr desc if you want....

No.

**Review by Shad0vvs — CHANGES_REQUESTED** [review]
Changes pm'ed.

**Review by Shad0vvs — APPROVED** [review]

**Pull request merged**
