### PR TITLE
Drone Evolution T3: The Reaper (Re-up)

### PR DESCRIPTION
**Pull request by ThePiachu**
# About the pull request

Original PR by @Geevies - https://github.com/cmss13-devs/cmss13/pull/1899 .

Since Geevies is currently not developing this PR, I figured I'd give it a go to polish up the original concept and see if it can be shipped as is or whether it will need a bigger rework.

Notable changes from the original PR:
- Reaper is now considered a builder caste, so it can repair structures, deal with walls and pick up eggs. It doesn't have any build abilities other than special structure building though.
- Removed trap hole placing since the reaper didn't have anything to put in there
- The Reaper corpse now contains Egg Plasma, so try not to die!
- Once #2232 goes through, the Reaper's Egg Plasma will be hive-coded

# Explain why it's good for the game

Drones need a cool T3 variant and this is a neat way to take that concept.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl: Geeves, sleepynecrons, ThePiachu
add: Added a new T3 caste for the drone line called the Reaper. It evolves from the carrier and has a support-combat focus.
/:cl:

### CODE REVIEW

**Review by harryob — CHANGES_REQUESTED** [review]
image
need to kill some .procs

**Review by stanalbatross — CHANGES_REQUESTED** [review]
going to categorically say now that the "frontline infection egg plasma funny" ability will not work and needs to be removed or replaced + it leads to reaper eclipsing carrier and taking its niche

the caste should be wider support not just a better carrier that can operate solo with a few other abilities

**Review by morrowwolf — CHANGES_REQUESTED** [review]
The chemical injection in general last time was a serious issue as it was OD'ing people and medics were struggling to manage that consistently. 

Health and armor need rebalanced lower likely.

Getting hugged should really only happen from a facehugger or research fuckery IMO.

**Comment by ThePiachu** [comment]
After some feedback it looks like this will need a more serious update, so drafting it for now

**Pull request closed without merging**
