### PR TITLE
More HPR ammo in req

### PR DESCRIPTION
**Pull request by CapCamIII**
# About the pull request

about doubles normal hpr ammo in req(to about 3x the amount of hprs), puts a tiny bit more holotargetting in req(to just over the amount of hprs)

# Explain why it's good for the game

not having enough ammo to equip everyone who takes an hpr sucks why was it this low

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl:
balance: there is about double the normal hpr ammo in req vendors now
balance: there is slightly more holo-targetting hpr ammo in req vendors now
/:cl:

### CODE REVIEW

**Comment by fira** [comment]
????? HPR ammo in Reqs almost never runs out and practically nobody wants to use the Holo Target boxes

**Comment by CapCamIII** [comment]
> ????? HPR ammo in Reqs almost never runs out and practically nobody wants to use the Holo Target boxes

@fira 
not to current round BUUUUT it ran out roundstart with 2 people taking it(including me) and i had none :D

**Comment by ihatethisengine** [comment]
> @fira not to current round BUUUUT it ran out roundstart with 2 people taking it(including me) and i had no ammo :D

You can just refill the boxes :\
Every HPR kit comes with 2 boxes + holo, just refill the boxes. You kinda supposed to.

**Comment by Diegoflores31** [comment]
i am pretty sure restricted weapons are not supposed to be abundant on ammunition at roundstart , also if you add the amount of ammo there is already at prep i think this may not be good balance wise

**Comment by CapCamIII** [comment]
@ihatethisengine there is 1(one) normal ammo box in the kit(not including the one in the magazine), and holo is bad(and also can't be refilled), meaning with the amount of mags in vendor you have 3 mags
@Diegoflores31 there are none at prep, and the ammo would not be "abundant" with this change, it would simply be enough to actually have enough to go with the amount of guns there are, right now its 1 drum per gun in the req vendors

**Comment by ihatethisengine** [comment]
> @ihatethisengine there is 1(one) normal ammo box in the kit(not including the one in the magazine), and holo is bad(and also can't be refilled), meaning with the amount of mags in vendor you have 3 mags

So as I said, you have 2 normal boxes and 1 holo. You have 800 round in the kit. 600 of them refillable, we can ignore holo since it's bad. If you carry Mk1 even if you take noobtrap ammo belt, you'll barely have the same amount of ammo, with Mk2 you'll have way less. Just refill when you're out of ammo??? Alternatively you can replace holo with normal box, since everyone is ditching holo anyway. If anyone wants holo they can ask req. Also, this is out of scope, but I am not sure if hpr boxes should fit in mag pouches/armor/webbings, but w/e.

**Comment by fira** [comment]
> > ????? HPR ammo in Reqs almost never runs out and practically nobody wants to use the Holo Target boxes
> 
> @fira not to current round BUUUUT it ran out roundstart with 2 people taking it(including me) and i had no ammo :D

Overall Reqs balance is subject to TM tests right now, there's been rounds with a lot more or less supply, it's a bit hard to compare

On top of the general reqs buffs there's [[#5018]] which replaces back the MK1 spawns by HPR boxes as was intended initially

I really don't think Reqs gonna need any more

**Comment by Birdtalon** [comment]
As Fira said above: req balance is subject to large changes currently under #4939 and #5018 

I believe this PR should be not be considered until after those have been appropriately balanced and merged.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Pull request closed without merging**
