### PR TITLE
Removes zombies in their entirety.

### PR DESCRIPTION
**Pull request by CapCamIII**
# I got approval please don't insta close 😄 

image

# About the pull request

Removes zombies in its entirety, all code, all mentions, everything but the sprites in case someone does something with them later on.

# Explain why it's good for the game

Zombies as a mode is fundamentally flawed and unfun, and it essentially CANNOT work as a enjoyable mode within our gameplay loop, and does not fit the setting of our game either.

The gameplay loop of zombies, as is now, is essentially the following:

Marine: Zombies, kill a million incredibly tanky zombies as they get constantly spawned til admins get bored and end the event, get hit once by a zombie corner-camping and be instantly infected without any possibility of a cure(it is never spawned, nor is it accessable to marines), hell-slowed(you now usually can't escape, and will end up with multiple fractures on top of your infection so you can't go kill more zombies before you are fully infected), and then killed as you can't escape. After all of this, you end up in the next stage, zombie gameplay.

Zombie:
A: You got infected as a marine and recovered by others while dead, your corpse has been stripped and thrown into an inescapable room(either literally inescapable through being completely walled in, or by being mostly walled in and just spam-flamed/shot without being able to escape), and are now stuck here til you get bored.
B: You got infected as a marine and not get recovered, or you joined as a freed mob zombie, you now get to chase marines who are faster than you, with ranged weapons, and abilities to know when you are there(MD, flares, NVGs), get instakilled by a flamer, or kited by a marine with M4RA/M39 who is faster than you to the point you have zero chance of catching up(this is even worse if you are an infected marine, who also has the armor slowdown), your only hope of getting kills/infections are to camp in a corner, go after players who are new/bad, or suicide rush into an open cade in the hope of getting a few infections(because you 1 tap infect no matter what if you land a hit), and get sent to the realm of zombie gameplay loop A.
C: You eventually wear down the marines and they evac, now when you get shipside you have to deal with impossible chokepoints, deathsquads being sent to "end the round", and more reinforcements from the shipside crew.

No matter which way you put it, zombies as a mode is quite unfun for both factions.

Also I'm going to add more onto this later but I'm not bothering right this second 😄 

# Testing Photographs and Procedure

It compiled.

# Changelog

:cl:
del: Zombies, and all zombie-related code, except sprites.
/:cl:

### CODE REVIEW

**Comment by morrowwolf** [comment]
Just for clarity I approved putting up the PR... like anyone can about anything ever. Feel free to close it.

**Comment by CABSHEP** [comment]
"Admemes can't run events for shit, so remove something" the pull request⟨™⟩.

Remove every single event-exclusive faction and gamemode in that case. Admemes can't run death squad events (they are just as bad as badly run zombies).

It is literally an event-exclusive stuff. Zombies being in the code harms normal rounds in no way, so why remove it? If they are in the code, somebody could try to fix them, which would be easier to do when they are like they are now, in comparsion to if they would be removed, then even the best, most fun and most balanced change would be shut down anyway, because again, admems can't run events for shit.

**Review by morrowwolf — COMMENTED** [review]
Fun conversation starter but as of now: no.

**Comment by CapCamIII** [comment]
Its so over.
Still worth making PR though, the discussion was fun to watch.

**Pull request closed without merging**
