### PR TITLE
Added more missing uniform icon states, differentiated a duplicate uniform

### PR DESCRIPTION
**Pull request by Ultimate-Fluff**
# About the pull request
This is part two to #2626. It addresses more missing rolled-up sleeves on uniforms with the ```UNIFORM_SLEEVE_ROLLABLE``` flag, tweaks I had forgotten to fix in the last PR, and it also addresses a duplicate ```marine_formal``` icon state. All info needed is in the changelog.

In addition, this pull request removes a duplicate ```bomber_2``` icon state in ```suits_0.dmi```, mentioned in issue #2734

# Explain why it's good for the game
Missing files and duplicate files need fixing.

# Changelog

:cl: Puckaboo2
fix: The two duplicate marine_formal uniform icon states have been differentiated into two separate uniforms, one for command and one for the layman marine. 
fix: Janitors can now roll up their sleeves.
fix: WY corporate security can now roll up their sleeves in addition to cutting them.
fix: Nurses can now roll their left cuffs up all the way.
tweak: Managers' uniforms have slightly longer sleeves and now properly fit their backs and do not cover the legs from behind.
tweak: Made the messy Detective's uniform more messy from the north and south directions.
del: Removed a duplicate black bomber suit icon state.
/:cl:

### CODE REVIEW

**Review by Agameofscones — CHANGES_REQUESTED** [review]
the manager uniform is presently backless and assless. Needs a back pixel line

**Comment by Ultimate-Fluff** [comment]
> the manager uniform is presently backless and assless. Needs a back pixel line

That wasn't my doing, but I will work on it.

**Comment by Ultimate-Fluff** [comment]
> the manager uniform is presently backless and assless. Needs a back pixel line

image

**Review by harryob — APPROVED** [review]
code is fine

**Pull request merged**
