### PR TITLE
Attachments resprite

### PR DESCRIPTION
**Pull request by Blundir**
# About the pull request

Resprites most of the extremely outdated attachments and tweaks some other ones.

aseprite_QPgozrw0MP

Some sprites are tweaked sprites from TGMC (compensator, bipod), others made by me. Smartscope sprite by **Crow**, discord tag **sir.crow**

# Explain why it's good for the game

Ancient sprites bad.

aseprite_GmqMKqsoCl

Here is a bright example of what i was aiming at.

aseprite_5DY817JvQX

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

dreamseeker_NQ4tNNyevb

dreamseeker_5StHtVILUv

dreamseeker_fKTlGTa7c6

image

image

image

</details>

# Changelog

:cl:
imageadd: resprite of majority of attachments
/:cl:

### CODE REVIEW

**Comment by Blundir** [comment]
> UBS looks good, mag harn and b8 end up looking _really_ weird in game

UBS is unchanged, the grenade launcher is

**Comment by TopHatPenguin** [comment]
cm shouldn't accept tgmc altered sprites

**Comment by Blundir** [comment]
> cm shouldn't accept tgmc altered sprites

I don't remember there being unspoken holy rule about it, it doesn't matter if it's ported, we only judge the sprite itself, other servers don't have a problem porting sprites from here, including tgmc.,

**Comment by TopHatPenguin** [comment]
Having a coherent and unique sprite style that is to be unmolested by porting from other servers should be the main priority of the spriter team. It is the very nature of what makes CM, CM. Continuing to port sprites from every tom, dick and harry will lose what makes CM unique and original, you can see this on every open source server that ports sprites from others as they lose their original style over time.

**Comment by Blundir** [comment]
> Having a coherent and unique sprite style that is to be unmolested by porting from other servers should be the main priority of the spriter team. It is the very nature of what makes CM, CM. Continuing to port sprites from every tom, dick and harry will lose what makes CM unique and original, you can see this on every open source server that ports sprites from others as they lose their original style over time.

Current attachments aren't coherent at all, and sorry, ancient jank isn't CM style, it is simply a bad sprite, and the fact some other sprite somewhere else looked completely fitting, doesn't damage the artstyle at all. If you want to look at zero sprite cohesion, look at skyrat, nsv, yogs, and many others and nobody here just blatantly ports sprites that do not fit. There is nothing bad in porting sprites especially if they were edited to fit better into the current artstyle, i could've just not mention that it's ported at all, nothing would change, and if you so want, make a new completely unique one yourself, i'd be happy do add a better replacement, but current one completely satisfies and looks miles better than what we previously had.

**Comment by TopHatPenguin** [comment]
I fundamentally disagree but we're both clearly cemented into our positions so nothing is likely to change. 

Much obliged for your time.

**Comment by Git-Nivrak** [comment]
The current sprites aren't "jank", they're quite good especially compared to *some* of the sprites on this PR

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Review by nauticall — APPROVED** [review]
sprites

**Pull request merged**
