### PR TITLE
Almayer Rework Part 1 - Prototype

### PR DESCRIPTION
**Pull request by LC4492**
# About the pull request

 I've teaked the USS Almayer basing in my own experience that I gathered in years of gameplay, making sure that the ship itself makes more sense and matches the lore more, while also improving gameplay features that, while I noticed while playing, have been poorly made, such as the replacement of the brig's holding cell for a cryosleep room, while brig ALREADY had a room for that. I made the changes mostly focusing on what I think it was lacking when I played, but while the changes can be a little radical, I've used the exact same space for all changes and in the end, it resulted in strangely wider, cleaner and direct halls and rooms, probably also improving movement and combat on those areas. Apart from that, no codes or anything else have been changed.
 I will be calling this a prototype because I will first gather feedback from the masses before continuing to part 2.

# Explain why it's good for the game

...While also making things wider and cleaner, I also gave back a lot of the details that updates have been little by little taking off the game, such as rooms that had been removed, stamps, pens and paperwork that had been practically abandoned and also made a step foward on giving direct improvements to certain areas onboard the ship, which from afar doesn't look like a lot, but in the end makes a ton of difference and cuts on time.

# Testing Photographs and Procedure
I will keep as a surprise. *winks

# Changelog

:cl:
add: 1. Gave the CO, the XO and others roles their respective stamps, going to add more in a part 2.
2. Updated the Requisitions to have a conveyor belt capable of easily moving supplies and crates around.
3. Re-used the old and unused agent dome and made, in the upper deck/aftship a "Blackbox Dome", containing the Blackbox of the USS Almayer.
4. Gave CIC a cleaner space, with a Command bubble capable of holding not only one, but two commanding officers (The CO and XO), as so, they can now work separately without putting their nose on eachother's work. (Other small changes, such as better object positions and others).
5. Gave Brig a new holding cell, more paperwork and evidence collection equipment, gave the Execution room wider spacing and an "audience room" for officers or for private guests, made the execution room storage fit in a smaller space, gave airlocks to the Perma cells (Now, with Military Police permission, Perma prisoners can use their "recreation" right), changed the armory position and gave it more equipment (Crowbars, insulated gloves and ammo belts of various types) and a new gun: The M41A MK2 (I know, not that new). (Other medium to small changes that will probably be easily found, such as a new position for the evidence room, etc.)
6. Gave the lifeboats more chairs (Because, what's the point of an evacuation port for 30 crew, at minimum, to have 6 chairs).
7. Gave the mess hall a bigger counter and changed the airlock's position.
8.  Other very small changes, such as computer emplacements, and other things that people will easily notice.

del: Removed some useless benches and other minimum stuff.

qol: Make things more straight-foward and at the same time, more detailed and cleaner, with wider halls and a better use of the space available, probably resulting in a much more efficient and logical workspace. 

fix: Fixed a few typos here and there, planning on working more on that on my part 2.

maptweak: I've teaked the Almayer, as explained above.

/:cl:

### CODE REVIEW

**Comment by Zonespace27** [comment]
This should almost definitely be atomized; these are a series of unrelated changes that serve to make this PR near-impossible to review well

**Review by Zonespace27 — CHANGES_REQUESTED** [review]
However you *did* de-convert the entire thing from the tgm format which is definitely a no-go

**Comment by LC4492** [comment]
> This should almost definitely be atomized; these are a series of unrelated changes that serve to make this PR near-impossible to review well

I surely can do that, will only take...a little more time.

**Comment by LC4492** [comment]
> However you _did_ de-convert the entire thing from the tgm format which is definitely a no-go

Aaaaaand yes, that was a mistake of mine, pardon.

**Comment by LC4492** [comment]
> This should almost definitely be atomized; these are a series of unrelated changes that serve to make this PR near-impossible to review well

Would you like some photos of the changed areas? Its really too much to fit on a changelog.

**Comment by stanalbatross** [comment]
this will require heavy atomisation, also do not expect all of these to go through

**Comment by harryob** [comment]
> > This should almost definitely be atomized; these are a series of unrelated changes that serve to make this PR near-impossible to review well
> 
> Would you like some photos of the changed areas? Its really too much to fit on a changelog.

mapdiffbot would do this if your map was in a mergeable state - you'll need to update it to match recent changes to the almayer map. furthermore, you need to use strongdmm for mapping instead of dreammaker

**Comment by LC4492** [comment]
I will be re-posting this PR in atomized forms and then will be closing this one.

**Comment by stanalbatross** [comment]
closing bc this is being atomised

**Pull request closed without merging**
