### PR TITLE
Heavy Armor Acid Buff

### PR DESCRIPTION
**Pull request by Geevies**
## About The Pull Request

Increases Heavy armor bio resistance from CLOTHING_ARMOR_MEDIUMLOW (15) to CLOTHING_ARMOR_HIGH (30).

## Why It's Good For The Game

It doesn't really make sense for heavy armor, which probably has more padding, to be weaker to acid than light armor is.

## Changelog

:cl:
balance: Increased Heavy armor bio resistance from CLOTHING_ARMOR_MEDIUMLOW (15) to CLOTHING_ARMOR_HIGH (30).
/:cl:

### CODE REVIEW

**Comment by Carnage068** [comment]
This gives me hope that is probably false.

**Review by stanalbatross — APPROVED** [review]
code is fine

**Comment by FlamermanGrills** [comment]
LETS FUCKING GOOOOOKKKK

**Comment by c4xmaniac** [comment]
Awesome heavy armor finally has acid protection maybe it won’t be useless now :D

**Comment by PhantomEpicness** [comment]
Heavy armor a little less useless. Nice.

**Comment by PhantomEpicness** [comment]
> This PR has been inactive for long enough to be automatically marked as stale. This means it is at risk of being auto closed in ~ 7 days, please address any outstanding review items and ensure your PR is finished, if these are all true and you are auto-staled anyway, you need to actively ask maintainers if your PR will be merged. Once you have done any of the previous actions then you should request a maintainer remove the stale label on your PR, to reset the stale timer. If you feel no maintainer will respond in that time, you may wish to close this PR youself, while you seek maintainer comment, as you will then be able to reopen the PR yourself

how about you automatically mark this ratio

**Pull request merged**
