### PR TITLE
Adds Service Jacket and Patrol Cap to requisition surplus vendor

### PR DESCRIPTION
**Pull request by morrowwolf**
## About The Pull Request

Adds the service jacket and patrol cap to requisition surplus vendor.

## Why It's Good For The Game

Service Jackets and Patrol Caps should be available for non-combat personnel without breaking into uniform vendors.

## Changelog

:cl: Morrow
add: Adds Service Jacket and Patrol Cap to requisition surplus vendor
/:cl:

### CODE REVIEW

**Comment by GoldenDarkness55** [comment]
Have you considered that they're unavailable for some reason? (however nonsencial it may be) If you want them accessible then maybe PR changing that instead of adding them through some other way, circumventing the lock in the first place?

**Comment by morrowwolf** [comment]
> Have you considered that they're unavailable for some reason? (however nonsencial it may be) If you want them accessible then maybe PR changing that instead of adding them through some other way, circumventing the lock in the first place?

They're not unavailable.  The surplus vendor is opened pretty much every single round.  I'm not advocating for deploying marines to wear service jackets instead of armor.  I like to have drip options for non-combatants without breaking through a wall or forcing it open which is hyper LRP and lame.

It is *the* marine service jacket.  Doesn't make sense to not have it in req.

**Comment by LilPenpusher** [comment]
Deploying without Armour is against SOP. As was pointed out, "have you considered that they aren't readily available for a reason?" 

Req staff would be getting arrested every round if this came through because handing out jackets for Marines to deploy with would be aiding and abetting a crime and we all know MPs would be pouncing on it.

**Comment by morrowwolf** [comment]
> Deploying without Armour is against SOP. As was pointed out, "have you considered that they aren't readily available for a reason?"
> 
> Req staff would be getting arrested every round if this came through because handing out jackets for Marines to deploy with would be aiding and abetting a crime and we all know MPs would be pouncing on it.

Again, they *are* readily available every single round.  That wall is shot open or taken down or someone turns off the APC's equipment toggle and crowbars the shutters.  This is really lame when in reality the service jacket would be a fairly common sight for anyone in the USCM.

We had an event round the other week that started with us being "post-operation" and on R&R.  I would love to be able to go to req as a squad marine and grab a service jacket and just chill out.  Instead, we have this area that is broken down and uniforms/random shit is thrown everywhere which is LRP as hell.

This second part is a IC issue that adds more to the game than takes away from it IMO.

**Comment by stanalbatross** [comment]
> Deploying without Armour is against SOP. As was pointed out, "have you considered that they aren't readily available for a reason?"
> 
> Req staff would be getting arrested every round if this came through because handing out jackets for Marines to deploy with would be aiding and abetting a crime and we all know MPs would be pouncing on it.

Basically, this. Therefore DNM until further discussion.

**Comment by LilPenpusher** [comment]
> > Deploying without Armour is against SOP. As was pointed out, "have you considered that they aren't readily available for a reason?"
> > Req staff would be getting arrested every round if this came through because handing out jackets for Marines to deploy with would be aiding and abetting a crime and we all know MPs would be pouncing on it.
> 
> Again, they _are_ readily available every single round. That wall is shot open or taken down or someone turns off the APC's equipment toggle and crowbars the shutters. This is really lame when in reality the service jacket would be a fairly common sight for anyone in the USCM.
> 
> We had an event round the other week that started with us being "post-operation" and on R&R. I would love to be able to go to req as a squad marine and grab a service jacket and just chill out. Instead, we have this area that is broken down and uniforms/random shit is thrown everywhere which is LRP as hell.
> 
> This second part is a IC issue that adds more to the game than takes away from it IMO.

If Req had a locked vendor like the current ones which only the RO could open up, then maybe.

But adding them like in this MR will NOT work. There is a massive difference between "I literally destroy a part of the ship to illegally obtain this thing" and "I am going to ask for this illegal thing from Req". Fun fact, if MPs catch you wearing a jacket before drop they can arrest you, which is why I'm confused about your analogy of the current state of things.

Yes, you can skeleton key that wall to get the jacket currently. No, it's far from legal. Why make that point at all? All this MR would do is get you AND Req arrested.

**Comment by Nanu308** [comment]
Inaccessible for a reason, will probably look at setting up permissions or a better system for those vendors at a later date.

**Comment by PhantomEpicness** [comment]
caption (1)

**Pull request closed without merging**
