### PR TITLE
Varadero, Strata, Kutjevo, Shiva energy fix

### PR DESCRIPTION
**Pull request by Noname995**
# About the pull request

Areas on this maps pull energy from default, and has energy when generators off
SMES added on Shiva generators points.

# Explain why it's good for the game

Fixes always good

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Tested.

</details>

# Changelog

:cl:
fix: Varadero, Strata, Kutjevo, Shiva maps now don't have infinity energy
add: Added SMES on Shiva generators points
/:cl:

### CODE REVIEW

**Comment by Git-Nivrak** [comment]
Shivas snowball has no generators in an accessible area for marines afaik

**Comment by Noname995** [comment]
> Shivas snowball has no generators in an accessible area for marines afaik

I checked this, have.
StrongDMM_zp1emnlXqt
image

**Comment by Git-Nivrak** [comment]
Those are generators, but you need the SMEs which actually sends the power

**Comment by Noname995** [comment]
> Those are generators, but you need the SMEs which actually sends the power

True. I thinking powernet has yourself energy storage, but not. I think i can place SMES near generators and this be alright?

**Comment by Noname995** [comment]
probably don't a feature...

**Review by harryob — APPROVED** [review]

**Pull request merged**
