### PR TITLE
Allows you to wear the warning cone

### PR DESCRIPTION
**Pull request by TheManWithNoHands**
# About the pull request

* makes the cone fit the head slot
* Adds on mob sprites for the cone

# Explain why it's good for the game

I dont need to explain myself.
You all know why i did this.

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

https://imgur.com/a/8DAFmMK

</details>

# Changelog
:cl: TheManWithNoHands
code: adds flags to cone, allowing it to be worn on head
imageadd: added on mob sprites for cone

/:cl:

### CODE REVIEW

**Comment by ihatethisengine** [comment]
Thank you. It has bothered me for years. God bless you.

**Comment by LC4492** [comment]
Remember to properly set the changelog, you need to write the changes you made on it.

**Comment by Drulikar** [comment]
Stale exempt until sprite reviewed

**Review by Drulikar — APPROVED** [review]
Of note huggers don't rip it off, but it doesn't block a hug nor decapitation.

**Comment by RavinHobo** [comment]
Finally a truly Scottish PR

**Comment by zzzmike** [comment]
this is long ago merged so no one will probably see this, but just in case, see https://forum.cm-ss13.com/t/campinkiller-player-report-brett-mcmatherson-rule-11-marine-law-mutinies-malicious-compliance/9392/4 for expectations on how this can play out with MPs/provost

**Comment by TheManWithNoHands** [comment]
Oh i read it. And im in love.
This is hilarious.

**Pull request merged**
