### PR TITLE
Toggle ghost now leaves the users mob visible

### LINKED ISSUE #5894: Ghost Vision & Self-Visibility borked
### Testmerges

Irrelevant

### Round ID

_No response_

### Description of the bug

Toggling Ghost Vision also makes your ghost invisible. Toggling Self-visibility does not work and the button sends no messages

### What's the difference with what should have happened?

Ghost Vision should keep your ghost and self visibility should actually work

### How do we reproduce this bug?

Toggle Ghost Vision
Toggle Self Visibility
_Enlightenment_

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

### PR DESCRIPTION
**Pull request by vero5123**
# About the pull request
Fixes #5894

# Explain why it's good for the game
bug fix

# Changelog
:cl:
fix: toggling ghost vision now keeps the user's mob visible.
/:cl:

### CODE REVIEW

**Comment by fira** [comment]
I'm not sure removing ghost plane handling is much of a fix

**Comment by Blundir** [comment]
This pr isn't exactly optimal feature-wise, seeing no ghosts at all is good for making screenshots both locally and on server itself, this pr just completely removes the ability, without providing alternatives.

**Comment by vero5123** [comment]
> This pr isn't exactly optimal feature-wise, seeing no ghosts at all is good for making screenshots both locally and on server itself, this pr just completely removes the ability, without providing alternatives.

No it doesn't, you toggle ghost visibility, which hides all mobs but yourself and then you toggle self visibility which hides youe mob from your pov and others.

**Review by PowerfulBacon — COMMENTED** [review]
Are there things on the ghost layer that would be inadvertantly hidden by changing the see_invisible flags?

**Comment by vero5123** [comment]
> Are there things on the ghost layer that would be inadvertantly hidden by changing the see_invisible flags?

Afik, No. Just the ghosts.

**Review by Drulikar — APPROVED** [review]

**Pull request merged**
