### PR TITLE
USCM Ponchos

### PR DESCRIPTION
**Pull request by morrowwolf**
## About The Pull Request

Ponchos!

https://cdn.discordapp.com/attachments/665956827326054440/1024348555432972298/unknown.png

The standard USCM poncho has variations for every climate. Custom fitted to be attached to standard USCM armor variants it is comfortable, warming or cooling as needed, and well-fit. A marine couldn't ask for more. Affectionately referred to as a "woobie".

The poncho attaches to standard armor variants as an accessory and can be found in the squad prep surplus vendor.

## Why It's Good For The Game

Customization good

## Changelog

:cl: Morrow, Triiodine
add: USCM Ponchos are now available in squad prep surplus vendors and can be attached to standard armor variants.
/:cl:

### CODE REVIEW

**Comment by AmoryBlaine** [comment]
Noice

**Comment by PhantomEpicness** [comment]
sovl

**Comment by c4xmaniac** [comment]
The woobie is the poncho liner :3

**Comment by Chocollateral** [comment]
such soul, thank you

**Comment by ApplePlastic** [comment]
speedmerge...????

**Comment by Blithering** [comment]
Now we just need rain to be more common.

**Comment by oniondry** [comment]
epic as frick, speedmerge NOW!!

**Comment by RoboticVodka** [comment]
It would be really nice if the poncho could close as well to protect the front of your body, no hood needed since we have helmet rain covers already anyways(Also adds more soul because I can look like the guards from MGSV Ground Zeros). Otherwise, I imagine people will just kinda treat it as a cape to 40K LARP in, I can already see every CO wearing it and emoting how their cape flutters in the wind as they raise their ceremonial sword to order a charge.
image

**Comment by Blithering** [comment]
> It would be really nice if the poncho could close as well to protect the front of your body, no hood needed since we have helmet rain covers already anyways(Also adds more soul because I can look like the guards from MGSV Ground Zeros). Otherwise, I imagine people will just kinda treat it as a cape to 40K LARP in, I can already see every CO wearing it and emoting how their cape flutters in the wind as they raise their ceremonial sword to order a charge. image

This, ponchos not capes! Also it gives a Vietnam feel

**Comment by Tristan63** [comment]
speedmerge +1

**Review by stanalbatross — APPROVED** [review]
code é good

**Review by nauticall — APPROVED** [review]
sprites LGTM!!

now add rain to LV >:)

**Comment by Geevies** [comment]
not goign to review code, if it goes wrong blame katrina
image

**Pull request merged**
