### PR TITLE
dual wielding nerf

### PR DESCRIPTION
**Pull request by stanalbatross**
## About The Pull Request

nerfs dual wielding by increasing scatter and reducing accuracy

## Why It's Good For The Game

being able to out-DPS an m2c with 2 pistols is not good

## Changelog

:cl:
balance: increased the scatter and decreased the accuracy of dual wielding
/:cl:

### CODE REVIEW

**Comment by Waseemq1235** [comment]
finally we get to fuck over dual mod users

**Review by morrowwolf — APPROVED** [review]
Code LGTM

**Comment by Carnage068** [comment]
Wasn’t too sure whether this should be nerfed or not for a while. It used to be kind of rare so I didn’t mind it, but in recent times it’s gotten really popular and it was starting to bug the hell out of me seeing it so much. The downsides really didn’t weigh down the upsides that much at all. I feel like this nerf is pretty justified, and tbh from looking at the numbers myself it doesn’t even seem like it’s going to be gutted or complete dogshit afterwards. People will still be able to use it to good effect, it just won’t be able to vaporize tanky T3s.

Overall great PR, it’s good to see you’re doing your part to balance out marine weaponry, although I think part of the reason people were running around with dual pistols was because shotgun juggling was removed (good) but buckshot was never compensated like it was said it would be (bad).

**Comment by Strobia** [comment]
Thank me xenoplayers, I harassed him until he nerf'd duel wielding.

**Comment by Carnage068** [comment]
> Thank me xenoplayers, I harassed him until he nerf'd duel wielding.

thx

**Comment by stanalbatross** [comment]
> buckshot was never compensated like it was said it would be (bad).

a PR has been made for this, hopefully will get looked at by nanu

**Comment by FoxyStalin** [comment]
A fair nerf that keeps it's strengths but makes it less all-around powerful.  Thumbs up.

**Comment by Carnage068** [comment]
> a PR has been made for this, hopefully will get looked at by nanu

Yeah I know but I didn't think it would get merged. Guess I was wrong though (good)

**Comment by Diegoflores31** [comment]
what if instead of just making it completely useless just take away the option of firing both pistols at the same time ?
like . forcing you to fire each gun at a time if you know what i mean

**Comment by c4xmaniac** [comment]
Good change, but you should still consider making the mod88 a restricted weapon. It's still going to be crazy strong just not at screen edge now.

**Comment by GoldenDarkness55** [comment]
Was this tested? When I tried to nerf akimbo I remember having to severely dumpster the stats across the board to get any decent effect. Maybe I was just doing something wrong but this doesn't seem like it'll have any impact on a mod88 with attachments.

**Comment by stanalbatross** [comment]
> Was this tested? When I tried to nerf akimbo I remember having to severely dumpster the stats across the board to get any decent effect. Maybe I was just doing something wrong but this doesn't seem like it'll have any impact on a mod88 with attachments.

Yes, I was only able to kill a lurker using two full mod 88s from a range of 2 tiles or less

All other ranges took over 1 mag

**Pull request merged**
