### PR TITLE
Hair Gradients

### PR DESCRIPTION
**Pull request by Geevies**
## About The Pull Request

Ported from https://github.com/tgstation/tgstation/pull/59435 but with code modified since our hair generation is different.

## Why It's Good For The Game

Allows for extended character customization options without having too much of a gameplay impact.

## Changelog

:cl:
add: Added hair gradients to character creation.
fix: Picking a color in character creation will now default to the pre-selected color, so it doesn't default to black each time.
/:cl:

### CODE REVIEW

**Comment by SuprisedBaby** [comment]
I will not forget this

**Comment by Chainsawicus** [comment]
I really do not want to see disgusting neon pink-green type hair, i'll be honest. It's already bad enough seeing people with ridiculously bright idiotic haircuts in a military server

**Review by stanalbatross — CHANGES_REQUESTED** [review]
make it cost 3-4 character creation points to enable hair gradients for your character

**Comment by Joelampost** [comment]
no thanks

**Comment by Shad0vvs** [comment]
> 

Two max for balance reasons.

**Comment by Shad0vvs** [comment]
> make it cost 3-4 character creation points to enable hair gradients for your character

Two max for balance reasons.

**Comment by AlionaVAHA** [comment]
> make it cost 3-4 character creation points to enable hair gradients for your character

3-4 is too much, two is ok. nothing is even better because its just a hair and RP buff and not an accessories. pink neon hair is lrp.

**Comment by kiVts** [comment]
3-4 is too much, 2 is ok. nothing is the best because this is just a hair gimmick and rp buff. not even accessories, setting points for this is stupid,  simply because most people wear helmets or beret(you can be decapped if you dont) and no one is going to notice that you got that cool gradient that you wasted whole 3 points which could spent on broken NVGs or said beret.

**Comment by johnravioliUSA** [comment]
This Shit looks stupid As Fuck

**Comment by hotimep** [comment]
i like the soft shading with regular hair colors but not the rainbow neon gradients, i DEMAND that you LIMIT the color choices

**Comment by c4xmaniac** [comment]
no

**Comment by kiVts** [comment]
I dont get why so many people dislike it

**Comment by neeshacark** [comment]
ive used this in the past to add slight color variations in hair. the belief here seems to be that it will be exclusively used by the neon hair people (which honestly isnt a bad thing anyway, idk why people get so triggered over it)

**Review by Agameofscones — APPROVED** [review]
nice fades

**Comment by kiVts** [comment]
Players and stan killed a harmless pr most people wouldn't even noticed.

**Comment by Geevies** [comment]
> make it cost 3-4 character creation points to enable hair gradients for your character

characters only have 1 character trait point, so i added it to that and made it cost 1 point

**Review by morrowwolf — APPROVED** [review]
Code approved

**Pull request merged**
