### PR TITLE
XO can award distinguished conduct medals

### PR DESCRIPTION
**Pull request by ihatethisengine**
# About the pull request
XO can award distinguished conduct medals.

# Explain why it's good for the game
We already have an non-WLed role that can give out medals and it wasn't a big issue. LRP is already against the rules for XO, so why not? Arguably XO is more motivated to give out medals than CO (deployed and perma) and we don't have a CO every round, so I think it would be fine.

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl: ihatethisengine
add: XO can award distinguished conduct medals.
/:cl:

### CODE REVIEW

**Review by Birdtalon — APPROVED** [review]

**Comment by nauticall** [comment]
DNM pending maintainer discussion. The uniqueness of COs being able to give medals is one of the more prevalent parts of the whitelist and we'll need to talk this over to see how that goes in the grand scheme of things.

**Review by Drulikar — CHANGES_REQUESTED** [review]
Please restrict the available medals XOs can give out to just the MARINE_CONDUCT_MEDAL

**Comment by ihatethisengine** [comment]
Done

**Comment by c4xmaniac2** [comment]
Queen medals already suck, now we're giving medals to a role with even less standards and a lower play time. Can't wait for the reddit gold big chungus queen killer medal from our favorite role 👍

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by NateDross** [comment]
If the decision is reached that this is approved shouldn't 'Bronze Heart Medal' also be included since it is a lower status or at best an equal medal of 'Medal of Distinguished Conduct' ?

'Medal of Exceptional Heroism' and 'Medal Of Valor' should remain CO whitelisted awards as they are very grand awards but the other two medals seem perfectly acceptable for a Captain to hand out.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Pull request closed without merging**
