### PR TITLE
FIxes UPP ert 

### PR DESCRIPTION
**Pull request by Joelampost**
# About the pull request
makes upp erts spawn with gear

# Explain why it's good for the game
ERTs should spawn with gear on i think
# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl: Joe lampost
fix: UPP ERTS now spawn with gear
/:cl:

### CODE REVIEW

**Review by Nanu308 — APPROVED** [review]
lgtm (ert without gear moment)

**Comment by Nanu308** [comment]
colon mark : and small F for CL

**Comment by Joelampost** [comment]
ya ya ya

**Comment by harryob** [comment]
duplicate of #7551

**Pull request closed without merging**
