### PR TITLE
Updates VSC tooling with PrettierX and the DMI Editor

### PR DESCRIPTION
**Pull request by harryob**
## About The Pull Request

updating from tgui upstream, we can use prettierx for standardised formatting tgstation/tgstation#67935
the DMI viewer is cool too tgstation/tgstation#66834

this:
adds prettierx
adds eslint-config-prettier to automatically disable conflicting ESlint rules
adds prettier, ZipFS (for yarn plug'n'play), DMI viewer as recommended extensions
automatically uses prettier when file saved in VSC
sets default DMI viewer as the new DMI viewer extension

testing wise i deleted my local repo and VScode + settings, i reinstalled VSC fresh, cloned my fork and it worked. tgui still worked, too

i'd appreciate a couple of people checking out this PR branch and seeing if it fucks it up for them, mind

## Why It's Good For The Game

easier to sprite
nicer to read code
simple as

## Changelog

shouldn't be any player facing changes

### CODE REVIEW

**Comment by carlarctg** [comment]
bless you backend tg porter devs

**Comment by harryob** [comment]
oh boy i wonder when icondiffbot2's gonna finish up

**Review by Watermelon914 — APPROVED** [review]

**Comment by stanalbatross** [comment]
can test to see if it breakies for anyone on main serb

**Comment by harryob** [comment]
@Watermelon914 conflicts resolved, again

**Pull request merged**
