### PR TITLE
Removes Ordnance Department

### PR DESCRIPTION
**Pull request by Steelpoint**
# About the pull request

This PR removes the Ordnance Department and the Ordnance Technician from the USS Almayer and the Marine roster respectively. 

# Explain why it's good for the game

In my opinion, and the opinion of others, OT explosives are a inherently overpowered, unpredictable and unfun mechanic for the game. 

This game is set around the concept of known threats. You know what a threat is when you examine it, you know what a grenade is going to do when thrown, you kind of know what a CAS is going to do, and you know the ranges of attacks, both firearm, grenade, explosives or mortar. 

Ergo the very concept of OT explosives completely abandons any concept of logic, skill or knowledge. OT grenades, mortar rounds and rockets, can typically be found to possess explosive ranges that cover the entire screen, capable of delivering lethal explosive and incendiary damage across a wide area. 

OT grenades can wipe out a entire screen of defences and crit high level xenos, OT mortar rounds are almost functionally mini-OBs wherein their explosive range and damage is so vast that many a target, marine or xenomorph, can still be caught and killed even beyond the hearing audio range of the sound, and OT rockets can quite literally fill most of the screen with extremely lethal incendiary fire that can kill most xenos before they can be saved by another, assuming they survived the high explosive payload. 

The only balancing consideration to this concept, is the competence of the person using the explosives, and the person who is making the explosives. Skill is one consideration but even we put limits on how strong a Xeno or Marine role is despite skill being a major factor in their strength, but there is no counterbalance to the person making the explosives considering the dozen of guides on Discord and the Forums that detail a meta-spreadsheet of how to make explosives before first drop that are, at least, max-caps. 

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl:
del: The Ordnance Technician has been removed from the Marine roster.
maptweak: The Ordnance Workshop has been removed from the USS Almayer. 
/:cl:

### CODE REVIEW

**Comment by TemptedGhost** [comment]
oh hell nah yo ass tweaking jigsaw

**Comment by RainbowStalin** [comment]
This is the PR that will save CM. Thank fuck.

**Comment by RainbowStalin** [comment]
One thing you have to consider though, is putting the industrial macerator from the OT workshop somewhere else. As its the only way to get thwei out of pred crystals.

**Comment by Drulikar** [comment]
Much like I've explained for other things, removal as the first choice won't fly with me. I am fine with OT relying much heavier on research though (as in require spending of research points for anything but basic explosives), including making them a part of the research department (they just don't need to move their workshop). It would be great to have demolitions testing as a means to generate some research points too.

But sorry I cannot accept outright removal.

**Comment by TheManWithNoHands** [comment]
> but there is no counterbalance to the person making the explosives considering the dozen of guides on Discord and the Forums that detail a meta-spreadsheet of how to make explosives before first drop that are, at least, max-caps.

https://www.nasa.gov/wp-content/uploads/static/history/afj/ap08fj/pdf/sa503-flightmanual.pdf

Here is the fligth manual for the Apollo Satun V. By your logic thats enough for you to be its pilot.
Go be an Astronaut. All it takes to do something is reading the instructions after all.

**Pull request closed without merging**
