### PR TITLE
Raise Corpsespawner Limit

### PR DESCRIPTION
**Pull request by BOBAMAx**
# About the pull request

Raises corpsespawner quota from 25 to 100. Limits intel points from human corpses to 5 (50 bodies).
Adds a bunch of corpsespawners to Trijent. Adds a couple to shivas and fiorina. Removes a bunch from solaris.

This would likely need a TM to see if the increased amount of bodies impacts server performance.

# Explain why it's good for the game

As it stands right now, there is a hard limit on 25 corpses per map. On a map like LV-624 this is mostly OK as it's fairly small and the corpsespawners are fairly spread out. On a map like Trijent and potentially Hybrisa, this severely limits the amount of bodies the average player will see in a given round. You would expect bigger maps to have more bodies but this is not the case. This has negatively affected Solaris specifically because the map has almost 100 corpsespawners, many of which are in caves or research labs, making the colony proper nearly devoid of life. Mappers are also in an arms race, competing for the 25 corpse spots in their map additions. 

Big Red needs to have some of it's corpse spawners removed if the limit is raised as many of these were placed down with the assumption that not all of them were going to spawn at once.

Trijent now looks more like a xenomorph outbreak has swept through the colony and less like the rapture occured and everyone vanished without a trace.

Shivas has a few extra bodies now.

Fiorina had almost no prisoner and scientist bodies and almost exclusively guard bodies. Isn't much of a prison science annex with no prisoners or scientists.

non-comprehensive before and after:

<details>
<summary>before</summary>

bigred1

</details>

<details>
<summary>after</summary>

bigred4

</details>

<details>
<summary>some trijent stuff</summary>

trijent1
trijent2

</details>

There doesn't need to ever be 10 bodies stuffed in the Eta locks but because the mapper wanted there to always be a couple, he put down ten to make it likely that a few would actually spawn. This is roundabout and stupid and causes "individual" corpsespawners to very rarely actually spawn a corpse, which is unintuitive from the mapper's perspective.

Also limits intel points from human bodies to prevent IOs from printing intel points from maps/inserts with a bunch of bodies.

# Testing Photographs and Procedure
Tested by starting big red on local and using my eyes. Also killed a bunch of dudes in research and human bodies stopped giving points after 5.

# Changelog
:cl: BOBAMA
maptweak: quadrupled the limit for roundstart corpses on maps.
maptweak: Removed Corpses from Solaris. Added corpses to Shivas, Fiorina, and Trijent
maptweak: added some "last stand" holds to Trijent and Shivas to put bodies in. Trijent research lab had most CMB weapons replaced with corporate/goon stuff.
balance: Intel points from human bodies are now capped at 5 (50 bodies)
/:cl:

### CODE REVIEW

**Comment by RainbowStalin** [comment]
As this affects intel points as well, shouldn’t the balance tag be added as well?

**Comment by Zenith00000** [comment]
Good idea, Hybrisa technically has 75 bodies including those on the roller beds, not including burst bodies at all. Which considering the size you rarely see, this would help gathering intel on Hybrisa a lot. The bodies also add to the soul/atmosphere, it's kinda sad when you just see pools of blood with no body spawning ect.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Review by Nanu308 — COMMENTED** [review]
Needs testing, tldr. Human tick and dead body impact on performance used to be the reason we had a set limit. On a side note, 100 is probably way too much.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Review by Drulikar — CHANGES_REQUESTED** [review]
Changelog should mention loot changes to desert dam and objective cap.

**Comment by BOBAMAx** [comment]
> Changelog should mention loot changes to desert dam and objective cap.

Changelog updated. I made a ton of minor map changes on these maps to add flavor to any bodies that were removed/added so it's impossible to go over everything but I tried not to rock the boat too much. Biggest changes would be bodies with weapons next to them like mp5s and corporate m41as.

**Review by Nanu308 — CHANGES_REQUESTED** [review]
Drop the shotguns, replace them with CMB revolvers. Don't really wish to touch/add more surv loot right now

**Comment by BOBAMAx** [comment]
> Drop the shotguns, replace them with CMB revolvers. Don't really wish to touch/add more surv loot right now

all 3 replaced.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Review by Nanu308 — APPROVED** [review]
mapping lgtm now

**Comment by Nanu308** [comment]
Might need to move corpses/look at corpse loot in future but this is fine

**Review by Drulikar — APPROVED** [review]

**Pull request merged**
