### PR TITLE
Removes BiMex Glasses flash protection

### PR DESCRIPTION
**Pull request by So-mii**
# About the pull request

 Removes the Flash Protection variable from the BiMex glasses, allowing people to not get stunned by flashes from both AOE or Direct

# Explain why it's good for the game

Stops people being able to evade MP's with minimal effort as they're just Welding Goggles with no downsides.
# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl:
balance: Removes flash protection from BiMex shades
/:cl:

### CODE REVIEW

**Comment by spartanbobby** [comment]
desc = "These are an expensive pair of BiMex sunglasses. This brand is popular with USCM foot sloggers because its patented mirror refraction has been said to offer protection from atomic flash, solar radiation, and targeting lasers. To top it all off, everyone seems to know a guy who knows a guy who knows a guy that had a laser pistol reflect off of his shades. BiMex came into popularity with the Marines after its 'Save the Colonies and Look Cool Doing It' ad campaign."

**Comment by sleepynecrons** [comment]
upvoted

**Comment by Red-byte3D** [comment]
Screenshot 2024-05-01 001556
 change the desc

**Comment by IroquoisLou** [comment]
image
Why are you removing lines that are canon features of the Bimex?

**Review by Nanu308 — APPROVED** [review]
_another marine nerf secured_

**Pull request merged**
