### PR TITLE
Xeno Acid Damage Buff

### PR DESCRIPTION
**Pull request by Geevies**
## About The Pull Request

Increases xeno acid blood damage from 12 damage to 25 damage.

## Why It's Good For The Game

In the aliens media, xeno blood is incredibly corrosive/acidic, so raising the damage makes it more faithful to the series.

## Changelog

:cl:
balance: Increased xeno acid blood damage from 12 to 25.
/:cl:

### CODE REVIEW

**Comment by hotimep** [comment]
shotgun nerf

**Comment by Diegoflores31** [comment]
uh... wont that make a m41 burst at 2 tiles range literally instakill you ?

**Comment by Listaless** [comment]
Personally against increasing acid blood damage, based on my memory's and experience of when acid blood damage was high, we shouldn't be using lore as a reason to buff things

**Comment by Bram-KEP** [comment]
an MK2 burst from close range will literally kill ppl now. acid blood damage was nerfed for a reason

**Comment by Paperbell** [comment]
Maybe the damage of the bullet could change how much the acid blood does? Or it could be some other quality added to projectiles. For example, buckshot groups would break more skin, resulting in more acid damage, while a rifle bullet would just make one hole, resulting in less acid, even if the rifle bullet did more damage to the alien.

**Comment by Kuusday** [comment]
This change will discourage bodyblocking for marines which is a method that competent players use to kill xenos with teamwork. A bad change that shows not enough thought was put into this PR. 25 is simply too much meaning those who PB with any weapon in general will be killing themselves with little consequence for the xenomorph.

**Comment by GoldenDarkness55** [comment]
Based

**Comment by Carnage068** [comment]
BASED AS FUCK!!!!!!!!!!!!!!!!!!!!!

cant wait to see it get denied lol

**Comment by Carnage068** [comment]
> Personally against increasing acid blood damage, based on my memory's and experience of when acid blood damage was high, we shouldn't be using lore as a reason to buff things

It doesn't do ANYTHING currently. Although, I think doubling the damage might be a little too much. It should probably be changed to 20 damage or 18 or something like that, but it won't matter because this is going to be denied anyway.

**Comment by Unknownity** [comment]
techwebs had a xeno tech that tripled the acid blood damage and nobody insta died yet. this is nothing

**Comment by MaximusRexCM** [comment]
I want to become soup +1

**Comment by Carnage068** [comment]
> techwebs had a xeno tech that tripled the acid blood damage and nobody insta died yet. this is nothing

Yeah, this. People LOVE to exaggerate and make a huge shitstorm over something useless being buffed to be decent, or in this case, functional, but still somewhat weak.

**Comment by Carnage068** [comment]
> Personally against increasing acid blood damage, based on my memory's and experience of when acid blood damage was high, we shouldn't be using lore as a reason to buff things

Your memory of acid blood was when it did nearly ten times the damage it does now. This change is a fifth of that, I don't think it's going to be anywhere NEAR instantly pain critting people like it used to, even if it did end up getting merged.

**Comment by FlamermanGrills** [comment]
Erm if this goes through heavy armor will need it's acid protection upped...

**Comment by Carnage068** [comment]
> Erm if this goes through heavy armor will need it's acid protection upped...

It needs its acid protection to be upped in the first place, honestly. Also if this change somehow does go through, it will probably help make heavy armor slightly more viable.

**Comment by c4xmaniac** [comment]
Based af

**Pull request merged**
