### PR TITLE
[MDB IGNORE] Removal of groundside nanomed refilling splints and skilless injectors. Nerfs non-med APC nanomeds.

### PR DESCRIPTION
**Pull request by morrowwolf**
## About The Pull Request

Removes nanomed refilling splints and skilless injectors.

## Why It's Good For The Game

This is step one of an overall medical nerf for the average PFC. The ability to refill the injectors on any nanomed in the colony is a bit too powerful all on top of making med APC less important as a source of medical refill.

## Changelog

:cl: Morrow
balance: Removes groundside nanomeds refilling splints and skilless injectors.
balance: Nerfs non-med APC nanomeds to basic groundside level.
/:cl:

### CODE REVIEW

**Review by ThePiachu — APPROVED** [review]
Code looks good

**Review by stanalbatross — CHANGES_REQUESTED** [review]
ARCHITECT COMMENTS
Nanomeds are found in pretty much 3 places - the dropship, the med APC, and on the ship
in all those 3 places, it is pretty trivial to restock injectors and refill splints in other ways
Therefore I do not think this nerf to SPECIFICALLY nanomeds is justified

The path I would take is to make med APC vendors not infinite resupply through use of a unique type

as it stands there is no reason to nerf every nanomed

**Review by harryob — APPROVED** [review]
the code remains all good

**Review by Agameofscones — APPROVED** [review]
regex moment

**Pull request merged**
