### PR TITLE
Turns all instances of 'colour' into 'color'

### PR DESCRIPTION
**Pull request by carlarctg**
# About the pull request

Turns all instances of 'colour' into 'color'.

Changed a shittily-named crayon variable's name.

# Explain why it's good for the game

We use burgerclapper english and we should standardize this

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
spellcheck: Removed all instances of 'colour' and replaced them with 'color'
/:cl:

### CODE REVIEW

**Comment by Segrain** [comment]
You got it backwards. The correct spelling is "colour".

**Comment by carlarctg** [comment]
thats bri'ish duge

**Comment by carlarctg** [comment]
were the uscm not the twe

**Comment by NewyearnewmeUwu** [comment]
USA USA USA USA USA USA USA

**Review by Nanu308 — APPROVED** [review]
this seems fine and surely wont break anything

**Pull request merged**
