### PR TITLE
shotgun ROF buff

### PR DESCRIPTION
**Pull request by stanalbatross**
## About The Pull Request

Buffs shotgun ROF a bit due to double chung making it somewhat weaker

## Why It's Good For The Game

shotgun has been weaker as a result of double chung removal, this should help it a little.

## Changelog

:cl:
balance: made the m37's fire rate 37rpm instead of 30rpm (same as the HG)
balance: bumped the HG's fire rate up a tier
/:cl:

### CODE REVIEW

**Comment by PhantomEpicness** [comment]
inb4 xenocord notices

**Comment by hotimep** [comment]
oh my gravy

**Comment by JohnDoe50974** [comment]
Good PR.

**Comment by Nanu308** [comment]
Not required, nor double shotgun removal been in long enough

**Pull request closed without merging**
