### PR TITLE
Removes bica OD IB fix and replaces with medic level surgery

### PR DESCRIPTION
**Pull request by morrowwolf**
# About the pull request

Removes bica OD IB fix.

Medics now get a "surgical case" in their essential equipment with the bare necessities to start a surgery. Doing and finishing the surgery can be done with a surgical line.

Medics and those with medical training can now identify IB areas via the check status verb.

IB surgery fix is now a NOVICE skill allowing medics to do it.

# Explain why it's good for the game

Bica OD IB fix is too easy and this should require a bit more thought into it than previously. While not intensely more difficult it will require downtime and attention rather than QC, triple bica, one kelo, and move on.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl: Morrow, Nauticall
add: Added new surgical case for medics that stores scalpel, retractor, hemostat
balance: Removes IB being fixed by bicaridine OD
balance: IB surgery fix is now able to be done at medic level
balance: medic-level and up can use the check status verb to locate IB locations
/:cl:

### CODE REVIEW

**Comment by FrogZeke** [comment]
There are a couple of bugs showing up with this one.  The hand scanner does not update with the location of the IB or the status of a surgical incision by rescanning and has to be closed first.  Even when the incision is closed, self-examine seems to show as it open, will retest.

**Comment by morrowwolf** [comment]
> There are a couple of bugs showing up with this one. The hand scanner does not update with the location of the IB or the status of a surgical incision by rescanning and has to be closed first. Even when the incision is closed, self-examine seems to show as it open, will retest.

Long term scanner bugs based off what I'm reading here. Not really in scope sadly but they're on my list somewhere.

**Comment by Ticker175** [comment]
I don't believe that it honestly makes much sense to have medics doing surgery, it will create a lot of confusion for new medics and casual players being operated on. in addition to this it also means that medics need to carry more stuff, they already have the largest kit of any role, even more than engineer (biggest in terms of the amount of stuff you need to preform your role well), making medics carry more shit would just be frustrating and im guessing would have most medics just ignoring people with IB (ive already had this happen to me twice whilst this has been merged)

**Comment by Sietchi** [comment]
> I don't believe that it honestly makes much sense to have medics doing surgery, it will create a lot of confusion for new medics and casual players being operated on. in addition to this it also means that medics need to carry more stuff, they already have the largest kit of any role, even more than engineer (biggest in terms of the amount of stuff you need to preform your role well), making medics carry more shit would just be frustrating and im guessing would have most medics just ignoring people with IB (ive already had this happen to me twice whilst this has been merged)

Agree with this, medic kit is already excessive, this is just effectively forcing them to take more stuff to fix a problem you probably come across once/twice per round - and frontline surgery doesn't make much sense at all. Why not just make the effects of the Bica overdose more severe so the marine has some incentive to keep out of the fight for a few minutes?

**Comment by Herotitan772** [comment]
> > I don't believe that it honestly makes much sense to have medics doing surgery, it will create a lot of confusion for new medics and casual players being operated on. in addition to this it also means that medics need to carry more stuff, they already have the largest kit of any role, even more than engineer (biggest in terms of the amount of stuff you need to preform your role well), making medics carry more shit would just be frustrating and im guessing would have most medics just ignoring people with IB (ive already had this happen to me twice whilst this has been merged)
> 
> Agree with this, medic kit is already excessive, this is just effectively forcing them to take more stuff to fix a problem you probably come across once/twice per round - and frontline surgery doesn't make much sense at all. Why not just make the effects of the Bica overdose more severe so the marine has some incentive to keep out of the fight for a few minutes?

I agree with both of you, I also had the same thought for how to fix the problem, just make the solution easier. It's fine if you want to allow both fixes, the OD is a high-risk and low-cost solution and the Surgery option is the safe and high-cost solution.

But another quite important thing to keep in mind regarding specifically frontline surgery is the fact that there are a group of devs that keep trying to remove groundside surgery for the reason of it not making logical sense.... so I am bewildered as to why that same group of devs are trying to now move groundside surgery from fob and specific medical facility.... to right at the point of contact with the enemy at the front where it makes EVEN LESS SENSE... honestly I want to keep this on topic but this does genuinely just seem like a desperate attempt to severely cripple marines

**Review by harryob — APPROVED** [review]
code fine

**Pull request merged**
