### PR TITLE
get_line() refactor

### PR DESCRIPTION
**Pull request by Doubleumc**
# About the pull request

The codebase currently has three line-drawing algorithms:
- `get_line()` - never used
- `getline()` - used once
- `getline2()` - used many times

They are all almost identical. There is no real use-case for one over the the other.

This PR removes `getline()` and `getline2()` and replaces those proc calls with `get_line()`. Furthermore, `get_line()` is replaced with a different method using linear interpolation, based on the examples here: https://www.redblobgames.com/grids/line-drawing/#optimization

The pros of this new method are consistent, reversible projectile paths (if you can shoot them they can shoot you), and that it is *possibly* more performant. Bresenham's line algorithm is famously fast -- for the 1960s. This new one looks to be faster on modern computer hardware. Floats aren't scary anymore.

# Explain why it's good for the game

Less duplicated code. Consistent projectile paths.
# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

The functions of interest are:
- `get_line()`, `getline()`, `getline2()` - in our codebase
- `getline_tgmc()` - TGMC's "Reasonably Optimized" version: https://github.com/tgstation/TerraGov-Marine-Corps/blob/2da5c237640d73e3e66ad79e34861e9682f4609c/code/__HELPERS/unsorted.dm#L816-L869
- `get_line_testA()` - the proposed replacement
image

The output of `get_line_testA()` is *not* identical to `getline2()`. A path starting at the center pillar and ending on a tiled floor has different results.
image

The following examples are a comparison between `getline2()` and `get_line_testA()`. All paths start at the wall and end at the ghost. Purple tiles are where both functions picked the same turf, red is unique to `getline2()`, blue is unique to `get_line_testA()`. Note that `get_line_testA()` results in the same path taken regardless of direction.

Example 1a: SW to NE
image
Example 1b: NE to SW
image

Example 2a: NW to SE
image
Example 2b: SE to NW
image

</details>

# Changelog

:cl:
refactor: projectile paths are the same in both directions, A->B and B->A
/:cl:

### CODE REVIEW

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by Doubleumc** [comment]
CORRECTION: the path is *more* consistently reversible that before, but its not always reversible. From about 70% for the original `getline2()` to about 80% for the new method.

**Comment by Doubleumc** [comment]
Compensated for a rounding inaccuracy, it is now consistently reversible for at least 100+ tiles.

**Review by Birdtalon — APPROVED** [review]
Looks good and haven't seen any big behaviour changes or problems from TM.

**Pull request merged**
