### PR TITLE
UPP Wall Flag

### PR DESCRIPTION
**Pull request by Steelpoint**
# About the pull request

Adds a medium sized UPP flag sprite to the game for mappers. 

# Explain why it's good for the game

Good for helping establish an area is under UPP control. 

# Testing Photographs and Procedure
Screenshot 2024-08-11 20 13 52

# Changelog
:cl:
add: A medium sized, wall mounted, UPP flag sprite has been added to the game, for mappers to use.
/:cl:

### CODE REVIEW

**Review by Blundir — APPROVED** [review]

**Comment by Zenith00000** [comment]
I did actually add a very similar flag with Hybrisa as I was making a TWE flag, so I thought I might as well make more. You're do look a lot nicer though, and mine are fairly low effort. Perhaps you could replace mine with better versions or expand your PR. Either way great stuff.

flags

**Comment by Steelpoint** [comment]
> I did actually add a very similar flag with Hybrisa as I was making a TWE flag, so I thought I might as well make more. Yours do look a lot nicer though, and mine are fairly low effort. Perhaps you could replace mine with better versions or expand your PR. Either way great stuff.
> 
> (The "worn" versions are primarily up for grabs for mappers who want to make some cool inserts if you're wondering, I'm sure they could see some use.)
> 
> flags

If you are adding them with your PR then we all look forward to using them

**Comment by Zenith00000** [comment]
> > I did actually add a very similar flag with Hybrisa as I was making a TWE flag, so I thought I might as well make more. Yours do look a lot nicer though, and mine are fairly low effort. Perhaps you could replace mine with better versions or expand your PR. Either way great stuff.
> > (The "worn" versions are primarily up for grabs for mappers who want to make some cool inserts if you're wondering, I'm sure they could see some use.)
> > flags
> 
> If you are adding them with your PR then we all look forward to using them

Yeah I'm just saying that your sprites are better, the ones I did don't look as good. If you're up for improving them then I can replace the sprites I have, because I'm not satisfied with them. Either way though no worries.

**Comment by Steelpoint** [comment]
> > > I did actually add a very similar flag with Hybrisa as I was making a TWE flag, so I thought I might as well make more. Yours do look a lot nicer though, and mine are fairly low effort. Perhaps you could replace mine with better versions or expand your PR. Either way great stuff.
> > > (The "worn" versions are primarily up for grabs for mappers who want to make some cool inserts if you're wondering, I'm sure they could see some use.)
> > > flags
> > 
> > 
> > If you are adding them with your PR then we all look forward to using them
> 
> Yeah I'm just saying that your sprites are better, the ones I did don't look as good. If you're up for improving them then I can replace the sprites I have, because I'm not satisfied with them. Either way though no worries.

I think your sprites are fine insofar as being more "torn" apart which might be a good alt-set for areas that are move old/overrun, I'd still include both sets.

**Comment by Blundir** [comment]
Yeah the ones Zenith showed are different size too, so i see no problem in having both sets

**Review by harryob — APPROVED** [review]

**Pull request merged**
