### PR TITLE
Adds IA as a vendor option (for more points than standard bottles)

### PR DESCRIPTION
**Pull request by zzzmike**
# About the pull request

Adds IA as a pill bottle in vendors for more points than the usual pill bottle.

# Explain why it's good for the game

I know this could be "controversial" but, in server corpsman/doctor culture, IA is pretty much mandatory to have with you. Anytime someone complains about being blind for example, you should give them an IA pill. WHY are we forcing chemistry to make pills which are basically necessary for all corpsman and all doctors every round? They are busy enough with the 8+ custom mixes listed on the chemistry wiki page - not to mention that I've seen people ask for things not on the wiki as well. In any case, they will still need to make it frequently because this change only adds it as an option for 6 points in gear vendors (more points than other pill bottles).

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl:
qol: IA is now an option for points in vendors
/:cl:

### CODE REVIEW

**Comment by Git-Nivrak** [comment]
Would make more sense to have imidazoline and alkysine available as separate options, so it's more on-par with the rest. I agree that it's pretty much mandatory to have IA however chemistry line should still have the more efficient mixes.

**Comment by zzzmike** [comment]
> Would make more sense to have imidazoline and alkysine available as separate options, so it's more on-par with the rest. I agree that it's pretty much mandatory to have IA however chemistry line should still have the more efficient mixes.

At least with MB and KD there is a use-case for using plain bica or plain kelo (it'll heal slower in the short term but it'll last longer in the bloodstream so it could be useful for future/drawn-out engagements) - But IMO plain imi + plain alky would seem to exist for no other reason than "let's give chemistry more work when they already have plenty to do"

**Comment by zzzmike** [comment]
> Would make more sense to have imidazoline and alkysine available as separate options, so it's more on-par with the rest. I agree that it's pretty much mandatory to have IA however chemistry line should still have the more efficient mixes.

Thought about this some more and I would support adding the separate options to WeyMed for free like plain bica is etc. - I added the mix for points because I know it's an enticing option to spend points to save time vs. going to chemistry for it - kinda like how spending points as a corpsman for a smartpistol can be enticing vs. going to req for it etc.

**Comment by TheManWithNoHands** [comment]
This is a noob trap to waste points. Plain and simple. IA is always made by chem, you dont have trobule getting it for free.
All this would do is ad an option to use points for something you can get unlimeted for free. Wich is not the point of point shops.
they are there for stuff you cant get easily more or are time intensive to get.

Worst off all, this will open the door for the other chem mixes to be added as well. Because the main reason for this is "why not?".

So hard no. This has no purpose to be.

**Comment by zzzmike** [comment]
> or are time intensive to get
Yes, this is a big part of why I added it. You wouldn't believe how long it takes to get chem to make essential things like IA sometimes, when they are busy with people asking for optional/niche stuff.

**Comment by TheManWithNoHands** [comment]
> Yes, this is a big part of why I added it. You wouldn't believe how long it takes to get chem to make essential things like IA sometimes, when they are busy with people asking for optional/niche stuff.

Some players not doing their role sometimes, isnt reason enough to start implementing stuff to remove part of said role.

**Comment by zzzmike** [comment]
> Some players not doing their role sometimes, isnt reason enough to start implementing stuff to remove part of said role.

I didn't say that they weren't doing their job, just that they were busy with custom requests rather than something that's considered mandatory at this point like IA. Also, custom chemical mixes from vendor is already a thing (revival mix, with another one pending - https://github.com/cmss13-devs/cmss13/pull/6914 )

**Comment by TheManWithNoHands** [comment]
> I didn't say that they weren't doing their job

Its a hyperbolic quote to broaden the general argument to its logical border. Dont take that as an acusation. Its only meant to show of the extreme case of the problem your trying to solve, to allow for a broader view.

>Also, chemical mixes from vendor is already a thing (revival mix, with another one pending - https://github.com/cmss13-devs/cmss13/pull/6914 )

Those arent the most common mixes that are added, like you want, but mixes that are situational and not always needed. Also they arent pills, but pouches wich are a whole nother deal. 'cause the pouches are about a large quantity of chemicals. Ammounts that are so large, that, persay, you need to stand in chem for 10-15 minutes until they are done. About 400u after all that fits in there. You would run the chem power dry with one HM alone.

IA isnt hard to do, its always made, and its not needed to buy. All this will do, is ad an option for newplayers to buy something to waste points on. Every old HM will spend their points on stuff instead that they cant get for free from medical. Like, extra stasis bags. Special armor. Or a chem pouch that doesnt fully shut down the chemline for like 5 minutes.

**Comment by zzzmike** [comment]
> Every old HM will spend their points on stuff instead that they cant get for free from medical. Like, extra stasis bags.

Every single HM yeah? I'm a plat HM and I'd spend points on it all the time. It's absolutely worth it in order to save myself time and save chem some machine energy. Also extra stasis bags are free from medical vendors which refill themselves over time.

> Or a chem pouch that doesnt fully shut down the chemline for like 5 minutes.

Yes, if only people didn't ask for stuff which doesn't shut down the chemline for 5+ minutes (if chemline being held up wasn't an issue then I wouldn't have made this PR)

**Comment by ihatethisengine** [comment]
Honestly, IA is such a relic that it needs to be rebalanced, just like they did with Bica OD not healing IB anymore.

**Comment by efzapa** [comment]
IA takes less than 60 seconds to make even by bald nurses if they have the wiki up

merging this would give nurses even less shit to do and be a point sink for new players

probably a slippery slope argument but I do see this being used as a ramp towards giving medics premixed ATD and UNGA down the road

**Comment by zzzmike** [comment]
> IA takes less than 60 seconds to make even by bald nurses if they have the wiki up

And yet, sometimes I'm waiting more than 10 minutes due to chemline, when I only want IA not any of the special chems. Chemistry should be specialized mixes like your examples of ATD/UNGA, not mandatory-every-round-for-every-medic stuff like IA. Besides, nurses are still gonna make IA because this costs points which not everyone is gonna use. Not to mention that it gets tedious for people to make every single round.

**Comment by ihatethisengine** [comment]
> And yet, sometimes I'm waiting more than 10 minutes due to chemline, when I only want IA not any of the special chems. Chemistry should be specialized mixes like your examples of ATD/UNGA, not mandatory-every-round-for-every-medic stuff like IA. Besides, nurses are still gonna make IA because this costs points which not everyone is gonna use. Not to mention that it gets tedious for people to make multiple batches of IA every single round.

What exactly makes you think IA is *mandatory*? Why bonemending is not mandatory, bonebreaks happens way more often. Why, as another example, iron is not mandatory (unless this is your next pr lol)? People running out of blood constantly. Only (not reasonable) reason you consider IA mandatory is the fact it is the only pill that lets you to completely remove organ damage (but only from head). You cannot heal lungs with pills, you cannot heal heart, you cannot heal kidney. Although you can temporary heal organs with peri (which kinda makes IA not mandatory already, also synth and doctor can easily fix organ damage). IA is so strong for no reason and you wanna remove the only small skill barrier that somewhat justifies its existence.

**Comment by zzzmike** [comment]
> What exactly makes you think IA is mandatory?

Because as long as IA exists roundstart, it's just wrong to not take it. (I don't even care if that is changed btw, I would happily close this PR if that was merged.) Also you can even detect eye/brain damage directly as HM with the recent penlight PR.

> Why bonemending is not mandatory

Because splints exist, and because a bonemending pill is not something that can be created roundstart.

> Why, as another example, iron is not mandatory

Because blood bags, MREs, and sometimes even MST in fob, exist.

**Comment by morrowwolf** [comment]
Pros:
Less annoying when you miss first drop because baldie is at the line and you just want some IA real fast.

Cons:
The more we make certain parts of loadouts "standard" (even if it's not free) the less people will feel able to experiment.
As annoying as the chem line is it can be a good spot to chat and interact with others. Every little change against this slowly erodes meaningful interaction between marine players.

Middling:
Continues the trend of trivializing the ability to trivialize long term wounds. Depending on how you see the game this could go either way. I think tension and genuine adrenaline reactions in the game are fueled by the consequences of actions. The more we make those consequences mean nothing for the sake of "it's annoying" the more we take away those real emotions when shit goes down. And sure, this is hardly killing the game but it's baby steps and since we're open source those baby steps are easy to keep walking.

**Comment by Nanu308** [comment]
Not really a fan of this personally as it removes some of the player interaction and inter-department teamwork, even if it's quite small. I do not believe you are entitled to ImiAlky, so personally not a fan of this PR.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by Wintermote** [comment]
IA should be standard like all your other chems as part of the baseline kit for treating all basic injuries in the field that medics handle.

Chemline is for specialized and more efficient drugs. We shouldn't have a chemline with 8 medics waiting to get IA; it's like forcing players to wait to get their bicardine and kelotane pills. IA is functionally mandatory for treating players but it's NOT in a players' starting kit???

**Comment by harryob** [comment]
feel free to reopen if you work it out with nanu to unblock the pr, otherwise stale

**Pull request closed without merging**
