### PR TITLE
1 Hour Zombie Revive fix

### LINKED ISSUE #2267: zombie ad their resurect timer starting at 1h00 instead of 1min
### Testmerges

No

### Description of the bug

zombie ad their resurect timer starting at 1h00 instead of 1min

### What's the difference with what should have happened?

zombie ad their resurect timer starting at 1h00 instead of 1min

### How do we reproduce this bug?

1.be a zombo
2.die
3.wait one hour
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

### PR DESCRIPTION
**Pull request by fluffe9911**
# About the pull request

This should fix the 1 hour zombie revive bug. Originally ported from https://github.com/cmss13-devs/cmss13/pull/2803 by kiVts then redone using a absurd amount of help from Drathek. Tested it works 100%

# Explain why it's good for the game
Zombies deciding to take a hour to revive is not intended and annoying.

Fixes #2267 

# Changelog

:cl:
fix: Zombies should no longer randomly decide to take a hour to revive.
/:cl:

### CODE REVIEW

**Comment by Huffie56** [comment]
i tested zombie revive on a server and they no longer take 1H to revive.
i don't know what issue your trying to fix there @fluffe9911 ?
did you even test zombie on local server to see if their was still an issue?

**Comment by kiVts** [comment]
> i tested zombie revive on a server and they no longer take 1H to revive. i don't know what issue your trying to fix there @fluffe9911 ? did you even test zombie on local server to see if their was still an issue?

Kill ~200 zombies with flame nuke and see for yourself, on your local server.

**Comment by Watermelon914** [comment]
You should explain how this is fixing the bug.
Additionally, I don't see how this would fix anything as you've only made it so that these timers don't get overriden but stack up.
If you want to make them unique, remove TIMER_OVERRIDE, keep TIMER_UNIQUE

**Comment by Watermelon914** [comment]
Also this seems like a serious hack, I don't see how this would fix the problem. This proc should only be called once, you should be looking into why this proc is being called multiple times, if it is, and fix that.

**Review by Watermelon914 — CHANGES_REQUESTED** [review]
see above

**Comment by fluffe9911** [comment]
I aint a coder I just know how to use github I took the fix from a different PR, I do not understand how it works, I do not understand how to fix the issue in any other way, I was simply going off of good faith for what the original author of the fix said.

Anyway as I said on the discord when I first made this if I get any push back im just gonna close this because I have no clue how to fix the issue other then how the original person did it.

**Comment by kiVts** [comment]
> > > i tested zombie revive on a server and they no longer take 1H to revive. i don't know what issue your trying to fix there @fluffe9911 ? did you even test zombie on local server to see if their was still an issue?
> > 
> > 
> > Kill ~200 zombies with flame nuke and see for yourself, on your local server.
> 
> i don't know what you mean by flame nuke? and i killed a bunch of zombie with flamethrower or guns etc... they all resurrected fine... main concern for me is that this "fix" hasn't been tested....

Flame OB I meant, sorry. Anyways - when I was spending my time with it, single thing I noticed is that, this happens only to corpses who get their faces burned away, so in the revive list it had like 20 Unknowns(literally, unknown, unknown, unknown, unknown, unknown, unknown, unknown etc) one unknown will get revived,( the last to die) other 19 will not revive at all. This is due to unique timer + override timer (I suppose so) override other people timers when last one is created. Removing it fixed the bug, this is probably(?) not the best way to fix it but also not the worst I suppose.

**Comment by fluffe9911** [comment]
With a ton of help from Drathek PR should be less hacky now and hopefully up to maintainer standards.

**Review by Drulikar — APPROVED** [review]

**Pull request merged**
