### PR TITLE
Adjusts tank weapons & updates them with modern mechanics

### PR DESCRIPTION
**Pull request by TheManWithNoHands**
# About the pull request

Lots of tank code is very old, which causes a lot to miss modern stuff.
* M56 Cupola now is fully just a M56D. Same fire rate, and autofire. Before it only had 3 shot burst.
* M92T grenade launcher gets hightoss. So it needs to abide by the rules of getting fucked by high walls.

As well DRG-N Flamer has its projectile speed is changed from 1 to 1.5 for having its size reduced.

# Explain why it's good for the game

Tank weapons are still a little fucky. Lots of ancient code, missing modernisation.
Only reason the M56 Cupola didnt have autofire was its age, so thats changed.
Furthermore, it is now 1:1 just a M56D. Although with sligthly larger spread Iirc.
Its not a competiion with the LTAA-AP, its now a more effective secondary automatic rifle. Which the secondaries should be, small versions of the big guns.

Also all that hightoss on the M92T does is give it less places to use it, and make it behave like every other grenade launcher.
Consitency between weapon types is good.

Furthermore i want to see the DRG-N more used. Previous projectile speed it had was honestly pretty slow.
It would have fit perfectly on the old DRG-N, but now with the 4 tile fire patern, it is simply too slow.
The smaller patern demand more precise hits, which a faster projectile travel speed makes more feasible.
In general, i hope this little change will be enough to make the DRG-N more fun to use. Will have to look at its performance, it definitely will need some more tweaks, testing can only tell me so much.

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl:TheManWithNoHands
balance: rebalanced highdamagenapalm for the tank flamer to change its projectile speed from 1 to 1.5
balance: gives the M56 Cupola autofire instead of burst, lowering its fire delay to 0.3
balance: gives the M92T grenade launcher PASS_HIGH_OVER and PASS_MOB_THRU bullet properties
/:cl:

### CODE REVIEW

**Comment by deathrobotpunch** [comment]
Minor spelling mistake

**Comment by TheManWithNoHands** [comment]
> Minor spelling mistake

where? I didnt write anything but code.

**Comment by deathrobotpunch** [comment]
> where?

> > Lots of tank cold is very old, wich causes a lot to miss modern stuff.

cold -> code, wich -> which

> > Tank weapons are still a little fucky. Lots of anchient code

anchient -> ancient

> > Wich the secondarys should be, small versions of the big guns.

wich -> which, secondarys -> secondaries

> > The smaller paterns demand more precise hits, wich a slow projectile travel speed makes more vehsibal.

wich -> which, vehsibal -> visible

> > it definitly will need some more tweaks, testing can only tell me so much.

definitly -> definitely

> > balance: gives the M92T grenade launcher PASS_HIGH_OVER and PASS_MOB_THRU bullet propertys.

propertys -> properties

**Comment by TheManWithNoHands** [comment]
Its in the pr text and not actually ingame, who cares.

**Review by harryob — APPROVED** [review]
lets see how thsi goes

**Pull request merged**
