### PR TITLE
You can now rig custom C4 to a wheelchair and detonate it with a bell

### PR DESCRIPTION
**Pull request by iloveloopers**
# About the pull request
wire the wheelchair then put in a custom plastic explosive, press the bell repeatedly until it explodes (15% chance for it to explode each click except the first)
you must be sitting on the wheelchair with the bell in hand

# Explain why it's good for the game
its funny
adds more features to the game

# Testing Photographs and Procedure

https://github.com/cmss13-devs/cmss13/assets/140007537/4497b96f-42bc-4e26-809e-68283a310377

# Changelog

:cl:
add: You can now rig custom C4 to a wheelchair and denotate it with a bell
/:cl:

### CODE REVIEW

**Comment by Skatuk** [comment]
Speedmerge

**Comment by Git-Nivrak** [comment]
It should be visual on the chair

**Comment by HeresKozmos** [comment]
the PR that CM needs 🙏

**Comment by s5nt** [comment]
gem

**Comment by ihatethisengine** [comment]
The reference is not subtle enough to be considered a reference.

**Comment by iloveloopers** [comment]
1984 antigrief check added

**Pull request closed without merging**
