### PR TITLE
New hard hat sprites

### PR DESCRIPTION
**Pull request by Youtubeboy139**
## About The Pull Request

Adds in new CM specific Hard hat sprites - both item and onmob sprites. Also changes the Fireman's Helmet to include a built-in mask that separates it from the other hardhats.
cmss13-New Hardhats 1
cmss13-New Hardhats 2

## Why It's Good For The Game

Adds better sprites to help the coherency of the art style. Also makes the Fireman's Helmet act more like a Fireman's helmet.

## Changelog

:cl:
imageadd: New hard hat item sprites
imageadd: New hard hat onmob sprites
change: Adds a mask to the Fireman's Helmet
/:cl:

### CODE REVIEW

**Comment by MusselMain** [comment]
What're the new hardhat colors for? I assume red is firefighter, yellow is engineering, and white is the CE's, but what about brown and blue? are they mining and something else? or are brown and blue just alternatives to the yellow engineering helmets?

**Comment by MusselMain** [comment]
> What're the new hardhat colors for? I assume red is firefighter, yellow is engineering, and white is the CE's, but what about brown and blue? are they mining and something else? or are brown and blue just alternatives to the yellow engineering helmets?

I do want to emphasize I'm not complaining, just curious

**Comment by Youtubeboy139** [comment]
> What're the new hardhat colors for? I assume red is firefighter, yellow is engineering, and white is the CE's, but what about brown and blue? are they mining and something else? or are brown and blue just alternatives to the yellow engineering helmets?

I don't know what exactly the colors are for honestly, this specific set of colors has been around since TG if I remember correctly

**Comment by Youtubeboy139** [comment]
Re-requesting review to shake the Stale Bot, please ignore

**Review by thwompa — APPROVED** [review]
okay after a second look, one issue.

the shading on each of the objs and the onmobs is very flat. cm artstyle is typically high contrast with dark outlines. these needed to be updated to match that.

**Review by JeserTheFox — APPROVED** [review]

**Review by FransFeiffer — APPROVED** [review]
Sprites LGTM

**Pull request merged**
