### PR TITLE
Reopens #4583 (Experimental Tackle Changes)

### PR DESCRIPTION
**Pull request by Staykeu**
# About the pull request

Reopens https://github.com/cmss13-devs/cmss13/pull/4583 (description is mostly pulled from it)

This PR removes all randomness from xeno tackles.

If you hit the maximum tackle for the caste you are playing, you will tackle.

Depending on how much damage the person being tackled has it will lower the required tackles.

The minimum required tackle "tap" is succeeded once a human is at or below 70 health.

Alongside this, tackle chances have been moved around to try and account for randomness no longer being a factor.

Three castes in particular have been moved higher on purpose above the others: warriors, lurkers, and runners.

# Explain why it's good for the game

Twofold:

Randomness with tackle chance creates insanely unfun situations where you get two tap disarmed by a drone and want to die.

Stun combat is slowly but surely being cut away and we want to encourage people to fight.

Do note, we still want xenos to cap so the maximum damage to reach the minimum amount of tackles is 70 damage. These numbers will be flexible as we see what happens in the tests.
# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Not tested.

</details>

# Changelog
:cl: Stakeyng
balance: Xeno tackles are no longer random and range in required disarms based on damage to the disarmed. Max damage to get minimum number of tackles is 70.
balance: Alongside xeno tackles being no longer random, pretty much every caste has had tweaks to their disarm related variables. Specific nerfs to: warrior, lurker, and runner.
/:cl:

### CODE REVIEW

**Comment by hislittlecuzingames** [comment]
Looks like the random chance to fail is removed _and_ an additional tile or two of range is being added throughout.

**Comment by Staykeu** [comment]
> Looks like the random chance to fail is removed _and_ an additional tile or two of range is being added throughout.

this is a compromise for xenos no longer being able to insta-down a full-health marine

**Comment by InsaneRed** [comment]
please properly name the pr

**Comment by Staykeu** [comment]
WIP until a way for xenos to see a targets damage is implemented.

**Comment by private-tristan** [comment]
here's a handy chart I made for xeno caste to tackles on varying marine HP
image

**Comment by Staykeu** [comment]
> here's a handy chart I made for xeno caste to tackles on varying marine HP image

i applaud your work but this is could register as an inaccuracy in the future, this PR is still very subject to changes, specifically to the number values

you'd also need to state whether or not health is increasing on descent in the graph, or increase on descent

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by morrowwolf** [comment]
There were serious issues to this that I never got around to putting in fixes for. Two things just from memory:
Xenos need a way to tell what "tier" the person they're tackling is at. Whether examining them to give a "they look hurt" message or whatever. Otherwise, this is encouraging just killing instead of capping (which is arguable whether we want or not) and is frustrating to engage with.
Some of the values still seriously needed tweaked. Anything with a stun should generally have a slightly higher number of required tackles to avoid stun->cap guarantees.

**Comment by Staykeu** [comment]
> There were serious issues to this that I never got around to putting in fixes for. Two things just from memory: Xenos need a way to tell what "tier" the person they're tackling is at. Whether examining them to give a "they look hurt" message or whatever. Otherwise, this is encouraging just killing instead of capping (which is arguable whether we want or not) and is frustrating to engage with. Some of the values still seriously needed tweaked. Anything with a stun should generally have a slightly higher number of required tackles to avoid stun->cap guarantees.

A sprite/a process of sprites has been made to display human health states, highlighting perfect cap timing, however I'm not skilled enough to implement these sprites myself. If anyone wants to attempt that be my guest, I'll be happy to respond as fast as I can with the file (over discord, unable to be shared on github, unfortunately). Just let me know.

As for the second half, I feel that's something that will be worked out with time, people seem more interested in giving criticisms without specific solutions so it's not terribly obvious which values need to be at what range. If the PR breaks through the issue of the spriting, I'm sure kinks in the delicate balances can be worked out through time and TMs.

**Comment by Staykeu** [comment]
This goes without saying but work on this is halted until i get unbanned from the discord server lolololo

**Pull request closed without merging**
