### PR TITLE
Port /tg/ PR #75835 - Linux 515 fcopy() crash fix

### PR DESCRIPTION
**Pull request by fira**
Details here: https://github.com/tgstation/tgstation/pull/75835

### CODE REVIEW

**Comment by Drulikar** [comment]
Glad I added that 515 unit test; though also failing on TG too. Likely not worth merging until they sort out why or can confirm for sure that all those errors somehow are false positives.

**Comment by Drulikar** [comment]
I can confirm they are not false positives: 
image
You just don't get icons.

**Comment by fira** [comment]
Whathefuk...

**Comment by Drulikar** [comment]
Looks like Walter's edit should be viable.

**Comment by fira** [comment]
Indeed. I don't know why I thought fexists() would work with RSC bundled resources...

**Comment by Drulikar** [comment]
This still seems kinda unstable. So character panel never ended up loading in the human model, and each time it was opened it would incrementally add in more clothes sprites. Everything else seemed fine, expect that it then proceeded to crash or disconnect (ending the debug run). These were the errors I experienced related to the character panel: 
[dd.log](https://github.com/cmss13-devs/cmss13/files/11645893/dd.log)

Its not obvious yet what caused a crash/disconnection though. I was using 515.1606. Will try again using 515.1608.

**Comment by fira** [comment]
I'm not sure these are related, it all reads out as a null mob. Intriguing though...
In any case this is meant primarily for TM to the Linux server so we can find out what happens there

**Pull request merged**
