### PR TITLE
Adds Ceramic Plates to the CL Briefcase

### PR DESCRIPTION
**Pull request by Geevies**
## About The Pull Request

Marines have very few reasons to interact with the Corporate Liaison, as it stands, the biggest reason to even bother speaking with them is to take their ultrazine, give them a wedgie, then run away.

This ends today.

With the introduction of Ceramic Plates to the CL Briefcase, marines will have a true reason to stick by the CL's side, especially because of how fragile it is. Marines will need a constant resupply as the round goes through. Better stay on the CL's good side!

## Why It's Good For The Game

Marines have very few reasons to interact with the Corporate Liaison, as it stands, the biggest reason to even bother speaking with them is to take their ultrazine, give them a wedgie, then run away.

With the introduction of Ceramic Plates to the CL Briefcase, marines will have a true reason to stick by the CL's side, especially because of how fragile it is. Marines will need a constant resupply as the round goes through. Better stay on the CL's good side!

## Changelog

:cl: Geeves
add: Added the option to buy ceramic plates to the CL's Briefcase.
/:cl:

### CODE REVIEW

**Comment by JohnDoe50974** [comment]
Nice. CLs can use it for themselves to give them an edge during antat events or tasks, too. A hreat example of "rework, not remove" in action.

**Comment by BKryth** [comment]
Good change, increases CL RP

**Comment by Bram-KEP** [comment]
Is this a literal plate

This is amazing

**Comment by hotimep** [comment]
think fast xeno main
5Og8

**Comment by Diegoflores31** [comment]
i dont really understand the meaning of this feature as i read the code you mean a literal Plate made of ceramic and not the one you fit in your uniform. 
this is a meme PR obviously.

**Comment by PhantomEpicness** [comment]
BASED FUCKING PR


CM-SS13 is not related to the Disney-owned "Aliens" Franchise and IP This is an entirely fan-made project. In case of an investigation by any federal entity or similar, I do not have any involvement with this group nor with the people in it, I do not know how I am here, probably added by a thrid party, I do not support any actions by the members of this group. Any and all content made by this account were made without my permission and I have no knowledge of the usage of this GitHub ©️  account to contribute to CM-SS13.

**Comment by Mechanelize** [comment]
> i dont really understand the meaning of this feature as i read the code you mean a literal Plate made of ceramic and not the one you fit in your uniform. this is a meme PR obviously.

you throw them at people

**Review by Agameofscones — APPROVED** [review]
Fine china like this is what really adds to the CM experience, and really helps you feel like you're playing a marine

**Review by stanalbatross — APPROVED** [review]

**Pull request merged**
