### PR TITLE
adds landmarks for thunderdome & xeno_spawn

### PR DESCRIPTION
**Pull request by ItsVyzo**
# About the pull request
adds landmarks for thunderdome & xeno_spawn

# Explain why it's good for the game
Mapper life made easier

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl: LTNTS
imageadd: landmarks for xeno_spawn
imageadd: landmarks for thunderdome
/:cl:

### CODE REVIEW

**Comment by ItsVyzo** [comment]
not a feature but ok q-q

**Review by nauticall — APPROVED** [review]
sprites work, looks good to me!

**Review by harryob — APPROVED** [review]
code is fine

**Review by FransFeiffer — APPROVED** [review]
Ayup, it do be looking fine doe

**Pull request merged**
