### PR TITLE
Adds Large Tool Pouch

### PR DESCRIPTION
**Pull request by stobarico**
## About The Pull Request

This PR adds a large tool pouch to a few roles.

## Why It's Good For The Game

A large tool pouch gives the selected roles more loadout flexibility at the price of points or a slot with other good choices (Example: SL and their large ammo pouches)

## Changelog

🆑
add: Added large tools pouch, fits 6 tools: ComTech (3 Points), SL (Selectable Pouch), RTO (5 Points), Synth  (Selectable Pouch), CO  (Selectable Pouch), VC (5 Points) and Requisitions (Same pop scaling as large ammo/shotgun pouches), CE (In their locker) get them.
/🆑

### CODE REVIEW

**Comment by morrowwolf** [comment]
Would also be cool if chief engineer spawned with it.

**Comment by stobarico** [comment]
> Would also be cool if chief engineer spawned with it.
> 
> Line 138ish of ...\code\modules\gear_presets\uscm_ship.dm

Added to their locker instead, replacing the normal one that would spawn there.

**Comment by morrowwolf** [comment]
> > Would also be cool if chief engineer spawned with it.
> > Line 138ish of ...\code\modules\gear_presets\uscm_ship.dm
> 
> Added to their locker instead, replacing the normal one that would spawn there.

I don't think that locker is used on the Almayer anymore but I may be mistaken.

**Comment by MusselMain** [comment]
Give this to Combat Technician's vendors for a few points, it'd let them carry a fair amount of tools while not having to use the belt slot.

**Comment by stobarico** [comment]
> Give this to Combat Technician's vendors for a few points, it'd let them carry a fair amount of tools while not having to use the belt slot.

It's already in for ComTech for 3 points

**Comment by stobarico** [comment]
> > > Would also be cool if chief engineer spawned with it.
> > > Line 138ish of ...\code\modules\gear_presets\uscm_ship.dm
> > 
> > 
> > Added to their locker instead, replacing the normal one that would spawn there.
> 
> I don't think that locker is used on the Almayer anymore but I may be mistaken.

I've just checked and that's true, put it in their loadout.

**Comment by GoldenDarkness55** [comment]
Isnt this just powercreep? Might aswell replace the belt as a free item if it's going to be 3 points.

**Comment by PhantomEpicness** [comment]
A bit powercreepy as a normal tools pouch is fine for 90% of field use

**Comment by Nanu308** [comment]
This is powercreep and not required

**Pull request closed without merging**
