### PR TITLE
Update brig area to make more sense.

### PR DESCRIPTION
**Pull request by Huffie56**
# About the pull request
1-Merge the two hypersleep room into one for brig.
2-Put evidence room where interrogation room and move interrogation room just north of processing room in brig.
3-cleaning up the area to make them aesthetic around the changes...

# Explain why it's good for the game
1-we shouldn't have two hypersleep room for a department with 8 people maximum...
2-it make more sense to have interrogation room near processing room so that MP know it's here ...
# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

image

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl:
maptweak: Merge the two hypersleep room into one for brig.
maptweak: Put evidence room where interrogation room and move interrogation room just north of processing room in brig.
/:cl:

### CODE REVIEW

**Comment by Huffie56** [comment]
if you need me to provide more reason to why i did this or that i am all there just tag me here or on discord
and if you aren't reviewing just use the discord project chanel:
https://discord.com/channels/150315577943130112/1101181191211724890/threads/1132573735258435674

**Comment by Huffie56** [comment]
> Firstly, don't remove the windows in maintenance. They're not "bugs" they're deliberately there to allow looking out into space. The same reason there are windows in the access corridors north and south of CIC.
> 
> Second, can you change req_access & req_one_access_txt on the north door here image to match these, as this will allow senior command staff to open it as they can access the north half of Brig for this reason. image

it's weird if i remember correctly i just copy paste the bottom door of the interrogation room.
am i at-least allow to tweak the positioning of the windows in maintenance?

**Comment by Huffie56** [comment]
i added back the window in maintenance...
i change the variable to match what you show on your message above.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by Huffie56** [comment]
going to wait for forest PR to be merge before i fix the conflict.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by Huffie56** [comment]
> 

no worries.
good thing i didn't sink more hour in renovated brig.
(was thinking about renovate the infirmary, the armory and adding an holding cell)
was testing the water... i understand the argument for evidence locker being closer.
the part about investigation room being at processing being confusing not so much....
my big guess is that you aren't interested in any change to brig.

**Pull request closed without merging**
