### PR TITLE
weapon stats tgui

### PR DESCRIPTION
**Pull request by stanalbatross**
# About the pull request

remade the weapon status nanoui into tgui

image

# Explain why it's good for the game

fuck nanoui + this one actually updates

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
ui: remade the weapon status nanoui into tgui
/:cl:

### CODE REVIEW

**Comment by moltoretardo** [comment]
I'm probably not supposed to comment here but there's no discord message thingy.
All I want to say is that NanoUI had alot of very cool linearts illustrating the different weapons it'd be nice to see them ported too, unless it causes too much headaches

**Comment by stanalbatross** [comment]
> I'm probably not supposed to comment here but there's no discord message thingy.
> All I want to say is that NanoUI had alot of very cool linearts illustrating the different weapons it'd be nice to see them ported too, unless it causes too much headaches

I wanted to do this but the headache associated was very large

I might do it after this is merged, or someone else can

Just know that it involves like 80 images

**Comment by Nanu308** [comment]
Add lineart guns back, it was psoulful.

**Comment by stanalbatross** [comment]
> Add lineart guns back, it was psoulful.

image
done

**Review by harryob — APPROVED** [review]

**Pull request merged**
