### PR TITLE
Med skill rebalance Mk2

### PR DESCRIPTION
**Pull request by Katskan**
# About the pull request

2 main things, the medical 4 generalized multiplier changed to a non-standard value of 0.35, 10% less than it was before but 15% better than most recent. The other part is changing how medical skill affects defibrillators, with medical 4 shocking right as defibrillators finish their charge sound. Medical 2 is still unaffected by how the math works. 

# Explain why it's good for the game

Keeps some of the splint/inject/CPR time from before, while maximizing the speed you can get before the shock sound. 

# Testing Photographs and Procedure

**Please TM**

Tested on local server to make sure all the scaling worked properly. 

# Changelog

:cl:
balance: changed medical 4 skill speed multiplier from tier 2 to a non-standard 0.35
balance: changed defib medical skill speed scaling
/:cl:

### CODE REVIEW

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Review by Drulikar — APPROVED** [review]
Corpsman 7.0 seconds (2/4 medical)
CLF Synth 6.25 seconds (3/4 medical)
USCM Synth 5.05 seconds (4/4 medical)

**Comment by TheGamerdk** [comment]
Compared to before:

Pre-nerfs (Only relevant to shipside synthetic): 1,75
Post-nerf, pre-this: 3,5
This: 5.05

Approx. 300% slower

**Pull request closed without merging**
