### PR TITLE
Removes alien organ code

### PR DESCRIPTION
**Pull request by Zonespace27**
# About the pull request
8 year initial commit moment

None of this did anything anywhere

Closes https://github.com/cmss13-devs/cmss13/pull/2475

# Explain why it's good for the game
Tech debt decreased

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Compiles

</details>

🆑 
del: Removed fluff alien organs on CORSAT and sci annex
/🆑

### CODE REVIEW

**Review by harryob — APPROVED** [review]
the vox cortical stack

**Comment by Diegoflores31** [comment]
no changelog 👀

**Comment by harryob** [comment]
> no changelog 👀 
> 
> 
> 
> also isnt the "closes " supposed to be only for Issue reports ??

no playerfacing changes so it doesn't need one lol

also who cares that pr is already closed

**Comment by Zonespace27** [comment]
> Map changes are player facing changes ☠️

🤷 might as well

**Review by morrowwolf — APPROVED** [review]
map

**Pull request merged**
