### PR TITLE
LV Nightmare + Corpsespawner Returnal

### PR DESCRIPTION
**Pull request by Geevies**
## About The Pull Request

Added a rad new nightmare insert to LV, also returns the corpsespawner as a gamemode proc rather than an objectives one.

## Why It's Good For The Game

Nightmare inserts are cool, and changes up the map every now and then. Corpsespawners are also cool, and gives the map some story flavour.

## Changelog

:cl:
add: Added a new nightmare insert to LV, brought back the corpsespawner system.
/:cl:

### CODE REVIEW

**Comment by MusselMain** [comment]
Nightmare inserts are epic and I'm looking forward to seeing them on all maps (maybe) eventually

**Comment by c4xmaniac** [comment]
Speed merge now

**Review by Nanu308 — APPROVED** [review]
Map lgtm

**Review by Shad0vvs — CHANGES_REQUESTED** [review]
Claymores are invisible now,
icon_state = "_active" instead of m20_active

**Review by Shad0vvs — APPROVED** [review]

**Pull request merged**
