### PR TITLE
Survivor Job Additions + Some Minor Fixes

### PR DESCRIPTION
**Pull request by BadAtThisGame302**
# About the pull request

The purpose of this Pull Request is adding more survivor jobs like Flight Control Operator, most colonies have a small office in their space port or near the administration area that has a bubble for an ATC Officer or Operator, so as Cooliecan said on https://forum.cm-ss13.com/t/spitballing-ideas-for-new-survivor-jobs-on-all-colonies-maps/5136/2 which I agree with, could be fun to LARP as an ATC since an area for that character does exist.

# Explain why it's good for the game

Increases diversity for survivor jobs, could add more RP opportunities, plus like the Soro CL PR, LV has no special Liaison job like Solaris so I thought why not, it has a large corpo dome it deserves a unique Liaison IMO.  Now, about the Flight Control Operator, the name speaks for itself, most spaceports have a flight control bubble which are manned by Flight Control Operators/Officers, I gave him the trucker skills, though I thought about changing it to engineer stats. Didn't put him in any category he is like civilians a random for now (Don't think he fits in Engineer or Corporate category, or maybe he does?)

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl:
add: Added a LV-624 Corporate Liaison Survivor.
add: Added a Flight Control Operator Survivor to Solaris Ridge (for now, might be added to more maps soon!).
qol: made survivor.dm easier to use by moving the basic security surv with the engineer/scientist/doctor which it wierdly enough it wasn't with.
balance: rebalanced CL a lockable satchel.
fix: fixed the survivor.dm comments falsely saying that some surv types are not used anywhere when they are.
spellcheck: fixed the LV-624 announcement text, made it roll off the tongue easier.
code: changed CL and ICC survs shoes from centcom? To laceup.
/:cl:

### CODE REVIEW

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Review by Zonespace27 — APPROVED** [review]

**Pull request merged**
