### PR TITLE
Replaces xeno devouring with xeno hauling

### PR DESCRIPTION
**Pull request by moltoretardo**
# About the pull request
### **This change doesn't affect balance at all, the only things that change are the flavor texts and sounds around the mechanic**

This change the devouring action/regurgitate action into one that is more centered around the movie, which is hauling people around. it also get rid of useless vore centered comments in the codebase.

The mechanic remains the exact same: Drag marine, click on self to start the small timer, marine vanish and becomes non targetable. Some people came with alot of ideas that would make it even more immersive, like being able to use a sidearm while hauled, but I only focused on the fluff for now. I am aware that some might dislike the said text and I am willing to modify/upgrade whatever part that needs it, same goes for any sounds that were replaced.

It only applies to the transportation, xenomorph still regurgitate resin.
I also renamed some one letter variables.

# Explain why it's good for the game

The mechanic itself comes from an era in which SS13 didn't care much about the Alien lore, there're alot of vestiges in the old TG or BAY codebases that shows the code we are currently using (with some modifications) that date from prior CM. TG station decided to remove it for a while, since it was judged as out of place, only for someone to re-add it because it's "funny". Some part of it dated from 13 years ago. My point here is that it doesn't follow any of the universe's standards and that it was adopted here from an old SS13 gamemode.

The clip below shows a realistic way for them to carry people around.
https://user-images.githubusercontent.com/53326609/221436335-72217c31-4bc0-49a6-a01e-9a596b529c81.mp4

I've also replaced the old regurgitate icon with this **(with the incredible help of Kugamo)** :
drophaul

I believe that for CM to migrate into a slightly enhanced rp environment, some of the less immersive details that are shown must be changed. The media that have been shown makes the whole "eat to transport while keeping alive" quite unlikely, since most caste wouldn't be able to at all while others are literal acid bombs.
marineexample

There were alot of inconsistencies with the devouring.

- Why can't you ventcrawl while someone is ingested
- Why can you hear people that are ingested
- How come I can drop my gun outside while being inside
- Why are xeno forced to regurgitate after x seconds
- How am I not melted to death by the acid

Which are mostly due to balance, but are still all solved with the new descriptions as a marine would be heard, resisting, not melted, and a chore to drag in a vent with you. It also explains why you get stunned when released (from being slammed to the ground) and not stunned when you resist out, which was something unexplained. It also opens the door for adding custom hauling text to every caste, keeping an even better immersion. 

I understand that chestbursting is also an important mechanic hence why only the text changed. The only difference is that the noises you make aren't from a stomach. I really wanted to make it so that the xeno only fell into crit after being "resisted" from instead of gibbing but sadly that would touch balance so I'm keeping that for another PR. For now when you successfully slice a xeno to death, they will get the "scuffling" reason of death (instead of chestbursting) and will gib so that I'm not accused of killing the balance from the IO getting more xeno corpses. Chestbursting from larva unchanged.

Feel free to read all of the changed text and correct/propose better things if needed.

# New text examples

<details>
<summary>Screenshots & Videos</summary>

when you release someone
release

what people see when you release someone
forgor

when you haul someone
hauling

when you attack while held
attack

when you get blocked from hauling
stop hauling

dying from "chestburst"
scuffling

Some of the removed comments/text:
vored
gurgle

</details>

# Changelog

:cl: Molto
code: changed all of the devouring references into hauling references
refactor: changed one letter variables
imageadd: added a new release haul icon
/:cl:

### CODE REVIEW

**Review by Agameofscones — CHANGES_REQUESTED** [review]
the icon itself isn't great, and bears resemblance to too many others. I'd suggest a hand reaching out to pull an object, or a small icon of a human being dragged.

Right now the xeno staring at a U of pixels isn't very indicative of the ability and the function.

**Comment by moltoretardo** [comment]
> the icon itself isn't great, and bears resemblance to too many others. I'd suggest a hand reaching out to pull an object, or a small icon of a human being dragged.
> 
> Right now the xeno staring at a U of pixels isn't very indicative of the ability and the function.
> 
> good job on the rest of it though.

The icon represents a xeno dropping something (replacement of the regurgitate icon which was a xeno face) but I'll upgrade it so it's more indicative

**Comment by moltoretardo** [comment]
drophaul

Here is the new Icon with the gigantic help of Kugamo (I did 1% of the job and """borrowed""" his work...)

**Review by Zonespace27 — CHANGES_REQUESTED** [review]
If you're going to do this, make it go the full mile and actually visually "haul" the xeno (a la fireman carry) instead of just a name change

As of currently this looks lazy and potentially confusing to newbies

**Review by nauticall — APPROVED** [review]

**Comment by harryob** [comment]
lmk if you need any help with the above RQs

**Pull request closed without merging**
