### PR TITLE
Resprites - 2/2024 Edition

### PR DESCRIPTION
**Pull request by nauticall**
# About the pull request

Resprites various items in the game to be subjectively prettier and more up-to-date with modern standards. Among them are the following:
- First aid kits.
- Coffins.
- Material stacks.
- Mortar shells.
- Beakers, bottles and pill bottles (sprites ported and hue-shifted from Baystation/Aurora).

# Explain why it's good for the game
# Sprites
<details>
<summary>Sprites</summary>

image
image
image
image
image

</details>

# Changelog
:cl: nauticall
imageadd: Resprites first aid kits, coffins, material stacks, mortar shells, and chemistry items. Chemistry sprites ported from Baystation / Aurora.
fix: Recolors several reagent sprites to be more in-line with their established colors, such as on autoinjectors.
fix: Fixed invisible cloth tables.
fix: Fixed wrong shading on the large floodlight.
/:cl:

### CODE REVIEW

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Review by sleepynecrons — CHANGES_REQUESTED** [review]
everything looks great minus a few gripes

the values on the mortar shells are a little dull. i think they need a darker shade for an outline/accentuating the fins, and a sharper highlight to give it a more metallic look. the base palette also has a couple basically identical shades of grey

the groove on the lid (i have no idea what to call it 😭) of the coffins change position between closed and open versions. i do not know if that's intentional or not

**Review by sleepynecrons — APPROVED** [review]
sprites now approved

**Review by Drulikar — APPROVED** [review]
Code changes look fine. However a bit too many changes to verify so will TM a round or two to see if anyone notices anything wonky.

**Pull request merged**
