### PR TITLE
fixes bell going through walls

### PR DESCRIPTION
**Pull request by stanalbatross**
## About The Pull Request

bell will no longer trigger on enemies behind walls / blocked from seeing the bell by walls

## Why It's Good For The Game

inconsistency bug fix

## Changelog

:cl:
fix: the R1NG bell tower can no longer affect enemies through walls
/:cl:

### CODE REVIEW

**Comment by Segrain** [comment]
Questionable approach. So you do not want somebody to place a bell and then wall it off, fine. What if somebody places the bell in front of a wall and then takes that wall down? There will be no tripwires on that side, and the bell will not work at all.

**Comment by stanalbatross** [comment]
> Questionable approach. So you do not want somebody to place a bell and then wall it off, fine. What if somebody places the bell in front of a wall and then takes that wall down? There will be no tripwires on that side, and the bell will not work at all.

mmm, can't think of a good way to handle this other than doing the path check every time someone walks over a tripwire, and not qdeling the wires when walked over out of sight

**Comment by DylonBR** [comment]
bell F tier now. mini sentries are the new frontline meta

**Comment by Diegoflores31** [comment]
Tested on private server and it doesnt look as bad as it appears on paper. 👍

**Review by Shad0vvs — APPROVED** [review]

**Pull request merged**
