### PR TITLE
standardize numbers of slices you could make for snack items to six and refactor the code.

### PR DESCRIPTION
**Pull request by Huffie56**
## About The Pull Request

Remove a bunch of empty lines
Added/rework a block comment and fit all the comments about snack class that was there in it without deleting anything. Added/rework a block comment for the slice able snack. Added a block comment for pizza class
Put up a standard for all the slice able snack to have six slice being produce.
Remove some duplicate line.
Standardize bitesize to be =2 for pizza category.

## Why It's Good For The Game
Better code always good.

## Changelog

:cl:
refactor: Removed empty lines and change some annotation to fit current standard for it.
code: All the slice able snack items(cake cheese pizza) will now be cut in six instead of random number
refactor: Removed bitesize = 1lines in children object of snack since it's initiate at 1 already.
/:cl:

### CODE REVIEW

**Comment by fira** [comment]
Use `/*` as opener not `/**`, this is reserved for annotations

**Comment by Huffie56** [comment]
> Use `/*` as opener not `/**`, this is reserved for annotations

I tried to respect the examples in https://github.com/cmss13-devs/cmss13/blob/master/.github/guides/AUTODOC.mdfor making a block comment.
In it they open block comment by `/**` and close them with `*/` and they have a `*` on each line between.
I am confuse now did i miss something maybe i am on an old version of the document?

**Comment by harryob** [comment]
> > Use `/*` as opener not `/**`, this is reserved for annotations
> 
> 
> 
> I tried to respect the examples in https://github.com/cmss13-devs/cmss13/blob/master/.github/guides/AUTODOC.mdfor making a block comment.
> 
> In it they open block comment by `/**` and close them with `*/` and they have a `*` on each line between.
> 
> I am confuse now did i miss something maybe i am on an old version of the document?

if you want to make autodoc annotations, you have to be pretty exact in your comment structure. 

if you're not making autodoc annotations, just use /*

autodoc annotations show up on https://cmss13-devs.github.io/cmss13/ as our actual code documentation

**Comment by Huffie56** [comment]
> if you want to make autodoc annotations, you have to be pretty exact in your comment structure.
> 
> if you're not making autodoc annotations, just use /*
> 
> autodoc annotations show up on https://cmss13-devs.github.io/cmss13/ as our actual code documentation
thanks  will look into it and will modify like suggested.

**Comment by Huffie56** [comment]
I made huge mistake renamed my branch .... will try to fix it....

**Comment by Huffie56** [comment]
i think it's enough for a first batch of modification...

**Comment by harryob** [comment]
updated your PR title here too - do make sure they're descriptive

**Review by fira — APPROVED** [review]
looks fine by me

**Comment by Huffie56** [comment]
my third PR merge NICEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

**Pull request merged**
