### PR TITLE
just a little Vamp QoL

### PR DESCRIPTION
**Pull request by Diegoflores31**
# About the pull request

Adds Aim assist to Tail jab.

# Explain why it's good for the game
Sprite clicking can be a little hard to land taking into consideration the current marine speed and as this is the main vamp weapon i gave it a little help in that matter .

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl:
balance: Tail stab now provides aim assist ( you dont have to sprite click)
/:cl:

### CODE REVIEW

**Comment by Segrain** [comment]
This is no QoL. This is essentially a revert of #2909 and is a pure balance change.
As an occasional vampire player, I might have an opinion on whether such change is needed, but nobody asked mine.

**Comment by Diegoflores31** [comment]
> This is no QoL. This is essentially a revert of #2909 and is a pure balance change. As an occasional vampire player, I might have an opinion on whether such change is needed, but nobody asked mine.

incorrect . #2909 had special effects for sprite clicking(x1.5 damage) and more stuff including a 2 tile red line similar to ravager scissor cut. 
this is not a revert at all of that PR. just an aim assist as stated

**Comment by Zonespace27** [comment]
aim assist is in no uncertain terms a balance change

**Comment by thwompa** [comment]
image

**Comment by morrowwolf** [comment]
No thanks!

**Pull request closed without merging**
