### PR TITLE
Adds M2C and M56D Ammo to ASRS

### PR DESCRIPTION
**Pull request by IsProbablyCatto**
## About The Pull Request

Adds M2C and M56D ammo to ASRS

## Why It's Good For The Game

Increased use of both mounted turrets, with few/no way to refill once req has ran out. Should help to facilitate req's spending problems with HC's funding.

## Changelog

:cl:
balance: Added M2C and M56D Ammo to ASRS.
/:cl:

### CODE REVIEW

**Comment by IsProbablyCatto** [comment]
Broke things GitKraken side, should be fixed now. My bad about the close and reopen

**Comment by stanalbatross** [comment]
Solely promotes further use of these choke spam weapons which should be limited by their limited ammo, which is why it was never added to asrs in the first place. This goes against the design of both weapons. Strongly against, DNM will be added for further discussion with the dev team.

**Comment by optimisticdude** [comment]
ammo management and effective push commitments are written into the m2c's limited ammo design

source: i am the m2c dev

**Comment by IsProbablyCatto** [comment]
Yeah, was asked to add it and saw M56D wasnt in there too. Probably should have stopped there but thought why not PR to see if it gets denied.

**Comment by Nanu308** [comment]
No, weapons do require an investment to a degree, getting the ammo for free without any effort lets people spam/use those weapons even more freely.

**Pull request closed without merging**
