### PR TITLE
Replace amour to armor in the code because we use USA EN not  UK EN

### PR DESCRIPTION
**Pull request by Huffie56**
# About the pull request
Replace amour to armor in the code because we use USA EN not  UK EN
some map will require change to but i want to keep this PR a small as possible to avoid merge conflicts...

# Explain why it's good for the game
because code consistency is good
# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl:

code: Replace amour to armor in the code because we use USA EN not  UK EN

/:cl:

### CODE REVIEW

**Comment by harryob** [comment]
>  we use USA EN not UK EN

according to what? https://github.com/cmss13-devs/cmss13/blob/master/.github/guides/STYLES.md#things-that-do-not-matter our styleguide literally puts this under "things that do not matter"

**Comment by Huffie56** [comment]
> > we use USA EN not UK EN
> 
> according to what? https://github.com/cmss13-devs/cmss13/blob/master/.github/guides/STYLES.md#things-that-do-not-matter our styleguide literally puts this under "things that do not matter"

i have saw the guideline but i don't think it's a good idea to have a word using their UK and USA version all around the code.
having it unify to UK or USA will allow coder to easier understand the code...

**Comment by Git-Nivrak** [comment]
The only thing this will do is create annoying merge conflicts

**Comment by Huffie56** [comment]
> > we use USA EN not UK EN
> 
> according to what? https://github.com/cmss13-devs/cmss13/blob/master/.github/guides/STYLES.md#things-that-do-not-matter our styleguide literally puts this under "things that do not matter"

**Pull request closed without merging**
