### PR TITLE
Attackby refactor to enforce parent proc calls

### PR DESCRIPTION
**Pull request by boskoramen**
Needed to make a few changes in order for attackby flow to be more manageable. 

There were more changes I wanted to do (such as datumizing construction states and extracting a lot of attackby functionality to components/elements) but will just do that in a separate CR since base functionality is still mostly comprehensible.

Not entirely sure if I was able to cover every single attackby call, there are over 400 files that needed to be modified and logic was varied across the board. Used mostly regex search and vim macros to cover everything, very fun 😭 
# About the pull request

# Explain why it's good for the game

Shifting our code from having a bunch of inconsistent overrides and control flows to enforcing that signals are sent at base type procs will make refactoring the code to making more use of DCS a lot simpler.
# Testing Photographs and Procedure
Given the scope of this change, I don't think it is possible to test every test case by myself on my test server.

Made sure basic things worked:
- Storing things in backpacks
- Opening airlocks with items in your hand
- Adding attachments
- Reloading weapons
- Adding attachments
- Deconstructing some machines
- Hugging marines with huggers
- Building and deconstructing barricades
- Handling tables and racks
- Putting beakers in chem machines
This is not comprehensive of what was tested but again, cannot really foresee any oversights needs to be TM'd.

# Changelog
:cl: TheDonkified
fix: Fixed runtime when cryoing human-subtyped mobs without jobs such as monkeys and farwa
fix: Fixed issue with supplymarker landmarks not working properly when spawned
refactor: Refactored attackby to enforce parent proccalls (specifically so registered signals are always called)
refactor: Added ignitable element, setup for cigarettes, pipes, cigars, and candles at the moment
refactor: Added igniting element, setup for things that can light cigarettes, pipes, cigars, and candles such as flamers, lighters, etc
refactor: Added writable writing elements, setup for body bags, paper, beakers, airlock assemblies, and other items that interact with pens (and crayons)
refactor: Added writing elements, setup for pens and crayons
/:cl:

### CODE REVIEW

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by boskoramen** [comment]
going to try atomizing parts of this PR

**Pull request closed without merging**
