### PR TITLE
repaths /obj/screen to /atom/movable/screen

### PR DESCRIPTION
**Pull request by stanalbatross**
## About The Pull Request

a port in spirit of https://github.com/tgstation/tgstation/pull/54403

plus ports the screen map obj thingy as it's needed for the new paths

NEEDS TESTING ON LIVE

## Why It's Good For The Game

supposedly reduces memory usage or something? also I want it for another thing I will port from tg in the future

## Changelog

:cl:
refactor: repathed /obj/screen to /atom/movable/screen
/:cl:

### CODE REVIEW

**Review by morrowwolf — APPROVED** [review]
Code LGTM, ready to test

**Comment by morrowwolf** [comment]
Faded health and symbols: https://gyazo.com/4c22407f9775cbe66fc4109f37d4a80b

**Comment by stanalbatross** [comment]
> Faded health and symbols: https://gyazo.com/4c22407f9775cbe66fc4109f37d4a80b

will fix

**Review by morrowwolf — APPROVED** [review]
Code LGTM

**Pull request merged**
