### PR TITLE
New Icon: Red Skull for players dead from Hardcore trait/mode

### PR DESCRIPTION
**Pull request by blackdragonTOW**
# About the pull request

Adds a red skull to differentiate between HC death and normal perma.

# Explain why it's good for the game

Medhud and OOC observers can tell very quickly when they watch someone die if they were HC or not.  This adds a bit of cool factor to things, and removes ambiguity for those who have that info immediately on hand anyway.

# Testing Photographs and Procedure
Verified both with hardcore trait and gamemode enabled.  Xenos also should still only see the white skull and will not get extra info.
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
ui: Hardcore deaths are now marked with a unique red skull
imageadd: Red skull added for hardcore deaths
/:cl:

### CODE REVIEW

**Comment by blackdragonTOW** [comment]
Evidently that sprite sheet had a dupe on it that got in before we had a dupe check linter

**Review by FransFeiffer — APPROVED** [review]
Sprite fine, sprite aproved

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Review by morrowwolf — APPROVED** [review]

**Pull request merged**
