### PR TITLE
Beta queen to Bravo queen

### PR DESCRIPTION
**Pull request by TopHatPenguin**
# About the pull request

Extremely minor changes:
Beta Queen to Bravo Queen
Gamma Larva and Queen to Charlie Larva and Queen
Decapitlises typepaths in larva.dm and queen.dm

# Explain why it's good for the game

QOL

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>
Tested

</details>

# Changelog

:cl:
spellcheck: Changes beta queen to bravo queen and gamma to charlie | Decapitlises typepaths in larva.dm and queen.dm
/:cl:

### CODE REVIEW

**Comment by ThePiachu** [comment]
Squads follow the phonetic alphabet since they are military. Xenos would probably be classified under more scientific terms, so them following a greek alphabet does fit.

**Comment by harryob** [comment]
> Squads follow the phonetic alphabet since they are military. Xenos would probably be classified under more scientific terms, so them following a greek alphabet does fit.

i agree, but this is just for consistency - spawning in a `/mob/living/carbon/xenomorph/queen/Gamma` will currently make a charlie queen regardless, same with /Beta and making a bravo queen, as this is based on the hive number anyway

**Comment by realforest2001** [comment]
Could you decapitalise the hive subtypes?

**Comment by TopHatPenguin** [comment]
> Could you decapitalise the hive subtypes?

Yup! should be all good now.

**Review by harryob — APPROVED** [review]

**Pull request merged**
