### PR TITLE
Stompers

### PR DESCRIPTION
**Pull request by Blundir**
# About the pull request

Adds a pair of shoes that were featured on Ripley in Aliens

dreamseeker_89YO3FNp5U

dreamseeker_8HjbD0Qysm

<details>

image

</details>

As well as a box for them similar to the one they were shipped in one of the editions

dreamseeker_u4qW0CtxYF

<details>

image

</details>

Added box with these shoes on Solaris Ridge, Kutjevo Refinery and New Varadero

Also added a civillian survivor preset loosely resembling Ripley in second half of Aliens

dreamseeker_tWIOn5VjTi

<details>

image

</details>

Some inspiration was taken from these https://github.com/cmss13-devs/cmss13/pull/609 https://github.com/cmss13-devs/cmss13/pull/2727 but no sprites were taken from there, sprites in this pr are original.

Comparison of sprites from mentioned prs and this pr:

<details>

aseprite_XKIx44TGfx

</details>

All sprites made by me, with some bits of help from Crowfiord, discord tag sir.crow.

# Explain why it's good for the game

More lore friendly props - good.

# Changelog
:cl:
add: Stompers boots and box for them
add: new civillian survivor preset resembling Ripley
maptweak: stomper boots box on New Varadero, Solaris Ridge, Kutjevo Refinery
/:cl:

### CODE REVIEW

**Comment by thevandie** [comment]
YOOOO HE GOT THE DRIPP

**Comment by vero5123** [comment]
you are amazing.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Review by harryob — APPROVED** [review]

**Pull request merged**
