### PR TITLE
Adds external webbing vest to the IO's vendor as an alternative to the service jacket

### PR DESCRIPTION
**Pull request by kirieee**
# About the pull request

Adds an external webbing vest to the IO vendors. 

# Explain why it's good for the game

I think that the service jacket looks a little goofy for going into a combat zone, but I want to keep the utility and speed it provides. The external webbing has the same stats, it's just a different (and, in my opinion, better) look than wearing a service jacket into battle. 

# Testing Photographs and Procedure
Here's some pictures of the onmob and regular sprite: 
image
image

Opened game. Webbing was in the vendor. :3

# Changelog

:cl:
add: External webbing vest added to IO vendors
/:cl:

### CODE REVIEW

**Comment by fira** [comment]
But the webbing has no protection while the jacket does - or am I missing something here

**Comment by kirieee** [comment]
I've just checked. The webbing vest has no protection at all, however the service jacket has LOW protection in melee and bullet. I was under the assumption the stats were the same, but I still don't think that this is much of a problem. I'm somewhat inexperienced when it comes to balance so I might be wrong

**Comment by Steelpoint** [comment]
The asthetics of external webbing do look far more appealing than the service jacket, but the loss of armour will be a blow and make IOs even more vulnerable to damage if they take this instead of a jacket.

I did toy with the idea of adding a custom-custom external webbing that basically functioned identically to a service jacket but with the external webbing sprites as noted here: https://github.com/cmss13-devs/cmss13/pull/4341

I mostly closed it due to feeling mixed about adding another armour option but if this idea is warranted you could consider something like I did

**Comment by kirieee** [comment]
I think I'll try editing the external webbing and putting a custom version in, then, just to fully smooth things over. I'm not entirely sure how to make a whole new clothing item like that but I'll figure it out, hopefully with some help

**Comment by Steelpoint** [comment]
> I think I'll try editing the external webbing and putting a custom version in, then, just to fully smooth things over. I'm not entirely sure how to make a whole new clothing item like that but I'll figure it out, hopefully with some help

You can look over how I did it, the PR itself was fine I just ran into unrelated merge conflicts and a disinterest to finish the PR.

**Comment by Huffie56** [comment]
if your item isn't OP i would suggest you to add it to the clothing surplus vendor instead of just IO vendor...

**Comment by kirieee** [comment]
Adding it to the clothing vendors would essentially be the same as adding a service jacket to the vendors, too. I'm not opposed! But I think that some maintainers would be?

**Comment by Huffie56** [comment]
> Adding it to the clothing vendors would essentially be the same as adding a service jacket to the vendors, too. I'm not opposed! But I think that some maintainers would be?

as long as it's not OP and in small number i don't see a reason to not add them but yes maintainer have to approve it.
maybe just ask them on discord in dev channel?

**Pull request closed without merging**
