### PR TITLE
smartpistol auto-aim lock on ability

### PR DESCRIPTION
**Pull request by stanalbatross**
## About The Pull Request

Adds an ability for the smartpistol to "lock on" to a target, much like the sniper spec's ability. Once it is finished locking, it will produce a "stable" lock and all bullets fired from the gun will home into the target.

The lock is dropped when the weapon is unwielded, if the target goes over 7 tiles away, or after 15 seconds.

This PR is a copy of #220 , which I had to remake due to github not letting me reopen force pushed PRs. The PR was ready for review when it was auto-closed due to stale.

## Why It's Good For The Game

Smartpistol is underpowered right now, it does little damage and its utility is lowered by how inaccurate it can be. This should help to rectify that.

PLUS it's super cool.

## Changelog

:cl:
add: Added a new ability for the smart pistol - auto-aim. You can use it to lock onto a target and make your bullets automatically fire at it and home in at it while locked, after a short delay to lock onto the target. It can only be used while wielded.
add: the lock will drop on the pistol being unwielded, the target moving over 7 tiles away, or after 15 seconds. 
/:cl:

### CODE REVIEW

**Comment by tempelers** [comment]
This is a good change. Maybe more SGers will choose the pistol belt now.

**Comment by thwompa** [comment]
update actions.dmi and sprites are good

**Review by Shad0vvs — CHANGES_REQUESTED** [review]
Awaiting multiple target issue fix.

**Comment by stanalbatross** [comment]
>  Awaiting multiple target issue fix.

fixes

**Review by Shad0vvs — CHANGES_REQUESTED** [review]
Targeting humans from not your faction makes them appear nude and such...

**Comment by stanalbatross** [comment]
> Targeting humans from not your faction makes them appear nude and such...

fixed

**Comment by Shad0vvs** [comment]
broke again

**Comment by stanalbatross** [comment]
some issue with the overlay not removing on break_iff_locking

will fix

**Review by Shad0vvs — CHANGES_REQUESTED** [review]
Still getting stuck on mobs.

**Comment by Wintermote** [comment]
This is how I always thought the smartpistol should work. GREAT change.

Not sure how it is damage wise, I know presently the smartpistol is pretty weak and ineffective, but with the bullets always (?) hitting on lock it may now be an actual viable firearm.

My only requests would be aesthetic:
Bullets zip and fly around along arcs instead of a straight line
New sprite for the smartpistol because I think the current one is total ass

**Comment by stanalbatross** [comment]
I KNOW how to get this done and I WILL do it but not today

**Comment by AntoineXYZ** [comment]
Hell yeah, can you consider adding this to SL kit, following Geeves idea to give them a cool gun? (instead of the MkI)

**Comment by stanalbatross** [comment]
nvm I can't make this work

**Pull request closed without merging**
