### PR TITLE
Biolock & Tristan Donor Gear

### PR DESCRIPTION
**Pull request by Warfan1815**
# About the pull request

A change to Biolock's donor gear (credit to Thwomper for the sprite)
&
A change to Tristan's donor gear

Changes to legacy donor gear is allowed (to the best of my knowledge)

PR made on behalf of Biolock & Tristan.

# Explain why it's good for the game

Donor gear is good

# Testing Photographs and Procedure

https://cdn.discordapp.com/attachments/1144067901343666216/1144090409501474916/image.png

</details>

# Changelog

:cl:
add: Changes donor Biolock's medium medic armour to a light custom paintjob armour and donor Tristan's reactive scientist armour to a custom marine armour

### CODE REVIEW

**Comment by Biolock1** [comment]
What an absolute king. I had both Forest and Frozen give this change the okay ^-^

**Review by Drulikar — CHANGES_REQUESTED** [review]
See Files changes tab for annotations of the errors, but its basically, you forgot to edit the dmi here: 
image

**Comment by Warfan1815** [comment]
Fixed.

**Review by Drulikar — APPROVED** [review]
Code changes look fine.

**Comment by Tristan63** [comment]
Warfan is a god, big dubs!

**Review by sleepynecrons — CHANGES_REQUESTED** [review]
the shading on biolock's armor is fine, but the highlights on tristan's gear need some minor work with the darker color scheme.
made an example of what it should be closer to
image
if you'd rather just use my edit you can copy these images below into whatever software you're using to sprite
image
image




also, for biolock's helmet - "There is a built-in camera on the right side." but that isn't represented on the current sprite what's up with that. would be cool to see and make it more unique than a simple recolor

**Comment by Warfan1815** [comment]
@sleepynecrons fixed

**Review by sleepynecrons — APPROVED** [review]
sprites look fine now. approved

**Pull request merged**
