### PR TITLE
USCM Chestrig

### PR DESCRIPTION
**Pull request by Steelpoint**
# About the pull request

Adds a resprite of the USCM Welder-Chestrig in the form of the USCM chestrig. An alternative to a standard satchel, same carry capacity. 

# Explain why it's good for the game

Alternative ways for players to customize their apperance, I also feel a chestrig feels more thematic/in universe than a satchel. In terms of balance, this has no change since the chestrig has the same inventory size as a normal satchel.

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Screenshot 2024-02-01 14 37 08

Top: Armour, No Chestrig
Middle: Armour, Wearing Chestrig
Bottom: No Clothing, Wearing Chestrig

68747470733a2f2f696462322e616666656374656461726330372e636f2e756b2f696d616765732f32363339313036312f353632302f31383138333932393938363438303035393532372e706e67
68747470733a2f2f696462322e616666656374656461726330372e636f2e756b2f696d616765732f32363339313036312f353632302f363538303434393939383737383935313333352e706e67

</details>

# Changelog
:cl:
add: USCM Chestrig has been added to squad prep vendors, alternative sprite of a satchel, similar in appearance to the welder-chestrig.
/:cl:

### CODE REVIEW

**Comment by Steelpoint** [comment]
I am using the exact same sprites used elsewhere except removing the fuel tanks. I could alter the colour but from my brief examination the colours used are identical to pretty much every other similar chest rig sprite we use for marines.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Review by nauticall — APPROVED** [review]

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Review by Drulikar — APPROVED** [review]

**Pull request merged**
