### PR TITLE
Zone de commandement général - 2 - Mapping CIC Rework / Part 2

### PR DESCRIPTION
**Pull request by LC4492**
# About the pull request

This PR is focused on updating and modifying the Bridge and any command rooms around it (Such as the XO's/CO's Quarters, Synthetic Storage, etc), with the purpose of giving the place a refreshment and, of course, an improvement on efficiency. Feel free to analyse the photos below and to tinker with the map files. PS: This is an updated re-post of the last PR, carrying now a more utilitarian design, with a smaller bubble compartment and closer Overwatch computers. All changes requested on the last PR have been added here, including a new hall between the conference room and...Jones bed.

# Explain why it's good for the game

Analyse the map changes and say if its an improvement or not.

# Testing Photographs and Procedure

Captura de Tela (445)

image

image

# Changelog

:cl:
add: Added a little more munitions for the MK1 lockers (2 more normal mags per locker) and some extra boxes of buckshot/slugs to the MK221s lockers. Added a red-alert closet on the MP Checkpoint, of which holds a M39 sub-machinegun.
maptweak: Changed the Almayer's Bridge and the rooms surrounding it, such as the PO's, SO's, XO's and CO's quarters and others, with the help of Wulferion, thank you.
/:cl:

### CODE REVIEW

**Comment by kooarbiter** [comment]
The Staff officer consoles are perfectly fine as they already are, it feels like the bridge officers from the first level of halo 1, and seperating the consoles this far away makes it a pain in the ass for officers who almost always have to manage more than one squad. Currently Staff officers can stand between two squad consoles and acess them both from the same spot but they wouldnt be able to with this change

**Comment by LC4492** [comment]
> The Staff officer consoles are perfectly fine as they already are, it feels like the bridge officers from the first level of halo 1, and seperating the consoles this far away makes it a pain in the ass for officers who almost always have to manage more than one squad. Currently Staff officers can stand between two squad consoles and acess them both from the same spot but they wouldnt be able to with this change

That issue have been alliviated as best as possible, but sadly no improvements will be able to be made to anything if the OW consoles are the only problem you can see

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Review by morrowwolf — CHANGES_REQUESTED** [review]
image

CIC hallway areas should really not be split like this unless separate areas (and they're not really large enough for two areas). Maybe make the reception have the APC in it.

Otherwise I'm gonna TM this and see how people feel.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by Yellows91** [comment]
Its good but the SOs OW is too tight.

1x1 will have you run into the SO or have to go around (as XO/CO this is time critical that you cannot afford to go around)
2x2 will be better if possible

**Comment by LC4492** [comment]
> Its good but the SOs OW is too tight.
> 
> 1x1 will have you run into the SO or have to go around (as XO/CO this is time critical that you cannot afford to go around) 2x2 will be better if possible

I've given the bubble three exits, two of which allow for you to enter and exit without going around the SOs and/or running into them. Making the area *bigger* is still in prototype.

**Comment by drinkmorewater77** [comment]
These edits deleted/remove the ASO spawn. Before they would wake up with the rest of CIC, now they wake up with general crew/privates.

**Comment by LC4492** [comment]
> These edits deleted/remove the ASO spawn. Before they would wake up with the rest of CIC, now they wake up with general crew/privates.

Yes, the cryo room didn't had enough space for the ASO, so its still pending to select on where he will be sitting next.

**Comment by Zonespace27** [comment]
Thank you for the effort you've put into this PR, but it will be closed.

There are some good ideas here, but there's a lot of things that I and other maintainers disagree with on a conceptual level. In the future, please atomize your PRs more than this (this touches a hell of a lot more than CIC) so that some changes can get in.

Ultimately, I don't think this is much of an improvement over the old CIC, and if it's not broken, then there's nothing to fix.

**Pull request closed without merging**
