### PR TITLE
adds fireman carry to IOs

### PR DESCRIPTION
**Pull request by irakligabunia**
# About the pull request

gives IOs the ability to fireman carry

# Explain why it's good for the game

promotes IOs not being "lone wolves", carrying corpses for intel, their deceased/injured comrades to medical/safety and etcetra
SOs, SLs and most roles which are limited and such caliber already get this, and i do not think it will impact balance to a point where it'll get discussed :)

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl: stalkerino
balance: gave IOs ability to fireman carry
/:cl:

### CODE REVIEW

**Comment by Cthulhu80** [comment]
**balance: rebalanced something**
Don't do that, explicitly state what you're changing.

**Comment by irakligabunia** [comment]
i forgor to change it ;3

**Comment by Cthulhu80** [comment]
fix the linter error, 
Screen Shot 2023-10-11 at 3 45 16 PM

**Comment by fira** [comment]
Huh what???

**Comment by joookschad** [comment]
use a roller bed

**Comment by Zonespace27** [comment]
Thank you for the PR, but unfortunately this will be closed. My reasoning for such is that all existing roles w/ fireman carry are ones who command other marines (SL, SO, XO, dept heads, bar synth), and the IO role does not fit this. As it stands, I don't see the need to expand who gets fireman carry beyond the direct marine commanders. Furthermore, they are very capable of getting a roller bed and performing body recovery in a very similar yet more vulnerable manner.

**Pull request closed without merging**
