### PR TITLE
Removes *most* Privates (ME1) from the Enlisted Force

### PR DESCRIPTION
**Pull request by efzapa**
# About the pull request

I could be entirely wrong and feel free to correct me if Aliens CM lore says otherwise, but to my knowledge, an E1 in the Military, atleast in the Marines is usually exclusively used for those in Basic Training. This would be, unless I am wrong, a weird implication of the Colonial Marine Corps pulling Marines onto the front-lines without full training.

This PR basically bumps up any Marine that *was* a Private (with exception of Rifleman), up one Paygrade, so OTs, MTs, and MSTs can now be Corporals. Riflemen are still Privates as their total training can feasibly be short enough that they can be deployed before meeting their 6 month promotion period to PFC.

# Explain why it's good for the game

Immersion is good, seeing Marines that technically don't even have a rank patch is weird.

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl:
qol: All Marine Private roles/time milestones on the ship are now promoted up one paygrade with the exception of Rifleman.
/:cl:

### CODE REVIEW

**Comment by Detective-Google** [comment]
privates pretty much only exist for people who ARE still in training because they're new. almost all jobs stop being privates at their first service medal.

**Comment by spartanbobby** [comment]
https://avp.fandom.com/wiki/Trevor_Wierzbowski

**Comment by skycrafterf** [comment]
Basically EVERY branch ONLY has the first enlisted rank strictly for those still in basic training, Upon graduating from boot camp or similar they receive a promotion to E2. So this would be correct.

**Comment by Korey45** [comment]
As SEA, I see literally no point in this. I train a lot of people, and I feel like it'd be weird if I were training a PFC, like he didn't even know how to load his own rifle or put on his uniform. E1 is purely a training signifier that tells you that this person might need some help with the game and is kind of why they are an E1. 

Also, there's like a shit ton of E1s that are in combat in the book and movies.

**Comment by efzapa** [comment]
ok so i looked it up

Being a deployed Private would assume you did not get promoted right out of Boot Camp AND completed any Tech School you had to do AND got deployed within 3 months, since the PFC Promotion period is 6 months Active Service (Training is included in this)

this in mind i will revert Riflemen back to their prior ranks as it is more likely they would make that gap

**Comment by DexterDude** [comment]
aliens lore is different. half of the marines deployed in the movie were privates in rank. 

not only that, but it doesnt add anything to the game that mechanically benefits it.

**Comment by efzapa** [comment]
> aliens lore is different. half of the marines deployed in the movie were privates in rank.
> 
> not only that, but it doesnt add anything to the game that mechanically benefits it.

#7299 did not mechanically change anything and it was one of the best received PRs

mechanical additions and PR quality are not mutually inclusive

**Comment by efzapa** [comment]
I would also like to point out that MT and CT both have the same timelocks (1 Hour as Squad Role)

ComTech is PFC from the rip, and MT as it stands is a PVT.

OT also arguably has an even stronger case as you need an hour in any *Engineering* Role just to unlock it.

**Comment by efzapa** [comment]
> How is this "qol"?

honestly didn't know what other tag to put, its not really an addition nor removal, nor fix so *shrug

**Comment by Wintermote** [comment]
The E1 rank lets you immediately tell which players are completely new and need help. It doesn't need to be accurate, it serves a very useful function in gameplay. I'm pointing out new people for the SEA to help almost every other round, and I know they're new because I can see their rank is ME1.

Take that away is a net detriment, it doesn't benefit anything.

**Comment by efzapa** [comment]
> The E1 rank lets you immediately tell which players are completely new and need help. It doesn't need to be accurate, it serves a very useful function in gameplay. I'm pointing out new people for the SEA to help almost every other round, and I know they're new because I can see their rank is ME1.
> 
> Take that away is a net detriment, it doesn't benefit anything.

Except it's not particularly accurate.

read my above comment about how Nurse has Corporal from the rip and Comtech has PFC (Despite CT and MT having the same timelock, and OT having an even larger timelock)

If we are using ranks purely as a basis to judge people on experience, why are we not already demoting Nurse all the way to E1?

**Comment by ihatethisengine** [comment]
> It's ALSO not accurate in the sense that hours do not transfer from any other roles to the E1 ones, so you can be a plat CT with 250 hours, but if you play MT, you are labeled as "brand new" by the game

CT and MT have different responsibilities and even skills. So it makes sense to show that MT is brand new, since you can't build, for example, consoles as a CT but can and often need as an MT.

**Comment by harryob** [comment]
i don't believe this really provides anything. as mentioned, plenty of pvts in the source media and it is a useful in game signifier of experience in a role

**Pull request closed without merging**
