### PR TITLE
Attachment nerfs and removals

### PR DESCRIPTION
**Pull request by morrowwolf**
# About the pull request

This PR:

Removes the barrel charger from vendors

Removes all benefits other than wield delay mod from the angled grip

Adds wield delay to the extended barrel

# Explain why it's good for the game

Barrel charger is a straight damage increase and rather silly to work around given how burst works bypassing real fire rate concerns. If you know, you know. Horrible idea, I am amazed it's been around this long.

Angled grip had zero downside. Now it still has zero downside but isn't also a ton of accuracy buffs on top of the god-tier lower wield delay.

Extended barrel had zero downside. Now it has a downside.

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl: Morrow
balance: Removed the barrel charger from vendors
balance: Removed all benefits other than wield delay mod from the angled grip
balance: Added wield delay to extended barrel
/:cl:

### CODE REVIEW

**Comment by Diegoflores31** [comment]
It would be interesting too keep it as a Req buy only

**Comment by Nanu308** [comment]
approved, more changes coming as well. At worst we'll re-review this after merge.

**Review by BeagleGaming1 — APPROVED** [review]
Code seems good

**Comment by Huffie56** [comment]
did you intend to remove all BC even as loot on ground-site map?
because their is one left and random attachment spawn-er can spawn them....

**Pull request merged**
