### PR TITLE
Synth Headset Tracking

### PR DESCRIPTION
**Pull request by Geevies**
## About The Pull Request

Allows synths to select which SL they want to track, as well as COs, XOs, and LZs. It also tweaks some of the backend tracking code to make it easier to set up tracking. Also allows people to find squad singletons by their type.

## Why It's Good For The Game

It lets synths track people, pretty handy for synths.

## Changelog

:cl:
add: Synth headsets can now track COs, XOs, LZs, and each type of SL.
add: Synth headsets now have unique sprites.
/:cl:

### CODE REVIEW

**Review by Agameofscones — COMMENTED** [review]
https://github.com/cmss13-devs/cmss13/pull/37 Should be merged first, since you can just rebase and re-add your icons using the rebase dmi.

**Review by FransFeiffer — APPROVED** [review]
Sprites LGTM

**Review by stanalbatross — CHANGES_REQUESTED** [review]
when spawning in a synth via create-humans, their headset hud does not start on, and you have to take your earpiece off and on again to fix it.

Additionally, when select-equipmenting someone with a squad into an equipped version of their role, they just get an echo headset.

**Comment by Geevies** [comment]
> when spawning in a synth via create-humans, their headset hud does not start on, and you have to take your earpiece off and on again to fix it.
> 
> Additionally, when select-equipmenting someone with a squad into an equipped version of their role, they just get an echo headset.

fixed the first, the second should be dealt with when slimming down the USCM roles since my set squad thing fixed the need to have echo roles.

**Review by stanalbatross — APPROVED** [review]

**Pull request merged**
