### PR TITLE
Ice Classic December 2024 Testmerge

### PR DESCRIPTION
**Pull request by BeagleGaming1**
something something december testmerge only

Putting up now to test checks and hopefully get reviewed to make sure i didnt break something too much

### CODE REVIEW

**Comment by wgtjunior743** [comment]
Ice is nice..

**Comment by IroquoisLou** [comment]
Not Ice V2, instant downvote.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
Conflicts have been resolved. A maintainer will review the pull request shortly.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Comment by cm13-github** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Pull request closed without merging**
