### PR TITLE
Reduces the Burst timer from 10 minutes to 7.5 minutes

### PR DESCRIPTION
**Pull request by Diegoflores31**
# About the pull request

Reduces the Burst timer from 10 minutes to 7.5 minutes

# Explain why it's good for the game
Being Hugged is something that should be a life threat situation . currently you can see most of marines getting hugged and not even going back into the almayer because of the extremely long time they have to get back , combined with stasis bag being hugged is as most a minor anoyance for marines instead of a game ending threat. 

PD Future implementation : a medicine made by chemistry that makes larva go on stasis winout needing the bag. ( like super peri)

NOTE : this also affects HIVE burst timer . reducing it to 5 minutes from 6.6 minutes but it can be reverted if it proves to be too quick.

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl:
balance: reduced Larva Burst time from 10 minutes to 7.5 minutes
refactor: changed 1 letter vars.
/:cl:

### CODE REVIEW

**Review by morrowwolf — COMMENTED** [review]
People are not nearly scared enough about being hugged. One day I'll get to throwing stasis bag out and making it seriously terrifying.

**Comment by ihatethisengine** [comment]
I am not sure if shorter timer is a right way to make being hugged more scary. IMO a better way is to add some debuffs on infection (expect stage 1) to discourage hugged frontlining instead.

**Comment by Diegoflores31** [comment]
> I am not sure if shorter timer is a right way to make being hugged more scary. IMO a better way is to add some debuffs on infection (expect stage 1) to discourage hugged frontlining instead.

It can be adjusted further depending of how it goes ingame. The point is making being hugged a big deal instead of just shake shake and keep fragging .

**Comment by Drulikar** [comment]
I'd argue some marines are actually encouraged to continue fighting when hugged because then they are immune to huggers. This is probably one of several aspects that ought to change. Merely making the huggers still leap at hugged targets to stun them will then make nesting caps really awkward; so the only thing that comes to mind is maybe a signal on ranged attack & melee attack that makes them a valid target.

**Comment by ihatethisengine** [comment]
Maybe make hugged marines extra vulnerable to tackling?

**Comment by Diegoflores31** [comment]
Harry you need to leave the funny titles

**Comment by harryob** [comment]
> Harry you need to leave the funny titles

the pr titles is the bit that's left in the final commit to master, which we can keep if github nukes us off the planet, same with the pr description. it's better this way my friend

**Review by harryob — APPROVED** [review]

**Comment by cm13live** [comment]
This pull request has been mentioned on **CM-SS13**. Please provide feedback here:

https://forum.cm-ss13.com/t/make-being-facehugged-infected-terrifying/3016/5

**Comment by Weuyn** [comment]
level 2 anti parasitic already 'puts larva on stasis'. No one bothers making it because its too niche to carry about anyway.

**Comment by ondrej008** [comment]
> Maybe make hugged marines extra vulnerable to tackling?

They already are, once you knock a hugged marine down, your next tackles will instantly knock them down.

**Pull request merged**
